"""Relazioni cross-fonte ETSI EN 319 411-1 (fonte_id=17) verso tutte le altre
fonti gia' censite nel grafo (2026-09-23, ADR-0009 - fase 6 obbligatoria).

Modulo "capitolo virtuale" (nessuna riga obbligo/principio propria, solo
RELAZIONI) agganciato in coda alla lista capitoli di ETSI EN 319 411-1
(fonte_id=17) passata a inserisci_capitoli, DOPO che sia questa fonte sia
ETSI EN 319 411-2 (fonte_id=18) sono gia' presenti nel registro simbolico
(le due fonti si citano a vicenda, stesso vincolo gia' applicato a
ETSI TS 119 431-1/431-2).

Pipeline eseguita nella sessione principale (mai a subagent), 3 stadi
(ADR-0009):

1. Generazione candidati a zero token LLM: KNN sull'indice vettoriale HNSW
   gia' popolato (idxEmbeddingObbligo/idxEmbeddingPrincipio) dai 377 nodi di
   questa fonte verso tutti i nodi delle altre 17 fonti censite -> 3.510
   coppie con score >= 0.80 (soglia iniziale troppo permissiva per un
   catalogo di requisiti tecnici che condivide molto vocabolario con altri
   standard ETSI ESI gia' censiti): ridotto a top-3 per nodo con soglia
   elevata a >= 0.90, portando lo shortlist a 314 coppie.
2. Classificazione LLM sullo shortlist di 314 coppie (mai sul prodotto
   cartesiano 377 x ~2.500 nodi): 27 chiamate completion() dirette in
   parallelo con wait() (batch da 12 coppie), system prompt con tassonomia
   ristretta ai tipi rilevanti, output a schema JSON, prompt esplicitamente
   conservativo (omettere piuttosto che inventare).
3. Validazione: filtro confidence >= 0.5, verifica che ogni riferimento
   proposto (sia nodo_da sia nodo_a) esista realmente in Neo4j (per
   costruzione, essendo gli id risolti direttamente dai risultati Cypher
   della fase KNN/enrichment), deduplica su (nodo_da, nodo_a) tenendo la
   confidence piu' alta in caso di piu' proposte sulla stessa coppia.

Esito per fonte 17: 192 relazioni cross-fonte (si sovrappone a: 156, specifica: 22, richiama: 9, si applica a: 3, attua: 1, è condizionato da: 1).
Per fonte target: ETSI EN 319 401 (34): 1, ETSI TS 119 431-1 (71): 1, ETSI EN 319 411-2 (58): 1, ETSI TS 119 461 (13): 1, ETSI TS 119 431-2 (9): 1, Regole Tecniche AgID certificati qualificati 13/2/2020 (2): 1, Reg. (UE) 2015/1502 (3): 1, DPCM 22/2/2013 (1): 1, ETSI EN 319 412-5 (1): 1.
Zero verso: eIDAS, eIDAS2, CAD, SPID (DPCM 24/10/2014), DPCM 19/10/2021, Reg. (UE) 2025/1566, Reg. AgID modalita' attuative SPID, Codice Civile (nessun candidato KNN
sopra soglia con confidence sufficiente dopo classificazione).
"""

RIGHE_OBBLIGHI: list[dict] = []
RIGHE_PRINCIPI: list[dict] = []
INDICE_ARTICOLI_LOCALE: list[str] = []
MAPPATURA_LOCALE: dict[str, list[str]] = {}

RELAZIONI = [
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 1 (Scope)'),
        "nodo_a": ('principio', 10, 'clausola 4.1 (General)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 1 (Scope)'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 1 (Scope)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 2.1 (Normative references)'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 2.2 (Informative references)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 2.1 (Normative references)'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 2.1 (Normative references)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 2.2 (Informative references)'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 2.2 (Informative references)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 3.4 (Notations)'),
        "nodo_a": ('principio', 10, 'clausola 3.4 (Notation)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 3.4 (Notations)'),
        "nodo_a": ('principio', 9, 'clausola 3.4 (Notations)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 4.1'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 4.1 (General policy requirements concepts)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 4.1'),
        "nodo_a": ('principio', 11, 'Parte 2: clausola 4.1 (General policy requirements concepts)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 4.1'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 4.2.3'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-6.9.4-04'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 4.3'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 4.4 (SSAS component services)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 4.3'),
        "nodo_a": ('principio', 10, 'clausola 4.1 (General)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 5.1 (premessa)'),
        "nodo_a": ('obbligo', 10, 'REQ-4.2-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 5.3'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 5.3 (identificatori delle policy)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 5.3'),
        "nodo_a": ('obbligo', 17, 'Parte 2: GEN-6.3.3-02'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 5.3'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 4.2.2 (Certificate Policy — introduzione)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.2.1'),
        "nodo_a": ('obbligo', 15, 'par. 4.1 punto 1'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.3.11'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.3.11'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.3.11'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.8.10'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: OVR-6.4.2-10'),
        "nodo_a": ('obbligo', 10, 'REQ-7.8-04'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: OVR-6.4.2-10'),
        "nodo_a": ('obbligo', 10, 'REQ-7.6-02'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: OVR-6.4.2-10'),
        "nodo_a": ('obbligo', 10, 'REQ-7.4.1-10'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.4.7'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.4.7 (Key changeover)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.4.7'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.4.7'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.4.7'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.12 (Amendments)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: OVR-6.4.8-05'),
        "nodo_a": ('obbligo', 10, 'REQ-7.11.2-01'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: OVR-6.4.8-05'),
        "nodo_a": ('obbligo', 10, 'PRO-7.11.2-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: OVR-6.4.8-05'),
        "nodo_a": ('obbligo', 10, 'REQ-7.11.2-06'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: GEN-6.5.1-06'),
        "nodo_a": ('obbligo', 11, 'Parte 2: OVR-8.2-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: GEN-6.6.1-03'),
        "nodo_a": ('obbligo', 17, 'Parte 2: CSS-6.3.10-02B'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.7'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.7'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.7'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.6 (Compliance audit and other assessment)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.7'),
        "nodo_a": ('principio', 17, 'Parte 2: Annex B'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.1'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.8.1'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.1'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.1 (Fees)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.3'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.3 (Confidentiality of business information)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.5'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.5 (Intellectual property rights)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.5'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.8.5'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.7'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.7 (Disclaimers of warranties)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.7'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.8.7'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.8'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.8.8'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.8'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.8 (Limitations of liability)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.9'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.9 (Indemnities)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.10'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.10 (Term and termination)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.11'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.11 (Individual notices and communications with participants)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.12'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.12 (Amendments)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.12'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.9 (Indemnities)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.14'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.8.14'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.14'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.14 (Governing law)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.16'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.16 (Miscellaneous provisions)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.16'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.12 (Amendments)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: clausola 6.8.16'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.9 (Indemnities)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: Annex B (Conformity assessment checklist)'),
        "nodo_a": ('principio', 17, 'Parte 2: Annex B'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 1: Annex B (Conformity assessment checklist)'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-5.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-5.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.2-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.2-02'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 5.1 (premessa)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.2-04'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-5.1-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.2-05'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-5.1-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.2-07B'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-5.1-09'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-5.2-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.4.1-01'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-6.3.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-5.4.1-01'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-5.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: DIS-6.1-01A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: DIS-6.1-04'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: DIS-6.1-04'),
        "nodo_a": ('obbligo', 10, 'REQ-6.1-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: DIS-6.1-04'),
        "nodo_a": ('obbligo', 17, 'Parte 2: CSS-6.3.10-12'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: DIS-6.1-05'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.1-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: DIS-6.1-08'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.1-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-02AB'),
        "nodo_a": ('principio', 9, 'clausola 8.3.4 (ambito di applicazione)'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-05A'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 6.8.5'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-05B'),
        "nodo_a": ('obbligo', 9, 'QTS-C.2.4-04'),
        "tipo_relazione": 'si applica a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-05B'),
        "nodo_a": ('obbligo', 9, 'QTS-C.2.4-01'),
        "tipo_relazione": 'si applica a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-05B'),
        "nodo_a": ('obbligo', 9, 'QTS-C.2.4-03'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-05C'),
        "nodo_a": ('obbligo', 14, 'allegato, punto 2.1.3'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-05C'),
        "nodo_a": ('principio', 9, 'clausola 9.3'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-05C'),
        "nodo_a": ('obbligo', 9, 'USE-9.4-01X'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-08A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: LNK-A.7-01'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-09'),
        "nodo_a": ('principio', 9, 'COL-8.2.8-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-10'),
        "nodo_a": ('obbligo', 14, 'allegato, punto 2.1.3'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-13'),
        "nodo_a": ('obbligo', 14, 'allegato, punto 2.1.3'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-10A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: LNK-A.7-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-13A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: LNK-A.7-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-16'),
        "nodo_a": ('principio', 9, 'clausola 9.2.1.2'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-16'),
        "nodo_a": ('principio', 9, 'clausola 8.3.3 (ambito di applicazione)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-16A'),
        "nodo_a": ('principio', 9, 'clausola 9.2.1.2'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-16A'),
        "nodo_a": ('principio', 9, 'clausola 8.3.3 (ambito di applicazione)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-16B'),
        "nodo_a": ('obbligo', 11, 'Parte 1: LNK-A.7-01'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-16B'),
        "nodo_a": ('principio', 9, 'clausola 8.3.4 (ambito di applicazione)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-18'),
        "nodo_a": ('obbligo', 10, 'REQ-7.14.3-11'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.2.2-22'),
        "nodo_a": ('obbligo', 10, 'REQ-7.13-02'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REV-6.2.4-01'),
        "nodo_a": ('obbligo', 17, 'Parte 2: CSS-6.3.10-12'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: GEN-6.3.3-12'),
        "nodo_a": ('obbligo', 17, 'Parte 2: GEN-6.3.3-02'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: GEN-6.3.3-08'),
        "nodo_a": ('obbligo', 17, 'Parte 2: SDP-6.3.5-09'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: GEN-6.3.3-08'),
        "nodo_a": ('obbligo', 17, 'Parte 2: SDP-6.3.5-08'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.4-02'),
        "nodo_a": ('obbligo', 10, 'REQ-7.14.3-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.3.4-04'),
        "nodo_a": ('obbligo', 10, 'REQ-6.2-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.3.4-05'),
        "nodo_a": ('obbligo', 10, 'REQ-6.2-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.3.4-06'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-6.9.4-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.3.4-06'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 4.2.3 (Terms and conditions and PKI disclosure statement)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.4-17'),
        "nodo_a": ('obbligo', 10, 'REQ-7.10-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.3.5-04'),
        "nodo_a": ('obbligo', 17, 'Parte 2: SDP-6.3.5-08'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.3.5-04'),
        "nodo_a": ('obbligo', 17, 'Parte 2: SDP-6.3.5-09'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.3.5-05'),
        "nodo_a": ('obbligo', 17, 'Parte 2: SDP-6.3.5-08'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.3.5-05'),
        "nodo_a": ('obbligo', 17, 'Parte 2: SDP-6.3.5-09'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.6-06'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.7-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.6-06'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.8-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.6-06'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.6-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.6-07'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.7-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.6-07'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.8-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.6-07'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.6-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: GEN-6.3.6-10'),
        "nodo_a": ('principio', 4, 'art. 31 c.1'),
        "tipo_relazione": 'è condizionato da',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.7-05'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.7-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.7-05'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.8-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.7-05'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.6-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.7-06'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.7-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.7-06'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.8-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REG-6.3.7-06'),
        "nodo_a": ('obbligo', 17, 'Parte 2: REG-6.3.6-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: CSS-6.3.10-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.1-03'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: SDP-6.3.12-03'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 4.2.2'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.5.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.2-05'),
        "nodo_a": ('obbligo', 10, 'REQ-7.6-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.2-08'),
        "nodo_a": ('obbligo', 10, 'REQ-7.6-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.2-08'),
        "nodo_a": ('obbligo', 10, 'PRO-7.6-10'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.2-08'),
        "nodo_a": ('obbligo', 10, 'PRO-7.6-07'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.3-01A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.3-01A'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.4-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.4-01'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-7.2-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.5-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.5-01'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 4.1 (General policy requirements concepts)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.5-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.5-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: REV-6.4.5-09'),
        "nodo_a": ('obbligo', 10, 'REQ-7.10-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.5-11'),
        "nodo_a": ('obbligo', 10, 'REQ-7.10-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.5-11'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-6.4.5-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.8-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.8-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.8-02'),
        "nodo_a": ('obbligo', 10, 'REQ-7.11.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.8-02'),
        "nodo_a": ('obbligo', 10, 'REQ-7.11.2-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.8-08'),
        "nodo_a": ('obbligo', 10, 'REQ-7.11-1-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.4-01'),
        "tipo_relazione": 'si applica a',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.9-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-01'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 5.4.2'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.15-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.3-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-03'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-03'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.15-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.4.9-03'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.3-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.1-01'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-7.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.1-01'),
        "nodo_a": ('principio', 17, 'Parte 2: clausola 5.4.2'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: SDP-6.5.1-24'),
        "nodo_a": ('obbligo', 10, 'REQ-7.5-01'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: SDP-6.5.1-25'),
        "nodo_a": ('obbligo', 10, 'REQ-7.5-01'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.2-02'),
        "nodo_a": ('obbligo', 10, 'REQ-7.5-01'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.2-12'),
        "nodo_a": ('obbligo', 10, 'REQ-7.5-01'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.3-01'),
        "nodo_a": ('obbligo', 17, 'Parte 2: CSS-6.3.10-13'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.5-01A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.5.3-01A'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.5-01A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.3-01A'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.5-01A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.3-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.5-07'),
        "nodo_a": ('obbligo', 10, 'REQ-7.6-13'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.5-07'),
        "nodo_a": ('obbligo', 10, 'REQ-7.9.1-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.5-07'),
        "nodo_a": ('obbligo', 10, 'REQ-7.9.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.6-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.5.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.5.7-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.5.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.8.4-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.8.15-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.15-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.8.15-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.3-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.8.15-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.1-01'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-7.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.1-04'),
        "nodo_a": ('obbligo', 10, 'REQ-7.13-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.3-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.15-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.7.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.4-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.4-01'),
        "nodo_a": ('obbligo', 17, 'Parte 2: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-6.9.4-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-03'),
        "nodo_a": ('obbligo', 11, 'Parte 2: OVR-9-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-03'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-7-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-04'),
        "nodo_a": ('obbligo', 11, 'Parte 2: OVR-9-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-04'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-7-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-05'),
        "nodo_a": ('obbligo', 11, 'Parte 2: OVR-9-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-05'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-7-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-07'),
        "nodo_a": ('obbligo', 11, 'Parte 2: OVR-9-08'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-08'),
        "nodo_a": ('obbligo', 11, 'Parte 2: OVR-9-09'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-08'),
        "nodo_a": ('obbligo', 11, 'Parte 2: OVR-9-08'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-11'),
        "nodo_a": ('obbligo', 17, 'Parte 2: GEN-6.6.1-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.1-11'),
        "nodo_a": ('obbligo', 15, 'par. 4.1 punto 1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 2: OVR-9-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 1: OVR-7.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-7-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
]
