"""Estrazione granulare ETSI EN 319 401 V3.2.1 (2026-01) — Capitolo 3: clausole
7.1 (Internal organization: 7.1.1 General, 7.1.2 Organization reliability,
7.1.3 Segregation of duties), 7.2 (Human resources), 7.3 (Asset management:
7.3.1 General requirements, 7.3.2 Assets classification, 7.3.3 Storage media
and asset handling), 7.4 (Access control: 7.4.1 General, 7.4.2 Privileged and
system administration accounts, 7.4.3 Administration systems, 7.4.4
Identification, 7.4.5 Authentication, 7.4.6 Multi-factor authentication),
7.5 (Cryptographic controls).

Fonte 10 (numerazione definitiva cablata dalla sessione principale in
app/seed.py — questo modulo NON tocca seed.py). Testo ufficiale in
app/.source_cache/etsi_319_401/cap03.txt. Manifest di split:
app/.source_cache/etsi_319_401/manifest.json. Il file di testo inizia con
il titolo dell'intera clausola 7 "TSP management and operation" (paratesto
di intestazione, nessun contenuto normativo proprio) e termina esattamente
a fine 7.5 (REQ-7.5-05); la clausola 7.6 in poi (Physical and environmental
security ecc.) è assegnata al capitolo 4 e non compare in questo file.

Modellazione (ADR-0007), stesso criterio già applicato a ETSI TS 119 461
(fonte 9, vedi app/seed_data/etsi_119_461/cap02.py) per uno standard tecnico
ETSI a clausole/sottoclausole con requisiti numerati:

- Ogni requisito con prefisso REQ-x.y-nn o PRO-x.y-nn (grassetto nel testo)
  -> un Obbligo. `riferimento` = id esatto (es. "REQ-7.1.1-01",
  "PRO-7.1.1-04"), senza il marcatore "[CONDITIONAL]" quando presente (che
  va invece nel prefisso di `testo_integrale` e in `condizione_applicabilita`
  con la condizione testuale). Le sotto-liste puntate a)/b)/c)/... prive di
  un proprio id REQ/PRO restano nello stesso nodo del requisito chapeau che
  le introduce (es. REQ-7.2-01 include i punti a) e b); REQ-7.5-03 include
  i punti a)/b)/c) e la sotto-lista romana i)-xii) del punto c), nessuno dei
  quali porta un id REQ/PRO proprio).
- Tutto il contenuto di questo capitolo (clausole 7.1-7.5) è organizzato
  esclusivamente in requisiti numerati REQ-/PRO-: a differenza di altri
  capitoli ETSI con clausole introduttive prive di REQ (es. clausola 4 di
  ETSI TS 119 461), qui ogni intestazione di clausola/sottoclausola (7.1,
  7.1.1, 7.1.2, 7.1.3, 7.2, 7.3, 7.3.1, 7.3.2, 7.3.3, 7.4, 7.4.1-7.4.6, 7.5)
  è seguita direttamente da testo normativo numerato, senza un chapeau
  descrittivo autonomo che richieda un nodo Principio separato -> nessun
  Principio in questo capitolo, RIGHE_PRINCIPI = [].
- `tipo_obbligo`: "organizzativo" per le clausole 7.1 (Internal
  organization), 7.2 (Human resources) e 7.3 (Asset management) — gestione
  di persone, ruoli, responsabilità, asset a livello organizzativo, nessuna
  misura tecnica in senso stretto; "tecnico/sicurezza" per le clausole 7.4
  (Access control) e 7.5 (Cryptographic controls) — controlli tecnici di
  accesso, autenticazione e crittografia, come da istruzione esplicita del
  capofila di import.
- `soggetti`: [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}] per
  tutti gli 84 obblighi (soggetto sempre "The TSP shall/should ...").
- NOTE bibliografiche pure ("NOTE: See clause X of ISO/IEC 27002:2022
  [i.11] for guidance", elenchi di rimandi ad altri standard ETSI dove il
  medesimo requisito è incorporato) sono omesse da `testo_integrale` come
  da istruzione. NOTE con contenuto interpretativo sostanziale sono invece
  mantenute — es. REQ-7.2-05 (chiarisce chi rientra nella nozione di
  "personnel"), REQ-7.2-14 (NOTE 7/8 che precisano il perimetro dei ruoli
  System Administrator/Auditor), REQ-7.2-17 (NOTE 9 sulla fattibilità pratica
  della verifica dei precedenti in alcuni paesi), REQ-7.4.1-05 (NOTE 1 che
  lega il requisito ai ruoli fiduciari di REQ-7.2-14), REQ-7.5-03 (NOTE 2
  che chiarisce come la conformità a ETSI EN 319 411-1/-2 soddisfi il
  requisito di key management — nessuna relazione cross-fonte creata, solo
  testo).
- Marcature [CONDITIONAL]: REQ-7.2-18, REQ-7.2-19 (lavoro da remoto) e
  REQ-7.4.1-06 (autenticazione multi-fattore/continua "where appropriate",
  condizionata dalla classificazione del sistema) -> `condizione_applicabilita`
  valorizzata, marcatore "[CONDITIONAL]" mantenuto in testa a
  `testo_integrale`, omesso da `riferimento`.
- REQ-7.4.6-01 (Multi-factor authentication) rinvia testualmente a
  REQ-7.4.1-06 e REQ-7.4.5-02 punto a): rinvio interno riportato nel testo,
  nessuna relazione creata in questa fase (vedi vincolo RELAZIONI sotto).
- RELAZIONI = [] in questo modulo per vincolo esplicito di fase: nessuna
  relazione, né interna al capitolo né cross-capitolo né cross-fonte. La
  sessione principale gestirà il collegamento cross-fonte in una fase
  successiva dedicata (ADR-0009).
"""

RIGHE_OBBLIGHI = [
    {
        "riferimento": "REQ-7.1.1-01",
        "testo": "Il TSP deve stabilire responsabilità e poteri per la sicurezza dei sistemi di rete e informativi, assegnarli a ruoli, allocarli secondo le proprie esigenze e comunicarli agli organi di gestione.",
        "testo_integrale": "REQ-7.1.1-01: The TSP shall lay down responsibilities and authorities for network and information system security and assign them to roles, allocate them according to the TSP's needs, and communicate them to the management bodies.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.1-02",
        "testo": "Il TSP deve richiedere a tutto il personale e alle terze parti di applicare la sicurezza dei sistemi di rete e informativi in conformità alla politica stabilita sulla sicurezza dei sistemi di rete e informativi, alle politiche specifiche per argomento e alle procedure del TSP.",
        "testo_integrale": "REQ-7.1.1-02: The TSP shall require all personnel and third parties to apply network and information system security in accordance with the established policy on the security of network and information systems, topic-specific policies and procedures of the TSP.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.1-03",
        "testo": "Almeno una persona deve riferire direttamente agli organi di gestione in materia di sicurezza dei sistemi di rete e informativi.",
        "testo_integrale": "REQ-7.1.1-03: At least one person shall report directly to the management bodies on matters of network and information system security.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "PRO-7.1.1-04",
        "testo": "In base alle dimensioni del TSP, la sicurezza dei sistemi di rete e informativi deve essere coperta da ruoli dedicati o da compiti svolti in aggiunta a ruoli esistenti. Ciò deve essere documentato nel piano di gestione del rischio.",
        "testo_integrale": "PRO-7.1.1-04: Depending on the size of the TSP, network and information system security shall be covered by dedicated roles or duties carried out in addition to existing roles. This shall be documented in the risk management plan.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.1-05",
        "testo": "Il TSP deve riesaminare ruoli, responsabilità e poteri a intervalli pianificati e in occasione di incidenti significativi o di cambiamenti significativi alle operazioni o ai rischi.",
        "testo_integrale": "REQ-7.1.1-05: The TSP shall review roles, responsibilities and authorities at planned intervals and when significant incidents or changes to operations or risks occur.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.2-01",
        "testo": "L'organizzazione del TSP deve essere affidabile, in particolare secondo quanto specificato dai requisiti seguenti.",
        "testo_integrale": "REQ-7.1.2-01: The TSP organization shall be reliable. In particular:",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.2-02",
        "testo": "Le pratiche di servizio fiduciario secondo cui opera il TSP devono essere non discriminatorie.",
        "testo_integrale": "REQ-7.1.2-02: Trust service practices under which the TSP operates shall be non-discriminatory.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.2-03",
        "testo": "Il TSP dovrebbe rendere i propri servizi accessibili a tutti i richiedenti la cui attività rientri nel proprio campo di operatività dichiarato e che accettino di rispettare gli obblighi specificati nei termini e condizioni del TSP.",
        "testo_integrale": "REQ-7.1.2-03: The TSP should make its services accessible to all applicants whose activities fall within its declared field of operation and that agree to abide by their obligations as specified in the TSP's terms and conditions.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.2-04",
        "testo": "Il TSP deve mantenere risorse finanziarie sufficienti e/o ottenere un'adeguata assicurazione di responsabilità civile, in conformità alla legge applicabile, per coprire le responsabilità derivanti dalle proprie operazioni e/o attività.",
        "testo_integrale": "REQ-7.1.2-04: The TSP shall maintain sufficient financial resources and/or obtain appropriate liability insurance, in accordance with applicable law, to cover liabilities arising from its operations and/or activities.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.2-05",
        "testo": "Il TSP deve disporre della stabilità finanziaria e delle risorse necessarie per operare in conformità alla presente policy.",
        "testo_integrale": "REQ-7.1.2-05: The TSP shall have the financial stability and resources required to operate in conformity with this policy.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.2-06",
        "testo": "Il TSP deve disporre di politiche e procedure per la risoluzione di reclami e controversie ricevuti da clienti o altre parti affidanti in merito all'erogazione dei servizi o a qualsiasi altra questione correlata.",
        "testo_integrale": "REQ-7.1.2-06: The TSP shall have policies and procedures for the resolution of complaints and disputes received from customers or other relying parties about the provisioning of the services or any other related matters.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.1.3-01",
        "testo": "I compiti e le aree di responsabilità in conflitto devono essere separati per ridurre le opportunità di modifica non autorizzata o non intenzionale, o di uso improprio, degli asset del TSP.",
        "testo_integrale": "REQ-7.1.3-01: Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of the TSP's assets.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-01",
        "testo": "Il TSP deve garantire che i propri dipendenti e i fornitori e prestatori di servizi diretti comprendano e si impegnino rispetto alle proprie responsabilità di sicurezza, in modo appropriato ai servizi offerti e al ruolo ricoperto e in linea con la politica del TSP sulla sicurezza dei sistemi di rete e informativi. A tal fine il TSP deve: a) attuare meccanismi che assicurino che tutti i dipendenti, fornitori e prestatori di servizi diretti comprendano e seguano la politica e i processi di sicurezza informatica e di rete applicati dal TSP; che tutti gli utenti con accesso amministrativo o privilegiato siano consapevoli dei propri ruoli, responsabilità e poteri e agiscano di conseguenza; che i membri degli organi di gestione comprendano e agiscano in conformità al proprio ruolo, responsabilità e poteri in materia di sicurezza dei sistemi di rete e informativi; e che venga assunto personale qualificato per i rispettivi ruoli (ad esempio tramite controlli delle referenze, procedure di vetting, verifica delle certificazioni o test scritti); b) riesaminare l'assegnazione del personale a ruoli specifici, e il relativo impegno di risorse umane, a intervalli pianificati e almeno annualmente, aggiornando l'assegnazione ove necessario.",
        "testo_integrale": "REQ-7.2-01: The TSP shall ensure that their employees and direct suppliers and service providers understand and commit to their security responsibilities, as appropriate for the offered services and the job and in line with the TSP's policy on the security of network and information systems. The TSP shall, therefore: a) implement mechanism to ensure that: all employees, direct suppliers and service providers, wherever applicable, understand and follow the Information and Network Security Policy and processes that the TSP applies; all users with administrative or privileged access are aware of and act in accordance with their roles, responsibilities and authorities; members of management bodies understand and act in accordance with their role, responsibilities and authorities regarding network and information system security; personnel qualified for the respective roles are hired. EXAMPLE: Using tools such as reference checks, vetting procedures, validation of certifications, or written tests. b) review the assignment of personnel to specific roles, as well as their commitment of human resources in that regard, at planned intervals and at least annually. They shall update the assignment where necessary.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-02",
        "testo": "Il TSP deve impiegare personale e, se applicabile, subappaltatori, che possiedano la competenza, l'affidabilità, l'esperienza e le qualifiche necessarie e che abbiano ricevuto formazione in materia di cybersicurezza e di norme sulla protezione dei dati personali, come appropriato per i servizi offerti e per la funzione svolta.",
        "testo_integrale": "REQ-7.2-02: The TSP shall employ staff and, if applicable, subcontractors, who possess the necessary expertise, reliability, experience, and qualifications and who have received training regarding cybersecurity and personal data protection rules as appropriate for the offered services and the job function.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-03",
        "testo": "Il TSP deve individuare almeno una persona responsabile della sicurezza dei sistemi di rete e informativi, che riferisca al vertice aziendale.",
        "testo_integrale": "REQ-7.2-03: The TSP shall identify at least one person responsible for network and information security and reporting to top management.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-04",
        "testo": "Il personale del TSP in ruoli fiduciari, e, se applicabile, i suoi subappaltatori in ruoli fiduciari, devono poter soddisfare il requisito di \"conoscenza esperta, esperienza e qualifiche\" tramite formazione e credenziali formali, oppure esperienza effettiva, oppure una combinazione delle due.",
        "testo_integrale": "REQ-7.2-04: TSP's personnel in trusted roles, and, if applicable, its subcontractors in trusted roles, shall be able to fulfil the requirement of \"expert knowledge, experience and qualifications\" through formal training and credentials, or actual experience, or a combination of the two.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-05",
        "testo": "Il personale del TSP in ruoli fiduciari deve ricevere aggiornamenti regolari sulle nuove minacce e sulle pratiche di sicurezza correnti almeno ogni 12 mesi. Il personale impiegato da un TSP comprende anche il personale individuale ingaggiato contrattualmente per svolgere funzioni a supporto dei servizi del TSP; il personale eventualmente coinvolto nel monitoraggio dei servizi del TSP non deve necessariamente essere personale del TSP.",
        "testo_integrale": "REQ-7.2-05: TSP's personnel in trusted roles shall receive regular updates on new threats and current security practices at least every 12 months. NOTE 2: Personnel employed by a TSP include individual personnel contractually engaged in performing functions in support of the TSP's services. Personnel who can be involved in monitoring the TSP's services need not be TSP's personnel.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-06",
        "testo": "Devono essere applicate sanzioni disciplinari appropriate al personale che violi le politiche o procedure del TSP, in conformità a un processo disciplinare stabilito, comunicato e mantenuto per la gestione delle violazioni delle politiche di sicurezza dei sistemi di rete e informativi. Tale processo deve: a) tenere conto dei requisiti legali, statutari, contrattuali e aziendali rilevanti; b) essere riesaminato e, ove appropriato, aggiornato a intervalli pianificati, almeno annualmente, e quando necessario a seguito di modifiche legislative o cambiamenti significativi alle operazioni o ai rischi.",
        "testo_integrale": "REQ-7.2-06: Appropriate disciplinary sanctions shall be applied to personnel violating TSP's policies or procedures in accordance with an established communicated and maintained disciplinary process for handling violations of network and information system security policies. This process shall: a) take into consideration relevant legal, statutory, contractual and business requirements. b) be reviewed and, where appropriate, updated at planned intervals, at least annually, and when necessary due to legal changes or significant changes to operations or risks.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-07",
        "testo": "I ruoli e le responsabilità di sicurezza delle informazioni, come specificati nella politica del TSP sulla sicurezza dei sistemi di rete e informativi, devono essere documentati nelle descrizioni delle mansioni o in documenti disponibili a tutto il personale interessato, e allocati di conseguenza.",
        "testo_integrale": "REQ-7.2-07: Information security roles and responsibilities, as specified in the TSP's policy on the security of network and information systems, shall be documented in job descriptions or in documents available to all concerned personnel and allocated accordingly.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-08",
        "testo": "I ruoli fiduciari, da cui dipende l'operatività del TSP, devono essere chiaramente identificati.",
        "testo_integrale": "REQ-7.2-08: Trusted roles, on which the TSP's operation is dependent, shall be clearly identified.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-09",
        "testo": "Il personale del TSP (sia temporaneo che permanente) deve disporre di descrizioni delle mansioni definite dal punto di vista dei ruoli svolti, nel rispetto della separazione dei compiti e del privilegio minimo (cfr. clausola 7.1.2), determinando la sensibilità della posizione in base ai compiti e ai livelli di accesso, allo screening dei precedenti e alla formazione e consapevolezza del dipendente.",
        "testo_integrale": "REQ-7.2-09: TSP's personnel (both temporary and permanent) shall have job descriptions defined from the view point of roles fulfilled with segregation of duties and least privilege (see clause 7.1.2), determining position sensitivity based on the duties and access levels, background screening and employee training and awareness.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "PRO-7.2-10",
        "testo": "Ove appropriato, le descrizioni delle mansioni devono differenziare tra funzioni generali e funzioni specifiche del TSP, e dovrebbero includere i requisiti di competenze ed esperienza.",
        "testo_integrale": "PRO-7.2-10: Where appropriate, job descriptions shall differentiate between general functions and TSP's specific functions. These should include skills and experience requirements.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-11",
        "testo": "Il personale deve esercitare procedure e processi amministrativi e di gestione in linea con le procedure di gestione della sicurezza delle informazioni del TSP.",
        "testo_integrale": "REQ-7.2-11: Personnel shall exercise administrative and management procedures and processes that are in line with the TSP's information security management procedures.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-12",
        "testo": "Il personale dirigenziale deve possedere esperienza o formazione rispetto al servizio fiduciario erogato, familiarità con le procedure di sicurezza per il personale con responsabilità di sicurezza, ed esperienza in materia di sicurezza delle informazioni e valutazione del rischio sufficiente a svolgere le funzioni dirigenziali.",
        "testo_integrale": "REQ-7.2-12: Managerial personnel shall possess experience or training with respect to the trust service that is provided, familiarity with security procedures for personnel with security responsibilities and experience with information security and risk assessment sufficient to carry out management functions.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-13",
        "testo": "Tutto il personale del TSP in ruoli fiduciari deve essere esente da conflitti di interesse che possano pregiudicare l'imparzialità delle operazioni del TSP.",
        "testo_integrale": "REQ-7.2-13: All TSP's personnel in trusted roles shall be free from conflict of interest that might prejudice the impartiality of the TSP's operations.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-14",
        "testo": "I ruoli fiduciari devono comprendere ruoli che implicano le seguenti responsabilità: a) Security Officer: responsabilità complessiva della gestione dell'attuazione delle pratiche di sicurezza; b) Amministratori di sistema: autorizzati a installare, configurare e mantenere i sistemi affidabili del TSP per la gestione del servizio (compreso il ripristino del sistema); c) Operatori di sistema: responsabili della gestione quotidiana dei sistemi affidabili del TSP, autorizzati a eseguire il backup del sistema; d) Revisori di sistema (System Auditors): autorizzati a consultare gli archivi e i log di audit dei sistemi affidabili del TSP. Ruoli applicativi specifici aggiuntivi possono essere richiesti per particolari servizi fiduciari.",
        "testo_integrale": "REQ-7.2-14: Trusted roles shall include roles that involve the following responsibilities: a) Security Officers: Overall responsibility for administering the implementation of the security practices. b) System Administrators: Authorized to install, configure and maintain the TSP's trustworthy systems for service management. NOTE 7: This includes recovery of the system. c) System Operators: Responsible for operating the TSP's trustworthy systems on a day-to-day basis. Authorized to perform system backup. d) System Auditors: Authorized to view archives and audit logs of the TSP's trustworthy systems. NOTE 8: Additional application specific roles can be required for particular trust services.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-15",
        "testo": "Il personale del TSP deve essere formalmente nominato ai ruoli fiduciari dal management di vertice responsabile della sicurezza.",
        "testo_integrale": "REQ-7.2-15: TSP's personnel shall be formally appointed to trusted roles by senior management responsible for security.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-16",
        "testo": "I ruoli fiduciari devono essere accettati dalla persona nominata a ricoprire il ruolo.",
        "testo_integrale": "REQ-7.2-16: Trusted roles shall be accepted by the appointed person to fulfil the role.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-17",
        "testo": "Il personale non deve avere accesso alle funzioni fiduciarie finché non siano completate le verifiche necessarie. In alcuni paesi non è possibile per il TSP ottenere informazioni su condanne pregresse senza la collaborazione del candidato dipendente.",
        "testo_integrale": "REQ-7.2-17: Personnel shall not have access to the trusted functions until the necessary checks are completed. NOTE 9: In some countries it is not possible for TSP to obtain information on past convictions without the collaboration of the candidate employee.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-18",
        "testo": "Quando il personale lavora da remoto, il TSP deve attuare misure di cybersicurezza per proteggere le informazioni a cui si accede, che vengono elaborate o conservate al di fuori dei locali del TSP.",
        "testo_integrale": "[CONDITIONAL] REQ-7.2-18: When personnel are working remotely, TSP shall implement cybersecurity measures to protect information accessed, processed or stored outside the TSP's premises.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
        "condizione_applicabilita": "si applica solo quando il personale lavora da remoto",
    },
    {
        "riferimento": "REQ-7.2-19",
        "testo": "I TSP che consentono attività di lavoro da remoto devono emanare una politica specifica sul lavoro da remoto, che definisca le condizioni e le restrizioni di cybersicurezza rilevanti.",
        "testo_integrale": "[CONDITIONAL] REQ-7.2-19: TSPs allowing remote working activities shall issue a topic-specific policy on remote working that defines the relevant cybersecurity conditions and restrictions.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
        "condizione_applicabilita": "si applica solo ai TSP che consentono attività di lavoro da remoto",
    },
    {
        "riferimento": "REQ-7.2-20",
        "testo": "Il TSP deve garantire, nella misura in cui ciò sia fattibile, la verifica dei precedenti dei propri dipendenti, e ove applicabile dei fornitori e prestatori di servizi diretti, se necessario in relazione al loro ruolo, responsabilità e poteri.",
        "testo_integrale": "REQ-7.2-20: The TSP shall ensure to the extent feasible verification of the background of their employees, and where applicable of direct suppliers and service providers, if necessary for their role, responsibilities and authorisations.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-21",
        "testo": "Ai fini della verifica dei precedenti, il TSP deve: a) stabilire criteri che definiscano quali ruoli, responsabilità e poteri possano essere esercitati solo da persone i cui precedenti siano stati verificati; b) garantire che la verifica su tali persone sia effettuata prima che inizino a esercitare tali ruoli, responsabilità e poteri, tenendo conto delle leggi, dei regolamenti e dell'etica applicabili in proporzione ai requisiti aziendali, alla classificazione degli asset e ai sistemi di rete e informativi a cui si accede, nonché ai rischi percepiti.",
        "testo_integrale": "REQ-7.2-21: For the purpose of background verification, the TSP shall: a) put in place criteria, which set out which roles, responsibilities and authorities shall only be exercised by persons whose background has been verified; b) ensure that verification is performed on these persons before they start exercising these roles, responsibilities and authorities, which shall take into consideration the applicable laws, regulations, and ethics in proportion to the business requirements, the asset classification and the network and information systems to be accessed, and the perceived risks.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-22",
        "testo": "Il TSP deve riesaminare e, ove appropriato, aggiornare la politica di verifica dei precedenti a intervalli pianificati, almeno ogni due anni, e aggiornarla ove necessario.",
        "testo_integrale": "REQ-7.2-22: The TSP shall review and, where appropriate, update the background verification policy at planned intervals, at least every two years, and update it where necessary.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-23",
        "testo": "Il TSP deve garantire che le responsabilità e i doveri in materia di sicurezza dei sistemi di rete e informativi che restano validi dopo la cessazione o il cambiamento del rapporto di lavoro dei propri dipendenti siano definiti contrattualmente e resi vincolanti.",
        "testo_integrale": "REQ-7.2-23: The TSP shall ensure that network and information system security responsibilities and duties that remain valid after termination or change of employment of their employees are contractually defined and enforced.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.2-24",
        "testo": "Ai fini del REQ-7.2-23, il TSP deve includere nei termini e condizioni di impiego, nel contratto o nell'accordo individuale le responsabilità e i doveri che restano validi dopo la cessazione del rapporto di lavoro o del contratto, come le clausole di riservatezza.",
        "testo_integrale": "REQ-7.2-24: For the purpose of REQ-7.2-23, the TSP shall include in the individual's terms and conditions of employment, contract or agreement the responsibilities and duties that are still valid after termination of employment or contract, such as confidentiality clauses.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.1-01",
        "testo": "Il TSP deve garantire un livello adeguato di protezione dei propri asset, inclusi gli asset informativi.",
        "testo_integrale": "REQ-7.3.1-01: The TSP shall ensure an appropriate level of protection of its assets including information assets.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.1-02",
        "testo": "Gli asset forniti tramite una catena di fornitura devono essere protetti come specificato alla clausola 7.14.",
        "testo_integrale": "REQ-7.3.1-02: The assets provided through a supply chain shall be protected as specified in clause 7.14.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.2-01",
        "testo": "Il TSP deve mantenere un inventario accurato degli asset, quale prerequisito per un'efficace gestione delle vulnerabilità tecniche.",
        "testo_integrale": "REQ-7.3.2-01: The TSP shall maintain an accurate inventory of assets as a prerequisite for effective technical vulnerability management.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.2-02",
        "testo": "Ai fini della classificazione degli asset, il TSP deve: a) stabilire un sistema di livelli di classificazione per gli asset; b) associare tutti gli asset a un livello di classificazione, basato sui requisiti di riservatezza, integrità, autenticità e disponibilità, per indicare la protezione richiesta in base alla loro sensibilità, criticità, rischio e valore aziendale.",
        "testo_integrale": "REQ-7.3.2-02: For asset classification, the TSP shall: a) lay down a system of classification levels for assets; b) associate all assets with a classification level, based on confidentiality, integrity, authenticity and availability requirements, to indicate the protection required according to their sensitivity, criticality, risk and business value.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.2-03",
        "testo": "Il TSP deve assegnare un livello di classificazione a ciascun asset, o gruppo di asset, in base ai requisiti di protezione della riservatezza, integrità, autenticità e disponibilità, e in conformità alla propria valutazione del rischio e al valore aziendale.",
        "testo_integrale": "REQ-7.3.2-03: The TSP shall assign a classification level to each asset, or group of assets, based on requirements for protecting confidentiality, integrity, authenticity and availability, and in accordance with its risk assessment and business value.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.2-04",
        "testo": "Il TSP deve garantire che i requisiti di disponibilità di ciascun asset classificato, o gruppo di asset, siano allineati agli obiettivi di erogazione e ripristino descritti nel piano di continuità operativa e di disaster recovery.",
        "testo_integrale": "REQ-7.3.2-04: The TSP shall assure that the availability requirements of each asset, or group of assets, classified are aligned with the delivery and recovery objectives as described in the business and disaster recovery plan.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.2-05",
        "testo": "Il TSP deve condurre riesami periodici dei livelli di classificazione degli asset e aggiornarli, ove appropriato.",
        "testo_integrale": "REQ-7.3.2-05: The TSP shall conduct periodic reviews of the classification levels of the assets and update them, where appropriate.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.2-06",
        "testo": "Il TSP deve individuare, documentare e attuare regole per l'uso accettabile e procedure per la gestione delle informazioni e degli altri asset correlati.",
        "testo_integrale": "REQ-7.3.2-06: The TSP shall identify, document and implement rules for the acceptable use of and procedures for handling information and other associated assets.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.2-07",
        "testo": "Il TSP deve attuare e documentare procedure per il caso di cambiamento o cessazione del rapporto con personale interno ed esterno, appaltatori o altre terze parti, che prevedano la restituzione di tutti gli asset fisici ed elettronici precedentemente rilasciati, di proprietà del TSP o ad esso affidati.",
        "testo_integrale": "REQ-7.3.2-07: The TSP shall implement and document procedures in case of change or termination process of, internal and external personnel, contractors or other third parties in order to include the return of all previously issued physical and electronic assets owned by or entrusted to the TSP.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.3-01",
        "testo": "Il TSP deve stabilire, attuare e applicare una politica per la corretta gestione degli asset, inclusa la gestione delle informazioni e dei supporti di memorizzazione, in conformità alla propria politica sulla sicurezza dei sistemi di rete e informativi, e deve comunicare tale politica a chiunque utilizzi o gestisca gli asset. La politica deve: a) coprire l'intero ciclo di vita degli asset, inclusi acquisizione, uso, conservazione, trasporto e smaltimento; b) coprire i supporti informativi e di memorizzazione removibili, e la loro gestione da parte di terzi presso i locali del TSP o altre sedi in cui il supporto removibile sia connesso ai sistemi di rete e informativi del TSP; c) fornire regole sull'uso sicuro, la conservazione sicura, il trasporto sicuro e la cancellazione e distruzione irreversibile degli asset; e d) prevedere che il trasferimento avvenga in modo sicuro, in base al tipo di asset da trasferire.",
        "testo_integrale": "REQ-7.3.3-01: The TSP shall establish, implement and apply a policy for the proper handling of assets, including information and storage media management, in accordance with their policy on the security of network and information systems, and shall communicate this policy to anyone who uses or handles assets. The policy shall: a) cover the entire life cycle of the assets, including acquisition, use, storage, transportation and disposal; b) cover the removable information and storage media, and its handling by third parties at the TSP's premises or other locations where the removable media is connected to the TSP's network and information systems; c) provide rules on the safe use, safe storage, safe transport, and the irretrievable deletion and destruction of the assets; and d) provide that the transfer shall take place in a secure manner, in accordance with the type of asset to be transferred.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.3-02",
        "testo": "I supporti di memorizzazione utilizzati nei sistemi del TSP devono essere gestiti in modo sicuro per proteggerli da danni, furto, accesso non autorizzato e obsolescenza.",
        "testo_integrale": "REQ-7.3.3-02: Storage media used within the TSP's systems shall be securely handled to protect storage media from damage, theft, unauthorized access and obsolescence.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.3-03",
        "testo": "Il TSP deve mantenere una procedura di gestione dei supporti di memorizzazione conforme al REQ-7.3.3-02 per l'intera durata del periodo di conservazione dei registri richiesto.",
        "testo_integrale": "REQ-7.3.3-03: The TSP shall maintain a storage media management procedure that complies with REQ-7.3.3-02 for the duration of the required records retention period.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.3-04",
        "testo": "Il TSP deve riesaminare e, ove appropriato, aggiornare la politica a intervalli pianificati e in occasione di incidenti significativi o di cambiamenti significativi alle operazioni o ai rischi.",
        "testo_integrale": "REQ-7.3.3-04: The TSP shall review and, where appropriate, update the policy at planned intervals and when significant incidents or significant changes to operations or risks occur.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.3.3-05",
        "testo": "Il TSP deve stabilire, attuare e applicare una politica specifica sui supporti removibili che deve: a) prevedere il divieto tecnico di connessione dei supporti removibili salvo che sussista una motivazione organizzativa per il loro uso; b) prevedere la disabilitazione dell'autoesecuzione da tali supporti e la scansione dei supporti alla ricerca di codice malevolo prima del loro utilizzo sui sistemi del TSP; c) prevedere misure per il controllo e la protezione dei dispositivi di memorizzazione portatili contenenti dati durante il trasporto e la conservazione; d) ove appropriato, prevedere misure per l'uso di tecniche crittografiche a protezione dei dati sui supporti di memorizzazione removibili.",
        "testo_integrale": "REQ-7.3.3-05: The TSP shall establish, implement and apply a specific policy on removable media that shall: a) provide for a technical prohibition of the connection of removable media unless there is an organisational reason for their use; b) provide for disabling self-execution from such media and scanning the media for malicious code before they are used on the TSP's systems; c) provide measures for controlling and protecting portable storage devices containing data while in transit and in storage; d) where appropriate, provide measures for the use of cryptographic techniques to protect data on removable storage media.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-01",
        "testo": "Il TSP deve stabilire, documentare e attuare politiche di controllo degli accessi logici e fisici per l'accesso ai propri sistemi di rete e informativi, sulla base dei requisiti aziendali e dei requisiti di sicurezza dei sistemi di rete e informativi. Le politiche di controllo degli accessi devono: a) disciplinare l'accesso da parte di persone, incluso il personale, i visitatori e soggetti esterni come fornitori e prestatori di servizi; b) disciplinare l'accesso da parte di sistemi di rete e informativi; c) garantire che l'accesso sia concesso solo a utenti adeguatamente autenticati.",
        "testo_integrale": "REQ-7.4.1-01: The TSP shall establish, document and implement logical and physical access control policies for the access to their network and information systems, based on business requirements as well as network and information system security requirements. The access control policies shall: a) address access by persons, including staff, visitors, and external entities such as suppliers and service providers; b) address access by network and information systems; c) ensure that access is only granted to users that have been adequately authenticated.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-02",
        "testo": "Il TSP deve amministrare l'accesso degli utenti operatori, amministratori e altri account privilegiati e revisori di sistema, applicando il principio del \"minimo privilegio\" nella configurazione dei privilegi di accesso.",
        "testo_integrale": "REQ-7.4.1-02: The TSP shall administer user access of operators, administrators and other privileged accounts and system auditors applying the principle of \"least privileges\" when configuring access privileges.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-03",
        "testo": "Il TSP deve prevedere l'istituzione di account specifici da utilizzare per finalità amministrative quali installazione, configurazione, gestione o manutenzione.",
        "testo_integrale": "REQ-7.4.1-03: The TSP shall provide setting up specific accounts to be used for administrative purposes like installation, configuration, management or maintenance.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-04",
        "testo": "Gli account privilegiati devono essere utilizzati solo se i privilegi sono necessari per l'attività specifica.",
        "testo_integrale": "REQ-7.4.1-04: Privileged accounts shall be used only if the privileges are necessary for the specific activity.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-05",
        "testo": "Per gli account privilegiati devono essere utilizzate procedure forti di identificazione, autenticazione e autorizzazione. Ciò si applica in generale al personale nominato ai ruoli fiduciari ai sensi del REQ-7.2-14.",
        "testo_integrale": "REQ-7.4.1-05: Strong identification, authentication and authorisation procedures shall be used for privileged accounts. NOTE 1: This generally applies to personnel appointed to trusted roles as per REQ-7.2-14.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-06",
        "testo": "Ove appropriato, il TSP deve garantire che utenti e dispositivi siano autenticati tramite meccanismi di autenticazione a più fattori o continua, come voce, video e testo sicuri, prima di accedere alla rete del TSP e ai relativi sistemi informativi, in base alla classificazione dei sistemi a cui si accede.",
        "testo_integrale": "[CONDITIONAL] REQ-7.4.1-06: Where appropriate, the TSP shall ensure that users and devices are authenticated by multi-factor or continuous authentication mechanisms, such as secure voice, video and text, before accessing the TSP's network and ITS information systems, depending on the classification of the systems to be accessed.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
        "condizione_applicabilita": "si applica ove appropriato, in base alla classificazione dei sistemi a cui si accede",
    },
    {
        "riferimento": "REQ-7.4.1-07",
        "testo": "Il TSP deve concedere, modificare, revocare e documentare i diritti di accesso ai sistemi di rete e informativi in conformità alla politica di controllo degli accessi. Inoltre: a) il TSP deve riesaminare i diritti di accesso agli account privilegiati e amministrativi a intervalli pianificati, e i diritti di accesso devono essere modificati in base ai cambiamenti organizzativi; b) l'esito del riesame, incluse le necessarie modifiche dei diritti di accesso, deve essere documentato.",
        "testo_integrale": "REQ-7.4.1-07: The TSP shall provide, modify, remove and document access rights to network and information systems in accordance with the access control policy. In addition: a) The TSP shall review access rights to privileged and administrator accounts at planned intervals, and access rights shall be modified based on organisational changes. b) The result of the review, including the necessary changes of access rights, shall be documented.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-08",
        "testo": "Il TSP deve: a) assegnare e revocare i diritti di accesso in base ai principi di necessità di conoscere (need-to-know), minimo privilegio e separazione dei compiti; b) garantire che i diritti di accesso siano modificati di conseguenza in caso di cessazione o cambiamento del rapporto di lavoro; c) garantire che l'accesso ai sistemi di rete e informativi sia autorizzato dalle persone competenti; d) garantire che i diritti di accesso disciplinino adeguatamente l'accesso di terze parti, come visitatori, fornitori e prestatori di servizi, in particolare limitando i diritti di accesso per ambito e durata; e) mantenere un registro dei diritti di accesso concessi; e f) applicare la registrazione (logging) alla gestione dei diritti di accesso.",
        "testo_integrale": "REQ-7.4.1-08: The TSP shall: a) assign and revoke access rights based on the principles of need-to-know, least privilege and separation of duties; b) ensure that access rights are modified accordingly upon termination or change of employment; c) ensure that access to network and information systems is authorised by the relevant persons; d) ensure that access rights appropriately address third-party access, such as visitors, suppliers and service providers, in particular by limiting access rights in scope and in duration; e) maintain a register of access rights granted; and f) apply logging to the management of access rights.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-09",
        "testo": "L'accesso alle informazioni e alle funzioni dei sistemi applicativi deve essere limitato in conformità alla politica di controllo degli accessi.",
        "testo_integrale": "REQ-7.4.1-09: Access to information and application system functions shall be restricted in accordance with the access control policy.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-10",
        "testo": "Il sistema del TSP deve fornire controlli di sicurezza informatica sufficienti per la separazione dei ruoli fiduciari individuati nelle pratiche del TSP, inclusa la separazione tra le funzioni di amministrazione della sicurezza e di esercizio. In particolare, l'uso dei programmi di utilità di sistema deve essere limitato e controllato.",
        "testo_integrale": "REQ-7.4.1-10: The TSP's system shall provide sufficient computer security controls for the separation of trusted roles identified in TSP's practices, including the separation of security administration and operation functions. Particularly, use of system utility programs shall be restricted and controlled.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-11",
        "testo": "Il personale del TSP deve essere identificato e autenticato prima di utilizzare le applicazioni critiche relative al servizio.",
        "testo_integrale": "REQ-7.4.1-11: TSP's personnel shall be identified and authenticated before using critical applications related to the service.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-12",
        "testo": "Il personale del TSP deve essere responsabile (accountable) delle proprie attività, ad esempio mediante la conservazione dei log degli eventi.",
        "testo_integrale": "REQ-7.4.1-12: TSP's personnel shall be accountable for their activities. EXAMPLE: By retaining event logs.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-13",
        "testo": "I dati sensibili devono essere protetti dal rischio di essere rivelati tramite oggetti di memorizzazione riutilizzati (ad esempio file cancellati) o supporti di memorizzazione (cfr. clausola 7.3.2) resi accessibili a utenti non autorizzati.",
        "testo_integrale": "REQ-7.4.1-13: Sensitive data shall be protected against being revealed through re-used storage objects (e.g. deleted files) or storage media (see clause 7.3.2) being accessible to unauthorized users.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.1-14",
        "testo": "Il TSP deve riesaminare e, ove appropriato, aggiornare le politiche di controllo degli accessi a intervalli pianificati e in occasione di incidenti significativi o di cambiamenti significativi alle operazioni o ai rischi.",
        "testo_integrale": "REQ-7.4.1-14: The TSP shall review and, where appropriate, update the access control policies at planned intervals and when significant incidents or significant changes to operations or risks occur.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.2-01",
        "testo": "Il TSP deve mantenere politiche per la gestione degli account privilegiati e degli account di amministrazione del sistema, quale parte della politica di controllo degli accessi.",
        "testo_integrale": "REQ-7.4.2-01: The TSP shall maintain policies for management of privileged accounts and system administration accounts as part of the access control policy.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.2-02",
        "testo": "Le politiche per gli account privilegiati e gli account di amministrazione del sistema devono: a) stabilire procedure forti di identificazione, autenticazione (come l'autenticazione a più fattori) e autorizzazione per gli account privilegiati e di amministrazione del sistema; b) istituire account specifici da utilizzare esclusivamente per le operazioni di amministrazione del sistema, quali installazione, configurazione, gestione o manutenzione; c) individualizzare e limitare al massimo grado possibile i privilegi di amministrazione del sistema; d) prevedere che gli account di amministrazione del sistema siano utilizzati solo per connettersi ai sistemi di amministrazione del sistema.",
        "testo_integrale": "REQ-7.4.2-02: The policies for privileged accounts and system administration accounts shall: a) establish strong identification, authentication such as multi-factor authentication, and authorisation procedures for privileged accounts and system administration accounts; b) set up specific accounts to be used for system administration operations exclusively, such as installation, configuration, management or maintenance; c) individualise and restrict system administration privileges to the highest extent possible; d) provide that system administration accounts are only used to connect to system administration systems.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.2-03",
        "testo": "Il TSP deve riesaminare e documentare i diritti di accesso degli account privilegiati e di amministrazione del sistema a intervalli pianificati, incluse le necessarie modifiche dei diritti di accesso.",
        "testo_integrale": "REQ-7.4.2-03: The TSP shall review and document access rights of privileged and system administration accounts at planned intervals, including the necessary changes of access rights.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.3-01",
        "testo": "Il TSP deve limitare e controllare l'uso dei sistemi di amministrazione.",
        "testo_integrale": "REQ-7.4.3-01: The TSP shall restrict and control the use of administration systems.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.3-02",
        "testo": "Per i sistemi di amministrazione del sistema, il TSP deve: a) utilizzare i sistemi di amministrazione del sistema esclusivamente per finalità di amministrazione del sistema, e non per altre operazioni; b) separare logicamente tali sistemi dal software applicativo non utilizzato per finalità di amministrazione del sistema; e c) proteggere l'accesso ai sistemi di amministrazione del sistema mediante autenticazione e cifratura.",
        "testo_integrale": "REQ-7.4.3-02: For system administration systems, the TSP shall: a) only use system administration systems for system administration purposes, and not for any other operations; b) separate logically such systems from application software not used for system administrative purposes; and c) protect access to system administration systems through authentication and encryption.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.4-01",
        "testo": "Il TSP deve gestire l'intero ciclo di vita delle identità dei sistemi di rete e informativi e dei relativi utenti.",
        "testo_integrale": "REQ-7.4.4-01: The TSP shall manage the full life cycle of identities of network and information systems and their users.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.4-02",
        "testo": "Ai fini della gestione delle identità, il TSP deve: a) istituire identità univoche per i sistemi di rete e informativi e per i relativi utenti; b) collegare l'identità degli utenti a un'unica persona; c) garantire la supervisione delle identità dei sistemi di rete e informativi; e d) applicare la registrazione (logging) alla gestione delle identità.",
        "testo_integrale": "REQ-7.4.4-02: For identity management, the TSP shall: a) set up unique identities for network and information systems and their users; b) link the identity of users to a single person; c) ensure oversight of identities of network and information systems; and d) apply logging to the management of identities.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.4-03",
        "testo": "Il TSP deve consentire identità assegnate a più persone, come le identità condivise, solo laddove siano necessarie per motivi aziendali od operativi e siano soggette a un processo esplicito di approvazione e a documentazione.",
        "testo_integrale": "REQ-7.4.4-03: The TSP shall only permit identities assigned to multiple persons, such as shared identities, where they are necessary for business or operational reasons and are subject to an explicit approval process and documentation.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.4-04",
        "testo": "Il TSP deve tenere conto delle identità assegnate a più persone nel proprio quadro di gestione del rischio di cybersicurezza.",
        "testo_integrale": "REQ-7.4.4-04: The TSP shall take identities assigned to multiple persons into account in the cybersecurity risk management framework.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.4-05",
        "testo": "Il TSP deve riesaminare regolarmente le identità dei sistemi di rete e informativi e dei relativi utenti e, se non più necessarie, disattivarle senza ritardo.",
        "testo_integrale": "REQ-7.4.4-05: The TSP shall regularly review the identities for network and information systems and their users and, if no longer needed, deactivate them without delay.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.5-01",
        "testo": "Il TSP deve attuare procedure e tecnologie di autenticazione sicure, basate sulle restrizioni di accesso e sulla politica di controllo degli accessi.",
        "testo_integrale": "REQ-7.4.5-01: The TSP shall implement secure authentication procedures and technologies based on access restrictions and the policy on access control.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.5-02",
        "testo": "Ai fini dell'autenticazione, il TSP deve: a) garantire che la robustezza dell'autenticazione sia adeguata alla classificazione dell'asset a cui si accede; b) controllare l'assegnazione agli utenti e la gestione delle informazioni segrete di autenticazione mediante un processo che ne garantisca la riservatezza, comprese le indicazioni al personale sulla corretta gestione di tali informazioni; c) richiedere la modifica delle credenziali di autenticazione inizialmente, a intervalli predefiniti e in caso di sospetto di compromissione delle credenziali; d) richiedere il reset delle credenziali di autenticazione e il blocco degli utenti dopo un numero predefinito di tentativi di accesso falliti; e) terminare le sessioni inattive dopo un periodo predefinito di inattività; e f) richiedere credenziali separate per l'accesso privilegiato o agli account amministrativi.",
        "testo_integrale": "REQ-7.4.5-02: For authentication, the TSP shall: a) ensure the strength of authentication is appropriate to the classification of the asset to be accessed; b) control the allocation to users and management of secret authentication information by a process that ensures the confidentiality of the information, including advising personnel on appropriate handling of authentication information; c) require the change of authentication credentials initially, at predefined intervals and upon suspicion that the credentials were compromised; d) require the reset of authentication credentials and the blocking of users after a predefined number of unsuccessful log-in attempts; e) terminate inactive sessions after a predefined period of inactivity; and f) require separate credentials to access privileged access or administrative accounts.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.5-03",
        "testo": "Il TSP deve, nella misura in cui ciò sia fattibile, utilizzare metodi di autenticazione allo stato dell'arte, in conformità al rischio valutato associato e alla classificazione dell'asset a cui si accede, e informazioni di autenticazione univoche.",
        "testo_integrale": "REQ-7.4.5-03: The TSP shall to the extent feasible use state-of-the-art authentication methods, in accordance with the associated assessed risk and the classification of the asset to be accessed, and unique authentication information.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.5-04",
        "testo": "Il TSP deve riesaminare le procedure e le tecnologie di autenticazione a intervalli pianificati.",
        "testo_integrale": "REQ-7.4.5-04: The TSP shall review the authentication procedures and technologies at planned intervals.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.4.6-01",
        "testo": "Il TSP deve garantire che gli utenti siano autenticati come specificato nel REQ-7.4.1-06 e nel REQ-7.4.5-02, lettera a).",
        "testo_integrale": "REQ-7.4.6-01: The TSP shall ensure that users are authenticated as specified in REQ-7.4.1-06 and REQ-7.4.5-02, a).",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.5-01",
        "testo": "Devono essere presenti controlli di sicurezza adeguati per la gestione di qualsiasi chiave crittografica, algoritmo crittografico e dispositivo crittografico lungo l'intero ciclo di vita.",
        "testo_integrale": "REQ-7.5-01: Appropriate security controls shall be in place for the management of any cryptographic keys, cryptographic algorithms, and cryptographic devices throughout their lifecycle.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.5-02",
        "testo": "Il TSP deve stabilire, attuare e applicare una politica e procedure relative alla crittografia, al fine di garantire un uso adeguato ed efficace della crittografia per proteggere la riservatezza, l'autenticità e l'integrità dei dati, in linea con la classificazione degli asset del TSP e con i risultati della valutazione del rischio.",
        "testo_integrale": "REQ-7.5-02: The TSP shall establish, implement and apply a policy and procedures related to cryptography, with a view to ensuring adequate and effective use of cryptography to protect the confidentiality, authenticity and integrity of data in line with the TSP's asset classification and the results of the risk assessment.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.5-03",
        "testo": "La politica e le procedure per la crittografia devono stabilire: a) in conformità alla classificazione degli asset del TSP, il tipo, la robustezza e la qualità delle misure crittografiche richieste per proteggere gli asset del TSP, inclusi i dati a riposo e i dati in transito; b) sulla base del punto a), i protocolli o le famiglie di protocolli da adottare, nonché gli algoritmi crittografici, la robustezza dei cifrari, le soluzioni crittografiche e le pratiche d'uso da approvare e richiedere per l'uso da parte del TSP, seguendo, ove appropriato, un approccio di agilità crittografica; e c) l'approccio del TSP alla gestione delle chiavi, inclusi, ove appropriato, metodi per: i) generare chiavi diverse per sistemi e applicazioni crittografiche; ii) emettere e ottenere certificati di chiave pubblica; iii) distribuire le chiavi alle entità destinatarie, incluso come attivarle alla ricezione; iv) conservare le chiavi, incluso come gli utenti autorizzati ottengano l'accesso alle chiavi; v) modificare o aggiornare le chiavi, incluse le regole su quando e come cambiarle; vi) gestire le chiavi compromesse; vii) revocare le chiavi, incluso come ritirarle o disattivarle; viii) recuperare le chiavi perse o corrotte; ix) eseguire il backup o l'archiviazione delle chiavi; x) distruggere le chiavi; xi) registrare e sottoporre ad audit le attività relative alla gestione delle chiavi; e xii) stabilire le date di attivazione e disattivazione delle chiavi, garantendo che possano essere utilizzate solo per il periodo di tempo specificato secondo le regole dell'organizzazione sulla gestione delle chiavi. Per i TSP che emettono certificati in conformità a ETSI EN 319 411-1 o ETSI EN 319 411-2, i requisiti di gestione delle chiavi specificati in tali standard soddisfano il presente requisito.",
        "testo_integrale": "REQ-7.5-03: The policy and procedures for cryptography shall establish: a) in accordance with the TSP's classification of assets, the type, strength and quality of the cryptographic measures required to protect the TSP's assets, including data at rest and data in transit; b) based on point a), the protocols or families of protocols to be adopted, as well as cryptographic algorithms, cipher strength, cryptographic solutions and usage practices to be approved and required for use by the TSP, following, where appropriate, a cryptographic agility approach; and c) the TSP's approach to key management, including, where appropriate, methods for the following: i) generating different keys for cryptographic systems and applications; ii) issuing and obtaining public key certificates; iii) distributing keys to intended entities, including how to activate keys when received; iv) storing keys, including how authorised users obtain access to keys; v) changing or updating keys, including rules on when and how to change keys; vi) dealing with compromised keys; vii) revoking keys including how to withdraw or deactivate keys; viii) recovering lost or corrupted keys; ix) backing up or archiving keys; x) destroying keys; xi) logging and auditing of key management-related activities; and xii) setting activation and deactivation dates for keys ensuring that the keys can only be used for the specified period of time according to the organization's rules on key management. NOTE 2: For TSPs issuing certificates in accordance with ETSI EN 319 411-1 [i.5] or ETSI EN 319 411-2 [i.7], the key management requirements specified in those standards fulfil this requirement.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.5-04",
        "testo": "Il TSP deve riesaminare e, ove appropriato, aggiornare la propria politica e le procedure di crittografia a intervalli pianificati, tenendo conto dello stato dell'arte in materia di crittografia.",
        "testo_integrale": "REQ-7.5-04: The TSP shall review and, where appropriate, update their cryptography policy and procedures at planned intervals, taking into account the state of the art in cryptography.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "REQ-7.5-05",
        "testo": "Ai fini dell'erogazione dei propri servizi fiduciari, il TSP dovrebbe selezionare e utilizzare tecniche crittografiche idonee, in conformità a standard riconosciuti come ETSI TS 119 312.",
        "testo_integrale": "REQ-7.5-05: For the purpose of the provision of its trust services, the TSP should select and use suitable cryptographic techniques in accordance with recognized standards such as ETSI TS 119 312 [1].",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
]

RIGHE_PRINCIPI: list[dict] = []

INDICE_ARTICOLI_LOCALE = [
    "REQ-7.1.1-01",
    "REQ-7.1.1-02",
    "REQ-7.1.1-03",
    "PRO-7.1.1-04",
    "REQ-7.1.1-05",
    "REQ-7.1.2-01",
    "REQ-7.1.2-02",
    "REQ-7.1.2-03",
    "REQ-7.1.2-04",
    "REQ-7.1.2-05",
    "REQ-7.1.2-06",
    "REQ-7.1.3-01",
    "REQ-7.2-01",
    "REQ-7.2-02",
    "REQ-7.2-03",
    "REQ-7.2-04",
    "REQ-7.2-05",
    "REQ-7.2-06",
    "REQ-7.2-07",
    "REQ-7.2-08",
    "REQ-7.2-09",
    "PRO-7.2-10",
    "REQ-7.2-11",
    "REQ-7.2-12",
    "REQ-7.2-13",
    "REQ-7.2-14",
    "REQ-7.2-15",
    "REQ-7.2-16",
    "REQ-7.2-17",
    "REQ-7.2-18",
    "REQ-7.2-19",
    "REQ-7.2-20",
    "REQ-7.2-21",
    "REQ-7.2-22",
    "REQ-7.2-23",
    "REQ-7.2-24",
    "REQ-7.3.1-01",
    "REQ-7.3.1-02",
    "REQ-7.3.2-01",
    "REQ-7.3.2-02",
    "REQ-7.3.2-03",
    "REQ-7.3.2-04",
    "REQ-7.3.2-05",
    "REQ-7.3.2-06",
    "REQ-7.3.2-07",
    "REQ-7.3.3-01",
    "REQ-7.3.3-02",
    "REQ-7.3.3-03",
    "REQ-7.3.3-04",
    "REQ-7.3.3-05",
    "REQ-7.4.1-01",
    "REQ-7.4.1-02",
    "REQ-7.4.1-03",
    "REQ-7.4.1-04",
    "REQ-7.4.1-05",
    "REQ-7.4.1-06",
    "REQ-7.4.1-07",
    "REQ-7.4.1-08",
    "REQ-7.4.1-09",
    "REQ-7.4.1-10",
    "REQ-7.4.1-11",
    "REQ-7.4.1-12",
    "REQ-7.4.1-13",
    "REQ-7.4.1-14",
    "REQ-7.4.2-01",
    "REQ-7.4.2-02",
    "REQ-7.4.2-03",
    "REQ-7.4.3-01",
    "REQ-7.4.3-02",
    "REQ-7.4.4-01",
    "REQ-7.4.4-02",
    "REQ-7.4.4-03",
    "REQ-7.4.4-04",
    "REQ-7.4.4-05",
    "REQ-7.4.5-01",
    "REQ-7.4.5-02",
    "REQ-7.4.5-03",
    "REQ-7.4.5-04",
    "REQ-7.4.6-01",
    "REQ-7.5-01",
    "REQ-7.5-02",
    "REQ-7.5-03",
    "REQ-7.5-04",
    "REQ-7.5-05",
]

MAPPATURA_LOCALE = {rif: [rif] for rif in INDICE_ARTICOLI_LOCALE}

RELAZIONI: list[dict] = []
