"""CAD (D.Lgs. 82/2005) - Capo I, parte 1: Principi generali (artt. 1-5-bis).

Estrazione granulare ADR-0007 dal testo ufficiale vigente al 16/09/2026
(fonte: app/.source_cache/cad/cap01.txt). Copertura completa comma/lettera:
nessun discrimine di rilevanza, incluse le disposizioni di scopo/ambito e le
lettere/commi abrogati o soppressi (censiti con stato "abrogato").
"""

RIGHE_OBBLIGHI = [
    {
        "riferimento": "art. 2 c.1",
        "testo": "Lo Stato, le Regioni e le autonomie locali assicurano la disponibilità, gestione, accesso, trasmissione, conservazione e fruibilità dell'informazione in modalità digitale, organizzandosi e utilizzando le tecnologie dell'informazione e della comunicazione nel modo più adeguato agli interessi degli utenti.",
        "testo_integrale": "Lo Stato, le Regioni e le autonomie locali assicurano la disponibilita', la gestione, l'accesso, la trasmissione, la conservazione e la fruibilita' dell'informazione in modalita' digitale e si organizzano ed agiscono a tale fine utilizzando con le modalita' piu' appropriate e nel modo piu' adeguato al soddisfacimento degli interessi degli utenti le tecnologie dell'informazione e della comunicazione.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 2 c.6-bis",
        "testo": "Fermo restando che il Codice si applica agli atti di liquidazione, rettifica, accertamento e irrogazione di sanzioni tributarie, un DPCM o del Ministro delegato, su proposta del Ministro dell'economia e delle finanze, stabilisce modalità e termini di applicazione del Codice alle attività e funzioni ispettive e di controllo fiscale.",
        "testo_integrale": "Ferma restando l'applicabilita' delle disposizioni del presente decreto agli atti di liquidazione, rettifica, accertamento e di irrogazione delle sanzioni di natura tributaria, con decreto del Presidente del Consiglio dei ministri o del Ministro delegato, adottato su proposta del Ministro dell'economia e delle finanze, sono stabiliti le modalita' e i termini di applicazione delle disposizioni del presente Codice alle attivita' e funzioni ispettive e di controllo fiscale.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.1",
        "testo": "I soggetti di cui all'art. 2 c.2, i professionisti tenuti all'iscrizione in albi ed elenchi e i soggetti tenuti all'iscrizione nel registro delle imprese hanno l'obbligo di dotarsi di un domicilio digitale iscritto nell'elenco di cui agli artt. 6-bis o 6-ter.",
        "testo_integrale": "I soggetti di cui all'articolo 2, comma 2, i professionisti tenuti all'iscrizione in albi ed elenchi e i soggetti tenuti all'iscrizione nel registro delle imprese hanno l'obbligo di dotarsi di un domicilio digitale iscritto nell'elenco di cui agli articoli 6-bis o 6-ter.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.1-quater",
        "testo": "I soggetti di cui ai commi 1 e 1-bis devono fare uso diligente del proprio domicilio digitale e comunicarne ogni modifica secondo le Linee guida, che disciplinano anche l'aggiornamento dell'elenco di cui all'art. 6-quater in caso di decesso del titolare o di impossibilità sopravvenuta di avvalersene.",
        "testo_integrale": "I soggetti di cui ai commi 1 e 1-bis hanno l'obbligo di fare un uso diligente del proprio domicilio digitale e di comunicare ogni modifica o variazione del medesimo secondo le modalita' fissate nelle Linee guida. Con le stesse Linee guida, fermo restando quanto previsto ai commi 3-bis e 4-bis, sono definite le modalita' di gestione e di aggiornamento dell'elenco di cui all'articolo 6-quater anche nei casi di decesso del titolare del domicilio digitale eletto o di impossibilita' sopravvenuta di avvalersi del domicilio.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.3-bis",
        "testo": "Con DPCM o del Ministro delegato per la semplificazione e la P.A., sentiti AgID e Garante privacy e acquisito il parere della Conferenza unificata, è stabilita la data da cui le comunicazioni tra i soggetti di cui all'art. 2 c.2 e chi non ha eletto un domicilio digitale ai sensi del comma 1-bis avvengono esclusivamente in forma elettronica, determinando anche le modalità di attribuzione di un domicilio digitale o altre modalità di consegna dei documenti a chi ha un divario digitale.",
        "testo_integrale": "Con decreto del Presidente del Consiglio dei ministri o del Ministro delegato per la semplificazione e la pubblica amministrazione, sentiti l'AgID e il Garante per la protezione dei dati personali e acquisito il parere della Conferenza unificata, e' stabilita la data a decorrere dalla quale le comunicazioni tra i soggetti di cui all'articolo 2, comma 2, e coloro che non hanno provveduto a eleggere un domicilio digitale ai sensi del comma 1-bis, avvengono esclusivamente in forma elettronica. Con lo stesso decreto sono determinate le modalita' con le quali ai predetti soggetti e' attribuito un domicilio digitale ovvero altre modalita' con le quali, anche per superare il divario digitale, i documenti possono essere messi a disposizione e consegnati a coloro che non hanno accesso ad un domicilio digitale.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.4",
        "testo": "Dal 1° gennaio 2013, salvo diversa modalità di comunicazione/pubblicazione telematica prevista dalla normativa vigente, le amministrazioni pubbliche e i gestori o esercenti di pubblici servizi comunicano con la persona fisica esclusivamente tramite il domicilio digitale da essa dichiarato, pena l'applicazione dell'art. 18-bis.",
        "testo_integrale": "A decorrere dal 1° gennaio 2013, salvo i casi in cui e' prevista dalla normativa vigente una diversa modalita' di comunicazione o di pubblicazione in via telematica, le amministrazioni pubbliche e i gestori o esercenti di pubblici servizi comunicano con il cittadino esclusivamente tramite il domicilio digitale dallo stesso dichiarato ((. Per la violazione della presente disposizione si applica l'articolo 18-bis)). (28)",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "sanzioni": "art. 18-bis CAD",
    },
    {
        "riferimento": "art. 3-ter c.4",
        "testo": "Con decreto del Ministro dell'interno, di concerto con l'autorità politica delegata per l'innovazione tecnologica e con il Ministro per la P.A., sentito il Garante privacy, su proposta di AgID, possono essere individuate informazioni ulteriori rispetto a quelle del comma 3 e aggiornate le categorie di strumenti digitali del comma 2 in relazione all'evoluzione tecnologica.",
        "testo_integrale": "Con decreto del Ministro dell'interno, di concerto con l'Autorita' politica delegata in materia di innovazione tecnologica e transizione ((digitale e con il)) Ministro per la pubblica amministrazione, sentito il Garante per la protezione dei dati personali, su proposta dell'Agenzia per l'Italia digitale (AgID), possono essere individuate ((informazioni ulteriori)) rispetto a quelle previste dal comma 3 e possono essere aggiornate, in relazione alla evoluzione tecnologica, le categorie di strumenti digitali di cui al comma 2.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.5",
        "testo": "I gestori degli strumenti digitali mettono a disposizione dell'ANPR, tramite la piattaforma di cui all'art. 50-ter, i dati dei commi 3 e 4 entro il 30 aprile 2026 e li aggiornano costantemente al variare dello stato dello strumento; in caso di mancata registrazione/aggiornamento, ferme le responsabilità dei gestori verso il cittadino, AgID applica le sanzioni di cui agli artt. 32-bis o 18-bis nell'ambito dei poteri di vigilanza ex art. 14-bis c.2 lett. i).",
        "testo_integrale": "I dati di cui ai commi 3 e 4 sono messi a disposizione dell'ANPR dai gestori degli strumenti digitali tramite i servizi della piattaforma di cui all'articolo 50-ter entro il 30 aprile 2026 e costantemente ((aggiornati)) dagli stessi gestori al verificarsi delle variazioni di stato dello strumento mediante i servizi della medesima piattaforma di cui all'articolo 50-ter. In caso di mancata registrazione e ((aggiornamento)) nell'ANPR dei dati di cui al comma 2, ferme restando le responsabilita' dei gestori degli strumenti digitali nei confronti del cittadino, l'AgID, nell'ambito dei poteri di vigilanza di cui all'articolo 14-bis, comma 2, lettera i), applica le sanzioni previste dall'articolo 32-bis ovvero dall'articolo 18-bis. L'AgID assicura, tramite propri provvedimenti, il coordinamento con i gestori degli strumenti digitali ai fini del costante ((aggiornamento)) dei dati di cui ai commi 3 e 4.",
        "tipo_obbligo": "informativo/trasparenza",
        "stato": "vigente",
        "sanzioni": "art. 32-bis ovvero art. 18-bis CAD, applicate dall'AgID nell'ambito dei poteri di vigilanza ex art. 14-bis c.2 lett. i)",
    },
    {
        "riferimento": "art. 3-ter c.6",
        "testo": "L'ANPR comunica al cittadino ogni nuova attivazione degli strumenti digitali a lui riferibili, anche tramite il punto di accesso telematico di cui all'art. 64-bis o la piattaforma per le notifiche di cui all'art. 1 c.402 della l. 160/2019.",
        "testo_integrale": "L'ANPR comunica al cittadino ogni nuova attivazione degli strumenti digitali a lui riferibili, anche avvalendosi del punto di accesso telematico di cui all'articolo 64-bis ovvero della piattaforma digitale per le notifiche di cui all' articolo 1, comma 402, della legge 27 dicembre 2019, n. 160.",
        "tipo_obbligo": "informativo/trasparenza",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.7",
        "testo": "I gestori dell'identità digitale, tranne quella connessa alla carta d'identità elettronica, verificano e comunicano al richiedente, prima del rilascio e tramite la piattaforma di cui all'art. 50-ter, l'eventuale preesistenza di identità digitali già associate alla stessa persona.",
        "testo_integrale": "I gestori dell'identita' digitale, ad eccezione dell'identita' digitale connessa alla carta d'identita' elettronica, verificano e comunicano al richiedente prima del rilascio dell'identita' digitale, tramite la piattaforma di cui all'articolo 50-ter, la preesistenza di identita' digitali gia' associate alla medesima persona.",
        "tipo_obbligo": "informativo/trasparenza",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.13",
        "testo": "Le informazioni di cui ai commi 3 e 4 sono conservate nell'ANPR per un massimo di dodici mesi dalla registrazione della revoca o scadenza dello strumento e sono consultabili, previa autenticazione con livello di garanzia almeno significativo, solo dal cittadino interessato, fermi i commi 7-9; si applicano le misure tecniche/organizzative dell'allegato C al DPCM 194/2014 e le misure di sicurezza delle linee guida AgID ex art. 50-ter c.2.",
        "testo_integrale": "Le informazioni di cui ai commi 3 e 4 sono conservate nell'ANPR ((per la durata massima)) di dodici mesi dalla registrazione della revoca o della scadenza dello strumento da parte dei gestori e sono consultabili, previa autenticazione con livello di garanzia almeno significativo, esclusivamente dal cittadino cui si riferiscono, fermo restando quanto previsto ai commi 7, 8 e 9. Con riferimento ai trattamenti di dati personali, si applicano le misure tecniche e organizzative di cui all'allegato C al ((regolamento di cui al)) decreto del Presidente del Consiglio dei ministri 10 novembre 2014, n. 194, oltre che le specifiche misure di sicurezza di cui alle linee guida adottate dall'AgID ai sensi dell'articolo 50-ter, comma 2.",
        "tipo_obbligo": "di conservazione",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.14",
        "testo": "L'ANPR garantisce l'accesso ai dati dei commi 3 e 4 esclusivamente al cittadino interessato o al suo delegato ex art. 64-ter, e ai gestori degli strumenti digitali di cui al comma 2 per le finalità dell'articolo.",
        "testo_integrale": "L'ANPR assicura l'accesso ai dati di cui ai commi 3 e 4 esclusivamente al cittadino cui si riferiscono o al suo delegato ai sensi dell'articolo 64-ter e ai gestori degli strumenti digitali di cui al comma 2 per le finalita' di cui al presente articolo.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5 c.1",
        "testo": "I soggetti di cui all'art. 2 c.2 sono obbligati ad accettare, tramite la piattaforma di cui al comma 2, i pagamenti spettanti a qualsiasi titolo con sistemi di pagamento elettronico, inclusi, per i micro-pagamenti, quelli basati sul credito telefonico; resta ferma, tramite la stessa piattaforma, la possibilità di accettare altre forme di pagamento elettronico senza discriminazione tra schemi di pagamento abilitati ai sensi dell'art. 2 punti 33, 34 e 35 del regolamento UE 2015/751.",
        "testo_integrale": "I soggetti di cui all'articolo 2, comma 2, sono obbligati ad accettare, tramite la piattaforma di cui al comma 2, i pagamenti spettanti a qualsiasi titolo attraverso sistemi di pagamento elettronico, ivi inclusi, per i micro-pagamenti, quelli basati sull'uso del credito telefonico. Tramite la piattaforma elettronica di cui al comma 2, resta ferma la possibilita' di accettare anche altre forme di pagamento elettronico, senza discriminazione in relazione allo schema di pagamento abilitato per ciascuna tipologia di strumento di pagamento elettronico come definita ai sensi dell'articolo 2, punti 33), 34) e 35) del regolamento UE 2015/751 del Parlamento europeo e del Consiglio del 29 aprile 2015 relativo alle commissioni interbancarie sulle operazioni di pagamento basate su carta.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5 c.2",
        "testo": "Per attuare il comma 1, la Presidenza del Consiglio dei ministri mette a disposizione, tramite il Sistema pubblico di connettività, una piattaforma tecnologica per l'interconnessione e l'interoperabilità tra pubbliche amministrazioni e prestatori di servizi di pagamento abilitati, assicurando tramite gli strumenti dell'art. 64 l'autenticazione dei soggetti nell'intero processo di pagamento.",
        "testo_integrale": "Al fine di dare attuazione al comma 1, la Presidenza del Consiglio dei ministri mette a disposizione, attraverso il Sistema pubblico di connettivita', una piattaforma tecnologica per l'interconnessione e l'interoperabilita' tra le pubbliche amministrazioni e i prestatori di servizi di pagamento abilitati, al fine di assicurare, attraverso gli strumenti di cui all'articolo 64, l'autenticazione dei soggetti interessati all'operazione in tutta la gestione del processo di pagamento. (29) (31) (34) (36)",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5 c.2-ter",
        "testo": "I soggetti di cui all'art. 2 c.2 consentono di effettuare pagamenti elettronici tramite la piattaforma di cui al comma 2 anche per il pagamento spontaneo di tributi ex art. 2-bis del d.l. 193/2016.",
        "testo_integrale": "I soggetti di cui all'articolo 2, comma 2, consentono di effettuare pagamenti elettronici tramite la piattaforma di cui al comma 2 anche per il pagamento spontaneo di tributi di cui all'articolo 2-bis del decreto-legge 22 ottobre 2016, n. 193, convertito, con modificazioni dalla legge 1° dicembre 2016, n. 225.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5 c.2-quater",
        "testo": "I prestatori di servizi di pagamento abilitati eseguono i pagamenti verso le pubbliche amministrazioni tramite la piattaforma di cui al comma 2, fermo restando il sistema dei versamenti unitari di cui all'art. 17 e ss. del d.lgs. 241/1997, Capo III.",
        "testo_integrale": "I prestatori di servizi di pagamento abilitati eseguono pagamenti a favore delle pubbliche amministrazioni attraverso l'utilizzo della piattaforma di cui al comma 2. Resta fermo il sistema dei versamenti unitari di cui all'articolo 17 e seguenti del decreto legislativo 9 luglio 1997, n. 241, Capo III ((...)).",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5 c.2-quinquies",
        "testo": "Tramite la piattaforma di cui al comma 2, le informazioni sui pagamenti sono messe a disposizione anche del Ministero dell'economia e delle finanze - Dipartimento Ragioneria generale dello Stato.",
        "testo_integrale": "Tramite la piattaforma di cui al comma 2, le informazioni sui pagamenti sono messe a disposizione anche del Ministero dell'economia e delle finanze - Dipartimento Ragioneria generale dello Stato.",
        "tipo_obbligo": "informativo/trasparenza",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5 c.2-septies",
        "testo": "Con DPCM o del Ministro delegato per l'innovazione tecnologica e la digitalizzazione, di concerto con il Ministro dell'economia e delle finanze, sono definite le regole tecniche di funzionamento della piattaforma tecnologica e dei processi di cui al comma 2-sexies.",
        "testo_integrale": "Con decreto del Presidente del Consiglio dei Ministri o del Ministro delegato per l'innovazione tecnologica e la digitalizzazione, di concerto con il Ministro dell'economia e delle finanze, sono definite le regole tecniche di funzionamento della piattaforma tecnologica e dei processi di cui al comma 2-sexies.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5 c.4",
        "testo": "L'Agenzia per l'Italia digitale, sentita la Banca d'Italia, definisce linee guida per l'attuazione dell'articolo e per la specifica dei codici identificativi del pagamento di cui al comma 1, nonché le modalità con cui il prestatore dei servizi di pagamento mette a disposizione dell'ente le informazioni sul pagamento.",
        "testo_integrale": "L'Agenzia per l'Italia digitale, sentita la Banca d'Italia, definisce linee guida per l'attuazione del presente articolo e per la specifica dei codici identificativi del pagamento di cui al comma 1 e le modalita' attraverso le quali il prestatore dei servizi di pagamento mette a disposizione dell'ente le informazioni relative al pagamento medesimo.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5-bis c.1",
        "testo": "La presentazione di istanze, dichiarazioni, dati e lo scambio di informazioni e documenti, anche a fini statistici, tra imprese e amministrazioni pubbliche avviene esclusivamente con le tecnologie dell'informazione e della comunicazione; con le stesse modalità le amministrazioni pubbliche adottano e comunicano atti e provvedimenti amministrativi verso le imprese.",
        "testo_integrale": "La presentazione di istanze, dichiarazioni, dati e lo scambio di informazioni e documenti, anche a fini statistici, tra le imprese e le amministrazioni pubbliche avviene esclusivamente utilizzando le tecnologie dell'informazione e della comunicazione. Con le medesime modalita' le amministrazioni pubbliche adottano e comunicano atti e provvedimenti amministrativi nei confronti delle imprese.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5-bis c.2",
        "testo": "Con DPCM, su proposta del Ministro per la pubblica amministrazione e l'innovazione, di concerto con il Ministro dello sviluppo economico e il Ministro per la semplificazione normativa, sono adottate le modalità di attuazione del comma 1 da parte delle amministrazioni centrali e fissati i relativi termini.",
        "testo_integrale": "Con decreto del Presidente del Consiglio dei Ministri, su proposta del Ministro per la pubblica amministrazione e l'innovazione, di concerto con il Ministro dello sviluppo economico e con il Ministro per la semplificazione normativa, sono adottate le modalita' di attuazione del comma 1 da parte delle pubbliche amministrazioni centrali e fissati i relativi termini.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5-bis c.3",
        "testo": "AgID, anche avvalendosi degli uffici di cui all'art. 17, provvede alla verifica dell'attuazione del comma 1 secondo le modalità e i termini indicati nel decreto di cui al comma 2.",
        "testo_integrale": "((AgID)), anche avvalendosi degli uffici di cui all'articolo 17, provvede alla verifica dell'attuazione del comma 1 secondo le modalita' e i termini indicati nel decreto di cui al comma 2.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5-bis c.4",
        "testo": "Il Governo promuove l'intesa con regioni ed enti locali in sede di Conferenza unificata per l'adozione degli indirizzi utili alla realizzazione delle finalità del comma 1.",
        "testo_integrale": "Il Governo promuove l'intesa con regioni ed enti locali in sede di Conferenza unificata per l'adozione degli indirizzi utili alla realizzazione delle finalita' di cui al comma 1.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
    },
]

RIGHE_PRINCIPI = [
    {
        "riferimento": "art. 1 c.1 lett.0a)",
        "testo": "Definisce «AgID»: l'Agenzia per l'Italia digitale, istituita dall'art. 19 del d.l. 83/2012 conv. l. 134/2012.",
        "testo_integrale": "0a) AgID: l'Agenzia per l'Italia digitale di cui all'articolo 19 del decreto-legge 22 giugno 2012, n. 83, convertito, con modificazioni, dalla legge 7 agosto 2012, n. 134;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.a)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "a) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.b)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "b) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.c)",
        "testo": "Definisce «carta d'identità elettronica»: il documento d'identità su supporto informatico, con elementi di identificazione fisica del titolare, rilasciato dai comuni principalmente per dimostrare l'identità anagrafica.",
        "testo_integrale": "c) carta d'identita' elettronica: il documento d'identita' munito di elementi per l'identificazione fisica del titolare rilasciato su supporto informatico dalle amministrazioni comunali con la prevalente finalita' di dimostrare l'identita' anagrafica del suo titolare;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.d)",
        "testo": "Definisce «carta nazionale dei servizi»: il documento su supporto informatico che consente l'accesso per via telematica ai servizi delle pubbliche amministrazioni.",
        "testo_integrale": "d) carta nazionale dei servizi: il documento rilasciato su supporto informatico per consentire l'accesso per via telematica ai servizi erogati dalle pubbliche amministrazioni;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.e)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "e) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.f)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "f) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.g)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "g) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.h)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "h) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.i)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "i) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.i-bis)",
        "testo": "Definisce «copia informatica di documento analogico»: il documento informatico avente contenuto identico a quello del documento analogico da cui è tratto.",
        "testo_integrale": "i-bis) copia informatica di documento analogico: il documento informatico avente contenuto identico a quello del documento analogico da cui e' tratto;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.i-ter)",
        "testo": "Definisce «copia per immagine su supporto informatico di documento analogico»: il documento informatico avente contenuto e forma identici a quelli del documento analogico da cui è tratto.",
        "testo_integrale": "i-ter) copia per immagine su supporto informatico di documento analogico: il documento informatico avente contenuto e forma identici a quelli del documento analogico da cui e' tratto;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.i-quater)",
        "testo": "Definisce «copia informatica di documento informatico»: il documento informatico avente contenuto identico a quello del documento da cui è tratto, su supporto con diversa sequenza di valori binari.",
        "testo_integrale": "i-quater) copia informatica di documento informatico: il documento informatico avente contenuto identico a quello del documento da cui e' tratto su supporto informatico con diversa sequenza di valori binari;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.i-quinquies)",
        "testo": "Definisce «duplicato informatico»: il documento informatico ottenuto memorizzando, sullo stesso dispositivo o su dispositivi diversi, la medesima sequenza di valori binari del documento originario.",
        "testo_integrale": "i-quinquies) duplicato informatico: il documento informatico ottenuto mediante la memorizzazione, sullo stesso dispositivo o su dispositivi diversi, della medesima sequenza di valori binari del documento originario;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.i-sexies)",
        "testo": "Definisce «dati territoriali»: i dati che attengono, direttamente o indirettamente, a una località o a un'area geografica specifica.",
        "testo_integrale": "i-sexies) dati territoriali: i dati che attengono, direttamente o indirettamente, a una localita' o a un'area geografica specifica;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.l)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "l) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.l-bis)",
        "testo": "Definisce «formato aperto»: un formato di dati reso pubblico, documentato esaustivamente e neutro rispetto agli strumenti tecnologici necessari alla fruizione dei dati.",
        "testo_integrale": "l-bis) formato aperto: un formato di dati reso pubblico, documentato esaustivamente e neutro rispetto agli strumenti tecnologici necessari per la fruizione dei dati stessi;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.l-ter)",
        "testo": "Definisce «dati di tipo aperto»: i dati disponibili con licenza o previsione normativa che ne consenta l'uso da parte di chiunque anche a fini commerciali in formato disaggregato, accessibili in formati aperti e adatti al trattamento automatico con i relativi metadati, resi disponibili gratuitamente o ai soli costi marginali di riproduzione e divulgazione.",
        "testo_integrale": "l-ter) dati di tipo aperto: i dati che presentano le seguenti caratteristiche: 1) sono disponibili secondo i termini di una licenza o di una previsione normativa che ne permetta l'utilizzo da parte di chiunque, anche per finalita' commerciali, in formato disaggregato; 2) sono accessibili attraverso le tecnologie dell'informazione e della comunicazione, ivi comprese le reti telematiche pubbliche e private, in formati aperti ai sensi della lettera l-bis), sono adatti all'utilizzo automatico da parte di programmi per elaboratori e sono provvisti dei relativi metadati; 3) sono resi disponibili gratuitamente attraverso le tecnologie dell'informazione e della comunicazione, ivi comprese le reti telematiche pubbliche e private, oppure sono resi disponibili ai costi marginali sostenuti per la loro riproduzione e divulgazione salvo quanto previsto dall'articolo 7 del decreto legislativo 24 gennaio 2006, n. 36;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.m)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "m) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.n)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "n) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.n-bis)",
        "testo": "Definisce «Riutilizzo»: l'uso del dato secondo la definizione dell'art. 2, comma 1, lett. e), del d.lgs. 36/2006.",
        "testo_integrale": "n-bis) Riutilizzo: uso del dato di cui all'articolo 2, comma 1, lettera e), del decreto legislativo 24 gennaio 2006, n. 36;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.n-ter)",
        "testo": "Definisce «domicilio digitale»: l'indirizzo elettronico eletto presso un servizio di PEC o un servizio elettronico di recapito certificato qualificato ai sensi del Regolamento eIDAS, valido per le comunicazioni elettroniche aventi valore legale.",
        "testo_integrale": "n-ter) domicilio digitale: un indirizzo elettronico eletto presso un servizio di posta elettronica certificata o un servizio elettronico di recapito certificato qualificato, come definito dal regolamento (UE) 23 luglio 2014 n. 910 del Parlamento europeo e del Consiglio in materia di identificazione elettronica e servizi fiduciari per le transazioni elettroniche nel mercato interno e che abroga la direttiva 1999/93/CE, di seguito \"Regolamento eIDAS\",valido ai fini delle comunicazioni elettroniche aventi valore legale;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.n-quater)",
        "testo": "Definisce «servizio in rete o on-line»: qualsiasi servizio di una amministrazione pubblica fruibile a distanza per via elettronica.",
        "testo_integrale": "n-quater) servizio in rete o on-line: qualsiasi servizio di una amministrazione pubblica fruibile a distanza per via elettronica;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.o)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "o) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.p)",
        "testo": "Definisce «documento informatico»: il documento elettronico che contiene la rappresentazione informatica di atti, fatti o dati giuridicamente rilevanti.",
        "testo_integrale": "p) documento informatico: il documento elettronico che contiene la rappresentazione informatica di atti, fatti o dati giuridicamente rilevanti;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.p-bis)",
        "testo": "Definisce «documento analogico»: la rappresentazione non informatica di atti, fatti o dati giuridicamente rilevanti.",
        "testo_integrale": "p-bis) documento analogico: la rappresentazione non informatica di atti, fatti o dati giuridicamente rilevanti;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.q)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "q) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.q-bis)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "q-bis) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.r)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "r) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.s)",
        "testo": "Definisce «firma digitale»: il tipo di firma qualificata basato su un sistema di chiavi crittografiche asimmetriche correlate (una pubblica e una privata) che consente al titolare, tramite la chiave privata, e a un terzo, tramite la chiave pubblica, di rendere manifesta e verificare rispettivamente la provenienza e l'integrità di uno o più documenti informatici.",
        "testo_integrale": "s) firma digitale: un particolare tipo di firma qualificata basata su un su un sistema di chiavi crittografiche, una pubblica e una privata, correlate tra loro, che consente al titolare ((di firma elettronica)) tramite la chiave privata ((e a un soggetto terzo)) tramite la chiave pubblica, rispettivamente, di rendere manifesta e di verificare la provenienza e l'integrita' di un documento informatico o di un insieme di documenti informatici;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.t)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "t) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.u)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "u) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.u-bis)",
        "testo": "Definisce «gestore di posta elettronica certificata»: il soggetto che presta servizi di trasmissione dei documenti informatici mediante la posta elettronica certificata.",
        "testo_integrale": "u-bis) gestore di posta elettronica certificata: il soggetto che presta servizi di trasmissione dei documenti informatici mediante la posta elettronica certificata;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.u-ter)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "u-ter)LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.u-quater)",
        "testo": "Definisce «identità digitale»: la rappresentazione informatica della corrispondenza tra un utente e i suoi attributi identificativi, verificata attraverso l'insieme dei dati raccolti e registrati in forma digitale secondo le modalità del decreto attuativo dell'art. 64.",
        "testo_integrale": "u-quater) identita' digitale: la rappresentazione informatica della corrispondenza tra un utente e i suoi attributi identificativi, verificata attraverso l'insieme dei dati raccolti e registrati in forma digitale secondo le modalita' fissate nel decreto attuativo dell'articolo 64;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.v)",
        "testo": "Definisce «originali non unici»: i documenti per i quali sia possibile risalire al contenuto attraverso altre scritture o documenti di conservazione obbligatoria, anche se in possesso di terzi.",
        "testo_integrale": "v) originali non unici: i documenti per i quali sia possibile risalire al loro contenuto attraverso altre scritture o documenti di cui sia obbligatoria la conservazione, anche se in possesso di terzi;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.v-bis)",
        "testo": "Definisce «posta elettronica certificata»: il sistema di comunicazione in grado di attestare l'invio e l'avvenuta consegna di un messaggio di posta elettronica e di fornire ricevute opponibili ai terzi.",
        "testo_integrale": "v-bis) posta elettronica certificata: sistema di comunicazione in grado di attestare l'invio e l'avvenuta consegna di un messaggio di posta elettronica e di fornire ricevute opponibili ai terzi;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.z)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "z) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.aa)",
        "testo": "Definisce «titolare (di firma elettronica)»: la persona fisica cui è attribuita la firma elettronica e che ha accesso ai dispositivi per la sua creazione nonché alle applicazioni per la sua apposizione.",
        "testo_integrale": "aa) titolare ((di firma elettronica)): la persona fisica cui e' attribuita la firma elettronica e che ha accesso ai dispositivi per la ((sua)) creazione ((nonche' alle applicazioni per la sua apposizione)) della firma elettronica;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.bb)",
        "testo": "Lettera soppressa dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "bb) LETTERA SOPPRESSA DAL D.LGS. 26 AGOSTO 2016, N. 179;",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 1 c.1 lett.cc)",
        "testo": "Definisce «titolare del dato»: uno dei soggetti di cui all'art. 2, comma 2, che ha originariamente formato per uso proprio o commissionato ad altri il documento che rappresenta il dato, o che ne ha la disponibilità.",
        "testo_integrale": "cc) titolare del dato: uno dei soggetti di cui all'articolo 2, comma 2, che ha originariamente formato per uso proprio o commissionato ad altro soggetto il documento che rappresenta il dato, o che ne ha la disponibilita';",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.dd)",
        "testo": "Definisce «interoperabilità»: la caratteristica di un sistema informativo, con interfacce pubbliche e aperte, di interagire automaticamente con altri sistemi informativi per lo scambio di informazioni e l'erogazione di servizi.",
        "testo_integrale": "dd) interoperabilita': caratteristica di un sistema informativo, le cui interfacce sono pubbliche e aperte, di interagire in maniera automatica con altri sistemi informativi per lo scambio di informazioni e l'erogazione di servizi;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.ee)",
        "testo": "Definisce «cooperazione applicativa»: la parte del Sistema Pubblico di Connettività finalizzata all'interazione tra i sistemi informatici dei soggetti partecipanti, per l'integrazione di metadati, informazioni, processi e procedimenti amministrativi.",
        "testo_integrale": "ee) cooperazione applicativa: la parte del Sistema Pubblico di Connettivita' finalizzata all'interazione tra i sistemi informatici dei soggetti partecipanti, per garantire l'integrazione dei metadati, delle informazioni, dei processi e procedimenti amministrativi.))",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.ff)",
        "testo": "Definisce «Linee guida»: le regole tecniche e di indirizzo adottate secondo il procedimento di cui all'art. 71.",
        "testo_integrale": "ff) Linee guida: le regole tecniche e di indirizzo adottate secondo il procedimento di cui all'articolo 71.",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1-bis",
        "testo": "Ai fini del CAD valgono le definizioni di cui all'art. 3 del Regolamento eIDAS.",
        "testo_integrale": "1-bis. Ai fini del presente Codice, valgono le definizioni di cui all'articolo 3 del Regolamento eIDAS;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1-ter",
        "testo": "Ove la legge consenta l'uso della posta elettronica certificata, è ammesso anche l'uso di altro servizio elettronico di recapito certificato qualificato ai sensi degli artt. 3, numero 37), e 44 del Regolamento eIDAS.",
        "testo_integrale": "1-ter. Ove la legge consente l'utilizzo della posta elettronica certificata e' ammesso anche l'utilizzo di altro servizio elettronico di recapito certificato ((qualificato ai sensi degli articoli 3, numero 37), e 44 del Regolamento eIDAS)).",
        "tipo_principio": "equivalenza giuridica",
        "stato": "vigente",
        "oggetti_giuridici": ["servizio di recapito elettronico certificato"],
    },
    {
        "riferimento": "art. 2 c.2",
        "testo": "Le disposizioni del Codice si applicano: alle pubbliche amministrazioni di cui all'art. 1 c.2 del d.lgs. 165/2001 (incluse le autorità di sistema portuale e le autorità amministrative indipendenti di garanzia, vigilanza e regolazione); ai gestori di servizi pubblici, comprese le società quotate, per i servizi di pubblico interesse; alle società a controllo pubblico di cui al d.lgs. 175/2016, escluse le società quotate di cui all'art. 2 c.1 lett. p) del medesimo decreto che non rientrino tra i gestori di servizi pubblici.",
        "testo_integrale": "Le disposizioni del presente Codice si applicano: a) alle pubbliche amministrazioni di cui all'articolo 1, comma 2, del decreto legislativo 30 marzo 2001, n. 165, nel rispetto del riparto di competenza di cui all'articolo 117 della Costituzione, ivi comprese le autorita' di sistema portuale, nonche' alle autorita' amministrative indipendenti di garanzia, vigilanza e regolazione; b) ai gestori di servizi pubblici, ivi comprese le societa' quotate, in relazione ai servizi di pubblico interesse; c) alle societa' a controllo pubblico, come definite nel decreto legislativo 19 agosto 2016, n. 175, escluse le societa' quotate di cui all'articolo 2, comma 1, lettera p), del medesimo decreto che non rientrino nella categoria di cui alla lettera b).",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 2 c.2-bis",
        "testo": "Comma abrogato dal D.Lgs. 30 dicembre 2010, n. 235.",
        "testo_integrale": "COMMA ABROGATO DAL D.LGS. 30 DICEMBRE 2010, N. 235.",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 2 c.3",
        "testo": "Le disposizioni del Codice e le relative Linee guida su documento informatico, firme elettroniche e servizi fiduciari (Capo II), riproduzione e conservazione dei documenti (artt. 43-44), domicilio digitale e comunicazioni elettroniche (art. 3-bis e Capo IV) e identità digitale (artt. 3-bis e 64) si applicano anche ai privati, salvo diversa previsione.",
        "testo_integrale": "Le disposizioni del presente Codice e le relative Linee guida concernenti il documento informatico, le firme elettroniche e i servizi fiduciari di cui al Capo II, la riproduzione e conservazione dei documenti di cui agli articoli 43 e 44, il domicilio digitale e le comunicazioni elettroniche di cui all'articolo 3-bis e al Capo IV, l'identita' digitale di cui agli articoli 3-bis e 64 si applicano anche ai privati, ove non diversamente previsto.",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 2 c.4",
        "testo": "Le disposizioni del Capo V, su accesso ai documenti informatici e fruibilità delle informazioni digitali, si applicano anche agli organismi di diritto pubblico.",
        "testo_integrale": "Le disposizioni di cui al capo V, concernenti l'accesso ai documenti informatici e la fruibilita' delle informazioni digitali, si applicano anche agli organismi di diritto pubblico.",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 2 c.5",
        "testo": "Le disposizioni del Codice si applicano nel rispetto della disciplina sul trattamento dei dati personali, in particolare del Codice privacy (d.lgs. 196/2003).",
        "testo_integrale": "Le disposizioni del presente Codice si applicano nel rispetto della disciplina in materia di trattamento dei dati personali e, in particolare, delle disposizioni del Codice in materia di protezione dei dati personali approvato con decreto legislativo 30 giugno 2003, n. 196;",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 2 c.6",
        "testo": "Il Codice non si applica alle attività e funzioni di ordine e sicurezza pubblica, difesa e sicurezza nazionale, polizia giudiziaria ed economico-finanziaria, consultazioni elettorali, né alle comunicazioni di emergenza/allerta di protezione civile; si applica invece al processo civile, penale, amministrativo, contabile e tributario in quanto compatibile, salvo diversa disciplina del processo telematico.",
        "testo_integrale": "Le disposizioni del presente Codice non si applicano limitatamente all'esercizio delle attivita' e funzioni di ordine e sicurezza pubblica, difesa e sicurezza nazionale, polizia giudiziaria e polizia economico-finanziaria e consultazioni elettorali , nonche' alle comunicazioni di emergenza e di allerta in ambito di protezione civile. Le disposizioni del presente Codice si applicano al processo civile, penale, amministrativo, contabile e tributario, in quanto compatibili e salvo che non sia diversamente disposto dalle disposizioni in materia di processo telematico. ((52))",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3 c.1",
        "testo": "Chiunque ha diritto di usare, in modo accessibile ed efficace, le soluzioni e gli strumenti del CAD nei rapporti con i soggetti di cui all'art. 2 c.2, anche ai fini dell'esercizio dei diritti di accesso e della partecipazione al procedimento amministrativo, fermi restando i diritti delle minoranze linguistiche riconosciute.",
        "testo_integrale": "Chiunque ha il diritto di usare ((, in modo accessibile ed efficace,)) le soluzioni e gli strumenti di cui al presente Codice nei rapporti con i soggetti di cui all'articolo 2, comma 2, anche ai fini ((dell'esercizio dei diritti di accesso e)) della partecipazione al procedimento amministrativo, fermi restando i diritti delle minoranze linguistiche riconosciute.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3 c.1-bis",
        "testo": "Comma abrogato dal D.Lgs. 30 dicembre 2010, n. 235.",
        "testo_integrale": "COMMA ABROGATO DAL D.LGS. 30 DICEMBRE 2010, N. 235.",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 3 c.1-ter",
        "testo": "La tutela giurisdizionale davanti al giudice amministrativo è disciplinata dal codice del processo amministrativo.",
        "testo_integrale": "La tutela giurisdizionale davanti al giudice amministrativo e' disciplinata dal codice del processo amministrativo.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3 c.1-quater",
        "testo": "Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.",
        "testo_integrale": "((COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217)).",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 3 c.1-quinquies",
        "testo": "Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.",
        "testo_integrale": "((COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217)).",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 3 c.1-sexies",
        "testo": "Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.",
        "testo_integrale": "((COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217)).",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 3-bis c.01",
        "testo": "Chiunque ha diritto di accedere ai servizi on-line offerti dai soggetti di cui all'art. 2 c.2 tramite la propria identità digitale, anche attraverso il punto di accesso telematico di cui all'art. 64-bis.",
        "testo_integrale": "Chiunque ha il diritto di accedere ai servizi on-line offerti dai soggetti di cui all'articolo 2, comma 2, tramite la propria identita' digitale e anche attraverso il punto di accesso telematico di cui all'articolo 64-bis. (29)",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.1-bis",
        "testo": "Fermo l'obbligo del comma 1, chiunque ha facoltà di eleggere o modificare il proprio domicilio digitale da iscrivere nell'elenco di cui all'art. 6-quater; se il domicilio eletto non è più attivo si procede alla cancellazione d'ufficio secondo le Linee guida.",
        "testo_integrale": "Fermo restando quanto previsto al comma 1, chiunque ha facolta' di eleggere o modificare il proprio domicilio digitale da iscrivere nell'elenco di cui all'articolo 6-quater. Nel caso in cui il domicilio eletto risulti non piu' attivo si procede alla cancellazione d'ufficio dall'indice di cui all'articolo 6-quater secondo le modalita' fissate nelle Linee guida.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.1-ter",
        "testo": "I domicili digitali di cui ai commi 1, 1-bis e 4-quinquies sono eletti secondo le modalità stabilite dalle Linee guida; le persone fisiche possono eleggere il domicilio digitale anche tramite il punto di accesso telematico di cui all'art. 64-bis, il servizio on-line dell'ANPR di cui all'art. 62, o recandosi presso l'ufficio anagrafe del proprio comune di residenza.",
        "testo_integrale": "I domicili digitali di cui ai commi 1, 1-bis e 4-quinquies sono eletti secondo le modalita' stabilite con le Linee guida. Le persone fisiche possono altresi' eleggere il domicilio digitale avvalendosi del servizio di cui all'articolo 64-bis , di quello reso disponibile on-line dall'Anagrafe nazionale della popolazione residente (ANPR) di cui all'articolo 62, ovvero recandosi presso l'ufficio anagrafe del proprio comune di residenza.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.2",
        "testo": "Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.",
        "testo_integrale": "COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217.",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 3-bis c.3",
        "testo": "Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 3-bis c.4-bis",
        "testo": "Fino alla data del decreto di cui al comma 3-bis, i soggetti di cui all'art. 2 c.2 possono predisporre le comunicazioni verso chi non ha un domicilio digitale attivo, funzionante o raggiungibile come documenti informatici sottoscritti con firma digitale o altra firma elettronica qualificata, da conservare nei propri archivi, inviando per posta ordinaria o raccomandata a.r. copia analogica recante il contrassegno di cui all'art. 23 c.2-bis o l'indicazione a stampa del responsabile in sostituzione della firma autografa.",
        "testo_integrale": "Fino alla data fissata nel decreto di cui al comma 3-bis, i soggetti di cui all'articolo 2, comma 2, possono predisporre le comunicazioni ai soggetti che non hanno un domicilio digitale ovvero nei casi di domicilio digitale non attivo, non funzionante o non raggiungibile, come documenti informatici sottoscritti con firma digitale o altra firma elettronica qualificata, da conservare nei propri archivi, ed inviare agli stessi, per posta ordinaria o raccomandata con avviso di ricevimento, copia analogica di tali documenti su cui e' apposto a stampa il contrassegno di cui all'articolo 23, comma 2-bis o l'indicazione a mezzo stampa del responsabile pro tempore in sostituzione della firma autografa ai sensi dell'articolo 3 del decreto legislativo 12 febbraio 1993, n. 39 ovvero un avviso con le indicazioni delle modalita' con le quali i suddetti documenti sono messi a disposizione e consegnati al destinatario.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.4-ter",
        "testo": "Le comunicazioni di cui al comma 4-bis soddisfano a tutti gli effetti di legge gli obblighi di conservazione ed esibizione dei documenti, se la copia analogica inviata riporta una dicitura che specifica che il documento informatico da cui è tratta è stato predisposto come documento nativo digitale ed è disponibile presso l'amministrazione.",
        "testo_integrale": "Le disposizioni di cui al comma 4-bis soddisfano a tutti gli effetti di legge gli obblighi di conservazione e di esibizione dei documenti previsti dalla legislazione vigente laddove la copia analogica inviata al cittadino contenga una dicitura che specifichi che il documento informatico, da cui la copia e' tratta, e' stato predisposto come documento nativo digitale ed e' disponibile presso l'amministrazione. (28)",
        "tipo_principio": "valore probatorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.4-quater",
        "testo": "La copia analogica con l'indicazione a mezzo stampa del responsabile in sostituzione della firma autografa ai sensi dell'art. 3 del d.lgs. 39/1993 soddisfa le condizioni di cui all'art. 23 c.2-bis, salvo che il documento rappresenti, per sua natura, una certificazione rilasciata dall'amministrazione da utilizzare nei rapporti tra privati.",
        "testo_integrale": "La copia analogica con l'indicazione a mezzo stampa del responsabile in sostituzione della firma autografa ai sensi dell'articolo 3 del decreto legislativo 12 febbraio 1993, n. 39, soddisfa le condizioni di cui all'articolo 23, comma 2-bis, salvo i casi in cui il documento rappresenti, per propria natura, una certificazione rilasciata dall'amministrazione da utilizzarsi nei rapporti tra privati.",
        "tipo_principio": "valore probatorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.4-quinquies",
        "testo": "È possibile eleggere anche un domicilio digitale speciale per determinati atti, procedimenti o affari; resta ferma la validità ai fini delle comunicazioni elettroniche aventi valore legale, e chi lo ha eletto non può opporre eccezioni su forma e data di spedizione/ricezione delle comunicazioni o notificazioni ivi indirizzate.",
        "testo_integrale": "E' possibile eleggere anche un domicilio digitale speciale per determinati atti, procedimenti o affari. In tal caso, ferma restando la validita' ai fini delle comunicazioni elettroniche aventi valore legale, colui che lo ha eletto non puo' opporre eccezioni relative alla forma e alla data della spedizione e del ricevimento delle comunicazioni o notificazioni ivi indirizzate.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-bis c.5",
        "testo": "Dall'attuazione delle disposizioni del presente articolo non devono derivare nuovi o maggiori oneri per la finanza pubblica.",
        "testo_integrale": "Dall'attuazione delle disposizioni di cui al presente articolo non devono derivare nuovi o maggiori oneri a carico della finanza pubblica.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.1",
        "testo": "Il cittadino può accedere alle informazioni relative ai propri strumenti digitali tramite un servizio dedicato reso disponibile in modalità sicura dal portale dell'ANPR di cui all'art. 62.",
        "testo_integrale": "Il cittadino puo' accedere alle informazioni relative ai propri strumenti digitali, attraverso un servizio dedicato reso disponibile in modalita' sicura dal portale dell'Anagrafe nazionale della popolazione residente (ANPR) di cui all'articolo 62.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.2",
        "testo": "Ai fini del comma 1 è istituita nell'ANPR un'apposita sezione con i dati, registrati e costantemente aggiornati dai rispettivi gestori, relativi a: le identità digitali (carta d'identità elettronica, SPID, Carta Nazionale dei Servizi) e gli attestati elettronici di dati di identificazione personale ex art. 64-quater; le deleghe di cui all'art. 64-ter; i domicili digitali eletti ai sensi dell'art. 3-bis.",
        "testo_integrale": "Ai fini del comma 1 e' istituita nell'ANPR un'apposita sezione contenente i dati riferibili ai seguenti strumenti digitali intestati al cittadino, registrati e costantemente ((aggiornati)) dai gestori degli strumenti stessi: a) le identita' digitali di cui al ((sistema della carta di identita' elettronica, al sistema pubblico per la gestione dell'identita' digitale di cittadini e imprese (SPID) )) e alla Carta Nazionale dei Servizi nonche' gli attestati elettronici di dati di identificazione personale rilasciati ai sensi dell'articolo 64-quater; b) le deleghe di cui all'articolo 64-ter; c) i domicili digitali eletti ai sensi dell'articolo 3-bis.",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.3",
        "testo": "Per ogni strumento digitale di cui al comma 2, l'ANPR è integrata e costantemente aggiornata con: tipologia dello strumento; gestore con denominazione del soggetto emettitore; natura pubblica o privata del gestore; identificativo/numero di serie dello strumento; livello di garanzia dell'autenticazione, ove applicabile; stato dello strumento (valido, revocato, scaduto); data di rilascio; data di scadenza; per la piattaforma delle deleghe, i dati identificativi dei delegati e le date di inizio/termine della delega.",
        "testo_integrale": "Per ogni strumento digitale di cui al comma 2, ((l'ANPR)) e' integrata e costantemente ((aggiornata)) con le seguenti informazioni: a) tipologia di strumento digitale; b) gestore dello strumento con la denominazione del soggetto emettitore; c) natura del gestore, se pubblico o privato; d) identificativo dello strumento: il numero di serie, l'identificativo o il codice seriale dello strumento, ove esistente; e) livello di garanzia dello strumento: l'indicatore del grado di affidabilita' dell'autenticazione, ove applicabile; f) stato dello strumento: se valido, revocato o scaduto; g) data di rilascio, nel formato giorno/mese/anno; h) scadenza, nel formato giorno/mese/anno; i) nel caso ((della piattaforma per la gestione delle deleghe)): i dati identificativi dei soggetti delegati e la data di inizio di validita' e termine della delega.",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.8",
        "testo": "Previo consenso del cittadino, i gestori degli strumenti digitali di cui alle lettere b) e c) del comma 2 (tranne quelli connessi alla carta d'identità elettronica), quali gestori di pubblico servizio, possono verificare tramite la piattaforma di cui all'art. 50-ter, prima del rilascio, l'esistenza di strumenti dello stesso tipo già associati alla persona fisica.",
        "testo_integrale": "Previo consenso del cittadino, i gestori degli altri strumenti digitali di cui alle lettere b) e c) del comma 2, ad eccezione di quelli connessi alla carta d'identita' elettronica, in qualita' di gestori di pubblico servizio, possono, tramite ((la piattaforma di cui all'articolo 50-ter)) e prima del rilascio dello strumento, verificare l'eventuale esistenza di strumenti della medesima tipologia gia' associati alla persona fisica.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.9",
        "testo": "Le verifiche di cui ai commi 7 e 8 restituiscono solo il numero di identità digitali, senza ulteriori dettagli; gli esiti sono resi disponibili al cittadino contestualmente alla verifica.",
        "testo_integrale": "Le verifiche di cui ai commi 7 e 8 restituiscono unicamente il numero di identita' digitali, senza alcun dettaglio ((delle stesse)); gli esiti sono resi disponibili al cittadino contestualmente alla verifica.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.10",
        "testo": "La titolarità del trattamento dei dati dell'ANPR spetta al Ministero dell'interno per conservazione, comunicazione e misure di sicurezza; i gestori degli strumenti digitali di cui al comma 2 sono titolari del trattamento di registrazione e aggiornamento dei dati di propria competenza.",
        "testo_integrale": "La titolarita' del trattamento dei dati contenuti nell'ANPR e' attribuita al Ministero dell'interno sotto i profili della conservazione, della comunicazione e dell'adozione delle relative misure di sicurezza; i gestori degli strumenti digitali di cui al comma 2 sono titolari del trattamento di registrazione e aggiornamento dei dati di propria competenza nell'ANPR.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.11",
        "testo": "La società incaricata della realizzazione delle funzionalità dell'ANPR e della gestione della sezione di cui al comma 2 (art. 83 c.15 del d.l. 112/2008) è nominata responsabile del trattamento ex art. 28 del regolamento (UE) 2016/679.",
        "testo_integrale": "La societa' di cui all'articolo 83, comma 15, del decreto-legge 25 giugno 2008, n. 112, convertito, con modificazioni, dalla legge 6 agosto 2008, n. 133, incaricata della realizzazione delle funzionalita' ((dell'ANPR)) e della gestione ((della sezione)) di cui al comma 2 ((del presente articolo)), e' nominata responsabile del trattamento ai sensi dell'articolo 28 del regolamento (UE) 2016/679 del Parlamento europeo e del Consiglio, del 27 aprile 2016.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 3-ter c.12",
        "testo": "Le società che registrano e aggiornano, per conto dei titolari del trattamento, i dati della sezione ANPR di cui al comma 2 con gli strumenti digitali dei commi 3 e 4 assumono la qualifica di responsabili del trattamento ex art. 28 del regolamento (UE) 2016/679.",
        "testo_integrale": "Le societa' che registrano e aggiornano, per conto dei titolari del trattamento, ((i dati nella sezione dell'ANPR)) di cui al comma 2, con i dati degli strumenti digitali di cui ai commi 3 e 4, assumono la qualifica di responsabili del trattamento ai sensi dell'articolo 28 del regolamento (UE) 2016/679.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 4",
        "testo": "Articolo abrogato dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "((ARTICOLO ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179))",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 5 c.2-bis",
        "testo": "Comma abrogato dal D.L. 6 novembre 2021, n. 152.",
        "testo_integrale": "COMMA ABROGATO DAL D.L. 6 NOVEMBRE 2021, N. 152.",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 5 c.2-sexies",
        "testo": "La piattaforma tecnologica di cui al comma 2 può essere utilizzata anche per facilitare e automatizzare, tramite pagamenti elettronici, i processi di certificazione fiscale tra privati, tra cui fatturazione elettronica e memorizzazione/trasmissione dei corrispettivi giornalieri ex artt. 1-2 del d.lgs. 127/2015.",
        "testo_integrale": "La piattaforma tecnologica di cui al comma 2 puo' essere utilizzata anche per facilitare e automatizzare, attraverso i pagamenti elettronici, i processi di certificazione fiscale tra soggetti privati, tra cui la fatturazione elettronica e la memorizzazione e trasmissione dei dati dei corrispettivi giornalieri di cui agli articoli 1 e 2 del decreto legislativo 5 agosto 2015, n. 127.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 5 c.3",
        "testo": "Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 5 c.3-bis",
        "testo": "Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 5 c.3-ter",
        "testo": "Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.",
        "testo_integrale": "COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.",
        "tipo_principio": "altro",
        "stato": "abrogato",
    },
    {
        "riferimento": "art. 5 c.5",
        "testo": "Le attività previste dall'articolo si svolgono con le risorse umane, finanziarie e strumentali disponibili a legislazione vigente.",
        "testo_integrale": "Le attivita' previste dal presente articolo si svolgono con le risorse umane, finanziarie e strumentali disponibili a legislazione vigente.",
        "tipo_principio": "altro",
        "stato": "vigente",
    },
]

INDICE_ARTICOLI_LOCALE = [
    "art. 1 c.1 lett.0a)",
    "art. 1 c.1 lett.a)",
    "art. 1 c.1 lett.b)",
    "art. 1 c.1 lett.c)",
    "art. 1 c.1 lett.d)",
    "art. 1 c.1 lett.e)",
    "art. 1 c.1 lett.f)",
    "art. 1 c.1 lett.g)",
    "art. 1 c.1 lett.h)",
    "art. 1 c.1 lett.i)",
    "art. 1 c.1 lett.i-bis)",
    "art. 1 c.1 lett.i-ter)",
    "art. 1 c.1 lett.i-quater)",
    "art. 1 c.1 lett.i-quinquies)",
    "art. 1 c.1 lett.i-sexies)",
    "art. 1 c.1 lett.l)",
    "art. 1 c.1 lett.l-bis)",
    "art. 1 c.1 lett.l-ter)",
    "art. 1 c.1 lett.m)",
    "art. 1 c.1 lett.n)",
    "art. 1 c.1 lett.n-bis)",
    "art. 1 c.1 lett.n-ter)",
    "art. 1 c.1 lett.n-quater)",
    "art. 1 c.1 lett.o)",
    "art. 1 c.1 lett.p)",
    "art. 1 c.1 lett.p-bis)",
    "art. 1 c.1 lett.q)",
    "art. 1 c.1 lett.q-bis)",
    "art. 1 c.1 lett.r)",
    "art. 1 c.1 lett.s)",
    "art. 1 c.1 lett.t)",
    "art. 1 c.1 lett.u)",
    "art. 1 c.1 lett.u-bis)",
    "art. 1 c.1 lett.u-ter)",
    "art. 1 c.1 lett.u-quater)",
    "art. 1 c.1 lett.v)",
    "art. 1 c.1 lett.v-bis)",
    "art. 1 c.1 lett.z)",
    "art. 1 c.1 lett.aa)",
    "art. 1 c.1 lett.bb)",
    "art. 1 c.1 lett.cc)",
    "art. 1 c.1 lett.dd)",
    "art. 1 c.1 lett.ee)",
    "art. 1 c.1 lett.ff)",
    "art. 1 c.1-bis",
    "art. 1 c.1-ter",
    "art. 2 c.1",
    "art. 2 c.2 lett.a)",
    "art. 2 c.2 lett.b)",
    "art. 2 c.2 lett.c)",
    "art. 2 c.2-bis",
    "art. 2 c.3",
    "art. 2 c.4",
    "art. 2 c.5",
    "art. 2 c.6",
    "art. 2 c.6-bis",
    "art. 3 c.1",
    "art. 3 c.1-bis",
    "art. 3 c.1-ter",
    "art. 3 c.1-quater",
    "art. 3 c.1-quinquies",
    "art. 3 c.1-sexies",
    "art. 3-bis c.01",
    "art. 3-bis c.1",
    "art. 3-bis c.1-bis",
    "art. 3-bis c.1-ter",
    "art. 3-bis c.1-quater",
    "art. 3-bis c.2",
    "art. 3-bis c.3",
    "art. 3-bis c.3-bis",
    "art. 3-bis c.4",
    "art. 3-bis c.4-bis",
    "art. 3-bis c.4-ter",
    "art. 3-bis c.4-quater",
    "art. 3-bis c.4-quinquies",
    "art. 3-bis c.5",
    "art. 3-ter c.1",
    "art. 3-ter c.2 lett.a)",
    "art. 3-ter c.2 lett.b)",
    "art. 3-ter c.2 lett.c)",
    "art. 3-ter c.3 lett.a)",
    "art. 3-ter c.3 lett.b)",
    "art. 3-ter c.3 lett.c)",
    "art. 3-ter c.3 lett.d)",
    "art. 3-ter c.3 lett.e)",
    "art. 3-ter c.3 lett.f)",
    "art. 3-ter c.3 lett.g)",
    "art. 3-ter c.3 lett.h)",
    "art. 3-ter c.3 lett.i)",
    "art. 3-ter c.4",
    "art. 3-ter c.5",
    "art. 3-ter c.6",
    "art. 3-ter c.7",
    "art. 3-ter c.8",
    "art. 3-ter c.9",
    "art. 3-ter c.10",
    "art. 3-ter c.11",
    "art. 3-ter c.12",
    "art. 3-ter c.13",
    "art. 3-ter c.14",
    "art. 4",
    "art. 5 c.1",
    "art. 5 c.2",
    "art. 5 c.2-bis",
    "art. 5 c.2-ter",
    "art. 5 c.2-quater",
    "art. 5 c.2-quinquies",
    "art. 5 c.2-sexies",
    "art. 5 c.2-septies",
    "art. 5 c.3",
    "art. 5 c.3-bis",
    "art. 5 c.3-ter",
    "art. 5 c.4",
    "art. 5 c.5",
    "art. 5-bis c.1",
    "art. 5-bis c.2",
    "art. 5-bis c.3",
    "art. 5-bis c.4",
]

MAPPATURA_LOCALE = {
    "art. 1 c.1 lett.0a)": ["art. 1 c.1 lett.0a)"],
    "art. 1 c.1 lett.a)": ["art. 1 c.1 lett.a)"],
    "art. 1 c.1 lett.b)": ["art. 1 c.1 lett.b)"],
    "art. 1 c.1 lett.c)": ["art. 1 c.1 lett.c)"],
    "art. 1 c.1 lett.d)": ["art. 1 c.1 lett.d)"],
    "art. 1 c.1 lett.e)": ["art. 1 c.1 lett.e)"],
    "art. 1 c.1 lett.f)": ["art. 1 c.1 lett.f)"],
    "art. 1 c.1 lett.g)": ["art. 1 c.1 lett.g)"],
    "art. 1 c.1 lett.h)": ["art. 1 c.1 lett.h)"],
    "art. 1 c.1 lett.i)": ["art. 1 c.1 lett.i)"],
    "art. 1 c.1 lett.i-bis)": ["art. 1 c.1 lett.i-bis)"],
    "art. 1 c.1 lett.i-ter)": ["art. 1 c.1 lett.i-ter)"],
    "art. 1 c.1 lett.i-quater)": ["art. 1 c.1 lett.i-quater)"],
    "art. 1 c.1 lett.i-quinquies)": ["art. 1 c.1 lett.i-quinquies)"],
    "art. 1 c.1 lett.i-sexies)": ["art. 1 c.1 lett.i-sexies)"],
    "art. 1 c.1 lett.l)": ["art. 1 c.1 lett.l)"],
    "art. 1 c.1 lett.l-bis)": ["art. 1 c.1 lett.l-bis)"],
    "art. 1 c.1 lett.l-ter)": ["art. 1 c.1 lett.l-ter)"],
    "art. 1 c.1 lett.m)": ["art. 1 c.1 lett.m)"],
    "art. 1 c.1 lett.n)": ["art. 1 c.1 lett.n)"],
    "art. 1 c.1 lett.n-bis)": ["art. 1 c.1 lett.n-bis)"],
    "art. 1 c.1 lett.n-ter)": ["art. 1 c.1 lett.n-ter)"],
    "art. 1 c.1 lett.n-quater)": ["art. 1 c.1 lett.n-quater)"],
    "art. 1 c.1 lett.o)": ["art. 1 c.1 lett.o)"],
    "art. 1 c.1 lett.p)": ["art. 1 c.1 lett.p)"],
    "art. 1 c.1 lett.p-bis)": ["art. 1 c.1 lett.p-bis)"],
    "art. 1 c.1 lett.q)": ["art. 1 c.1 lett.q)"],
    "art. 1 c.1 lett.q-bis)": ["art. 1 c.1 lett.q-bis)"],
    "art. 1 c.1 lett.r)": ["art. 1 c.1 lett.r)"],
    "art. 1 c.1 lett.s)": ["art. 1 c.1 lett.s)"],
    "art. 1 c.1 lett.t)": ["art. 1 c.1 lett.t)"],
    "art. 1 c.1 lett.u)": ["art. 1 c.1 lett.u)"],
    "art. 1 c.1 lett.u-bis)": ["art. 1 c.1 lett.u-bis)"],
    "art. 1 c.1 lett.u-ter)": ["art. 1 c.1 lett.u-ter)"],
    "art. 1 c.1 lett.u-quater)": ["art. 1 c.1 lett.u-quater)"],
    "art. 1 c.1 lett.v)": ["art. 1 c.1 lett.v)"],
    "art. 1 c.1 lett.v-bis)": ["art. 1 c.1 lett.v-bis)"],
    "art. 1 c.1 lett.z)": ["art. 1 c.1 lett.z)"],
    "art. 1 c.1 lett.aa)": ["art. 1 c.1 lett.aa)"],
    "art. 1 c.1 lett.bb)": ["art. 1 c.1 lett.bb)"],
    "art. 1 c.1 lett.cc)": ["art. 1 c.1 lett.cc)"],
    "art. 1 c.1 lett.dd)": ["art. 1 c.1 lett.dd)"],
    "art. 1 c.1 lett.ee)": ["art. 1 c.1 lett.ee)"],
    "art. 1 c.1 lett.ff)": ["art. 1 c.1 lett.ff)"],
    "art. 1 c.1-bis": ["art. 1 c.1-bis"],
    "art. 1 c.1-ter": ["art. 1 c.1-ter"],
    "art. 2 c.1": ["art. 2 c.1"],
    "art. 2 c.2": ["art. 2 c.2 lett.a)", "art. 2 c.2 lett.b)", "art. 2 c.2 lett.c)"],
    "art. 2 c.2-bis": ["art. 2 c.2-bis"],
    "art. 2 c.3": ["art. 2 c.3"],
    "art. 2 c.4": ["art. 2 c.4"],
    "art. 2 c.5": ["art. 2 c.5"],
    "art. 2 c.6": ["art. 2 c.6"],
    "art. 2 c.6-bis": ["art. 2 c.6-bis"],
    "art. 3 c.1": ["art. 3 c.1"],
    "art. 3 c.1-bis": ["art. 3 c.1-bis"],
    "art. 3 c.1-ter": ["art. 3 c.1-ter"],
    "art. 3 c.1-quater": ["art. 3 c.1-quater"],
    "art. 3 c.1-quinquies": ["art. 3 c.1-quinquies"],
    "art. 3 c.1-sexies": ["art. 3 c.1-sexies"],
    "art. 3-bis c.01": ["art. 3-bis c.01"],
    "art. 3-bis c.1": ["art. 3-bis c.1"],
    "art. 3-bis c.1-bis": ["art. 3-bis c.1-bis"],
    "art. 3-bis c.1-ter": ["art. 3-bis c.1-ter"],
    "art. 3-bis c.1-quater": ["art. 3-bis c.1-quater"],
    "art. 3-bis c.2": ["art. 3-bis c.2"],
    "art. 3-bis c.3": ["art. 3-bis c.3"],
    "art. 3-bis c.3-bis": ["art. 3-bis c.3-bis"],
    "art. 3-bis c.4": ["art. 3-bis c.4"],
    "art. 3-bis c.4-bis": ["art. 3-bis c.4-bis"],
    "art. 3-bis c.4-ter": ["art. 3-bis c.4-ter"],
    "art. 3-bis c.4-quater": ["art. 3-bis c.4-quater"],
    "art. 3-bis c.4-quinquies": ["art. 3-bis c.4-quinquies"],
    "art. 3-bis c.5": ["art. 3-bis c.5"],
    "art. 3-ter c.1": ["art. 3-ter c.1"],
    "art. 3-ter c.2": ["art. 3-ter c.2 lett.a)", "art. 3-ter c.2 lett.b)", "art. 3-ter c.2 lett.c)"],
    "art. 3-ter c.3": ["art. 3-ter c.3 lett.a)", "art. 3-ter c.3 lett.b)", "art. 3-ter c.3 lett.c)", "art. 3-ter c.3 lett.d)", "art. 3-ter c.3 lett.e)", "art. 3-ter c.3 lett.f)", "art. 3-ter c.3 lett.g)", "art. 3-ter c.3 lett.h)", "art. 3-ter c.3 lett.i)"],
    "art. 3-ter c.4": ["art. 3-ter c.4"],
    "art. 3-ter c.5": ["art. 3-ter c.5"],
    "art. 3-ter c.6": ["art. 3-ter c.6"],
    "art. 3-ter c.7": ["art. 3-ter c.7"],
    "art. 3-ter c.8": ["art. 3-ter c.8"],
    "art. 3-ter c.9": ["art. 3-ter c.9"],
    "art. 3-ter c.10": ["art. 3-ter c.10"],
    "art. 3-ter c.11": ["art. 3-ter c.11"],
    "art. 3-ter c.12": ["art. 3-ter c.12"],
    "art. 3-ter c.13": ["art. 3-ter c.13"],
    "art. 3-ter c.14": ["art. 3-ter c.14"],
    "art. 4": ["art. 4"],
    "art. 5 c.1": ["art. 5 c.1"],
    "art. 5 c.2": ["art. 5 c.2"],
    "art. 5 c.2-bis": ["art. 5 c.2-bis"],
    "art. 5 c.2-ter": ["art. 5 c.2-ter"],
    "art. 5 c.2-quater": ["art. 5 c.2-quater"],
    "art. 5 c.2-quinquies": ["art. 5 c.2-quinquies"],
    "art. 5 c.2-sexies": ["art. 5 c.2-sexies"],
    "art. 5 c.2-septies": ["art. 5 c.2-septies"],
    "art. 5 c.3": ["art. 5 c.3"],
    "art. 5 c.3-bis": ["art. 5 c.3-bis"],
    "art. 5 c.3-ter": ["art. 5 c.3-ter"],
    "art. 5 c.4": ["art. 5 c.4"],
    "art. 5 c.5": ["art. 5 c.5"],
    "art. 5-bis c.1": ["art. 5-bis c.1"],
    "art. 5-bis c.2": ["art. 5-bis c.2"],
    "art. 5-bis c.3": ["art. 5-bis c.3"],
    "art. 5-bis c.4": ["art. 5-bis c.4"],
}

RELAZIONI = [
    {
        "nodo_da": ("principio", None, "art. 3 c.1"),
        "nodo_a": ("principio", None, "art. 2 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-bis c.1"),
        "nodo_a": ("principio", None, "art. 2 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-bis c.3-bis"),
        "nodo_a": ("principio", None, "art. 2 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-bis c.3-bis"),
        "nodo_a": ("principio", None, "art. 3-bis c.1-bis"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-bis c.4"),
        "nodo_a": ("principio", None, "art. 2 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-bis c.1-ter"),
        "nodo_a": ("obbligo", None, "art. 3-bis c.1"),
        "tipo_relazione": "specifica",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-bis c.1-ter"),
        "nodo_a": ("principio", None, "art. 3-bis c.1-bis"),
        "tipo_relazione": "specifica",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-bis c.1-ter"),
        "nodo_a": ("principio", None, "art. 3-bis c.4-quinquies"),
        "tipo_relazione": "specifica",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-bis c.1-quater"),
        "nodo_a": ("obbligo", None, "art. 3-bis c.1"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-bis c.1-quater"),
        "nodo_a": ("principio", None, "art. 3-bis c.1-bis"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-bis c.4-bis"),
        "nodo_a": ("principio", None, "art. 2 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-bis c.4-bis"),
        "nodo_a": ("obbligo", None, "art. 3-bis c.3-bis"),
        "tipo_relazione": "è condizionato da",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-bis c.4-ter"),
        "nodo_a": ("principio", None, "art. 3-bis c.4-bis"),
        "tipo_relazione": "specifica",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-ter c.2"),
        "nodo_a": ("obbligo", None, "art. 3-bis c.1"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-ter c.5"),
        "nodo_a": ("principio", None, "art. 3-ter c.3"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-ter c.5"),
        "nodo_a": ("obbligo", None, "art. 3-ter c.4"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-ter c.9"),
        "nodo_a": ("obbligo", None, "art. 3-ter c.7"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 3-ter c.9"),
        "nodo_a": ("principio", None, "art. 3-ter c.8"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-ter c.13"),
        "nodo_a": ("principio", None, "art. 3-ter c.3"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-ter c.13"),
        "nodo_a": ("obbligo", None, "art. 3-ter c.4"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-ter c.14"),
        "nodo_a": ("principio", None, "art. 3-ter c.3"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3-ter c.14"),
        "nodo_a": ("obbligo", None, "art. 3-ter c.4"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 5 c.1"),
        "nodo_a": ("principio", None, "art. 2 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 5 c.1"),
        "nodo_a": ("obbligo", None, "art. 5 c.2"),
        "tipo_relazione": "richiede come precondizione",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 5 c.2-ter"),
        "nodo_a": ("principio", None, "art. 2 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 5 c.2-ter"),
        "nodo_a": ("obbligo", None, "art. 5 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 5 c.2-quater"),
        "nodo_a": ("obbligo", None, "art. 5 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 5 c.2-quinquies"),
        "nodo_a": ("obbligo", None, "art. 5 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 5 c.2-sexies"),
        "nodo_a": ("obbligo", None, "art. 5 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 5 c.2-septies"),
        "nodo_a": ("principio", None, "art. 5 c.2-sexies"),
        "tipo_relazione": "specifica",
        "evidence_type": "textual",
        "confidence": None,
    },
]
