"""Estrazione granulare CAD (D.Lgs. 82/2005, testo vigente) — Capo I, parte 2.

Artt. 6-15: indici dei domicili digitali (6, 6-bis, 6-ter, 6-quater, 6-quinquies),
diritto a servizi on-line (7), alfabetizzazione informatica (8), connettivita'
negli uffici pubblici (8-bis), partecipazione democratica elettronica (9),
artt. 10-11 abrogati (D.Lgs. 179/2016), norme generali per l'uso delle TIC
nell'azione amministrativa (12), formazione informatica dei dipendenti
pubblici (13), codice di condotta tecnologica ed esperti (13-bis), rapporti
Stato/Regioni/autonomie locali (14), Agenzia per l'Italia digitale (14-bis),
digitalizzazione e riorganizzazione (15).

Copertura completa ADR-0007: ogni comma/lettera del range e' rappresentato da
esattamente un nodo (Obbligo o Principio), incluse le disposizioni di
scopo/definitorie e i commi/articoli abrogati (censiti con stato "abrogato").

`testo_integrale` e' copia letterale dal testo ufficiale in
`app/.source_cache/cad/cap02.txt` (incluse le doppie parentesi che Normattiva
usa per segnalare porzioni modificate da decreti successivi, e le apostrofi
codificate come apice singolo ASCII: e' per e, ecc. — fedelta' al file
sorgente, nessuna ricostruzione a memoria). `testo` e' una parafrasi in
italiano corrente.

Formato dei riferimenti: "art. N c.M" o "art. N c.M lett.x", coerente con lo
stile gia' in uso nel censimento (es. DPCM 22/2/2013 in `app/seed.py`).
"""


RIGHE_OBBLIGHI = [
    {
        'riferimento': 'art. 6 c.1-quater',
        'testo': "I soggetti pubblici di cui all'art. 2 c.2 notificano direttamente ai domicili digitali (art. 3-bis) i propri atti, inclusi verbali sanzionatori, atti impositivi/di riscossione e ingiunzioni, salve le disposizioni tributarie specifiche; la conformità della copia informatica all'originale è attestata dal responsabile del procedimento ex artt. 22 e 23-bis.",
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, notificano direttamente presso i domicili digitali di cui all'articolo 3-bis i propri atti, compresi i verbali relativi alle sanzioni amministrative, gli atti impositivi di accertamento e di riscossione e le ingiunzioni di cui all'articolo 2 del regio decreto 14 aprile 1910, n. 639, fatte salve le specifiche disposizioni in ambito tributario. La conformita' della copia informatica del documento notificato all'originale e' attestata dal responsabile del procedimento in conformita' a quanto disposto agli articoli 22 e 23-bis.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-bis c.1',
        'testo': "È istituito presso il Ministero dello sviluppo economico l'INI-PEC, pubblico elenco dei domicili digitali di imprese e professionisti, per favorire istanze/dichiarazioni telematiche e lo scambio informativo con le PA.",
        'testo_integrale': "Al fine di favorire la presentazione di istanze, dichiarazioni e dati, nonche' lo scambio di informazioni e documenti tra i soggetti di cui all'articolo 2, comma 2 e le imprese e i professionisti in modalita' telematica, e' istituito il pubblico elenco denominato Indice nazionale dei domicili digitali (INI-PEC) delle imprese e dei professionisti, presso il Ministero per lo sviluppo economico.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-bis c.2-bis',
        'testo': "L'INI-PEC acquisisce dagli ordini e collegi professionali gli attributi qualificati di identità digitale per le finalità del decreto ex art. 64 c.2-sexies.",
        'testo_integrale': "L'INI-PEC acquisisce dagli ordini e dai collegi professionali gli attributi qualificati dell'identita' digitale ai fini di quanto previsto dal decreto di cui all'articolo 64, comma 2-sexies.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-bis c.4',
        'testo': "Il Ministero dello sviluppo economico, sentita l'AgID, si avvale delle strutture informatiche delle Camere di commercio per realizzare e gestire l'INI-PEC, definendo con proprio decreto (entro 60 giorni) le modalità di accesso e aggiornamento.",
        'testo_integrale': "Il Ministero per lo sviluppo economico, al fine del contenimento dei costi e dell'utilizzo razionale delle risorse, sentita l'Agenzia per l'Italia digitale, si avvale per la realizzazione e gestione operativa dell'Indice nazionale di cui al comma 1 delle strutture informatiche delle Camere di commercio deputate alla gestione del registro imprese e ne definisce con proprio decreto, da emanare entro 60 giorni dalla data di entrata in vigore della presente disposizione, le modalita' di accesso e di aggiornamento.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-bis c.5',
        'testo': "Il decreto di cui al c.4 definisce le modalità con cui ordini/collegi professionali e PA comunicano all'INI-PEC gli indirizzi PEC dei professionisti, e gli strumenti telematici delle Camere di commercio per ottimizzarne raccolta e aggiornamento.",
        'testo_integrale': "Nel decreto di cui al comma 4 sono anche definite le modalita' e le forme con cui gli ordini e i collegi professionali ((nonche' le pubbliche amministrazioni)) comunicano all'Indice nazionale di cui al comma 1 tutti gli indirizzi PEC relativi ai professionisti di propria competenza e sono previsti gli strumenti telematici resi disponibili dalle Camere di commercio per il tramite delle proprie strutture informatiche al fine di ottimizzare la raccolta e aggiornamento dei medesimi indirizzi.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-ter c.1',
        'testo': "È istituito l'Indice dei domicili digitali di PA, gestori di pubblici servizi e società a controllo pubblico, per pubblicità dei riferimenti telematici e comunicazioni/notifiche a tutti gli effetti di legge con i privati.",
        'testo_integrale': 'Al fine di assicurare la pubblicita\' dei riferimenti telematici delle pubbliche amministrazioni, dei gestori dei pubblici servizi e delle societa\' a controllo pubblico, e\' istituito il pubblico elenco di fiducia denominato "Indice dei domicili digitali della pubblica amministrazione, dei gestori di pubblici servizi e delle societa\' a controllo pubblico", nel quale sono indicati i domicili digitali da utilizzare per le comunicazioni, per lo scambio di informazioni e per l\'invio di documenti a tutti gli effetti di legge tra le pubbliche amministrazioni, i gestori di pubblici servizi, le societa\' a controllo pubblico e i privati.',
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-ter c.1-bis',
        'testo': "L'Indice garantisce, su richiesta, l'inserimento dei dati per la fatturazione elettronica (L. 244/2007 art.1 co.209-213; D.Lgs. 148/2018) per ogni PA, gestore di pubblico servizio o società a controllo pubblico.",
        'testo_integrale': "Per ogni pubblica amministrazione o gestore di pubblico servizio nonche' per le societa' a controllo pubblico, l'Indice di cui al comma 1 garantisce, a richiesta del soggetto, l'inserimento dei dati utili per la gestione della fattura elettronica ai sensi dell'articolo 1, commi 209, 210, 211, 212 e 213, della legge 24 dicembre 2007, n. 244, e del decreto legislativo 27 dicembre 2018, n. 148.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-ter c.2',
        'testo': "Realizzazione e gestione dell'Indice sono affidate all'AgID, che può avvalersi di elenchi già formati dalle PA, incluso quello ex art.1 c.3 L. 196/2009.",
        'testo_integrale': "La realizzazione e la gestione dell'Indice sono affidate all'AgID, che puo' utilizzare a tal fine elenchi e repertori gia' formati dalle amministrazioni pubbliche , incluso l'elenco di cui all'articolo 1, comma 3, ((della)) legge 31 dicembre 2009, n. 196",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-ter c.2-bis',
        'testo': "L'iscrizione all'Indice avviene su richiesta o d'ufficio da AgID, non incompatibile con l'INI-PEC; i due indici garantiscono l'univocità e il costante allineamento dei domicili tramite la piattaforma ex art. 50-ter.",
        'testo_integrale': "L'iscrizione ((nell'Indice di cui al comma 1)) avviene a richiesta del soggetto interessato o d'ufficio da parte dell'AgID e non e' incompatibile con l'iscrizione nell'Indice di cui all'articolo 6-bis. Ai fini di garantire l'univocita' dei domicili digitali nei pubblici elenchi, l'Indice di cui al presente articolo e quello di cui all'articolo 6-bis garantiscono il costante allineamento dei domicili digitali, tramite i servizi della piattaforma di cui all'articolo 50-ter.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-ter c.3',
        'testo': "Le amministrazioni, i gestori di pubblici servizi e le società a controllo pubblico aggiornano l'Indice tempestivamente (almeno semestralmente); la mancata comunicazione rileva ai fini della responsabilità dirigenziale/retribuzione di risultato, e si applica la sanzione di cui all'art. 18-bis.",
        'testo_integrale': "Le amministrazioni di cui al comma 1, i gestori di pubblici servizi e le societa' a controllo pubblico aggiornano gli indirizzi e i dati dell'Indice ((di cui al medesimo comma 1)) tempestivamente e comunque con cadenza almeno semestrale, secondo le indicazioni dell'AgID. La mancata comunicazione degli elementi necessari al completamento dell'Indice e del loro aggiornamento e' valutata ai fini della responsabilita' dirigenziale e dell'attribuzione della retribuzione di risultato ai dirigenti responsabili. In caso di violazione delle disposizioni di cui al presente comma, si applica l'articolo 18-bis.",
        'tipo_obbligo': 'sanzionatorio',
        'stato': 'vigente',
        'severita': 'media',
        'sanzioni': 'Responsabilità dirigenziale, riduzione retribuzione di risultato; sanzione ex art. 18-bis CAD.',
    },
    {
        'riferimento': 'art. 6-quater c.1',
        'testo': "È istituito l'Indice dei domicili digitali di persone fisiche, professionisti e altri enti di diritto privato non iscritti all'INI-PEC (domicili eletti ex art. 3-bis c.1-bis); realizzazione e gestione affidate ad AgID tramite le Camere di commercio; il professionista non iscritto all'INI-PEC può eleggere sia un domicilio professionale sia uno personale distinto.",
        'testo_integrale': "E' istituito il pubblico elenco dei domicili digitali delle persone fisiche, dei professionisti e degli altri enti di diritto privato non tenuti all'iscrizione nell'indice di cui all'articolo 6-bis, nel quale sono indicati i domicili eletti ai sensi dell'articolo 3-bis, comma 1-bis. La realizzazione e la gestione del presente Indice sono affidate all'AgID, che vi provvede avvalendosi delle strutture informatiche delle Camere di commercio gia' deputate alla gestione dell'elenco di cui all'articolo 6-bis. E' fatta salva la facolta' del professionista, non iscritto in albi, registri o elenchi professionali di cui all'articolo 6-bis, di eleggere presso il presente Indice un domicilio digitale professionale e un domicilio digitale personale diverso dal primo.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-quater c.3',
        'testo': "AgID aggiorna/trasferisce costantemente in ANPR i domicili digitali delle persone fisiche contenuti nell'Indice, e il Ministero dell'interno fa altrettanto in senso inverso da ANPR all'Indice; con le risorse disponibili a legislazione vigente, senza nuovi oneri.",
        'testo_integrale': "AgID provvede costantemente all'aggiornamento e al trasferimento dei domicili digitali delle persone fisiche contenuti nell'elenco di cui al presente articolo nell'ANPR e il Ministero dell'interno provvede costantemente all'aggiornamento e al trasferimento dei domicili digitali delle persone fisiche contenuti ((nell'ANPR)) nell'elenco di cui al presente articolo. Le funzioni di aggiornamento e trasferimento dei dati sono svolte con le risorse disponibili a legislazione vigente, senza nuovi o maggiori oneri a carico della ((finanza pubblica)).",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-quinquies c.1',
        'testo': 'La consultazione online degli elenchi (artt. 6-bis, 6-ter, 6-quater) è libera senza autenticazione; gli elenchi sono in formato aperto.',
        'testo_integrale': "La consultazione on-line degli elenchi di cui agli articoli 6-bis, 6-ter e 6-quater e' consentita a chiunque senza necessita' di autenticazione. Gli elenchi sono realizzati in formato aperto.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-quinquies c.2',
        'testo': "L'estrazione dei domicili digitali dagli elenchi avviene secondo le modalità fissate da AgID nelle Linee guida.",
        'testo_integrale': "L'estrazione dei domicili digitali dagli elenchi, di cui agli articoli 6-bis, 6-ter e 6-quater, e' effettuata secondo le modalita' fissate da AgID nelle Linee guida.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-quinquies c.3',
        'testo': 'È vietato utilizzare i domicili digitali per comunicazioni commerciali (art. 2 c.1 lett. f, D.Lgs. 70/2003) senza la preventiva autorizzazione del titolare.',
        'testo_integrale': "In assenza di preventiva autorizzazione del titolare dell'indirizzo, e' vietato l'utilizzo dei domicili digitali di cui al presente articolo ((per l'invio di comunicazioni commerciali, come definite dall'articolo 2, comma 1, lettera f), del decreto legislativo 9 aprile 2003, n. 70)).",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 7 c.1',
        'testo': "I soggetti art. 2 c.2 riorganizzano e aggiornano i servizi, sulla base dell'analisi delle esigenze degli utenti, rendendoli disponibili online nel rispetto del Codice e degli standard/livelli di qualità AgID (Linee guida, aggiornati periodicamente).",
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, provvedono alla riorganizzazione e all'aggiornamento dei servizi resi, sulla base di una preventiva analisi delle reali esigenze ((degli utenti)) e rendono disponibili ((on-line i propri servizi)) nel rispetto delle disposizioni del presente Codice e degli standard ((e dei livelli di qualita' individuati e periodicamente aggiornati dall'AgID con proprie Linee guida tenuto anche conto dell'evoluzione tecnologica)).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 7 c.3',
        'testo': 'Per i servizi in rete, i soggetti art. 2 c.2 raccolgono la soddisfazione degli utenti su qualità/fruibilità/accessibilità/tempestività e pubblicano sul proprio sito i relativi dati, incluse le statistiche di utilizzo.',
        'testo_integrale': "Per i servizi in rete, i soggetti di cui all'articolo 2, comma 2, consentono agli utenti di esprimere la soddisfazione rispetto alla qualita', anche in termini di fruibilita', accessibilita' e tempestivita', del servizio reso all'utente stesso e pubblicano sui propri siti i dati risultanti, ivi incluse le statistiche di utilizzo.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 8 c.1',
        'testo': 'Lo Stato e i soggetti art. 2 c.2 promuovono iniziative per la cultura digitale dei cittadini (specie minori e categorie a rischio di esclusione), anche per competenze di informatica giuridica e uso dei servizi digitali PA, avvalendosi di vari mezzi incluso il servizio radiotelevisivo.',
        'testo_integrale': "Lo Stato e i soggetti di cui all'articolo 2, comma 2, promuovono iniziative volte a favorire la diffusione della cultura digitale tra i cittadini con particolare riguardo ai minori e alle categorie a rischio di esclusione, anche al fine di favorire lo sviluppo di competenze di informatica giuridica e l'utilizzo dei servizi digitali delle pubbliche amministrazioni con azioni specifiche e concrete, avvalendosi di un insieme di mezzi diversi fra i quali il servizio radiotelevisivo.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 8-bis c.1',
        'testo': 'I soggetti art. 2 c.2 favoriscono la connettività Internet in uffici e luoghi pubblici (scuola, sanità, turismo), anche mettendo a disposizione la banda inutilizzata, nel rispetto degli standard di sicurezza AgID.',
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, favoriscono, in linea con gli obiettivi dell'Agenda digitale europea, la disponibilita' di connettivita' alla rete Internet presso gli uffici pubblici e altri luoghi pubblici, in particolare nei settori scolastico, sanitario e di interesse turistico, anche prevedendo che la porzione di banda non utilizzata dagli stessi uffici sia messa a disposizione degli utenti ((nel rispetto degli)) standard di sicurezza fissati dall'Agid.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 8-bis c.2',
        'testo': 'I soggetti art. 2 c.2 mettono a disposizione degli utenti connettività a banda larga, nei limiti disponibili e secondo le modalità AgID.',
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, mettono a disposizione degli utenti connettivita' a banda larga per l'accesso alla rete Internet nei limiti della banda disponibile e con le modalita' determinate dall'AgID.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 9 c.1',
        'testo': "I soggetti art. 2 c.2 favoriscono l'uso delle nuove tecnologie per la partecipazione democratica dei cittadini (anche residenti all'estero) e l'esercizio dei diritti politici/civili, anche tramite consultazioni telematiche preventive sugli schemi di atto.",
        'testo_integrale': "((I soggetti di cui all'articolo 2, comma 2,)) favoriscono ogni forma di uso delle nuove tecnologie per promuovere una maggiore partecipazione dei cittadini, anche residenti all'estero, al processo democratico e per facilitare l'esercizio dei diritti politici e civili ((e migliorare la qualita' dei propri atti, anche attraverso l'utilizzo, ove previsto e nell'ambito delle risorse disponibili a legislazione vigente, di forme di consultazione preventiva per via telematica sugli schemi di atto da adottare)).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 12 c.1',
        'testo': "Le PA, nell'organizzare autonomamente la propria attività, utilizzano le TIC per efficienza/efficacia/economicità/imparzialità/trasparenza/semplificazione/partecipazione, nel rispetto di uguaglianza e non discriminazione, per l'effettivo riconoscimento dei diritti dei cittadini/imprese, in conformità al Piano triennale (art. 14-bis c.2 lett. b).",
        'testo_integrale': "Le pubbliche amministrazioni nell'organizzare autonomamente la propria attivita' utilizzano le tecnologie dell'informazione e della comunicazione per la realizzazione degli obiettivi di efficienza, efficacia, economicita', imparzialita', trasparenza, semplificazione e partecipazione nel rispetto dei principi di uguaglianza e di non discriminazione, nonche' per l'effettivo riconoscimento dei diritti dei cittadini e delle imprese di cui al presente Codice in conformita' agli obiettivi indicati nel Piano triennale per l'informatica nella pubblica amministrazione di cui all'articolo 14-bis, comma 2, lettera b).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 12 c.1-bis',
        'testo': 'Gli organi di Governo, nelle direttive generali ex art.14 c.1 D.Lgs. 165/2001, e le PA, nel piano di performance ex art.10 D.Lgs.150/2009, dettano disposizioni attuative del Codice.',
        'testo_integrale': "Gli organi di Governo nell'esercizio delle funzioni di indirizzo politico ed in particolare nell'emanazione delle direttive generali per l'attivita' amministrativa e per la gestione ai sensi del comma 1 dell'articolo 14 del decreto legislativo 30 marzo 2001, n. 165, e le amministrazioni pubbliche nella redazione del piano di performance di cui all'articolo 10 del decreto legislativo 27 ottobre 2009, n. 150, dettano disposizioni per l'attuazione delle disposizioni del presente Codice.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 12 c.1-ter',
        'testo': "I dirigenti rispondono dell'osservanza/attuazione del Codice ex artt. 21 e 55 D.Lgs. 165/2001 (ferme responsabilità penali/civili/contabili); l'attuazione rileva ai fini della valutazione della performance organizzativa e individuale.",
        'testo_integrale': "I dirigenti rispondono dell'osservanza ed attuazione delle disposizioni di cui al presente Codice ai sensi e nei limiti degli articoli 21 e 55 del decreto legislativo 30 marzo 2001, n. 165, ferme restando le eventuali responsabilita' penali, civili e contabili previste dalle norme vigenti. L'attuazione delle disposizioni del presente Codice e' comunque rilevante ai fini della misurazione e valutazione della performance organizzativa ed individuale dei dirigenti.",
        'tipo_obbligo': 'sanzionatorio',
        'stato': 'vigente',
        'sanzioni': 'Responsabilità dirigenziale ex artt. 21 e 55 D.Lgs. 165/2001; rilevanza su valutazione performance.',
    },
    {
        'riferimento': 'art. 12 c.2',
        'testo': 'Le PA utilizzano le TIC nei rapporti interni, interamministrativi e con i privati, garantendo interoperabilità dei sistemi e integrazione dei processi di servizio nel rispetto delle Linee guida.',
        'testo_integrale': "Le pubbliche amministrazioni utilizzano, nei rapporti interni, in quelli con altre amministrazioni e con i privati, le tecnologie dell'informazione e della comunicazione, garantendo l'interoperabilita' dei sistemi e l'integrazione dei processi di servizio fra le diverse amministrazioni nel rispetto delle Linee guida. (28)",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'condizione_applicabilita': 'La disposizione si applica con riferimento ai nuovi sistemi informativi delle pubbliche amministrazioni (art. 11, comma 2, D.Lgs. 26 agosto 2016, n. 179).',
    },
    {
        'riferimento': 'art. 12 c.3',
        'testo': "Le PA assicurano uniformità e graduale integrazione delle modalità di interazione con i servizi informatici (incluse reti telefoniche fisse/mobili), qualunque sia il canale, nel rispetto dell'autonomia di ciascun erogatore.",
        'testo_integrale': "Le pubbliche amministrazioni operano per assicurare l'uniformita' e la graduale integrazione delle modalita' di interazione degli utenti con i servizi informatici , ivi comprese le reti di telefonia fissa e mobile in tutte le loro articolazioni, da esse erogati, qualunque sia il canale di erogazione, nel rispetto della autonomia e della specificita' di ciascun erogatore di servizi.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 12 c.3-bis',
        'testo': 'I soggetti art. 2 c.2 favoriscono il BYOD (o dispositivi personalizzabili) per la prestazione lavorativa; in tal caso adottano misure di sicurezza dei dati (nel rispetto della privacy), informano adeguatamente i lavoratori (linee guida) e disciplinano uso di webcam/microfoni, previa informazione alle organizzazioni sindacali.',
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, favoriscono l'uso da parte dei lavoratori di dispositivi elettronici personali o, se di proprieta' dei predetti soggetti, personalizzabili, al fine di ottimizzare la prestazione lavorativa, nel rispetto delle condizioni di sicurezza nell'utilizzo. In caso di uso di dispositivi elettronici personali, i soggetti di cui all'articolo 2, comma 2, nel rispetto della disciplina in materia di trattamento dei dati personali, adottano ogni misura atta a garantire la sicurezza e la protezione delle informazioni e dei dati, tenendo conto delle migliori pratiche e degli standard nazionali, europei e internazionali per la protezione delle proprie reti, nonche' ((a condizione che sia data al lavoratore adeguata informazione)) sull'uso sicuro dei dispositivi, anche attraverso la diffusione di apposite linee guida, e disciplinando, tra l'altro l'uso di webcam e microfoni ((, previa informazione alle organizzazioni sindacali)).",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 12 c.3-ter',
        'testo': 'Per il lavoro agile, i soggetti art. 2 c.2 lett. a) acquistano beni e sviluppano sistemi/servizi informatici che consentano accesso remoto (L. 300/1970, D.Lgs. 81/2008, L. 81/2017), assicurando sicurezza informatica adeguata (specie per servizi cloud), informando i lavoratori e disciplinando le attività svolgibili, previa informazione sindacale.',
        'testo_integrale': "Al fine di agevolare la diffusione del lavoro agile quale modalita' di esecuzione del rapporto di lavoro subordinato, i soggetti di cui all'articolo 2, comma 2, lettera a), acquistano beni e progettano e sviluppano i sistemi informativi e i servizi informatici con modalita' idonee a consentire ai lavoratori di accedere da remoto ad applicativi, dati e informazioni necessari allo svolgimento della prestazione lavorativa, nel rispetto della legge 20 maggio 1970, n. 300, del decreto legislativo 9 aprile 2008, n. 81 e della legge 22 maggio 2017, n. 81, assicurando un adeguato livello di sicurezza informatica, in linea con le migliori pratiche e gli standard nazionali ed internazionali per la protezione delle proprie reti, nonche' ((a condizione che sia data al lavoratore adeguata informazione)) sull'uso sicuro degli strumenti impiegati, con particolare riguardo a quelli erogati tramite fornitori di servizi in cloud, anche attraverso la diffusione di apposite linee guida, e disciplinando anche la tipologia di attivita' che possono essere svolte ((, previa informazione alle organizzazioni sindacali)).",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 13 c.1',
        'testo': 'Le PA, nei limiti delle risorse disponibili, attuano politiche di reclutamento e formazione del personale su TIC, accessibilità e tecnologie assistive (art. 8 L. 4/2004).',
        'testo_integrale': "Le pubbliche amministrazioni ((, nell'ambito delle risorse finanziarie disponibili, attuano politiche di reclutamento e)) formazione del personale finalizzate alla conoscenza e all'uso delle tecnologie dell'informazione e della comunicazione, nonche' dei temi relativi all'accessibilita' e alle tecnologie assistive, ai sensi dell'articolo 8 della legge 9 gennaio 2004, n. 4.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 13 c.1-bis',
        'testo': 'Le politiche di formazione (c.1) sviluppano anche le competenze tecnologiche, di informatica giuridica e manageriali dei dirigenti, per la transizione alla modalità operativa digitale.',
        'testo_integrale': "Le politiche di formazione di cui al comma 1 sono altresi' volte allo sviluppo delle competenze tecnologiche, di informatica giuridica e manageriali dei dirigenti, per la transizione alla modalita' operativa digitale.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 13-bis c.1',
        'testo': "I soggetti art. 2 c.2 lett. a) progettano/sviluppano sistemi informatici e servizi digitali coerenti con l'agenda digitale italiana/europea e nel rispetto del codice di condotta tecnologica (adottato dal Capo Dipartimento trasformazione digitale, sentiti AgID e nucleo sicurezza cibernetica ex art.12 c.6 D.Lgs.65/2018, con parere Conferenza unificata, entro 60 giorni).",
        'testo_integrale': "Al fine di favorire la digitalizzazione della pubblica amministrazione e garantire il necessario coordinamento sul piano tecnico delle varie iniziative di innovazione tecnologica, i soggetti di cui all'articolo 2, comma 2, lettera a), nell'ambito delle risorse disponibili, progettano, realizzano e sviluppano i propri sistemi informatici e servizi digitali, in coerenza con gli obiettivi dell'agenda digitale italiana ed europea e nel rispetto del codice di condotta tecnologica adottato dal Capo dipartimento della struttura della Presidenza del Consiglio dei ministri competente per la trasformazione digitale, ((sentiti l'AgID)) e il nucleo per la sicurezza cibernetica di cui all'articolo 12, comma 6, del decreto legislativo 18 maggio 2018, n. 65 e acquisito il parere della Conferenza unificata di cui all'articolo 8 del decreto legislativo 28 agosto 1997, n. 281, entro sessanta giorni dall'entrata in vigore della presente disposizione.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 13-bis c.3',
        'testo': 'I soggetti art. 2 c.2 lett. a) che avviano progetti di sviluppo di servizi digitali devono rispettare il codice di condotta tecnologica e possono avvalersi di esperti qualificati (nei limiti delle risorse disponibili); il codice indica le attività degli esperti (incl. formazione del personale, in collaborazione col responsabile transizione digitale), durata massima, requisiti e trattamento economico massimo.',
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, lettera a), che avviano progetti di sviluppo dei servizi digitali sono tenuti a rispettare il codice di condotta tecnologica ((e possono avvalersi)), singolarmente o in forma associata, di uno o piu' esperti in possesso di comprovata esperienza e qualificazione professionale nello sviluppo e nella gestione di processi complessi di trasformazione tecnologica e progetti di trasformazione digitale, nel limite delle risorse progettuali disponibili a legislazione vigente per lo scopo. Il codice di condotta tecnologica indica anche le principali attivita', ivi compresa la formazione del personale, che gli esperti svolgono in collaborazione con il responsabile per la transizione digitale dell'amministrazione pubblica interessata, nonche' il limite massimo di durata dell'incarico, i requisiti di esperienza e qualificazione professionale e il trattamento economico massimo da riconoscere agli esperti.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 13-bis c.4',
        'testo': "Nella realizzazione/sviluppo dei sistemi informativi va sempre assicurata l'integrazione con le piattaforme abilitanti (artt.5, 62, 64, 64-bis) e l'accesso remoto per il lavoro agile, con adeguata sicurezza informatica, consapevolezza dei lavoratori (linee guida) e disciplina delle attività svolgibili.",
        'testo_integrale': "Nella realizzazione ((e nello sviluppo)) dei sistemi informativi, e' sempre assicurata l'integrazione con le piattaforme abilitanti previste dagli articoli 5, 62, 64 e 64-bis, nonche' la possibilita' di accedere da remoto ad applicativi, ((dati e informazioni necessari)) allo svolgimento della prestazione lavorativa in modalita' agile, assicurando un adeguato livello di sicurezza informatica, in linea con le migliori pratiche e gli standard nazionali ed internazionali per la protezione delle proprie reti, nonche' promuovendo la consapevolezza dei lavoratori sull'uso sicuro dei suddetti sistemi informativi, anche attraverso la diffusione di apposite linee guida, e disciplinando anche la tipologia di attivita' che possono essere svolte.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 13-bis c.5',
        'testo': 'AgID verifica il rispetto del codice di condotta tecnologica e può diffidare i soggetti inadempienti; la violazione costituisce mancato raggiungimento di risultato/obiettivo dei dirigenti responsabili e comporta riduzione (non inferiore al 30%) della retribuzione di risultato/trattamento accessorio, oltre al divieto di premi/incentivi nelle strutture interessate.',
        'testo_integrale': "L'AgID verifica il rispetto del codice di condotta tecnologica da parte dei soggetti interessati e puo' diffidare i soggetti a conformare la propria condotta agli obblighi previsti dal codice. La progettazione, la realizzazione e lo sviluppo di servizi digitali e sistemi informatici in violazione del codice di condotta tecnologica costituiscono mancato raggiungimento di uno specifico risultato e di un rilevante obiettivo da parte dei dirigenti responsabili delle strutture competenti e comportano la riduzione, non inferiore al 30 per cento, della retribuzione di risultato e del trattamento accessorio collegato alla performance individuale dei dirigenti competenti, oltre al divieto di attribuire premi o incentivi nell'ambito delle medesime strutture.",
        'tipo_obbligo': 'sanzionatorio',
        'stato': 'vigente',
        'severita': 'alta',
        'sanzioni': 'Riduzione non inferiore al 30% di retribuzione di risultato/trattamento accessorio dei dirigenti; divieto premi/incentivi nella struttura; diffida AgID.',
    },
    {
        'riferimento': 'art. 14 c.1',
        'testo': "In attuazione dell'art. 117 c.2 lett. r) Cost., lo Stato disciplina il coordinamento informatico dei dati di amministrazione statale/regionale/locale, con regole tecniche per sicurezza/interoperabilità dei sistemi e per l'accesso ai servizi in rete.",
        'testo_integrale': "In attuazione del disposto dell'articolo 117, secondo comma, lettera r), della Costituzione, lo Stato disciplina il coordinamento informatico dei dati dell'amministrazione statale, regionale e locale, dettando anche le regole tecniche necessarie per garantire la sicurezza e l'interoperabilita' dei sistemi informatici e dei flussi informativi per la circolazione e lo scambio dei dati e per l'accesso ai servizi erogati in rete dalle amministrazioni medesime.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14 c.2',
        'testo': "Stato, regioni ed enti locali promuovono intese/accordi tramite Conferenza unificata per l'Agenda digitale e la digitalizzazione coordinata dell'azione amministrativa; la Presidenza del Consiglio (anche con AgID) assicura il coordinamento informatico statale/regionale/locale, favorendo infrastrutture/standard che riducano costi e migliorino servizi, con adeguata sicurezza informatica e consapevolezza dei lavoratori (linee guida).",
        'testo_integrale': "Lo Stato, le regioni e le autonomie locali promuovono le intese e gli accordi e adottano, attraverso la Conferenza unificata, gli indirizzi utili per realizzare gli obiettivi dell'Agenda digitale europea e nazionale e realizzare un processo di digitalizzazione dell'azione amministrativa coordinato e condiviso e per l'individuazione delle Linee guida. ((La Presidenza del Consiglio dei ministri, anche avvalendosi dell'AgID,)) assicura il coordinamento informatico dell'amministrazione statale, regionale e locale, con la finalita' di progettare e monitorare l'evoluzione strategica del sistema informativo della pubblica amministrazione, favorendo l'adozione di infrastrutture e standard che riducano i costi sostenuti dalle amministrazioni e migliorino i servizi erogati ((assicurando un adeguato livello di sicurezza informatica, in linea con le migliori pratiche e gli standard nazionali ed internazionali per la protezione delle proprie reti, nonche' promuovendo la consapevolezza dei lavoratori sull'uso sicuro dei suddetti sistemi informativi, anche attraverso la diffusione di apposite linee guida che disciplinano anche la tipologia di attivita' che possono essere svolte.)).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14 c.2-bis',
        'testo': "Le regioni promuovono sul territorio la digitalizzazione coordinata e condivisa dell'azione amministrativa tra gli enti locali.",
        'testo_integrale': "Le regioni promuovono sul territorio azioni tese a realizzare un processo di digitalizzazione dell'azione amministrativa coordinato e condiviso tra le autonomie locali.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14 c.2-ter',
        'testo': 'Regioni ed enti locali digitalizzano la propria azione amministrativa e implementano le TIC per servizi migliori a cittadini/imprese, secondo le modalità del c.2.',
        'testo_integrale': "Le regioni e gli enti locali digitalizzano la loro azione amministrativa e implementano l'utilizzo delle tecnologie dell'informazione e della comunicazione per garantire servizi migliori ai cittadini e alle imprese, secondo le modalita' di cui al comma 2.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.a',
        'testo': "AgID emana Linee guida (regole, standard, guide tecniche) e svolge indirizzo, vigilanza e controllo sull'attuazione del Codice, anche con atti amministrativi generali, su agenda digitale, digitalizzazione PA, sicurezza informatica, interoperabilità e cooperazione applicativa con l'UE.",
        'testo_integrale': "emanazione di Linee guida contenenti regole, standard e guide tecniche, nonche' di indirizzo, vigilanza e controllo sull'attuazione e sul rispetto delle norme di cui al presente Codice, anche attraverso l'adozione di atti amministrativi generali, in materia di agenda digitale, digitalizzazione della pubblica amministrazione, sicurezza informatica, interoperabilita' e cooperazione applicativa tra sistemi informatici pubblici e quelli dell'Unione europea;",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.b',
        'testo': "AgID programma e coordina l'uso delle TIC dalle PA redigendo e verificando il Piano triennale per l'informatica nella PA (obiettivi e interventi), elaborato anche sui dati dei soggetti art. 2 c.2 e approvato dal Presidente del Consiglio/Ministro delegato entro il 30 settembre di ogni anno.",
        'testo_integrale': "programmazione e coordinamento delle attivita' delle amministrazioni per l'uso delle tecnologie dell'informazione e della comunicazione, mediante la redazione e la successiva verifica dell'attuazione del Piano triennale per l'informatica nella pubblica amministrazione contenente la fissazione degli obiettivi e l'individuazione dei principali interventi di sviluppo e gestione dei sistemi informativi delle amministrazioni pubbliche. Il predetto Piano e' elaborato dall'AgID, anche sulla base dei dati e delle informazioni acquisiti dai soggetti di cui all'articolo 2, comma 2, ed e' approvato dal Presidente del Consiglio dei ministri o dal Ministro delegato entro il 30 settembre di ogni anno;",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.c',
        'testo': 'AgID monitora le attività delle amministrazioni (inclusi gli investimenti ex art.1 c.492 lett. a-bis L.232/2016) rispetto al Piano triennale e verifica i risultati/costi-benefici dei sistemi informatici secondo modalità proprie.',
        'testo_integrale': "monitoraggio delle attivita' svolte dalle amministrazioni, ivi inclusi gli investimenti effettuati ai sensi dell'articolo 1, comma 492, lettera a-bis), della legge 11 dicembre 2016, n. 232, in relazione alla loro coerenza con il Piano triennale di cui alla lettera b) e verifica dei risultati conseguiti dalle singole amministrazioni con particolare riferimento ai costi e benefici dei sistemi informatici secondo le modalita' fissate dalla stessa Agenzia;",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.d',
        'testo': 'AgID predispone, realizza e gestisce interventi/progetti di innovazione (anche tramite terzi), progetta e coordina iniziative strategiche di preminente interesse nazionale, anche intersettoriali.',
        'testo_integrale': "predisposizione, realizzazione e gestione di interventi e progetti di innovazione, anche realizzando e gestendo direttamente o avvalendosi di soggetti terzi, specifici progetti in tema di innovazione ad essa assegnati nonche' svolgendo attivita' di progettazione e coordinamento delle iniziative strategiche e di preminente interesse nazionale, anche a carattere intersettoriale;",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.e',
        'testo': 'AgID promuove la cultura digitale e la ricerca, anche tramite comunità digitali regionali.',
        'testo_integrale': "promozione della cultura digitale e della ricerca anche tramite comunita' digitali regionali;",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.f',
        'testo': "AgID rilascia pareri tecnici obbligatori non vincolanti su schemi di contratti/accordi quadro delle PA centrali per beni/servizi di sistemi informativi automatizzati (soglie: 1M€ procedura negoziata, 2M€ procedura ristretta/aperta), valutando congruità tecnico-economica secondo efficacia/economicità/standard condivisi, entro 45 giorni (artt.16, 17-bis L.241/1990); copia dei pareri di competenza ANAC è trasmessa all'ANAC.",
        'testo_integrale': "rilascio di pareri tecnici, obbligatori e non vincolanti, sugli schemi di contratti e accordi quadro da parte delle pubbliche amministrazioni centrali concernenti l'acquisizione di beni e servizi relativi a sistemi informativi automatizzati per quanto riguarda la congruita' tecnico-economica, qualora il valore lordo di detti contratti sia superiore a euro 1.000.000,00 nel caso di procedura negoziata e a euro 2.000.000,00 nel caso di procedura ristretta o di procedura aperta. Il parere e' reso tenendo conto dei principi di efficacia, economicita', ottimizzazione della spesa delle pubbliche amministrazioni e favorendo l'adozione di infrastrutture condivise e standard che riducano i costi sostenuti dalle singole amministrazioni e il miglioramento dei servizi erogati, nonche' in coerenza con i principi, i criteri e le indicazioni contenuti nei piani triennali approvati. Il parere e' reso entro il termine di quarantacinque giorni dal ricevimento della relativa richiesta. Si applicano gli articoli 16 e 17-bis della legge 7 agosto 1990, n. 241, e successive modificazioni. Copia dei pareri tecnici attinenti a questioni di competenza dell'Autorita' nazionale anticorruzione e' trasmessa dall'AgID a detta Autorita';",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.g',
        'testo': "AgID rilascia pareri tecnici obbligatori e vincolanti su elementi essenziali (oggetto, valore, procedura, criterio di aggiudicazione, clausole principali) delle gare Consip/soggetti aggregatori (art.9 D.L.66/2014) per beni/servizi informatici strategici nel piano triennale (art.1 c.512 L.208/2015), entro 45 giorni, con applicazione dell'art. 17-bis L.241/1990 e dei periodi 2-5 della lett. f).",
        'testo_integrale': "rilascio di pareri tecnici, obbligatori e vincolanti, sugli elementi essenziali delle procedure di gara bandite, ai sensi dell'articolo 1, comma 512 della legge 28 dicembre 2015, n. 208, da Consip e dai soggetti aggregatori di cui all'articolo 9 del decreto-legge 24 aprile 2014, n. 66, concernenti l'acquisizione di beni e servizi relativi a sistemi informativi automatizzati e definiti di carattere strategico nel piano triennale. Il parere e' reso entro il termine di quarantacinque giorni dal ricevimento della relativa richiesta e si applica l'articolo 17-bis della legge 7 agosto 1990, n. 241, e successive modificazioni. Ai fini della presente lettera per elementi essenziali si intendono l'oggetto della fornitura o del servizio, il valore economico del contratto, la tipologia di procedura che si intende adottare, il criterio di aggiudicazione e relativa ponderazione, le principali clausole che caratterizzano le prestazioni contrattuali. Si applica quanto previsto nei periodi da 2 a 5 della lettera f);",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.h',
        'testo': "AgID definisce criteri e modalità per il monitoraggio dell'esecuzione dei contratti da parte dell'amministrazione interessata.",
        'testo_integrale': "definizione di criteri e modalita' per il monitoraggio sull'esecuzione dei contratti da parte dell'amministrazione interessata ((...));",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.i',
        'testo': "AgID vigila, come organismo designato ex art.17 Reg. UE 910/2014, sui servizi fiduciari, sui gestori PEC, sui soggetti art.34 c.1-bis lett.b) e sui soggetti pubblici/privati partecipanti a SPID (art.64); può irrogare le sanzioni amministrative ex art. 32-bis, commisurate a gravità della violazione e danno all'utenza.",
        'testo_integrale': "vigilanza sui servizi fiduciari ai sensi dell'articolo 17 del regolamento UE 910/2014 in qualita' di organismo a tal fine designato, sui gestori di posta elettronica certificata, sui (( soggetti di cui all'articolo 34, comma 1-bis, lettera b) )), nonche' sui soggetti, pubblici e privati, che partecipano a SPID di cui all'articolo 64; nell'esercizio di tale funzione l'Agenzia puo' irrogare per le violazioni accertate a carico dei soggetti vigilati le sanzioni amministrative di cui all'articolo 32-bis in relazione alla gravita' della violazione accertata e all'entita' del danno provocato all'utenza;",
        'tipo_obbligo': 'sanzionatorio',
        'stato': 'vigente',
        'sanzioni': "Sanzioni amministrative ex art. 32-bis CAD, commisurate a gravità della violazione e danno all'utenza.",
    },
    {
        'riferimento': 'art. 14-bis c.2 lett.l',
        'testo': 'AgID svolge ogni altra funzione attribuita da specifiche disposizioni di legge e dallo Statuto.',
        'testo_integrale': 'ogni altra funzione attribuitale da specifiche disposizioni di legge e dallo Statuto.',
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14-bis c.3',
        'testo': "Fermo il c.2, AgID svolge ogni altra funzione già attribuita per legge/regolamento a DigitPA e all'Agenzia per la diffusione delle tecnologie per l'innovazione.",
        'testo_integrale': "Fermo restando quanto previsto al comma 2, AgID svolge ogni altra funzione prevista da leggi e regolamenti gia' attribuita a DigitPA, all'Agenzia per la diffusione delle tecnologie per l'innovazione ((...)).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 15 c.1',
        'testo': 'La riorganizzazione strutturale/gestionale delle PA (per gli obiettivi ex art.12 c.1) avviene anche tramite il più esteso utilizzo delle TIC in una strategia coordinata di digitalizzazione.',
        'testo_integrale': "La riorganizzazione strutturale e gestionale delle pubbliche amministrazioni volta al perseguimento degli obiettivi di cui all'articolo 12, comma 1, avviene anche attraverso il migliore e piu' esteso utilizzo delle tecnologie dell'informazione e della comunicazione nell'ambito di una coordinata strategia che garantisca il coerente sviluppo del processo di digitalizzazione.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 15 c.2',
        'testo': 'In attuazione del c.1, le PA razionalizzano/semplificano procedimenti, attività gestionali, documenti, modulistica e modalità di accesso/presentazione istanze, in conformità alle prescrizioni tecnologiche delle Linee guida.',
        'testo_integrale': "In attuazione del comma 1, le pubbliche amministrazioni provvedono in particolare a razionalizzare e semplificare i procedimenti amministrativi, le attivita' gestionali, i documenti, la modulistica, le modalita' di accesso e di presentazione delle istanze da parte dei cittadini e delle imprese, assicurando che l'utilizzo delle tecnologie dell'informazione e della comunicazione avvenga in conformita' alle prescrizioni tecnologiche definite nelle ((Linee guida)).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 15 c.2-bis',
        'testo': 'Le PA, valutando i progetti di investimento in innovazione tecnologica, tengono conto dei risparmi effettivi della razionalizzazione (c.2) e dei relativi costi/economie.',
        'testo_integrale': "Le pubbliche amministrazioni nella valutazione dei progetti di investimento in materia di innovazione tecnologica tengono conto degli effettivi risparmi derivanti dalla razionalizzazione di cui al comma 2, nonche' dei costi e delle economie che ne derivano.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 15 c.2-ter',
        'testo': "Le PA quantificano annualmente (art.27 D.Lgs.150/2009) i risparmi conseguiti attuando i commi 1 e 2; due terzi sono utilizzati secondo l'art.27 c.1 D.Lgs.150/2009, un terzo finanzia ulteriori progetti di innovazione.",
        'testo_integrale': "Le pubbliche amministrazioni, quantificano annualmente, ai sensi dell'articolo 27, del decreto legislativo 27 ottobre 2009, n.150, i risparmi effettivamente conseguiti in attuazione delle disposizioni di cui ai commi 1 e 2. Tali risparmi sono utilizzati, per due terzi secondo quanto previsto dall'articolo 27, comma 1, del citato decreto legislativo n. 150 del 2009 e in misura pari ad un terzo per il finanziamento di ulteriori progetti di innovazione.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 15 c.2-quater',
        'testo': 'AgID individua nelle Linee guida criteri/modalità di attuazione dei commi 2-bis e 2-ter; ogni PA dà conto annualmente delle relative attività nella relazione sulla gestione ex art.11 c.6 D.Lgs.118/2011.',
        'testo_integrale': "AgID individua, nell'ambito delle Linee guida, criteri e modalita' di attuazione dei commi 2-bis e 2-ter, prevedendo che ogni pubblica amministrazione dia conto annualmente delle attivita' previste dai predetti commi nella relazione sulla gestione di cui all'articolo 11, comma 6, del decreto legislativo 23 giugno 2011, n. 118.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 15 c.3',
        'testo': "Le PA attuano la digitalizzazione dell'azione amministrativa in modo da garantire la partecipazione dell'Italia alle reti transeuropee di scambio elettronico dati/servizi tra amministrazioni UE.",
        'testo_integrale': "La digitalizzazione dell'azione amministrativa e' attuata dalle pubbliche amministrazioni con modalita' idonee a garantire la partecipazione dell'Italia alla costruzione di reti transeuropee per lo scambio elettronico di dati e servizi fra le amministrazioni dei Paesi membri dell'Unione europea.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
]

RIGHE_PRINCIPI = [
    {
        'riferimento': 'art. 6 c.1',
        'testo': "Le comunicazioni tramite i domicili digitali sono effettuate agli indirizzi degli elenchi di cui agli artt. 6-bis, 6-ter e 6-quater, o al domicilio speciale eletto ai sensi dell'art. 3-bis c.4-quinquies. Le comunicazioni elettroniche trasmesse a un domicilio digitale ex art. 3-bis producono, quanto a momento di spedizione e ricezione, gli stessi effetti giuridici della raccomandata con ricevuta di ritorno ed equivalgono alla notificazione postale, salvo diversa disposizione di legge. Si intendono spedite se inviate al proprio gestore, consegnate se rese disponibili al domicilio digitale del destinatario (salva prova di mancata consegna non imputabile al destinatario). Data e ora di trasmissione/ricezione sono opponibili ai terzi se apposte secondo le Linee guida.",
        'testo_integrale': "Le comunicazioni tramite i domicili digitali sono effettuate agli indirizzi inseriti negli elenchi di cui agli articoli 6-bis, 6-ter e 6-quater, o a quello eletto come domicilio speciale per determinati atti o affari ai sensi dell'articolo 3-bis, comma 4-quinquies. Le comunicazioni elettroniche trasmesse ad uno dei domicili digitali di cui all'articolo 3-bis producono, quanto al momento della spedizione e del ricevimento, gli stessi effetti giuridici delle comunicazioni a mezzo raccomandata con ricevuta di ritorno ed equivalgono alla notificazione per mezzo della posta salvo che la legge disponga diversamente. Le suddette comunicazioni si intendono spedite dal mittente se inviate al proprio gestore e si intendono consegnate se rese disponibili al domicilio digitale del destinatario, salva la prova che la mancata consegna sia dovuta a fatto non imputabile al destinatario medesimo. La data e l'ora di trasmissione e ricezione del documento informatico sono opponibili ai terzi se apposte in conformita' alle Linee guida.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6 c.1-bis',
        'testo': 'Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 6 c.1-ter',
        'testo': "Definisce quale sia l'elenco dei domicili digitali applicabile a ciascuna categoria di soggetti: INI-PEC (art. 6-bis) per imprese e professionisti; Indice PA/gestori (art. 6-ter) per i soggetti art. 2 c.2 lett. a) e b); Indice persone fisiche/altri enti (art. 6-quater) per le persone fisiche e gli altri enti di diritto privato.",
        'testo_integrale': "L'elenco dei domicili digitali delle imprese e dei professionisti e' l'Indice nazionale dei domicili digitali (INI-PEC) delle imprese e dei professionisti di cui all'articolo 6-bis. L'elenco dei domicili digitali dei soggetti di cui all'articolo 2, comma 2, lettere a) e b), e' l'Indice degli indirizzi della pubblica amministrazione e dei gestori di pubblici servizi, di cui all'articolo 6-ter. L'elenco dei domicili digitali delle persone fisiche e degli altri enti di diritto privato diversi da quelli di cui al primo e al secondo periodo e' l'Indice degli indirizzi delle persone fisiche e degli altri enti di diritto privato di cui all'articolo 6-quater.",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6 c.2',
        'testo': 'Comma abrogato dal D.Lgs. 30 dicembre 2010, n. 235.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 30 DICEMBRE 2010, N. 235.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 6 c.2-bis',
        'testo': 'Comma abrogato dal D.Lgs. 30 dicembre 2010, n. 235.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 30 DICEMBRE 2010, N. 235.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 6-bis c.2',
        'testo': "L'INI-PEC è alimentato dagli indirizzi PEC del registro imprese e degli ordini/collegi professionali (art. 16 D.L. 185/2008); vi confluiscono anche i domicili di professionisti iscritti in elenchi pubblici istituiti per legge; i domicili ivi inseriti sono mezzo esclusivo di comunicazione/notifica con i soggetti art. 2 c.2.",
        'testo_integrale': "L'Indice nazionale di cui al comma 1 e' realizzato a partire dagli elenchi di indirizzi PEC costituiti presso il registro delle imprese e gli ordini o collegi professionali, in attuazione di quanto previsto dall'articolo 16 del decreto-legge 29 novembre 2008, n. 185, convertito, con modificazioni, dalla legge 28 gennaio 2009, n. 2. ((Nell'Indice nazionale sono inseriti anche i domicili digitali dei professionisti diversi da quelli di cui al primo periodo, iscritti in elenchi o registri detenuti dalle pubbliche amministrazioni e istituiti con legge dello Stato.)) I domicili digitali inseriti in tale Indice costituiscono mezzo esclusivo di comunicazione e notifica con i soggetti di cui all'articolo 2, comma 2.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-bis c.3',
        'testo': 'Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 6-bis c.6',
        'testo': "Clausola di invarianza finanziaria: dall'attuazione dell'articolo non devono derivare nuovi o maggiori oneri per la finanza pubblica.",
        'testo_integrale': "Dall'attuazione delle disposizioni di cui al presente articolo non devono derivare nuovi o maggiori oneri a carico della finanza pubblica.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-quater c.2',
        'testo': "Per i professionisti iscritti in albi il domicilio digitale è l'indirizzo INI-PEC (salvo diritto di eleggerne uno diverso ex art. 3-bis c.1-bis); il Ministero dello sviluppo economico rende disponibili ad AgID, tramite servizi informatici da Linee guida, gli indirizzi già in INI-PEC.",
        'testo_integrale': "Per i professionisti iscritti in albi ed elenchi il domicilio digitale e' l'indirizzo inserito nell'elenco di cui all'articolo 6-bis, fermo restando il diritto di eleggerne uno diverso ai sensi dell'articolo 3-bis, comma 1-bis. Ai fini dell'inserimento dei domicili dei professionisti nel predetto elenco il Ministero dello sviluppo economico rende disponibili all'AgID, tramite servizi informatici individuati nelle Linee guida, i relativi indirizzi gia' contenuti nell'elenco di cui all'articolo 6-bis.",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 6-quinquies c.4',
        'testo': 'Gli elenchi contengono le informazioni su elezione, modifica o cessazione del domicilio digitale.',
        'testo_integrale': 'Gli elenchi di cui agli articoli 6-bis, 6-ter e 6-quater contengono le informazioni relative alla elezione, modifica o cessazione del domicilio digitale.',
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 7 c.01',
        'testo': 'Chiunque ha diritto di fruire in forma digitale e integrata dei servizi dei soggetti art. 2 c.2, tramite gli strumenti telematici delle PA e il punto di accesso (art. 64-bis), anche da dispositivi mobili.',
        'testo_integrale': "Chiunque ha diritto di fruire dei servizi erogati dai soggetti di cui all'articolo 2, comma 2, in forma digitale e in modo integrato, tramite gli strumenti telematici messi a disposizione dalle pubbliche amministrazioni e il punto di accesso di cui all'articolo 64-bis, anche attraverso dispositivi mobili.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'condizione_applicabilita': "Il diritto e' riconosciuto a decorrere dalla data di attivazione del punto di accesso di cui all'art. 64-bis (art. 65, comma 6, D.Lgs. 13 dicembre 2017, n. 217).",
    },
    {
        'riferimento': 'art. 7 c.2',
        'testo': 'Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 7 c.4',
        'testo': "In caso di violazione degli obblighi dell'articolo, gli utenti (fermo il diritto di rivolgersi al difensore civico digitale ex art.17) possono agire in giudizio, anche secondo il D.Lgs. 198/2009 (class action pubblica amministrazione).",
        'testo_integrale': "In caso di violazione degli obblighi di cui al presente articolo, ((gli utenti, fermo restando il diritto di rivolgersi al difensore civico digitale di cui all'articolo 17,)) possono agire in giudizio, anche nei termini e con le modalita' stabilite nel decreto legislativo 20 dicembre 2009, n. 198.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 10',
        'testo': 'Articolo abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'ARTICOLO ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 11',
        'testo': 'Articolo abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'ARTICOLO ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 12 c.4',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 12 c.5',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 12 c.5-bis',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 13-bis c.2',
        'testo': 'Il codice di condotta tecnologica disciplina progettazione/sviluppo/implementazione di progetti, sistemi e servizi digitali delle PA, nel rispetto della non discriminazione, dei diritti/libertà fondamentali e della disciplina sul perimetro di sicurezza nazionale cibernetica.',
        'testo_integrale': "((2. Il codice di condotta tecnologica disciplina le modalita' di progettazione, sviluppo e implementazione dei progetti, sistemi e servizi digitali delle amministrazioni pubbliche, nel rispetto del principio di non discriminazione, dei diritti e delle liberta' fondamentali delle persone e della disciplina in materia di perimetro nazionale di sicurezza cibernetica))",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 14 c.3',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 14 c.3-bis',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 14-bis c.1',
        'testo': "Definisce AgID come agenzia preposta all'attuazione dell'Agenda Digitale Italiana/europea; promuove l'innovazione digitale e l'uso delle TIC nella PA e nei rapporti con cittadini/imprese, nel rispetto di legalità/imparzialità/trasparenza ed efficienza/economicità/efficacia; collabora con le istituzioni UE e adempie agli obblighi internazionali dello Stato nelle materie di competenza.",
        'testo_integrale': "L'Agenzia per l'Italia Digitale (AgID) e' preposta alla realizzazione degli obiettivi dell'Agenda Digitale Italiana, in coerenza con gli indirizzi dettati dal Presidente del Consiglio dei ministri o dal Ministro delegato, e con l'Agenda digitale europea. AgID, in particolare, promuove l'innovazione digitale nel Paese e l'utilizzo delle tecnologie digitali nell'organizzazione della pubblica amministrazione e nel rapporto tra questa, i cittadini e le imprese, nel rispetto dei principi di legalita', imparzialita' e trasparenza e secondo criteri di efficienza, economicita' ed efficacia. Essa presta la propria collaborazione alle istituzioni dell'Unione europea e svolge i compiti necessari per l'adempimento degli obblighi internazionali assunti dallo Stato nelle materie di competenza.",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 15 c.3-bis',
        'testo': 'Comma abrogato dal D.L. 6 luglio 2012, n. 95, convertito con modificazioni dalla L. 7 agosto 2012, n. 135.',
        'testo_integrale': 'COMMA ABROGATO DAL D.L. 6 LUGLIO 2012, N. 95, CONVERTITO CON MODIFICAZIONI DALLA L. 7 AGOSTO 2012, N. 135.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 15 c.3-ter',
        'testo': 'Comma abrogato dal D.L. 6 luglio 2012, n. 95, convertito con modificazioni dalla L. 7 agosto 2012, n. 135.',
        'testo_integrale': 'COMMA ABROGATO DAL D.L. 6 LUGLIO 2012, N. 95, CONVERTITO CON MODIFICAZIONI DALLA L. 7 AGOSTO 2012, N. 135.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 15 c.3-quater',
        'testo': 'Comma abrogato dal D.L. 6 luglio 2012, n. 95, convertito con modificazioni dalla L. 7 agosto 2012, n. 135.',
        'testo_integrale': 'COMMA ABROGATO DAL D.L. 6 LUGLIO 2012, N. 95, CONVERTITO CON MODIFICAZIONI DALLA L. 7 AGOSTO 2012, N. 135.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 15 c.3-quinquies',
        'testo': 'Comma abrogato dal D.L. 6 luglio 2012, n. 95, convertito con modificazioni dalla L. 7 agosto 2012, n. 135.',
        'testo_integrale': 'COMMA ABROGATO DAL D.L. 6 LUGLIO 2012, N. 95, CONVERTITO CON MODIFICAZIONI DALLA L. 7 AGOSTO 2012, N. 135.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 15 c.3-sexies',
        'testo': 'Comma abrogato dal D.L. 6 luglio 2012, n. 95, convertito con modificazioni dalla L. 7 agosto 2012, n. 135.',
        'testo_integrale': 'COMMA ABROGATO DAL D.L. 6 LUGLIO 2012, N. 95, CONVERTITO CON MODIFICAZIONI DALLA L. 7 AGOSTO 2012, N. 135.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 15 c.3-septies',
        'testo': 'Comma abrogato dal D.L. 6 luglio 2012, n. 95, convertito con modificazioni dalla L. 7 agosto 2012, n. 135.',
        'testo_integrale': 'COMMA ABROGATO DAL D.L. 6 LUGLIO 2012, N. 95, CONVERTITO CON MODIFICAZIONI DALLA L. 7 AGOSTO 2012, N. 135.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 15 c.3-octies',
        'testo': 'Comma abrogato dal D.L. 6 luglio 2012, n. 95, convertito con modificazioni dalla L. 7 agosto 2012, n. 135.',
        'testo_integrale': 'COMMA ABROGATO DAL D.L. 6 LUGLIO 2012, N. 95, CONVERTITO CON MODIFICAZIONI DALLA L. 7 AGOSTO 2012, N. 135.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
]

INDICE_ARTICOLI_LOCALE = [
    'art. 6 c.1',
    'art. 6 c.1-bis',
    'art. 6 c.1-ter',
    'art. 6 c.1-quater',
    'art. 6 c.2',
    'art. 6 c.2-bis',
    'art. 6-bis c.1',
    'art. 6-bis c.2',
    'art. 6-bis c.2-bis',
    'art. 6-bis c.3',
    'art. 6-bis c.4',
    'art. 6-bis c.5',
    'art. 6-bis c.6',
    'art. 6-ter c.1',
    'art. 6-ter c.1-bis',
    'art. 6-ter c.2',
    'art. 6-ter c.2-bis',
    'art. 6-ter c.3',
    'art. 6-quater c.1',
    'art. 6-quater c.2',
    'art. 6-quater c.3',
    'art. 6-quinquies c.1',
    'art. 6-quinquies c.2',
    'art. 6-quinquies c.3',
    'art. 6-quinquies c.4',
    'art. 7 c.01',
    'art. 7 c.1',
    'art. 7 c.2',
    'art. 7 c.3',
    'art. 7 c.4',
    'art. 8 c.1',
    'art. 8-bis c.1',
    'art. 8-bis c.2',
    'art. 9 c.1',
    'art. 10',
    'art. 11',
    'art. 12 c.1',
    'art. 12 c.1-bis',
    'art. 12 c.1-ter',
    'art. 12 c.2',
    'art. 12 c.3',
    'art. 12 c.3-bis',
    'art. 12 c.3-ter',
    'art. 12 c.4',
    'art. 12 c.5',
    'art. 12 c.5-bis',
    'art. 13 c.1',
    'art. 13 c.1-bis',
    'art. 13-bis c.1',
    'art. 13-bis c.2',
    'art. 13-bis c.3',
    'art. 13-bis c.4',
    'art. 13-bis c.5',
    'art. 14 c.1',
    'art. 14 c.2',
    'art. 14 c.2-bis',
    'art. 14 c.2-ter',
    'art. 14 c.3',
    'art. 14 c.3-bis',
    'art. 14-bis c.1',
    'art. 14-bis c.2 lett.a',
    'art. 14-bis c.2 lett.b',
    'art. 14-bis c.2 lett.c',
    'art. 14-bis c.2 lett.d',
    'art. 14-bis c.2 lett.e',
    'art. 14-bis c.2 lett.f',
    'art. 14-bis c.2 lett.g',
    'art. 14-bis c.2 lett.h',
    'art. 14-bis c.2 lett.i',
    'art. 14-bis c.2 lett.l',
    'art. 14-bis c.3',
    'art. 15 c.1',
    'art. 15 c.2',
    'art. 15 c.2-bis',
    'art. 15 c.2-ter',
    'art. 15 c.2-quater',
    'art. 15 c.3',
    'art. 15 c.3-bis',
    'art. 15 c.3-ter',
    'art. 15 c.3-quater',
    'art. 15 c.3-quinquies',
    'art. 15 c.3-sexies',
    'art. 15 c.3-septies',
    'art. 15 c.3-octies',
]

MAPPATURA_LOCALE = {
    'art. 6 c.1': ['art. 6 c.1'],
    'art. 6 c.1-bis': ['art. 6 c.1-bis'],
    'art. 6 c.1-ter': ['art. 6 c.1-ter'],
    'art. 6 c.1-quater': ['art. 6 c.1-quater'],
    'art. 6 c.2': ['art. 6 c.2'],
    'art. 6 c.2-bis': ['art. 6 c.2-bis'],
    'art. 6-bis c.1': ['art. 6-bis c.1'],
    'art. 6-bis c.2': ['art. 6-bis c.2'],
    'art. 6-bis c.2-bis': ['art. 6-bis c.2-bis'],
    'art. 6-bis c.3': ['art. 6-bis c.3'],
    'art. 6-bis c.4': ['art. 6-bis c.4'],
    'art. 6-bis c.5': ['art. 6-bis c.5'],
    'art. 6-bis c.6': ['art. 6-bis c.6'],
    'art. 6-ter c.1': ['art. 6-ter c.1'],
    'art. 6-ter c.1-bis': ['art. 6-ter c.1-bis'],
    'art. 6-ter c.2': ['art. 6-ter c.2'],
    'art. 6-ter c.2-bis': ['art. 6-ter c.2-bis'],
    'art. 6-ter c.3': ['art. 6-ter c.3'],
    'art. 6-quater c.1': ['art. 6-quater c.1'],
    'art. 6-quater c.2': ['art. 6-quater c.2'],
    'art. 6-quater c.3': ['art. 6-quater c.3'],
    'art. 6-quinquies c.1': ['art. 6-quinquies c.1'],
    'art. 6-quinquies c.2': ['art. 6-quinquies c.2'],
    'art. 6-quinquies c.3': ['art. 6-quinquies c.3'],
    'art. 6-quinquies c.4': ['art. 6-quinquies c.4'],
    'art. 7 c.01': ['art. 7 c.01'],
    'art. 7 c.1': ['art. 7 c.1'],
    'art. 7 c.2': ['art. 7 c.2'],
    'art. 7 c.3': ['art. 7 c.3'],
    'art. 7 c.4': ['art. 7 c.4'],
    'art. 8 c.1': ['art. 8 c.1'],
    'art. 8-bis c.1': ['art. 8-bis c.1'],
    'art. 8-bis c.2': ['art. 8-bis c.2'],
    'art. 9 c.1': ['art. 9 c.1'],
    'art. 10': ['art. 10'],
    'art. 11': ['art. 11'],
    'art. 12 c.1': ['art. 12 c.1'],
    'art. 12 c.1-bis': ['art. 12 c.1-bis'],
    'art. 12 c.1-ter': ['art. 12 c.1-ter'],
    'art. 12 c.2': ['art. 12 c.2'],
    'art. 12 c.3': ['art. 12 c.3'],
    'art. 12 c.3-bis': ['art. 12 c.3-bis'],
    'art. 12 c.3-ter': ['art. 12 c.3-ter'],
    'art. 12 c.4': ['art. 12 c.4'],
    'art. 12 c.5': ['art. 12 c.5'],
    'art. 12 c.5-bis': ['art. 12 c.5-bis'],
    'art. 13 c.1': ['art. 13 c.1'],
    'art. 13 c.1-bis': ['art. 13 c.1-bis'],
    'art. 13-bis c.1': ['art. 13-bis c.1'],
    'art. 13-bis c.2': ['art. 13-bis c.2'],
    'art. 13-bis c.3': ['art. 13-bis c.3'],
    'art. 13-bis c.4': ['art. 13-bis c.4'],
    'art. 13-bis c.5': ['art. 13-bis c.5'],
    'art. 14 c.1': ['art. 14 c.1'],
    'art. 14 c.2': ['art. 14 c.2'],
    'art. 14 c.2-bis': ['art. 14 c.2-bis'],
    'art. 14 c.2-ter': ['art. 14 c.2-ter'],
    'art. 14 c.3': ['art. 14 c.3'],
    'art. 14 c.3-bis': ['art. 14 c.3-bis'],
    'art. 14-bis c.1': ['art. 14-bis c.1'],
    'art. 14-bis c.2 lett.a': ['art. 14-bis c.2 lett.a'],
    'art. 14-bis c.2 lett.b': ['art. 14-bis c.2 lett.b'],
    'art. 14-bis c.2 lett.c': ['art. 14-bis c.2 lett.c'],
    'art. 14-bis c.2 lett.d': ['art. 14-bis c.2 lett.d'],
    'art. 14-bis c.2 lett.e': ['art. 14-bis c.2 lett.e'],
    'art. 14-bis c.2 lett.f': ['art. 14-bis c.2 lett.f'],
    'art. 14-bis c.2 lett.g': ['art. 14-bis c.2 lett.g'],
    'art. 14-bis c.2 lett.h': ['art. 14-bis c.2 lett.h'],
    'art. 14-bis c.2 lett.i': ['art. 14-bis c.2 lett.i'],
    'art. 14-bis c.2 lett.l': ['art. 14-bis c.2 lett.l'],
    'art. 14-bis c.3': ['art. 14-bis c.3'],
    'art. 15 c.1': ['art. 15 c.1'],
    'art. 15 c.2': ['art. 15 c.2'],
    'art. 15 c.2-bis': ['art. 15 c.2-bis'],
    'art. 15 c.2-ter': ['art. 15 c.2-ter'],
    'art. 15 c.2-quater': ['art. 15 c.2-quater'],
    'art. 15 c.3': ['art. 15 c.3'],
    'art. 15 c.3-bis': ['art. 15 c.3-bis'],
    'art. 15 c.3-ter': ['art. 15 c.3-ter'],
    'art. 15 c.3-quater': ['art. 15 c.3-quater'],
    'art. 15 c.3-quinquies': ['art. 15 c.3-quinquies'],
    'art. 15 c.3-sexies': ['art. 15 c.3-sexies'],
    'art. 15 c.3-septies': ['art. 15 c.3-septies'],
    'art. 15 c.3-octies': ['art. 15 c.3-octies'],
}

RELAZIONI = [
    {
        "nodo_da": ('principio', None, 'art. 6 c.1-ter'),
        "nodo_a": ('obbligo', None, 'art. 6-bis c.1'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('principio', None, 'art. 6 c.1-ter'),
        "nodo_a": ('obbligo', None, 'art. 6-ter c.1'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('principio', None, 'art. 6 c.1-ter'),
        "nodo_a": ('obbligo', None, 'art. 6-quater c.1'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 6-bis c.4'),
        "nodo_a": ('obbligo', None, 'art. 6-bis c.1'),
        "tipo_relazione": 'specifica',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 6-ter c.2-bis'),
        "nodo_a": ('obbligo', None, 'art. 6-bis c.1'),
        "tipo_relazione": 'si sovrappone a',
    },
    {
        "nodo_da": ('principio', None, 'art. 6-quater c.2'),
        "nodo_a": ('obbligo', None, 'art. 6-bis c.1'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('principio', None, 'art. 7 c.4'),
        "nodo_a": ('obbligo', None, 'art. 7 c.1'),
        "tipo_relazione": 'si applica a',
    },
    {
        "nodo_da": ('principio', None, 'art. 7 c.4'),
        "nodo_a": ('obbligo', None, 'art. 7 c.3'),
        "tipo_relazione": 'si applica a',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 12 c.1'),
        "nodo_a": ('obbligo', None, 'art. 14-bis c.2 lett.b'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('principio', None, 'art. 13-bis c.2'),
        "nodo_a": ('obbligo', None, 'art. 13-bis c.1'),
        "tipo_relazione": 'specifica',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 13-bis c.5'),
        "nodo_a": ('obbligo', None, 'art. 13-bis c.3'),
        "tipo_relazione": 'sanziona',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 15 c.2-bis'),
        "nodo_a": ('obbligo', None, 'art. 15 c.2'),
        "tipo_relazione": 'specifica',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 15 c.2-ter'),
        "nodo_a": ('obbligo', None, 'art. 15 c.2'),
        "tipo_relazione": 'specifica',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 15 c.2-quater'),
        "nodo_a": ('obbligo', None, 'art. 15 c.2-bis'),
        "tipo_relazione": 'specifica',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 15 c.2-quater'),
        "nodo_a": ('obbligo', None, 'art. 15 c.2-ter'),
        "tipo_relazione": 'specifica',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 15 c.1'),
        "nodo_a": ('obbligo', None, 'art. 12 c.1'),
        "tipo_relazione": 'richiama',
    },
]
