"""Estrazione granulare CAD (ADR-0007) — Capo V (parte 2) - Anagrafi e identita' digitali: artt. 62-64-bis.

Fonte: D.Lgs. 82/2005 (CAD), testo vigente al 16/09/2026.
Testo ufficiale: app/.source_cache/cad/cap06.txt.

Contenuto: art. 62 (Anagrafe nazionale della popolazione residente - ANPR), 62-bis (Banca dati
nazionale dei contratti pubblici), 62-ter (Anagrafe nazionale degli assistiti - ANA), 62-quater
(Anagrafe nazionale dell'istruzione - ANIST), 62-quinquies (Anagrafe nazionale dell'istruzione
superiore - ANIS), 62-sexies (Anagrafe nazionale digitale della gente di mare - ANGEMAR), 63
(abrogato), 64 (Sistema pubblico per la gestione delle identita' digitali - SPID/CIE - e modalita' di
accesso ai servizi in rete delle PA), 64-bis (Accesso telematico ai servizi della PA).

Nota sul confine di capitolo: il manifest (app/.source_cache/cad/manifest.json) titola questo
capitolo "artt. 62-64 ter", ma il file sorgente app/.source_cache/cad/cap06.txt termina con l'art.
64-bis; l'art. 64-ter (Piattaforma di gestione deleghe) apre invece app/.source_cache/cad/cap07.txt
ed e' quindi di competenza del capitolo successivo (non duplicato qui).

Copertura completa per comma/lettera (nessun discrimine di rilevanza): l'art. 63 e i singoli commi
abrogati dell'art. 64 (1, 2, 2-septies, 2-octies, 3) sono censiti come Principio con stato "abrogato"
anziche' omessi. Quando un comma elenca, tramite lettere a)...n), sfaccettature omogenee di un'unica
prescrizione continua (es. art. 62 c.6, art. 62-ter c.7, art. 62-quater c.6, art. 62-quinquies c.5,
art. 62-sexies c.4, art. 64 c.2-sexies), l'intero comma e' modellato come un solo nodo (un solo item
di indice), con `testo_integrale` che riporta l'intero comma comprese tutte le lettere.

`testo_integrale` e' copiato verbatim dal testo ufficiale, incluse le marcature '((' '))' con cui il
testo vigente segnala le porzioni inserite/modificate da decreti successivi (per gli artt. 62-quater
e 62-quinquies, interamente inseriti da un unico intervento normativo, il marcatore di apertura '((' e
di chiusura '))' e' riportato rispettivamente nel primo comma e nell'ultimo comma dell'articolo) e le
annotazioni tipo "COMMA ABROGATO DAL D.LGS. ..." presenti nel file sorgente, comprese le sigle
numeriche tra parentesi (es. "(28)", "(38)") che nel testo ufficiale rimandano ai blocchi
AGGIORNAMENTO a fine articolo.
"""

RIGHE_OBBLIGHI: list[dict] = [
    {
        'riferimento': 'art. 62 c.1',
        'testo': "E' istituita presso il Ministero dell'interno l'ANPR, base di dati di interesse nazionale che subentra all'INA e all'AIRE; l'ANPR è sottoposta a un audit di sicurezza annuale secondo le regole tecniche di cui all'art. 51, i cui risultati confluiscono nella relazione annuale del Garante privacy.",
        'testo_integrale': 'E\' istituita presso il Ministero dell\'interno l\'ANPR, quale base di dati di interesse nazionale, ai sensi dell\'articolo 60, che subentra all\'Indice nazionale delle anagrafi (INA), istituito ai sensi del quinto comma dell\'articolo 1 della legge 24 dicembre 1954, n. 1228, recante "Ordinamento delle anagrafi della popolazione residente" e all\'Anagrafe della popolazione italiana residente all\'estero (AIRE), istituita ai sensi della legge 27 ottobre 1988, n. 470, recante "Anagrafe e censimento degli italiani all\'estero" Tale base di dati e\' sottoposta ad un audit di sicurezza con cadenza annuale in conformita\' alle regole tecniche di cui all\'articolo 51. I risultati dell\'audit sono inseriti nella relazione annuale del Garante per la protezione dei dati personali.',
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.2',
        'testo': "Ferme le attribuzioni del sindaco quale ufficiale di governo, l'ANPR subentra alle anagrafi comunali della popolazione residente e dei cittadini italiani residenti all'estero; il piano di graduale subentro va completato entro il 31 dicembre 2014, e fino ad allora l'ANPR acquisisce automaticamente in via telematica i dati dei comuni non ancora subentrati.",
        'testo_integrale': "Ferme restando le attribuzioni del sindaco di cui all'articolo 54, comma 3, del testo unico delle leggi sull'ordinamento degli enti locali, approvato con il decreto legislativo 18 agosto 2000, n. 267, l'ANPR subentra altresi' alle anagrafi della popolazione residente e dei cittadini italiani residenti all'estero tenute dai comuni. Con il decreto di cui al comma 6 e' definito un piano per il graduale subentro dell'ANPR alle citate anagrafi, da completare entro il 31 dicembre 2014. Fino alla completa attuazione di detto piano, l'ANPR acquisisce automaticamente in via telematica i dati contenuti nelle anagrafi tenute dai comuni per i quali non e' ancora avvenuto il subentro. L'ANPR e' organizzata secondo modalita' funzionali e operative che garantiscono la univocita' dei dati stessi.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'condizione_applicabilita': 'piano di subentro da completare entro il 31 dicembre 2014',
    },
    {
        'riferimento': 'art. 62 c.2-bis',
        'testo': "L'ANPR contiene anche l'archivio nazionale informatizzato dei registri di stato civile comunali, garantendo ai comuni i servizi per il suo utilizzo, e fornisce i dati per le liste di leva militare, secondo le modalità definite con decreti di cui al comma 6-bis.",
        'testo_integrale': "L'ANPR contiene altresi' l'archivio nazionale informatizzato dei registri di stato civile tenuti dai comuni garantendo agli stessi, anche progressivamente, i servizi necessari all'utilizzo del medesimo e fornisce i dati ai fini della tenuta delle liste di cui all'articolo 1931 del codice dell'ordinamento militare di cui al decreto legislativo 15 marzo 2010, n. 66, secondo le modalita' definite con uno o piu' decreti di cui al comma 6-bis. Le modalita' e i tempi di adesione da parte dei comuni all'archivio nazionale informatizzato, con conseguente dismissione della versione analogica dei registri di stato civile, sono definiti con uno o piu' decreti di cui al comma 6-bis. (38)",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.2-ter',
        'testo': "Con uno o più decreti di cui al comma 6-bis sono definite le modalità di integrazione nell'ANPR delle liste elettorali e dei dati di iscrizione nelle liste di sezione.",
        'testo_integrale': "Con uno o piu' decreti di cui al comma 6-bis sono definite le modalita' di integrazione nell'ANPR delle liste elettorali e dei dati relativi all'iscrizione nelle liste di sezione di cui al decreto del Presidente della Repubblica 20 marzo 1967, n. 223. (38)",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.2-quater',
        'testo': "I dati su strade urbane e numeri civici contenuti nell'ANPR devono restare costantemente allineati con quelli dell'Archivio nazionale dei numeri civici delle strade urbane (ANNCSU).",
        'testo_integrale': "I dati relativi alle strade urbane e ai numeri civici contenuti nell'ANPR sono costantemente allineati con i medesimi dati resi disponibili dall'Archivio nazionale dei numeri civici delle strade urbane (ANNCSU), di cui all'articolo 3 del decreto-legge 18 ottobre 2012, n. 179, convertito, con modificazioni, dalla legge 17 dicembre 2012, n. 221.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.3',
        'testo': "L'ANPR assicura ai comuni dati, atti e strumenti per le funzioni statali del sindaco e mette a disposizione un sistema di interscambio dati/servizi/transazioni per le funzioni comunali; consente ai comuni la certificazione anagrafica anche telematica (con sigillo elettronico qualificato, esente da bollo per il 2021-2022) e attribuisce a ciascun cittadino un codice identificativo univoco per l'interoperabilità tra banche dati pubbliche.",
        'testo_integrale': "L'ANPR assicura ai comuni la disponibilita' dei dati, degli atti e degli strumenti per lo svolgimento delle funzioni di competenza statale attribuite al sindaco ai sensi dell'articolo 54, comma 3, del testo unico delle leggi sull'ordinamento degli enti locali di cui al decreto legislativo 18 agosto 2000, n. 267, e mette a disposizione dei comuni un sistema di controllo, gestione e interscambio, puntuale e massivo, di dati, servizi e transazioni necessario ai sistemi locali per lo svolgimento delle funzioni istituzionali di competenza comunale. Al fine dello svolgimento delle proprie funzioni, anche ampliando l'offerta dei servizi erogati on-line a cittadini e imprese, direttamente o tramite soggetti affidatari dei servizi, il Comune puo' utilizzare i dati anagrafici eventualmente detenuti localmente e costantemente allineati con ANPR al fine esclusivo di erogare o usufruire di servizi o funzionalita' non fornite da ANPR. I Comuni accedono alle informazioni anagrafiche contenute nell'ANPR, nel rispetto delle disposizioni in materia di protezione dei dati personali e delle misure di sicurezza definite con decreto del Presidente del Consiglio dei ministri ai sensi del comma 6, lettera a), per l'espletamento, anche con modalita' automatiche, delle verifiche necessarie all'erogazione dei propri servizi e allo svolgimento delle proprie funzioni. L'ANPR consente ai comuni la certificazione dei dati anagrafici nel rispetto di quanto previsto dall'articolo 33 del decreto del Presidente della Repubblica 30 maggio 1989, n. 223, anche in modalita' telematica. La certificazione dei dati anagrafici in modalita' telematica e' assicurata dal Ministero dell'Interno tramite l'ANPR mediante l'emissione di documenti digitali muniti di sigillo elettronico qualificato, ai sensi del Regolamento (UE) n. 910/2014 del Parlamento europeo e del Consiglio, del 23 luglio 2014, esenti da imposta di bollo limitatamente agli anni 2021 e 2022. I comuni inoltre possono consentire, mediante la piattaforma di cui all'articolo 50-ter ovvero anche mediante apposite convenzioni, la fruizione dei dati anagrafici da parte dei soggetti aventi diritto. L'ANPR assicura ai soggetti di cui all'articolo 2, comma 2, lettere a) e b), l'accesso ai dati contenuti nell'ANPR. L'ANPR attribuisce a ciascun cittadino un codice identificativo univoco per garantire la circolarita' dei dati anagrafici e l'interoperabilita' con le altre banche dati delle pubbliche amministrazioni e dei gestori di servizi pubblici di cui all'articolo 2, comma 2, lettere a) e b). Il codice identificativo univoco di cui all' ottavo periodo consente l'interoperabilita' tra banche dati delle pubbliche amministrazioni e dei gestori di servizi pubblici.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.3-bis',
        'testo': "Le PA e i gestori di servizi pubblici accedono automaticamente ai dati ANPR, per le finalità istituzionali dichiarate, tramite la piattaforma digitale nazionale dati, quali titolari autonomi del trattamento, rispondendo in via esclusiva di pertinenza, liceità e sicurezza degli accessi; l'amministrazione titolare dell'ANPR non risponde di trattamenti difformi da parte di tali soggetti, ferma la vigilanza AgID.",
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, lettere a) e b), accedono automaticamente ai dati contenuti nell'ANPR, per le finalita' istituzionali dichiarate, tramite la piattaforma di cui all'articolo 50-ter, in qualita' di titolari autonomi del trattamento e rispondono in via esclusiva della pertinenza, liceita' e sicurezza dei trattamenti per i quali e' effettuato l'accesso.\nL'amministrazione titolare ((dell'ANPR)) non e' responsabile per il trattamento dei dati effettuati dai medesimi soggetti in difformita' dalle finalita' dichiarate, ((ferma restando)) la vigilanza sugli accessi effettuata secondo le linee guida adottate ((dall'AgID)).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.4',
        'testo': "Il decreto di cui al comma 6 disciplina le modalità di integrazione nell'ANPR dei dati dei cittadini registrati in altre anagrafi e dei dati su numero/data emissione/scadenza della carta d'identità.",
        'testo_integrale': "Con il decreto di cui al comma 6 sono disciplinate le modalita' di integrazione nell'ANPR dei dati dei cittadini attualmente registrati in anagrafi istituite presso altre amministrazioni nonche' dei dati relativi al numero e alla data di emissione e di scadenza della carta di identita' della popolazione residente.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.5',
        'testo': "Le PA e i gestori di servizi pubblici, per la gestione e raccolta informatizzata di dati dei cittadini, si avvalgono esclusivamente dell'ANPR oppure garantiscono un costante allineamento dei propri archivi (integrati con il codice identificativo univoco) con le anagrafiche ANPR.",
        'testo_integrale': "Ai fini della gestione e della raccolta informatizzata di dati dei cittadini, i soggetti di cui all'articolo 2, comma 2, lettere a) e b), si avvalgono esclusivamente dell'ANPR, che viene integrata con gli ulteriori dati a tal fine necessari, o garantiscono un costante allineamento dei propri archivi informatizzati, integrati con il codice identificativo univoco di cui al comma 3, con le anagrafiche contenute nell'ANPR.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.6',
        'testo': "Con uno o più DPCM sono stabiliti tempi e modalità di attuazione dell'articolo, con riferimento a: a) garanzie/misure di sicurezza, tempi di conservazione e accesso ai dati da parte delle PA; b) criteri di interoperabilità dell'ANPR con altre banche dati nazionali/regionali; c) erogazione di altri servizi ANPR (es. invio telematico di attestazioni/dichiarazioni di nascita e morte).",
        'testo_integrale': "Con uno o piu' decreti del Presidente del Consiglio dei Ministri, su proposta del Ministro dell'interno, del Ministro per la pubblica amministrazione e la semplificazione e del Ministro delegato all'innovazione tecnologica, di concerto con il Ministro dell'economia e delle finanze, d'intesa con l'Agenzia per l'Italia digitale, la Conferenza permanente per i rapporti tra lo Stato, le regioni e le province autonome di Trento e di Bolzano nonche' con la Conferenza Stato - citta', di cui all'articolo 8 del decreto legislativo 28 agosto 1997, n. 281, per gli aspetti d'interesse dei comuni, sentita l'ISTAT e acquisito il parere del Garante per la protezione dei dati personali, sono stabiliti i tempi e le modalita' di attuazione delle disposizioni del presente articolo, anche con riferimento:\na) alle garanzie e alle misure di sicurezza da adottare nel trattamento dei dati personali, alle modalita' e ai tempi di conservazione dei dati e all'accesso ai dati da parte delle pubbliche amministrazioni per le proprie finalita' istituzionali secondo le modalita' di cui all'articolo (50);\nb) ai criteri per l'interoperabilita' dell'ANPR con le altre banche dati di rilevanza nazionale e regionale, secondo le regole tecniche del sistema pubblico di connettivita' di cui al capo VIII del presente Codice, in modo che le informazioni di anagrafe, una volta rese dai cittadini, si intendano acquisite dalle pubbliche amministrazioni senza necessita' di ulteriori adempimenti o duplicazioni da parte degli stessi;\nc) all'erogazione di altri servizi resi disponibili dall'ANPR, tra i quali il servizio di invio telematico delle attestazioni e delle dichiarazioni di nascita ai sensi dell'articolo 30, comma 4, del decreto del Presidente della Repubblica 3 novembre 2000, n. 396, e della dichiarazione di morte ai sensi degli articoli 72 e 74 dello stesso decreto nonche' della denuncia di morte prevista dall'articolo 1 del regolamento di polizia mortuaria di cui al decreto del Presidente della Repubblica 10 settembre 1990, n. 285, compatibile con il sistema di trasmissione di cui al decreto del Ministro della salute in data 26 febbraio 2010, pubblicato nella Gazzetta Ufficiale n. 65 del 19 marzo 2010.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62 c.6-bis',
        'testo': "Con decreti del Ministro dell'interno è assicurato l'aggiornamento dei servizi ANPR verso PA, enti erogatori di servizi pubblici e privati, oltre all'adeguamento/evoluzione tecnica della piattaforma ANPR.",
        'testo_integrale': "Con uno o piu' decreti del Ministro dell'interno, adottati di concerto con il Ministro per l'innovazione tecnologica e la transizione digitale e il Ministro per la pubblica amministrazione, sentiti il Garante per la protezione dei dati personali e la Conferenza Stato-citta' ed autonomie locali, sono assicurati l'aggiornamento dei servizi resi disponibili dall'ANPR alle pubbliche amministrazioni, agli organismi che erogano pubblici servizi e ai privati, nonche' l'adeguamento e l'evoluzione delle caratteristiche tecniche della piattaforma di funzionamento dell'ANPR. (38)",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-ter c.1',
        'testo': "Per rafforzare il monitoraggio della spesa sanitaria e l'automazione amministrativa, è istituita, nell'ambito del sistema informativo del MEF, l'Anagrafe nazionale degli assistiti (ANA).",
        'testo_integrale': "Per rafforzare gli interventi in tema di monitoraggio della spesa del settore sanitario, accelerare il processo di automazione amministrativa e migliorare i servizi per i cittadini e le pubbliche amministrazioni, e' istituita, nell'ambito del sistema informativo realizzato dal Ministero dell'economia e delle finanze in attuazione di quanto disposto dall'articolo 50 del decreto-legge 30 settembre 2003, n. 269, convertito, con modificazioni, dalla legge 24 novembre 2003, n. 326, l'Anagrafe nazionale degli assistiti (ANA).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-ter c.2',
        'testo': "L'ANA, realizzata dal MEF d'intesa col Ministero della salute per il monitoraggio LEA, nel rispetto dell'art. 62 c.5, subentra alle anagrafi/elenchi degli assistiti delle ASL, che mantengono la titolarità dei dati di propria competenza e ne assicurano l'aggiornamento.",
        'testo_integrale': "L'ANA, realizzata dal Ministero dell'economia e delle finanze, in accordo con il Ministero della salute in relazione alle specifiche esigenze di monitoraggio dei livelli essenziali di assistenza (LEA), nel rispetto delle previsioni di cui al comma 5 dell'articolo 62 del presente Codice, subentra, per tutte le finalita' previste dalla normativa vigente, alle anagrafi e agli elenchi degli assistiti tenuti dalle singole aziende sanitarie locali, ai sensi dell'articolo 7 della legge 7 agosto 1982, n. 526, che mantengono la titolarita' dei dati di propria competenza e ne assicurano l'aggiornamento.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-ter c.3',
        'testo': "L'ANA assicura alla singola ASL la disponibilità di dati e strumenti di propria competenza e garantisce l'accesso ai dati da parte delle PA per finalità istituzionali, secondo le modalità dell'art. 60 c.2-bis.",
        'testo_integrale': "L'ANA assicura alla singola azienda sanitaria locale la disponibilita' dei dati e degli strumenti per lo svolgimento delle funzioni di propria competenza e garantisce l'accesso ai dati in essa contenuti da parte delle pubbliche amministrazioni per le relative finalita' istituzionali, secondo le modalita' di cui ((all'articolo 60, comma 2-bis,)) del presente Codice.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-ter c.4',
        'testo': "Con il subentro dell'ANA, l'ASL cessa di fornire ai cittadini il libretto sanitario personale cartaceo; resta facoltà del cittadino accedere in rete ai propri dati ANA o richiederne copia cartacea in ASL.",
        'testo_integrale': "Con il subentro dell'ANA, l'azienda sanitaria locale cessa di fornire ai cittadini il libretto sanitario personale previsto dall'articolo 27 della legge 23 dicembre 1978, n. 833. E' facolta' dei cittadini di accedere in rete ai propri dati contenuti nell'ANA, secondo le modalita' di cui al comma 1 dell'articolo 6 del presente Codice, ovvero di richiedere presso l'azienda sanitaria locale competente copia cartacea degli stessi.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-ter c.5',
        'testo': "In caso di trasferimento di residenza del cittadino, l'ANA ne dà immediata comunicazione telematica alle ASL interessate; l'ASL della nuova residenza prende in carico il cittadino e aggiorna l'ANA per i dati di competenza, senza che il cittadino debba comunicare nulla alle ASL.",
        'testo_integrale': "In caso di trasferimento di residenza del cittadino, l'ANA ne da' immediata comunicazione in modalita' telematica alle aziende sanitarie locali interessate dal trasferimento. L'azienda sanitaria locale nel cui territorio e' compresa la nuova residenza provvede alla presa in carico del cittadino, nonche' all'aggiornamento dell'ANA per i dati di propria competenza. Nessun'altra comunicazione in merito al trasferimento di residenza e' dovuta dal cittadino alle aziende sanitarie locali interessate. (28)",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-ter c.6',
        'testo': "L'ANA assicura al nuovo sistema informativo sanitario nazionale del Ministero della salute l'accesso ai dati e agli strumenti per garantire appropriatezza/efficacia delle cure e per le finalità dell'art. 15 c.25-bis del d.l. 95/2012.",
        'testo_integrale': "L'ANA assicura al nuovo sistema informativo sanitario nazionale realizzato dal Ministero della salute in attuazione di quanto disposto dall'articolo 87 della legge 23 dicembre 2000, n. 388, con le modalita' definite dal decreto del Presidente del Consiglio dei ministri di cui al comma 7, l'accesso ai dati e la disponibilita' degli strumenti funzionali a garantire l'appropriatezza e l'efficacia delle prestazioni di cura erogate al cittadino, nonche' per le finalita' di cui all'articolo 15, comma 25-bis, del decreto-legge 6 luglio 2012, n. 95, convertito, con modificazioni, dalla legge 7 agosto 2012, n. 135. (28)",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-ter c.7',
        'testo': "Entro il 30/6/2014, con DPCM sono stabiliti: a) i contenuti dell'ANA (incl. medico di base/pediatra, codice esenzione, domicilio); b) il piano di subentro alle anagrafi ASL, da completare entro il 30/6/2015; c) garanzie/misure di sicurezza e criteri di interoperabilità con altre banche dati, nel rispetto della normativa privacy.",
        'testo_integrale': "Entro il 30 giugno 2014, con decreto del Presidente del Consiglio dei ministri, su proposta del Ministro della salute e del Ministro dell'economia e delle finanze, previa intesa in sede di Conferenza permanente per i rapporti tra lo Stato, le regioni e le province autonome di Trento e di Bolzano, sono stabiliti:\na) i contenuti dell'ANA, tra i quali devono essere inclusi ((le scelte del medico di medicina generale e del pediatra di libera scelta)), il codice esenzione e il domicilio;\nb) il piano per il graduale subentro dell'ANA alle anagrafi e agli elenchi degli assistiti tenuti dalle singole aziende sanitarie locali, da completare entro il 30 giugno 2015;\nc) le garanzie e le misure di sicurezza da adottare, i criteri per l'interoperabilita' dell'ANA con le altre banche dati di rilevanza nazionale e regionale, nonche' le modalita' di cooperazione dell'ANA con banche dati gia' istituite a livello regionale per le medesime finalita', nel rispetto della normativa sulla protezione dei dati personali, di cui al decreto legislativo 30 giugno 2003, n. 196, e delle regole tecniche del sistema pubblico di connettivita', ai sensi del presente Codice.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'condizione_applicabilita': 'decreto da adottare entro il 30 giugno 2014; piano di subentro ANA da completare entro il 30 giugno 2015',
    },
    {
        'riferimento': 'art. 62-quater c.1',
        'testo': "Per rafforzare gli interventi nel settore dell'istruzione e l'automazione amministrativa, è istituita, nell'ambito del sistema informativo hubscuola del Ministero dell'istruzione, l'Anagrafe nazionale dell'istruzione (ANIST).",
        'testo_integrale': "((Per rafforzare gli interventi nel settore dell'istruzione, accelerare il processo di automazione amministrativa e migliorare i servizi per i cittadini e per le pubbliche amministrazioni, e' istituita, nell'ambito di un apposito sistema informativo denominato hubscuola, realizzato dal Ministero dell'istruzione, l'Anagrafe nazionale dell'istruzione (ANIST).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quater c.2',
        'testo': "L'ANIST, realizzata dal Ministero dell'istruzione, subentra alle anagrafi/banche dati di studenti, docenti, personale ATA, istituzioni ed edifici scolastici (anche regionali/provinciali/locali), che ne mantengono la titolarità per la propria competenza e ne assicurano l'aggiornamento.",
        'testo_integrale': "L'ANIST, realizzata dal Ministero dell'istruzione, subentra, per tutte le finalita' previste dalla normativa vigente, alle anagrafi e alle banche di dati degli studenti, dei docenti, del personale amministrativo, tecnico e ausiliario (ATA), delle istituzioni scolastiche e degli edifici scolastici, anche istituite a livello regionale, provinciale e locale per le medesime finalita', che mantengono la titolarita' dei dati di propria competenza e ne assicurano l'aggiornamento.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quater c.3',
        'testo': "L'ANIST assicura a regioni, comuni e istituzioni scolastiche la disponibilità di dati/strumenti di competenza, garantisce l'accesso PA per finalità istituzionali, e mette a disposizione del Ministero dell'interno le informazioni sui titoli di studio per l'inserimento in ANPR.",
        'testo_integrale': "L'ANIST assicura alle regioni, ai comuni e alle istituzioni scolastiche la disponibilita' dei dati e degli strumenti per lo svolgimento delle funzioni di propria competenza, garantisce l'accesso ai dati in essa contenuti da parte delle pubbliche amministrazioni per le relative finalita' istituzionali e mette a disposizione del Ministero dell'interno le informazioni relative ai titoli di studio per il loro inserimento nell'ANPR.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quater c.4',
        'testo': "Anche ai fini dell'art. 62 c.5, l'ANIST è costantemente allineata con l'ANPR per i dati di studenti/famiglie/docenti/ATA; è alimentata con i dati di rendimento scolastico tramite interoperabilità coi registri scolastici e allineata con l'ANNCSU per i numeri civici.",
        'testo_integrale': "Anche ai fini del comma 5 dell'articolo 62, l'ANIST e' costantemente allineata con l'ANPR per quanto riguarda i dati degli studenti e delle loro famiglie, dei docenti e del personale ATA.\nL'ANIST e' costantemente alimentata con i dati relativi al rendimento scolastico degli studenti attraverso l'interoperabilita' con i registri scolastici di cui all'articolo 7, comma 31, del decreto-legge 6 luglio 2012, n. 95, convertito, con modificazioni, dalla legge 7 agosto 2012, n. 135. L'ANIST, con riferimento alla codifica e al georiferimento dei numeri civici in essa contenuti, e' costantemente aggiornata attraverso l'allineamento con le risultanze dell'Archivio nazionale dei numeri civici delle strade urbane, di cui all'articolo 3 del decreto-legge 18 ottobre 2012, n. 179, convertito, con modificazioni, dalla legge 17 dicembre 2012, n. 221.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quater c.5',
        'testo': "I cittadini possono accedere all'ANIST per consultare i propri dati e ottenere certificazioni, con le modalità dell'art. 64 c.2-quater o tramite il punto di accesso dell'art. 64-bis; l'ANIST rende disponibili i dati per automatizzare le iscrizioni online alle scuole di ogni ordine e grado.",
        'testo_integrale': "I cittadini, per consultare i propri dati e ottenere il rilascio di certificazioni, possono accedere all'ANIST con le modalita' di cui al comma 2-quater dell'articolo 64 ovvero tramite il punto di accesso di cui all'articolo 64-bis. L'ANIST rende disponibili i dati necessari per automatizzare le procedure di iscrizione on line alle istituzioni scolastiche di ogni ordine e grado, di cui all'articolo 7, comma 28, del decreto-legge 6 luglio 2012, n. 95, convertito, con modificazioni, dalla legge 7 agosto 2012, n. 135.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quater c.6',
        'testo': "Con decreto del Ministro dell'istruzione (entro il 30/9/2021) sono stabiliti: a) i dati contenuti nell'ANIST (studenti, docenti/ATA, istituzioni/edifici); b) garanzie/misure di sicurezza e modalità di cooperazione/alimentazione tramite i registri scolastici, nel rispetto della privacy; l'allineamento con altre banche dati avviene secondo le linee guida AgID sull'interoperabilità.",
        'testo_integrale': "Con decreto del Ministro dell'istruzione, di concerto con il Ministro per l'innovazione tecnologica e la transizione digitale e con il Ministro per la pubblica amministrazione, da adottare entro il 30 settembre 2021, previa intesa in sede di Conferenza unificata di cui all'articolo 8 del decreto legislativo 28 agosto 1997, n. 281, acquisito il parere del Garante per la protezione dei dati personali, sono stabiliti:\na) i dati che devono essere contenuti nell'ANIST, con riferimento alle tre componenti degli studenti, dei docenti e personale ATA e delle istituzioni scolastiche ed edifici scolastici;\nb) le garanzie e le misure di sicurezza da adottare, le modalita' di cooperazione dell'ANIST con banche di dati istituite a livello regionale, provinciale e locale per le medesime finalita', nonche' le modalita' di alimentazione da parte dei registri scolastici di cui all'articolo 7, comma 31, del decreto-legge 6 luglio 2012, n. 95, convertito, con modificazioni, dalla legge 7 agosto 2012, n. 135, nel rispetto della normativa in materia di protezione dei dati personali e delle regole tecniche del sistema pubblico di connettivita'.\nL'allineamento dell'ANIST con le altre banche di dati di rilevanza nazionale, regionale, provinciale e locale avviene in conformita' alle linee guida adottate dall'AgID in materia di interoperabilita'))",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'condizione_applicabilita': 'decreto da adottare entro il 30 settembre 2021',
    },
    {
        'riferimento': 'art. 62-quinquies c.1',
        'testo': "Per rafforzare gli interventi nel settore universitario/ricerca e l'automazione amministrativa, è istituita, a cura del Ministero dell'università e della ricerca, l'Anagrafe nazionale dell'istruzione superiore (ANIS).",
        'testo_integrale': "((Per rafforzare gli interventi nel settore dell'universita' e della ricerca, accelerare il processo di automazione amministrativa e migliorare i servizi per i cittadini e le pubbliche amministrazioni, e' istituita, a cura del Ministero dell'universita' e della ricerca, l'Anagrafe nazionale dell'istruzione superiore (ANIS).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quinquies c.2',
        'testo': "L'ANIS è alimentata dalle istituzioni della formazione superiore (che mantengono la titolarità dei dati e ne assicurano l'aggiornamento) e dall'Anagrafe nazionale di studenti/diplomati/laureati ITS; assicura a ciascuna istituzione disponibilità di dati/strumenti, garantisce l'accesso PA, rende disponibili dati per le iscrizioni online e assicura l'interoperabilità con altre banche dati MUR.",
        'testo_integrale': "L'ANIS e' alimentata, con le modalita' individuate con il decreto di cui al comma 5, dalle istituzioni della formazione superiore, che mantengono la titolarita' dei dati di propria competenza e ne assicurano l'aggiornamento, nonche' tramite l'Anagrafe nazionale degli studenti, dei diplomati e dei laureati degli istituti tecnici superiori e delle istituzioni della formazione superiore, di cui all'articolo 1-bis del decreto-legge 9 maggio 2003, n. 105, convertito, con modificazioni, dalla legge 11 luglio 2003, n. 170. L'ANIS assicura alla singola istituzione la disponibilita' dei dati e degli strumenti per lo svolgimento delle funzioni di propria competenza e garantisce l'accesso ai dati in essa contenuti da parte delle pubbliche amministrazioni per le relative finalita' istituzionali. L'ANIS rende disponibili i dati necessari per automatizzare le procedure di iscrizione on line alle istituzioni della formazione superiore e assicura l'interoperabilita' con le altre banche di dati di rilevanza nazionale che sono di interesse del Ministero dell'universita' e della ricerca per le relative finalita' istituzionali.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quinquies c.3',
        'testo': "Ai sensi dell'art. 62 c.5, l'ANIS è costantemente allineata con l'ANPR per i dati di studenti e laureati.",
        'testo_integrale': "Ai sensi del comma 5 dell'articolo 62 del presente codice, l'ANIS e' costantemente allineata con l'ANPR per quanto riguarda i dati degli studenti e dei laureati.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quinquies c.4',
        'testo': "I cittadini possono accedere all'ANIS per consultare i propri dati e ottenere certificazioni, tramite le modalità dell'art. 64 c.2-quater o il punto di accesso dell'art. 64-bis.",
        'testo_integrale': "I cittadini, per consultare i propri dati e ottenere il rilascio di certificazioni, possono accedere all'ANIS mediante le modalita' di cui al comma 2-quater dell'articolo 64 ovvero tramite il punto di accesso di cui all'articolo 64-bis.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-quinquies c.5',
        'testo': "Con decreto del Ministro dell'università e della ricerca (entro il 31/12/2021) sono stabiliti: a) i contenuti dell'ANIS (iscrizioni, istituzione, corso, titoli, altri dati MUR); b) garanzie/misure di sicurezza e modalità di alimentazione dalle istituzioni/dall'Anagrafe ITS, nel rispetto della privacy; l'allineamento con le altre anagrafi avviene secondo le linee guida AgID sull'interoperabilità.",
        'testo_integrale': "Con decreto del Ministro dell'universita' e della ricerca, di concerto con il Ministro per l'innovazione tecnologica e la transizione digitale e con il Ministro per la pubblica amministrazione, da adottare entro il 31 dicembre 2021, acquisito il parere del Garante per la protezione dei dati personali, sono stabiliti:\na) i contenuti dell'ANIS, tra i quali i dati relativi alle iscrizioni degli studenti, all'istituzione di appartenenza e al relativo corso di studi, i titoli conseguiti e gli ulteriori dati relativi presenti nelle altre banche di dati di rilevanza nazionale di interesse del Ministero dell'universita' e della ricerca cui lo stesso puo' accedere per le relative finalita' istituzionali;\nb) le garanzie e le misure di sicurezza da adottare nonche' le modalita' di alimentazione da parte delle istituzioni della formazione superiore nonche' tramite l'Anagrafe nazionale degli studenti, dei diplomati e dei laureati degli istituti tecnici superiori e delle istituzioni della formazione superiore, nel rispetto della normativa in materia di protezione dei dati personali e delle regole tecniche del sistema pubblico di connettivita'.\nL'allineamento dell'ANIS con l'Anagrafe nazionale degli studenti, dei diplomati e dei laureati degli istituti tecnici superiori e delle istituzioni della formazione superiore, con l'ANPR e con le altre anagrafi di interesse del Ministero dell'universita' e della ricerca per le relative finalita' istituzionali avviene in conformita' alle linee guida adottate dall'AgID in materia di interoperabilita'))",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'condizione_applicabilita': 'decreto da adottare entro il 31 dicembre 2021',
    },
    {
        'riferimento': 'art. 62-sexies c.1',
        'testo': "È istituita presso il Ministero delle infrastrutture e dei trasporti l'Anagrafe nazionale digitale della gente di mare (ANGEMAR), per la gestione unitaria/digitale/interoperabile dei dati su carriera, titoli, imbarchi, abilitazioni/certificazioni; al raggiungimento della piena operatività sostituisce le anagrafi/registri/archivi vigenti, incluso il codice della navigazione e i relativi regolamenti attuativi.",
        'testo_integrale': "E' istituita, presso il Ministero delle infrastrutture e dei trasporti, l'Anagrafe nazionale digitale della gente di mare (ANGEMAR), finalizzata alla gestione unitaria, digitale e interoperabile dei dati relativi alla carriera professionale, ai titoli, agli imbarchi e alle abilitazioni e certificazioni della gente di mare, anche ai fini del collocamento e del monitoraggio del mercato del lavoro marittimo. L'ANGEMAR, al raggiungimento della piena operativita', sostituisce le anagrafi, ((i registri e gli archivi)) previsti a legislazione vigente, ivi ((compresi quelli previsti dal)) codice della navigazione, di cui al regio decreto 30 marzo 1942, n. 327, ((dal regolamento di cui al decreto)) del Presidente della Repubblica 15 febbraio 1952, n. 328, e ((dal regolamento di cui al decreto)) del Presidente della Repubblica 18 aprile 2006, n. 231.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-sexies c.2',
        'testo': "L'ANGEMAR è integrata con la piattaforma digitale nazionale dati e consente alimentazione/aggiornamento/consultazione da parte di uffici d'iscrizione, personale gente di mare, armatori, centri di formazione autorizzati e soggetti internazionali convenzionati; è costantemente aggiornata per la coerenza con ANPR (art. 62), ANIST (art. 62-quater), ANIS (art. 62-quinquies), SASN e altre anagrafi/basi dati.",
        'testo_integrale': "L'ANGEMAR e' integrata con i servizi della piattaforma digitale nazionale dati di cui all'articolo 50-ter e consente l'alimentazione, l'aggiornamento e la consultazione dei dati da parte degli ((uffici)) d'iscrizione della gente di mare, del personale appartenente alla gente di mare, degli armatori e dei centri di formazione autorizzati nonche' dei soggetti internazionali convenzionati per le parti di rispettiva competenza. L'ANGEMAR, per il tramite dei servizi resi disponibili dalla piattaforma di cui all'articolo 50-ter, e' costantemente aggiornata al fine di assicurare la coerenza dei dati ivi contenuti con l'anagrafe di cui all'articolo 62 (ANPR), con le anagrafi di cui all'articolo 62-quater (ANIST) e all'articolo 62-quinquies (ANIS), con i servizi di assistenza sanitaria al personale navigante (SASN) nonche', per le informazioni di competenza, con le anagrafi e le ((basi di dati)) detenute da altre amministrazioni.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-sexies c.3',
        'testo': "Entro 180 giorni dalla piena operatività dell'ANGEMAR, il libretto di navigazione è rilasciato sulla base delle informazioni ANGEMAR ed è reso disponibile anche tramite l'IT-Wallet; il libretto, con microprocessore, è carta valore la cui produzione/fornitura è affidata dal Ministero infrastrutture alla società ex L. 559/1966.",
        'testo_integrale': "Entro centottanta giorni dalla piena operativita' dell'ANGEMAR, il libretto di navigazione di cui all'articolo 122 del codice della navigazione ((,)) di cui al regio decreto n. 327 del 1942, e' rilasciato sulla base delle informazioni contenute nell'ANGEMAR ed e' reso disponibile anche tramite il Sistema di portafoglio digitale italiano - Sistema IT-Wallet, ai sensi dell'articolo 64-quater. Il libretto di navigazione, dotato di microprocessore per la memorizzazione delle informazioni necessarie alla verifica dell'identita' del titolare e di quelle definite dai decreti di cui al comma 4, e' carta valore ai sensi dell'articolo 2, comma 10-bis, della legge 13 luglio 1966, n. 559, e la sua produzione e fornitura sono affidate dal Ministero delle infrastrutture e dei trasporti alla societa' di cui all'articolo 1 della medesima legge n. 559 del 1966.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'condizione_applicabilita': 'entro centottanta giorni dalla piena operatività dell’ANGEMAR',
    },
    {
        'riferimento': 'art. 62-sexies c.4',
        'testo': 'Con decreti del Ministro delle infrastrutture e dei trasporti sono definiti: a) i dati ANGEMAR e le modalità di alimentazione/aggiornamento/conservazione con misure di sicurezza informatica conformi al GDPR; b) le caratteristiche del libretto di navigazione e le modalità di verifica/consultazione.',
        'testo_integrale': "Con uno o piu' decreti del Ministro delle infrastrutture e dei trasporti, di concerto con l'Autorita' politica delegata in materia di innovazione tecnologica e transizione digitale, ove nominata, sono definiti:\na) i dati contenuti nell'ANGEMAR, nonche' le modalita' di alimentazione, aggiornamento e conservazione degli stessi, con particolare riguardo alle misure di sicurezza informatica e alle specifiche tecniche e organizzative per la gestione e il trattamento dei dati personali, in conformita' al regolamento (UE) 2016/679 del Parlamento europeo e del Consiglio, del 27 aprile 2016;\nb) le caratteristiche del libretto di navigazione di cui all'articolo 122 del codice della navigazione di cui al regio decreto n. 327 del 1942, rilasciato ai sensi del comma 3, nonche' le modalita' di verifica e consultazione dello stesso.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 62-sexies c.5',
        'testo': "In attesa della piena operatività, l'ANGEMAR mette a disposizione un servizio informatico provvisorio per l'inserimento dei dati essenziali da parte del personale marittimo e dei centri di formazione, secondo decreto direttoriale del Ministero infrastrutture; tali dati confluiscono poi nell'ANGEMAR e sono validati secondo i decreti di cui al comma 4.",
        'testo_integrale': "Nelle more della piena operativita', ((l'ANGEMAR)) mette a disposizione un servizio informatico provvisorio per l'inserimento ((dei dati e delle informazioni essenziali da parte del personale appartenente alla gente di mare e dei centri di formazione autorizzati)), secondo le modalita' definite con decreto direttoriale del Ministero delle infrastrutture e dei trasporti. I dati e le informazioni di cui al primo periodo confluiscono nell'ANGEMAR e sono oggetto di successiva validazione secondo le modalita' stabilite dai decreti di cui al comma 4.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 64 c.2-bis',
        'testo': "Per favorire la diffusione dei servizi in rete e agevolare l'accesso di cittadini e imprese anche in mobilità, è istituito, a cura dell'AgID, il sistema pubblico per la gestione dell'identità digitale di cittadini e imprese (SPID).",
        'testo_integrale': "Per favorire la diffusione di servizi in rete e agevolare l'accesso agli stessi da parte di cittadini e imprese, anche in mobilita', e' istituito, a cura dell'Agenzia per l'Italia digitale, il sistema pubblico per la gestione dell'identita' digitale di cittadini e imprese (SPID). (28)",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 64 c.2-quater',
        'testo': "L'accesso ai servizi in rete delle PA che richiedono identificazione informatica avviene tramite SPID o carta d'identità elettronica; il sistema SPID è adottato dalle PA nei tempi/modalità del decreto di cui al comma 2-sexies, fermo restando l'art. 3-bis c.01.",
        'testo_integrale': "L'accesso ai servizi in rete erogati dalle pubbliche amministrazioni che richiedono identificazione informatica avviene tramite SPID, nonche' tramite la carta di identita' elettronica. Il sistema SPID e' adottato dalle pubbliche amministrazioni nei tempi e secondo le modalita' definiti con il decreto di cui al comma 2-sexies. Resta fermo quanto previsto dall'articolo 3-bis, comma 01.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 64 c.2-sexies',
        'testo': "Con DPCM sono definite le caratteristiche del sistema SPID: a) modello architetturale/organizzativo; b) modalità/requisiti di accreditamento dei gestori d'identità digitale; c) standard tecnologici per l'interoperabilità delle credenziali; d) modalità di adesione di cittadini/imprese utenti; e) tempi/modalità di adozione da parte delle PA erogatrici; f) modalità di adesione delle imprese erogatrici.",
        'testo_integrale': "Con decreto del Presidente del Consiglio dei ministri, su proposta del Ministro delegato per l'innovazione tecnologica e del Ministro per la pubblica amministrazione e la semplificazione, di concerto con il Ministro dell'economia e delle finanze, sentito il Garante per la protezione dei dati personali, sono definite le caratteristiche del sistema SPID, anche con riferimento:\na) al modello architetturale e organizzativo del sistema;\nb) alle modalita' e ai requisiti necessari per l'accreditamento dei gestori dell'identita' digitale;\nc) agli standard tecnologici e alle soluzioni tecniche e organizzative da adottare anche al fine di garantire l'interoperabilita' delle credenziali e degli strumenti di accesso resi disponibili dai gestori dell'identita' digitale nei riguardi di cittadini e imprese; (28)\nd) alle modalita' di adesione da parte di cittadini e imprese in qualita' di utenti di servizi in rete; (28)\ne) ai tempi e alle modalita' di adozione da parte delle pubbliche amministrazioni in qualita' di erogatori di servizi in rete;\nf) alle modalita' di adesione da parte delle imprese interessate in qualita' di erogatori di servizi in rete.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 64 c.2-decies',
        'testo': 'I gestori di identità digitali e i gestori di attributi qualificati forniscono gratuitamente alle PA, in qualità di fornitori dei servizi, le verifiche da essi rese disponibili.',
        'testo_integrale': "Le pubbliche amministrazioni, in qualita' di fornitori dei servizi, usufruiscono gratuitamente delle verifiche rese disponibili dai gestori di identita' digitali e dai gestori di attributi qualificati.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 64 c.2-undecies',
        'testo': "AgID tiene un elenco pubblico, consultabile anche telematicamente, dei gestori dell'identità digitale accreditati.",
        'testo_integrale': "I gestori dell'identita' digitale accreditati sono iscritti in un apposito elenco pubblico, tenuto da AgID, consultabile anche in via telematica.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 64 c.3-bis',
        'testo': 'Fatto salvo il comma 2-nonies, le PA statali (art. 2 c.2 lett.a) utilizzano esclusivamente SPID e CIE per identificare i cittadini che accedono ai propri servizi in rete; con decreto è stabilita la data da cui le stesse PA useranno esclusivamente SPID/CIE/CNS anche per imprese e professionisti, e la data da cui le PA territoriali e gli altri enti (lett. b e c) useranno esclusivamente SPID/CIE/CNS per gli utenti dei propri servizi online.',
        'testo_integrale': "Fatto salvo quanto previsto dal comma 2-nonies, i soggetti di cui all'articolo 2, comma 2, lettera a), utilizzano esclusivamente le identita' digitali SPID e la carta di identita' elettronica ai fini dell'identificazione dei cittadini che accedono ai propri servizi in rete. Con uno o piu' decreti del Presidente del Consiglio dei ministri o del Ministro delegato per l'innovazione tecnologica e la transizione digitale e' stabilita la data a decorrere dalla quale i soggetti di cui all'articolo 2, comma 2, lettera a), utilizzano esclusivamente le identita' digitali SPID, la carta di identita' elettronica e la Carta Nazionale dei servizi per consentire l'accesso delle imprese e dei professionisti ai propri servizi in rete, nonche' la data a decorrere dalla quale i soggetti di cui all'articolo 2, comma 2, lettere b) e c) utilizzano esclusivamente le identita' digitali SPID, la carta di identita' elettronica e la carta Nazionale dei servizi ai fini dell'identificazione degli utenti dei propri servizi on-line.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 64 c.3-ter',
        'testo': "I gestori dell'identità digitale accreditati, quali gestori di pubblico servizio, prima del rilascio dell'identità digitale a una persona fisica verificano i dati identificativi del richiedente (incl. residenza/domicilio digitale) mediante consultazione gratuita dell'ANPR, anche tramite la piattaforma digitale nazionale dati; ripetono la verifica almeno annualmente, anche per accertare l'esistenza in vita; il direttore AgID fissa la data di decorrenza dell'obbligo.",
        'testo_integrale': "((3-ter. I gestori dell'identita' digitale accreditati, in qualita' di gestori di pubblico servizio, prima del rilascio dell'identita' digitale a una persona fisica, verificano i dati identificativi del richiedente, ivi inclusi l'indirizzo di residenza e, ove disponibili, il domicilio digitale o altro indirizzo di contatto, mediante consultazione gratuita dei dati disponibili presso l'ANPR di cui all'articolo 62, anche tramite la piattaforma prevista dall'articolo 50-ter. Tali verifiche sono svolte anche successivamente al rilascio dell'identita' digitale, con cadenza almeno annuale, anche ai fini della verifica dell'esistenza in vita. Il direttore dell'AgID, previo accertamento dell'operativita' delle funzionalita' necessarie, fissa la data a decorrere dalla quale i gestori dell'identita' digitale accreditati sono tenuti ad effettuare le verifiche di cui ai precedenti periodi))",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'condizione_applicabilita': "obbligo efficace dalla data fissata dal direttore dell'AgID, previo accertamento dell'operatività delle funzionalità necessarie",
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 64-bis c.1',
        'testo': "I soggetti di cui all'art. 2 c.2 rendono fruibili i propri servizi in rete, in conformità alle Linee guida, tramite il punto di accesso telematico attivato presso la Presidenza del Consiglio, senza nuovi o maggiori oneri per la finanza pubblica.",
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, rendono fruibili i propri servizi in rete, in conformita' alle Linee guida, tramite il punto di accesso telematico attivato presso la Presidenza del Consiglio dei ministri, senza nuovi o maggiori oneri per la finanza pubblica.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 64-bis c.1-bis',
        'testo': "Per rendere effettivo il diritto di cui all'art. 7 c.01, i soggetti art.2 c.2, i fornitori di identità digitali e i prestatori di servizi fiduciari qualificati progettano/sviluppano i propri sistemi per garantire integrazione/interoperabilità con i servizi di cui ai commi 1 e 1-ter, espongono le interfacce applicative di ciascun servizio, e adottano gli strumenti di analisi AgID per verificare il rispetto degli standard/livelli di qualità dell'art. 7 c.1.",
        'testo_integrale': "Al fine di rendere effettivo il diritto di cui all'articolo 7, comma 01, i soggetti di cui all'articolo 2, comma 2, i fornitori di identita' digitali e i prestatori dei servizi fiduciari qualificati, in sede di evoluzione, progettano e sviluppano i propri sistemi e servizi in modo da garantire l'integrazione e l'interoperabilita' tra i diversi sistemi e servizi e con i servizi di cui ai commi 1 e 1-ter, espongono per ogni servizio le relative interfacce applicative e, al fine di consentire la verifica del rispetto degli standard e livelli di qualita' di cui all'articolo 7, comma 1, adottano gli strumenti di analisi individuati dall'AgID con le Linee guida.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 64-bis c.1-ter',
        'testo': 'Le PA statali (art. 2 c.2 lett.a) rendono fruibili i propri servizi in rete, nel rispetto della neutralità tecnologica, tramite applicazione mobile anche attraverso il punto di accesso telematico, salvo impedimenti tecnologici attestati dalla società PagoPA ex art. 8 c.2 d.l. 135/2018.',
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, lettera a), rendono fruibili i propri servizi in rete, nel rispetto del principio di neutralita' tecnologica, tramite applicazione su dispositivi mobili anche attraverso il punto di accesso telematico di cui al presente articolo, salvo impedimenti di natura tecnologica attestati dalla societa' di cui all'articolo 8, comma 2 del decreto-legge 14 dicembre 2018, n. 135, convertito, con modificazioni, dalla legge 11 febbraio 2019, n. 12.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 64-bis c.1-quater',
        'testo': 'Le PA statali (art. 2 c.2 lett.a) rendono fruibili tutti i loro servizi anche in modalità digitale, avviando i relativi progetti di trasformazione digitale entro il 28 febbraio 2021.',
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, lettera a), rendono fruibili tutti i loro servizi anche in modalita' digitale e, al fine di attuare il presente articolo, avviano i relativi progetti di trasformazione digitale entro il 28 febbraio 2021.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'condizione_applicabilita': 'progetti di trasformazione digitale da avviare entro il 28 febbraio 2021',
    },
    {
        'riferimento': 'art. 64-bis c.1-quinquies',
        'testo': "La violazione dell'art. 64 c.3-bis e delle disposizioni dell'art. 64-bis costituisce mancato raggiungimento di un risultato/obiettivo rilevante per i dirigenti responsabili e comporta la riduzione (non inferiore al 30%) della retribuzione di risultato/trattamento accessorio, oltre al divieto di premi/incentivi nella struttura.",
        'testo_integrale': "La violazione dell'articolo 64, comma 3-bis e delle disposizioni di cui al presente articolo, costituisce mancato raggiungimento di uno specifico risultato e di un rilevante obiettivo da parte dei dirigenti responsabili delle strutture competenti e comporta la riduzione, non inferiore al 30 per cento della retribuzione di risultato e del trattamento accessorio collegato alla performance individuale dei dirigenti competenti, oltre al divieto di attribuire premi o incentivi nell'ambito delle medesime strutture.",
        'tipo_obbligo': 'sanzionatorio',
        'stato': 'vigente',
        'sanzioni': "riduzione non inferiore al 30% della retribuzione di risultato e del trattamento accessorio collegato alla performance individuale dei dirigenti competenti, oltre al divieto di attribuire premi o incentivi nell'ambito delle medesime strutture",
    },
]

RIGHE_PRINCIPI: list[dict] = [
    {
        'riferimento': 'art. 62-bis c.1',
        'testo': "Per ridurre gli oneri amministrativi e assicurare efficacia, trasparenza e controllo in tempo reale della spesa pubblica in lavori/servizi/forniture (anche a fini anticorruzione), si utilizza la Banca dati nazionale dei contratti pubblici (BDNCP), gestita dall'ANAC ai sensi dell'art. 213 del d.lgs. 50/2016.",
        'testo_integrale': 'Per favorire la riduzione degli oneri amministrativi derivanti dagli obblighi informativi ed assicurare l\'efficacia, la trasparenza e il controllo in tempo reale dell\'azione amministrativa per l\'allocazione della spesa pubblica in lavori, servizi e forniture, anche al fine del rispetto della legalita\' e del corretto agire della pubblica amministrazione e prevenire fenomeni di corruzione, si utilizza la "Banca dati nazionale dei contratti pubblici" (BDNCP) ((gestita dall\'Autorita\' Nazionale Anticorruzione ai sensi dell\'articolo 213 del decreto legislativo 18 aprile 2016, n. 50)).',
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 63',
        'testo': 'Articolo abrogato dal D.Lgs. 13 dicembre 2017, n. 217.',
        'testo_integrale': '((ARTICOLO ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217))',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 64 c.1',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 64 c.2',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 64 c.2-ter',
        'testo': 'Il sistema SPID è un insieme aperto di soggetti pubblici e privati che, previo accreditamento AgID, identificano gli utenti per consentire loro di compiere attività e accedere a servizi in rete.',
        'testo_integrale': "Il sistema SPID e' costituito come insieme aperto di soggetti pubblici e privati che, previo accreditamento da parte dell'AgID, secondo modalita' definite con il decreto di cui al comma 2-sexies, identificano gli utenti per consentire loro il compimento di attivita' e l'accesso ai servizi in rete.",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['identificazione elettronica'],
    },
    {
        'riferimento': 'art. 64 c.2-quinquies',
        'testo': "I soggetti privati hanno facoltà di avvalersi di SPID o della CIE per la gestione dell'identità digitale dei propri utenti; l'adesione esonera tali soggetti dall'obbligo generale di sorveglianza sulle attività dei propri siti (art. 17 d.lgs. 70/2003).",
        'testo_integrale': "Ai fini dell'erogazione dei propri servizi in rete, e' altresi' riconosciuta ai soggetti privati, secondo le modalita' definite con il decreto di cui al comma 2-sexies, la facolta' di avvalersi del sistema SPID per la gestione dell'identita' digitale dei propri utenti, nonche' la facolta' di avvalersi della carta di identita' elettronica. L'adesione al sistema SPID ovvero l'utilizzo della carta di identita' elettronica per la verifica dell'accesso ai propri servizi erogati in rete per i quali e' richiesto il riconoscimento dell'utente esonera i predetti soggetti da un obbligo generale di sorveglianza delle attivita' sui propri siti, ai sensi dell'articolo 17 del decreto legislativo 9 aprile 2003, n. 70.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['identificazione elettronica'],
    },
    {
        'riferimento': 'art. 64 c.2-septies',
        'testo': 'Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 64 c.2-octies',
        'testo': 'Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 64 c.2-nonies',
        'testo': "L'accesso di cui al comma 2-quater può avvenire anche con la carta nazionale dei servizi (CNS).",
        'testo_integrale': "L'accesso di cui al comma 2-quater puo' avvenire anche con la carta nazionale dei servizi.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'oggetti_giuridici': ['identificazione elettronica'],
    },
    {
        'riferimento': 'art. 64 c.2-duodecies',
        'testo': "La verifica dell'identità digitale con livello di garanzia almeno significativo produce, nelle transazioni elettroniche e nell'accesso ai servizi in rete (anche tramite canali fisici), gli effetti del documento di riconoscimento equipollente ex art. 35 d.P.R. 445/2000; l'identità digitale così verificata attesta anche gli attributi qualificati dell'utente (abilitazioni, stati, qualità personali, dati attestati da gestori di attributi qualificati), secondo le Linee guida AgID.",
        'testo_integrale': "La verifica dell'identita' digitale con livello di garanzia almeno significativo, ai sensi dell'articolo 8, paragrafo 2, del Regolamento (UE) n. 910/2014 del Parlamento e del Consiglio europeo del 23 luglio 2014, produce, nelle transazioni elettroniche o per l'accesso ai servizi in rete, gli effetti del documento di riconoscimento equipollente, di cui all'articolo 35 del testo unico di cui al decreto del Presidente della Repubblica 28 dicembre 2000, n. 445. ((La disposizione di cui al periodo precedente si applica altresi' in caso di identificazione elettronica ai fini dell'accesso ai servizi erogati dalle pubbliche amministrazioni e dai soggetti privati tramite canali fisici)). L'identita' digitale, verificata ai sensi del presente articolo e con livello di sicurezza almeno significativo, attesta gli attributi qualificati dell'utente, ivi compresi i dati relativi al possesso di abilitazioni o autorizzazioni richieste dalla legge ovvero stati, qualita' personali e fatti contenuti in albi, elenchi o registri pubblici o comunque accertati da soggetti titolari di funzioni pubbliche, ((ovvero gli altri dati, fatti e informazioni funzionali alla fruizione di un servizio attestati da un gestore di attributi qualificati,)) secondo le modalita' stabilite da AgID con Linee guida.",
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['identificazione elettronica', 'attestato elettronico di attributi qualificato'],
    },
    {
        'riferimento': 'art. 64 c.3',
        'testo': 'Comma abrogato dal D.Lgs. 30 dicembre 2010, n. 235.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 30 DICEMBRE 2010, N. 235. (11)',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 64-bis c.1-sexies',
        'testo': "I minori che hanno compiuto 14 anni possono accedere e utilizzare il punto di accesso telematico, anche per ottenere/esibire attestazioni, titoli o abilitazioni con effetti giuridici (incluso l'IT-Wallet), senza necessità di assenso dell'esercente la responsabilità genitoriale, salvo i casi in cui la legge richieda espressamente il suo intervento/autorizzazione.",
        'testo_integrale': "((Ai minori che abbiano compiuto il quattordicesimo anno di eta' sono consentiti l'accesso e l'utilizzo del punto di accesso telematico di cui al presente articolo, anche per l'ottenimento e l'esibizione di attestazioni, titoli o abilitazioni aventi effetti giuridici, compresi quelli resi disponibili mediante il Sistema di portafoglio digitale italiano (Sistema IT-Wallet) di cui all'articolo 64-quater, senza che sia necessario l'assenso dell'esercente la responsabilita' genitoriale, fatti salvi i casi in cui la legge richieda espressamente l'intervento o l'autorizzazione dell'esercente la responsabilita' genitoriale per l'ottenimento di specifiche attestazioni, titoli o abilitazioni ovvero per la fruizione di specifici servizi)).",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
]

INDICE_ARTICOLI_LOCALE: list[str] = [
    'art. 62 c.1',
    'art. 62 c.2',
    'art. 62 c.2-bis',
    'art. 62 c.2-ter',
    'art. 62 c.2-quater',
    'art. 62 c.3',
    'art. 62 c.3-bis',
    'art. 62 c.4',
    'art. 62 c.5',
    'art. 62 c.6',
    'art. 62 c.6-bis',
    'art. 62-bis c.1',
    'art. 62-ter c.1',
    'art. 62-ter c.2',
    'art. 62-ter c.3',
    'art. 62-ter c.4',
    'art. 62-ter c.5',
    'art. 62-ter c.6',
    'art. 62-ter c.7',
    'art. 62-quater c.1',
    'art. 62-quater c.2',
    'art. 62-quater c.3',
    'art. 62-quater c.4',
    'art. 62-quater c.5',
    'art. 62-quater c.6',
    'art. 62-quinquies c.1',
    'art. 62-quinquies c.2',
    'art. 62-quinquies c.3',
    'art. 62-quinquies c.4',
    'art. 62-quinquies c.5',
    'art. 62-sexies c.1',
    'art. 62-sexies c.2',
    'art. 62-sexies c.3',
    'art. 62-sexies c.4',
    'art. 62-sexies c.5',
    'art. 63',
    'art. 64 c.1',
    'art. 64 c.2',
    'art. 64 c.2-bis',
    'art. 64 c.2-ter',
    'art. 64 c.2-quater',
    'art. 64 c.2-quinquies',
    'art. 64 c.2-sexies',
    'art. 64 c.2-septies',
    'art. 64 c.2-octies',
    'art. 64 c.2-nonies',
    'art. 64 c.2-decies',
    'art. 64 c.2-undecies',
    'art. 64 c.2-duodecies',
    'art. 64 c.3',
    'art. 64 c.3-bis',
    'art. 64 c.3-ter',
    'art. 64-bis c.1',
    'art. 64-bis c.1-bis',
    'art. 64-bis c.1-ter',
    'art. 64-bis c.1-quater',
    'art. 64-bis c.1-quinquies',
    'art. 64-bis c.1-sexies',
]

MAPPATURA_LOCALE: dict[str, list[str]] = {
    'art. 62 c.1': ['art. 62 c.1'],
    'art. 62 c.2': ['art. 62 c.2'],
    'art. 62 c.2-bis': ['art. 62 c.2-bis'],
    'art. 62 c.2-ter': ['art. 62 c.2-ter'],
    'art. 62 c.2-quater': ['art. 62 c.2-quater'],
    'art. 62 c.3': ['art. 62 c.3'],
    'art. 62 c.3-bis': ['art. 62 c.3-bis'],
    'art. 62 c.4': ['art. 62 c.4'],
    'art. 62 c.5': ['art. 62 c.5'],
    'art. 62 c.6': ['art. 62 c.6'],
    'art. 62 c.6-bis': ['art. 62 c.6-bis'],
    'art. 62-ter c.1': ['art. 62-ter c.1'],
    'art. 62-ter c.2': ['art. 62-ter c.2'],
    'art. 62-ter c.3': ['art. 62-ter c.3'],
    'art. 62-ter c.4': ['art. 62-ter c.4'],
    'art. 62-ter c.5': ['art. 62-ter c.5'],
    'art. 62-ter c.6': ['art. 62-ter c.6'],
    'art. 62-ter c.7': ['art. 62-ter c.7'],
    'art. 62-quater c.1': ['art. 62-quater c.1'],
    'art. 62-quater c.2': ['art. 62-quater c.2'],
    'art. 62-quater c.3': ['art. 62-quater c.3'],
    'art. 62-quater c.4': ['art. 62-quater c.4'],
    'art. 62-quater c.5': ['art. 62-quater c.5'],
    'art. 62-quater c.6': ['art. 62-quater c.6'],
    'art. 62-quinquies c.1': ['art. 62-quinquies c.1'],
    'art. 62-quinquies c.2': ['art. 62-quinquies c.2'],
    'art. 62-quinquies c.3': ['art. 62-quinquies c.3'],
    'art. 62-quinquies c.4': ['art. 62-quinquies c.4'],
    'art. 62-quinquies c.5': ['art. 62-quinquies c.5'],
    'art. 62-sexies c.1': ['art. 62-sexies c.1'],
    'art. 62-sexies c.2': ['art. 62-sexies c.2'],
    'art. 62-sexies c.3': ['art. 62-sexies c.3'],
    'art. 62-sexies c.4': ['art. 62-sexies c.4'],
    'art. 62-sexies c.5': ['art. 62-sexies c.5'],
    'art. 64 c.2-bis': ['art. 64 c.2-bis'],
    'art. 64 c.2-quater': ['art. 64 c.2-quater'],
    'art. 64 c.2-sexies': ['art. 64 c.2-sexies'],
    'art. 64 c.2-decies': ['art. 64 c.2-decies'],
    'art. 64 c.2-undecies': ['art. 64 c.2-undecies'],
    'art. 64 c.3-bis': ['art. 64 c.3-bis'],
    'art. 64 c.3-ter': ['art. 64 c.3-ter'],
    'art. 64-bis c.1': ['art. 64-bis c.1'],
    'art. 64-bis c.1-bis': ['art. 64-bis c.1-bis'],
    'art. 64-bis c.1-ter': ['art. 64-bis c.1-ter'],
    'art. 64-bis c.1-quater': ['art. 64-bis c.1-quater'],
    'art. 64-bis c.1-quinquies': ['art. 64-bis c.1-quinquies'],
    'art. 62-bis c.1': ['art. 62-bis c.1'],
    'art. 63': ['art. 63'],
    'art. 64 c.1': ['art. 64 c.1'],
    'art. 64 c.2': ['art. 64 c.2'],
    'art. 64 c.2-ter': ['art. 64 c.2-ter'],
    'art. 64 c.2-quinquies': ['art. 64 c.2-quinquies'],
    'art. 64 c.2-septies': ['art. 64 c.2-septies'],
    'art. 64 c.2-octies': ['art. 64 c.2-octies'],
    'art. 64 c.2-nonies': ['art. 64 c.2-nonies'],
    'art. 64 c.2-duodecies': ['art. 64 c.2-duodecies'],
    'art. 64 c.3': ['art. 64 c.3'],
    'art. 64-bis c.1-sexies': ['art. 64-bis c.1-sexies'],
}

RELAZIONI: list[dict] = [
    {
        'nodo_da': ('obbligo', None, 'art. 62-ter c.2'),
        'nodo_a': ('obbligo', None, 'art. 62 c.5'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-quater c.3'),
        'nodo_a': ('obbligo', None, 'art. 62 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-quater c.4'),
        'nodo_a': ('obbligo', None, 'art. 62 c.5'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-quinquies c.3'),
        'nodo_a': ('obbligo', None, 'art. 62 c.5'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-sexies c.2'),
        'nodo_a': ('obbligo', None, 'art. 62 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-sexies c.2'),
        'nodo_a': ('obbligo', None, 'art. 62-quater c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-sexies c.2'),
        'nodo_a': ('obbligo', None, 'art. 62-quinquies c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 64 c.2-nonies'),
        'nodo_a': ('obbligo', None, 'art. 64 c.2-quater'),
        'tipo_relazione': 'specifica',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 64 c.3-bis'),
        'nodo_a': ('principio', None, 'art. 64 c.2-nonies'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 64 c.3-ter'),
        'nodo_a': ('obbligo', None, 'art. 62 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 64-bis c.1-quinquies'),
        'nodo_a': ('obbligo', None, 'art. 64 c.3-bis'),
        'tipo_relazione': 'sanziona',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 64-bis c.1-quinquies'),
        'nodo_a': ('obbligo', None, 'art. 64-bis c.1'),
        'tipo_relazione': 'sanziona',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-quater c.5'),
        'nodo_a': ('obbligo', None, 'art. 64 c.2-quater'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-quater c.5'),
        'nodo_a': ('obbligo', None, 'art. 64-bis c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-quinquies c.4'),
        'nodo_a': ('obbligo', None, 'art. 64 c.2-quater'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 62-quinquies c.4'),
        'nodo_a': ('obbligo', None, 'art. 64-bis c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 64 c.2-quater'),
        'nodo_a': ('obbligo', None, 'art. 64 c.2-sexies'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 64 c.2-quinquies'),
        'nodo_a': ('obbligo', None, 'art. 64 c.2-sexies'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 64 c.2-ter'),
        'nodo_a': ('obbligo', None, 'art. 64 c.2-sexies'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 64 c.3-bis'),
        'nodo_a': ('obbligo', None, 'art. 64 c.2-quater'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
]
