"""Estrazione granulare CAD (ADR-0007) — Capo I (parte 3) / Capo II (parte 1): artt. 16-28.

Fonte: D.Lgs. 82/2005 (CAD), testo vigente al 16/09/2026.
Testo ufficiale: app/.source_cache/cad/cap03.txt.

Contenuto: artt. 16-18-bis (competenze Presidenza del Consiglio in materia di innovazione e
tecnologie, responsabile per la transizione digitale, difensore civico digitale, piattaforma
nazionale per la governance della trasformazione digitale, vigilanza/sanzioni AgID); artt. 19-28
(Capo II, parte 1: validita' ed efficacia probatoria dei documenti informatici, copie informatiche
di documenti analogici e viceversa, duplicati e copie informatiche, documenti amministrativi
informatici, firma digitale, firma autenticata, certificati di firma elettronica qualificata).

Copertura completa per comma/lettera (nessun discrimine di rilevanza): gli articoli/commi abrogati
(19, 26, 27 e i singoli commi soppressi negli artt. 20, 21, 22, 23-ter, 28) sono censiti come
Principio con stato "abrogato" anziche' omessi. Quando un comma elenca, tramite lettere a)...n),
sfaccettature omogenee di un'unica prescrizione continua (es. art. 16 c.1, art. 17 c.1, art. 24
c.4-ter, art. 28 c.3), l'intero comma e' modellato come un solo nodo (un solo item di indice), con
`testo_integrale` che riporta l'intero comma comprese tutte le lettere.

`testo_integrale` e' copiato verbatim dal testo ufficiale, incluse le marcature '((' '))' con cui il
testo vigente segnala le porzioni inserite/modificate da decreti successivi e le annotazioni tipo
"PERIODO SOPPRESSO DAL D.L. ..." presenti nel file sorgente.
"""

RIGHE_OBBLIGHI: list[dict] = [
    {
        'riferimento': 'art. 16 c.1',
        'testo': "Il Presidente del Consiglio dei Ministri o il Ministro delegato per l'innovazione e le tecnologie, nell'attivita' di coordinamento e valutazione del processo di digitalizzazione delle PA centrali, definisce le linee strategiche, valuta il corretto utilizzo delle risorse finanziarie, sostiene i progetti innovativi di rilievo strategico, promuove l'informazione sulle nuove tecnologie e stabilisce i criteri di pianificazione, gestione, qualita' e sicurezza dei sistemi informativi automatizzati delle PA centrali.",
        'testo_integrale': "Per il perseguimento dei fini di cui al presente codice, il Presidente del Consiglio dei Ministri o il Ministro delegato per l'innovazione e le tecnologie, nell'attivita' di coordinamento del processo di digitalizzazione e di coordinamento e di valutazione dei programmi, dei progetti e dei piani di azione formulati dalle pubbliche amministrazioni centrali per lo sviluppo dei sistemi informativi:\na) definisce con proprie direttive le linee strategiche, la pianificazione e le aree di intervento dell'innovazione tecnologica nelle pubbliche amministrazioni centrali, e ne verifica l'attuazione;\nb) ((approva il piano triennale di cui all'articolo 14-bis, comma 2, lettera b), e)) valuta, sulla base di criteri e metodiche di ottimizzazione della spesa, il corretto utilizzo delle risorse finanziarie per l'informatica e la telematica da parte delle singole amministrazioni centrali;\nc) ((promuove e)) sostiene progetti di grande contenuto innovativo, di rilevanza strategica, di preminente interesse nazionale, con particolare attenzione per i progetti di carattere intersettoriale;\nd) promuove l'informazione circa le iniziative per la diffusione delle nuove tecnologie;\ne) ((stabilisce i)) criteri in tema di pianificazione, progettazione, realizzazione, gestione, mantenimento dei sistemi informativi automatizzati delle pubbliche amministrazioni centrali e delle loro interconnessioni, nonche' della loro qualita' e relativi aspetti organizzativi e della loro sicurezza.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 16 c.2',
        'testo': "Il Presidente del Consiglio dei Ministri o il Ministro delegato per l'innovazione e le tecnologie riferisce ogni anno al Parlamento sullo stato di attuazione del Codice.",
        'testo_integrale': "Il Presidente del Consiglio dei Ministri o il Ministro delegato per l'innovazione e le tecnologie riferisce annualmente al Parlamento sullo stato di attuazione del presente codice.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 17 c.1',
        'testo': "Le pubbliche amministrazioni garantiscono l'attuazione delle linee strategiche di riorganizzazione e digitalizzazione definite dal Governo, affidando a un unico ufficio dirigenziale generale la transizione digitale e attribuendogli compiti di coordinamento su sistemi informativi, sicurezza informatica, accessibilita', organizzazione, cooperazione applicativa, diffusione di identita' digitale/domicilio digitale/firma digitale, e pianificazione degli acquisti ICT coerenti col piano triennale.",
        'testo_integrale': "Le pubbliche amministrazioni garantiscono l'attuazione delle linee strategiche per la riorganizzazione e la digitalizzazione dell'amministrazione definite dal Governo in coerenza con le Linee guida. A tal fine, ciascuna pubblica amministrazione affida a un unico ufficio dirigenziale generale, fermo restando il numero complessivo di tali uffici, la transizione alla modalita' operativa digitale e i conseguenti processi di riorganizzazione finalizzati alla realizzazione di un'amministrazione digitale e aperta, di servizi facilmente utilizzabili e di qualita', attraverso una maggiore efficienza ed economicita'. Al suddetto ufficio sono inoltre attribuiti i compiti relativi a:\na) coordinamento strategico dello sviluppo dei sistemi informativi, di telecomunicazione e fonia, in modo da assicurare anche la coerenza con gli standard tecnici e organizzativi comuni;\nb) indirizzo e coordinamento dello sviluppo dei servizi, sia interni che esterni, forniti dai sistemi informativi di telecomunicazione e fonia dell'amministrazione;\nc) indirizzo, pianificazione, coordinamento e monitoraggio della sicurezza informatica relativamente ai dati, ai sistemi e alle infrastrutture anche in relazione al sistema pubblico di connettivita', nel rispetto delle regole tecniche di cui all'articolo 51, comma 1;\nd) accesso dei soggetti disabili agli strumenti informatici e promozione dell'accessibilita' anche in attuazione di quanto previsto dalla legge 9 gennaio 2004, n. 4;\ne) analisi periodica della coerenza tra l'organizzazione dell'amministrazione e l'utilizzo delle tecnologie dell'informazione e della comunicazione, al fine di migliorare la soddisfazione dell'utenza e la qualita' dei servizi nonche' di ridurre i tempi e i costi dell'azione amministrativa;\nf) cooperazione alla revisione della riorganizzazione dell'amministrazione ai fini di cui alla lettera e);\ng) indirizzo, coordinamento e monitoraggio della pianificazione prevista per lo sviluppo e la gestione dei sistemi informativi di telecomunicazione e fonia;\nh) progettazione e coordinamento delle iniziative rilevanti ai fini di una piu' efficace erogazione di servizi in rete a cittadini e imprese mediante gli strumenti della cooperazione applicativa tra pubbliche amministrazioni, ivi inclusa la predisposizione e l'attuazione di accordi di servizio tra amministrazioni per la realizzazione e compartecipazione dei sistemi informativi cooperativi;(28)\ni) promozione delle iniziative attinenti l'attuazione delle direttive impartite dal Presidente del Consiglio dei Ministri o dal Ministro delegato per l'innovazione e le tecnologie;\nj) pianificazione e coordinamento del processo di diffusione, all'interno dell'amministrazione, dei sistemi di identita' e domicilio digitale, posta elettronica, protocollo informatico, firma digitale o firma elettronica qualificata e mandato informatico, e delle norme in materia di accessibilita' e fruibilita' nonche' del processo di integrazione e interoperabilita' tra i sistemi e servizi dell'amministrazione e quello di cui all'articolo 64-bis.\nj-bis) pianificazione e coordinamento degli acquisti di soluzioni e sistemi informatici, telematici e di telecomunicazione al fine di garantirne la compatibilita' con gli obiettivi di attuazione dell'agenda digitale e, in particolare, con quelli stabiliti nel piano triennale di cui all'articolo 16, comma 1, lettera b).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 17 c.1-ter',
        'testo': "Il responsabile dell'ufficio per la transizione digitale deve possedere adeguate competenze tecnologiche, di informatica giuridica e manageriali, e risponde direttamente all'organo di vertice politico per i compiti relativi alla transizione digitale.",
        'testo_integrale': "Il responsabile dell'ufficio di cui al comma 1 e' dotato di adeguate competenze tecnologiche, di informatica giuridica e manageriali e risponde, con riferimento ai compiti relativi alla transizione, alla modalita' digitale direttamente all'organo di vertice politico.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 17 c.1-quater',
        'testo': "Presso l'AgID e' istituito l'ufficio del difensore civico per il digitale, cui chiunque puo' segnalare presunte violazioni del Codice e della normativa sulla digitalizzazione della PA; il difensore civico, accertata la non manifesta infondatezza della segnalazione, la trasmette al Direttore generale dell'AgID per l'esercizio dei poteri di cui all'articolo 18-bis.",
        'testo_integrale': "E' istituito presso l'AgID l'ufficio del difensore civico per il digitale, a cui e' preposto un soggetto in possesso di adeguati requisiti di terzieta', autonomia e imparzialita'. Chiunque puo' presentare al difensore civico per il digitale, attraverso apposita area presente sul sito istituzionale dell'AgID, segnalazioni relative a presunte violazioni del presente Codice e di ogni altra norma in materia di digitalizzazione ed innovazione della pubblica amministrazione da parte dei soggetti di cui all'articolo 2, comma 2. Il difensore civico, accertata la non manifesta infondatezza della segnalazione, la trasmette al Direttore generale dell'AgID per l'esercizio dei poteri di cui all'articolo 18-bis. PERIODO SOPPRESSO DAL D.L. 31 MAGGIO 2021, N. 77. PERIODO SOPPRESSO DAL D.L. 31 MAGGIO 2021, N. 77. PERIODO SOPPRESSO DAL D.L. 31 MAGGIO 2021, N. 77.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 17 c.1-quinquies',
        'testo': 'AgID pubblica sul proprio sito una guida di riepilogo dei diritti di cittadinanza digitale previsti dal Codice.',
        'testo_integrale': 'AgID pubblica sul proprio sito una guida di riepilogo dei diritti di cittadinanza digitali previsti dal presente Codice.',
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 17 c.1-sexies',
        'testo': "Le pubbliche amministrazioni diverse da quelle statali individuano l'ufficio per il digitale tra quelli di livello dirigenziale o, in mancanza, un responsabile tra le posizioni apicali; in assenza del vertice politico, il responsabile risponde al vertice amministrativo dell'ente.",
        'testo_integrale': "Nel rispetto della propria autonomia organizzativa, le pubbliche amministrazioni diverse dalle amministrazioni dello Stato individuano l'ufficio per il digitale di cui al comma 1 tra quelli di livello dirigenziale oppure, ove ne siano privi, individuano un responsabile per il digitale tra le proprie posizioni apicali. In assenza del vertice politico, il responsabile dell'ufficio per il digitale di cui al comma 1 risponde direttamente a quello amministrativo dell'ente.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18 c.1',
        'testo': "Presso l'AgID e' realizzata una piattaforma per la consultazione pubblica e il confronto tra i portatori di interesse in relazione ai provvedimenti connessi all'attuazione dell'agenda digitale.",
        'testo_integrale': "E' realizzata presso l'AgID una piattaforma per la consultazione pubblica e il confronto tra i portatori di interesse in relazione ai provvedimenti connessi all'attuazione dell'agenda digitale.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18 c.2',
        'testo': "AgID identifica le caratteristiche tecnico-funzionali della piattaforma affinche' sia accessibile ai portatori di interessi pubblici e privati e idonea a raccogliere in modo trasparente, qualificato ed efficace suggerimenti e proposte emendative.",
        'testo_integrale': 'AgID identifica le caratteristiche tecnico-funzionali della piattaforma in maniera tale da garantire che la stessa sia accessibile ai portatori di interessi pubblici e privati e che sia idonea a raccogliere suggerimenti e proposte emendative in maniera trasparente, qualificata ed efficace.',
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18 c.3',
        'testo': "Il Piano triennale per l'informatica nella pubblica amministrazione e' pubblicato sulla piattaforma e aggiornato annualmente.",
        'testo_integrale': "Il Piano triennale per l'informatica nella pubblica amministrazione di cui all'articolo 14-bis e' pubblicato sulla piattaforma e aggiornato di anno in anno.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18 c.5',
        'testo': "I soggetti di cui all'articolo 2, comma 2, lettera a), tengono conto dei suggerimenti e delle proposte emendative raccolte attraverso la piattaforma.",
        'testo_integrale': "I soggetti di cui all'articolo 2, comma 2, lettera a), tengono conto di suggerimenti e proposte emendative raccolte attraverso la piattaforma.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18-bis c.1',
        'testo': "AgID esercita poteri di vigilanza, verifica, controllo e monitoraggio sul rispetto del Codice e della normativa sulla digitalizzazione della PA, procedendo d'ufficio o su segnalazione del difensore civico digitale all'accertamento delle violazioni; puo' richiedere e acquisire dati, documenti e informazioni presso i soggetti di cui all'articolo 2, comma 2; la mancata ottemperanza o la trasmissione di dati parziali o non veritieri e' sanzionata ai sensi del comma 5, in misura ridotta della meta'.",
        'testo_integrale': "L'AgID esercita poteri di vigilanza, verifica, controllo e monitoraggio sul rispetto delle disposizioni del presente Codice e di ogni altra norma in materia di innovazione tecnologica e digitalizzazione della pubblica amministrazione, ivi comprese quelle contenute nelle Linee guida e nel Piano triennale per l'informatica nella pubblica amministrazione, e procede, d'ufficio ovvero su segnalazione del difensore civico digitale, all'accertamento delle relative violazioni da parte dei soggetti di cui all'articolo 2, comma 2. Nell'esercizio dei poteri di vigilanza, verifica, controllo e monitoraggio, l'AgID richiede e acquisisce presso i soggetti di cui all'articolo 2, comma 2, dati, documenti e ogni altra informazione strumentale e necessaria. La mancata ottemperanza alla richiesta di dati, documenti o informazioni di cui al secondo periodo ovvero la trasmissione di informazioni o dati parziali o non veritieri e' punita ai sensi del comma 5, con applicazione della sanzione ivi prevista ridotta della meta'.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'sanzioni': "sanzione di cui al comma 5, ridotta della meta', per mancata ottemperanza alla richiesta di dati/documenti/informazioni",
    },
    {
        'riferimento': 'art. 18-bis c.2',
        'testo': 'Quando risultano violazioni, AgID procede alla contestazione nei confronti del trasgressore, assegnando un termine perentorio per scritti difensivi, documentazione e audizione.',
        'testo_integrale': "L'AgID, quando dagli elementi acquisiti risulta che sono state commesse una o piu' violazioni delle disposizioni di cui al comma 1, procede alla contestazione nei confronti del trasgressore, assegnandogli un termine perentorio per inviare scritti difensivi e documentazione e per chiedere di essere sentito.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18-bis c.3',
        'testo': "Accertate le violazioni contestate, AgID assegna un congruo termine perentorio per conformare la condotta, segnala le violazioni all'ufficio disciplinare competente e agli organismi indipendenti di valutazione, e pubblica le segnalazioni sul proprio sito.",
        'testo_integrale': "L'AgID, ove accerti la sussistenza delle violazioni contestate, assegna al trasgressore un congruo termine perentorio, proporzionato rispetto al tipo e alla gravita' della violazione, per conformare la condotta agli obblighi previsti dalla normativa vigente, segnalando le violazioni all'ufficio competente per i procedimenti disciplinari di ciascuna amministrazione, nonche' ai competenti organismi indipendenti di valutazione. L'AgID pubblica le predette segnalazioni su apposita area del proprio sito internet istituzionale.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18-bis c.5',
        'testo': "In caso di mancata ottemperanza alla richiesta di dati/documenti/informazioni, di trasmissione di dati parziali o non veritieri, o di violazione di specifici obblighi elencati del Codice e di altre norme, se il soggetto non conforma la condotta nel termine di cui al comma 3, AgID irroga una sanzione amministrativa pecuniaria da 10.000 a 100.000 euro, secondo la disciplina della l. 689/1981; i proventi sono ripartiti tra AgID e il Fondo di cui all'articolo 239 del d.l. 34/2020.",
        'testo_integrale': "In caso di mancata ottemperanza alla richiesta di dati, documenti o informazioni di cui al comma 1, ultimo periodo, ovvero di trasmissione di informazioni o dati parziali o non veritieri, nonche' di violazione degli obblighi previsti dagli articoli 5, 7, comma 3, 41, commi 2 e 2-bis, 43, comma 1-bis, 50, comma 3-ter, 50-ter, comma 5, 64, comma 3\xadbis, 64-bis del presente Codice, dall'articolo 65, comma 1, del decreto legislativo 13 dicembre 2017, n. 217 e dall'articolo 33-septies, comma 4, del decreto-legge 18 ottobre 2012, n. 179, convertito, con modificazioni, dalla legge 17 dicembre 2012, n. 221, ove il soggetto di cui all'articolo 2, comma 2, non ottemperi all'obbligo di conformare la condotta nel termine di cui al comma 3, l'AgID irroga la sanzione amministrativa pecuniaria nel minimo di euro 10.000 e nel massimo di euro 100.000. Si applica, per quanto non espressamente previsto dal presente articolo, la disciplina della legge 24 novembre 1981, n. 689. I proventi delle sanzioni sono versati in apposito capitolo di entrata del bilancio dello Stato per essere riassegnati allo stato di previsione della spesa del Ministero dell'economia e delle finanze a favore per il 50 per cento dell'AgID e per la restante parte al Fondo di cui all'articolo 239 del decreto-legge 19 maggio 2020, n. 34, convertito, con modificazioni, dalla legge 17 luglio 2020, n. 77.",
        'tipo_obbligo': 'sanzionatorio',
        'stato': 'vigente',
        'sanzioni': 'sanzione amministrativa pecuniaria da euro 10.000 a euro 100.000',
    },
    {
        'riferimento': 'art. 18-bis c.6',
        'testo': "Contestualmente alla sanzione per le violazioni piu' gravi (comma 5) o per violazione dell'articolo 13-bis, comma 4, AgID segnala la violazione alla struttura della Presidenza del Consiglio competente, che diffida ulteriormente il soggetto; decorso inutilmente il termine, puo' essere nominato un commissario ad acta, ovvero si procede secondo i poteri sostitutivi costituzionali per gli enti locali.",
        'testo_integrale': "Contestualmente all'irrogazione della sanzione nei casi di violazione delle norme specificamente indicate al comma 5, nonche' di violazione degli obblighi di cui all'articolo 13-bis, comma 4, l'AgID segnala la violazione alla struttura della Presidenza del Consiglio dei ministri competente per l'innovazione tecnologica e la transizione digitale che, ricevuta la segnalazione, diffida ulteriormente il soggetto responsabile a conformare la propria condotta agli obblighi previsti dalla disciplina vigente entro un congruo termine perentorio, proporzionato al tipo e alla gravita' della violazione, avvisandolo che, in caso di inottemperanza, potranno essere esercitati i poteri sostitutivi del Presidente del Consiglio dei ministri o del Ministro delegato. Decorso inutilmente il termine, il Presidente del Consiglio dei ministri o il Ministro delegato per l'innovazione tecnologica e la transizione digitale, valutata la gravita' della violazione, puo' nominare un commissario ad acta incaricato di provvedere in sostituzione. Al commissario non spettano compensi, indennita' o rimborsi. Nel caso di inerzia o ritardi riguardanti amministrazioni locali, si procede all'esercizio del potere sostitutivo di cui agli articoli 117, quinto comma, e 120, secondo comma, della Costituzione, ai sensi dell'articolo 8 della legge 5 giugno 2003, n. 131.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18-bis c.7',
        'testo': "AgID disciplina con proprio regolamento le procedure di contestazione, accertamento, segnalazione e irrogazione delle sanzioni previste dall'articolo.",
        'testo_integrale': "L'AgID, con proprio regolamento, disciplina le procedure di contestazione, accertamento, segnalazione e irrogazione delle sanzioni per le violazioni di cui alla presente disposizione.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 20 c.3',
        'testo': "Le regole tecniche per formazione, trasmissione, conservazione, copia, duplicazione, riproduzione e validazione dei documenti informatici, nonche' per generazione, apposizione e verifica delle firme elettroniche, sono stabilite con le Linee guida.",
        'testo_integrale': "Le regole tecniche per la formazione, per la trasmissione, la conservazione, la copia, la duplicazione, la riproduzione e la validazione dei documenti informatici, nonche' quelle in materia di generazione, apposizione e verifica di qualsiasi tipo di firma elettronica, sono stabilite ((con le Linee guida)). ((PERIODO SOPPRESSO DAL D.LGS. 13 DICEMBRE 2017, N. 217)).",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 20 c.4',
        'testo': "Con le medesime regole tecniche sono definite le misure tecniche, organizzative e gestionali per garantire integrita', disponibilita' e riservatezza delle informazioni contenute nel documento informatico.",
        'testo_integrale': "Con le medesime regole tecniche sono definite le misure tecniche, organizzative e gestionali volte a garantire l'integrita', la disponibilita' e la riservatezza delle informazioni contenute nel documento informatico.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 21 c.2-bis',
        'testo': "Salvo sottoscrizione autenticata, le scritture private di cui all'articolo 1350, primo comma, nn. 1-12, c.c., se fatte con documento informatico, sono sottoscritte a pena di nullita' con firma elettronica qualificata o digitale. Gli atti di cui al n. 13 dello stesso articolo, redatti su documento informatico o formati con procedimenti informatici, sono sottoscritti a pena di nullita' con firma elettronica avanzata, qualificata o digitale, ovvero formati con le modalita' dell'articolo 20, comma 1-bis, primo periodo.",
        'testo_integrale': "Salvo il caso di sottoscrizione autenticata, le scritture private di cui all'articolo 1350, primo comma, numeri da 1 a 12, del codice civile, se fatte con documento informatico, sono sottoscritte, a pena di nullita', con firma elettronica qualificata o con firma digitale. Gli atti di cui all'articolo 1350, numero 13), del codice civile redatti su documento informatico o formati attraverso procedimenti informatici sono sottoscritti, a pena di nullita', con firma elettronica avanzata, qualificata o digitale ((ovvero sono formati con le ulteriori modalita' di cui all'articolo 20, comma 1-bis, primo periodo)).",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'condizione_applicabilita': 'salvo il caso di sottoscrizione autenticata',
    },
    {
        'riferimento': 'art. 21 c.2-ter',
        'testo': "Fatto salvo il D.Lgs. 110/2010, ogni altro atto pubblico redatto su documento informatico e' sottoscritto dal pubblico ufficiale, a pena di nullita', con firma qualificata o digitale; parti, fidefacenti, interprete e testimoni sottoscrivono personalmente l'atto in presenza del pubblico ufficiale con firma avanzata, qualificata o digitale, ovvero con firma autografa acquisita digitalmente e allegata agli atti.",
        'testo_integrale': "Fatto salvo quanto previsto dal decreto legislativo 2 luglio 2010, n. 110, ogni altro atto pubblico redatto su documento informatico e' sottoscritto dal pubblico ufficiale a pena di nullita' con firma qualificata o digitale. Le parti, i fidefacenti, l'interprete e i testimoni sottoscrivono personalmente l'atto, in presenza del pubblico ufficiale, con firma avanzata, qualificata o digitale ovvero con firma autografa acquisita digitalmente e allegata agli atti.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 21 c.5',
        'testo': "Gli obblighi fiscali relativi ai documenti informatici e alla loro riproduzione su diversi supporti sono assolti secondo le modalita' definite con decreti del Ministro dell'economia e delle finanze, sentito il Ministro delegato per l'innovazione e le tecnologie.",
        'testo_integrale': "Gli obblighi fiscali relativi ai documenti informatici ed alla loro riproduzione su diversi tipi di supporto sono assolti secondo le modalita' definite con uno o piu' decreti del Ministro dell'economia e delle finanze, sentito il Ministro delegato per l'innovazione e le tecnologie.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 22 c.1-bis',
        'testo': "La copia per immagine su supporto informatico di un documento analogico e' prodotta con processi e strumenti che assicurano contenuto e forma identici all'originale, previo raffronto dei documenti o mediante certificazione di processo con tecniche idonee a garantire tale corrispondenza.",
        'testo_integrale': "La copia per immagine su supporto informatico di un documento analogico e' prodotta mediante processi e strumenti che assicurano che il documento informatico abbia contenuto e forma identici a quelli del documento analogico da cui e' tratto, previo raffronto dei documenti o attraverso certificazione di processo nei casi in cui siano adottate tecniche in grado di garantire la corrispondenza della forma e del contenuto dell'originale e della copia.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 22 c.5',
        'testo': "Salvo quanto previsto dal comma 4-bis, con DPCM possono essere individuate tipologie di documenti analogici originali unici per cui permane l'obbligo di conservazione dell'originale analogico, oppure, in caso di conservazione sostitutiva, la conformita' all'originale deve essere autenticata da notaio o altro pubblico ufficiale autorizzato con dichiarazione firmata digitalmente e allegata al documento informatico.",
        'testo_integrale': "Salvo quanto previsto dal comma 4-bis, con decreto del Presidente del Consiglio dei ministri possono essere individuate particolari tipologie di documenti analogici originali unici per le quali, in ragione di esigenze di natura pubblicistica, permane l'obbligo della conservazione dell'originale analogico oppure, in caso di conservazione sostitutiva, la loro conformita' all'originale deve essere autenticata da un notaio o da altro pubblico ufficiale a cio' autorizzato con dichiarazione da questi firmata digitalmente ed allegata al documento informatico.",
        'tipo_obbligo': 'di conservazione',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 23 c.2-bis',
        'testo': "Sulle copie analogiche di documenti informatici puo' essere apposto a stampa un contrassegno, secondo i criteri delle Linee guida, che consente di accedere al documento informatico o verificarne la corrispondenza con la copia; il contrassegno sostituisce a tutti gli effetti la sottoscrizione autografa del pubblico ufficiale, senza che possa essere richiesta altra copia con sottoscrizione autografa; chi appone il contrassegno deve rendere disponibili gratuitamente sul proprio sito le soluzioni per la relativa verifica.",
        'testo_integrale': "Sulle copie analogiche di documenti informatici puo' essere apposto a stampa un contrassegno, sulla base dei criteri definiti con le ((Linee guida)), tramite il quale e' possibile accedere al documento informatico, ovvero verificare la corrispondenza allo stesso della copia analogica. Il contrassegno apposto ai sensi del primo periodo sostituisce a tutti gli effetti di legge la sottoscrizione autografa del pubblico ufficiale e non puo' essere richiesta la produzione di altra copia analogica con sottoscrizione autografa del medesimo documento informatico. ((I soggetti che procedono all'apposizione del contrassegno rendono disponibili gratuitamente sul proprio sito Internet istituzionale idonee soluzioni per la verifica del contrassegno medesimo.)).",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 23-ter c.1-bis',
        'testo': "La copia su supporto informatico di documenti formati dalle pubbliche amministrazioni in origine su supporto analogico e' prodotta con processi e strumenti che assicurano contenuto identico all'originale, previo raffronto dei documenti o mediante certificazione di processo con tecniche idonee a garantire tale corrispondenza.",
        'testo_integrale': "La copia su supporto informatico di documenti formati dalle pubbliche amministrazioni in origine su supporto analogico e' prodotta mediante processi e strumenti che assicurano che il documento informatico abbia contenuto identico a quello del documento analogico da cui e' tratto, previo raffronto dei documenti o attraverso certificazione di processo nei casi in cui siano adottate tecniche in grado di garantire la corrispondenza del contenuto dell'originale e della copia.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 23-ter c.4',
        'testo': "In materia di formazione e conservazione di documenti informatici delle pubbliche amministrazioni, le Linee guida sono definite anche sentito il Ministero dei beni e delle attivita' culturali e del turismo.",
        'testo_integrale': "In materia di formazione e conservazione di documenti informatici delle pubbliche amministrazioni, le Linee guida sono definite anche sentito il Ministero dei beni e delle attivita' culturali e del turismo.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 23-ter c.5-bis',
        'testo': "I documenti amministrativi informatici devono essere fruibili indipendentemente dalla condizione di disabilita' personale, applicando i criteri di accessibilita' dei requisiti tecnici di cui all'articolo 11 della legge 9 gennaio 2004, n. 4.",
        'testo_integrale': "I documenti di cui al presente articolo devono essere fruibili indipendentemente dalla condizione di disabilita' personale, applicando i criteri di accessibilita' definiti dai requisiti tecnici di cui all'articolo 11 della legge 9 gennaio 2004, n. 4.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 24 c.1',
        'testo': "La firma digitale deve riferirsi in maniera univoca ad un solo soggetto e al documento o all'insieme di documenti cui e' apposta o associata.",
        'testo_integrale': "La firma digitale deve riferirsi in maniera univoca ad un solo soggetto ed al documento o all'insieme di documenti cui e' apposta o associata.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 24 c.3',
        'testo': 'Per generare la firma digitale deve utilizzarsi un certificato qualificato che, al momento della sottoscrizione, non risulti scaduto, revocato o sospeso.',
        'testo_integrale': "Per la generazione della firma digitale deve adoperarsi un certificato qualificato che, al momento della sottoscrizione, non risulti scaduto di validita' ovvero non risulti revocato o sospeso.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 24 c.4',
        'testo': "Attraverso il certificato qualificato devono rilevarsi, secondo le Linee guida, la validita' del certificato, gli elementi identificativi del titolare e del certificatore e gli eventuali limiti d'uso; le Linee guida definiscono anche le modalita', anche temporali, di apposizione della firma.",
        'testo_integrale': "Attraverso il certificato qualificato si devono rilevare, secondo le ((Linee guida)), la validita' del certificato stesso, nonche' gli elementi identificativi del titolare ((di firma digitale)) e del certificatore e gli eventuali limiti d'uso. ((Le linee guida definiscono altresi' le modalita', anche temporali, di apposizione della firma.))",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 25 c.2',
        'testo': "L'autenticazione della firma elettronica, anche mediante acquisizione digitale della sottoscrizione autografa, o di altra firma elettronica avanzata, consiste nell'attestazione del pubblico ufficiale che la firma e' stata apposta in sua presenza dal titolare, previo accertamento dell'identita' personale, della validita' dell'eventuale certificato elettronico e della non contrarieta' del documento all'ordinamento giuridico.",
        'testo_integrale': "L'autenticazione della firma elettronica, anche mediante l'acquisizione digitale della sottoscrizione autografa, o di qualsiasi altro tipo di firma elettronica avanzata consiste nell'attestazione, da parte del pubblico ufficiale, che la firma e' stata apposta in sua presenza dal titolare, previo accertamento della sua identita' personale, della validita' dell'eventuale certificato elettronico utilizzato e del fatto che il documento sottoscritto non e' in contrasto con l'ordinamento giuridico.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 28 c.3-bis',
        'testo': "Le informazioni di cui al comma 3 devono essere riconoscibili dai terzi e chiaramente evidenziate nel certificato; possono anche essere contenute in un separato certificato elettronico e rese disponibili in rete; le Linee guida definiscono le modalita' di attuazione, anche per pubbliche amministrazioni e ordini professionali.",
        'testo_integrale': "((Le informazioni di cui al comma 3 sono riconoscibili da parte dei terzi e chiaramente evidenziati nel certificato.)) Le informazioni di cui al comma 3 possono ((anche)) essere contenute in un separato certificato elettronico e possono essere rese disponibili anche in rete. ((Con le Linee guida)) sono definite le modalita' di attuazione del presente comma, anche in riferimento alle pubbliche amministrazioni e agli ordini professionali.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 28 c.4',
        'testo': "Il titolare, ovvero il terzo interessato se richiedente ai sensi del comma 3, comunica tempestivamente al certificatore il modificarsi o il venir meno delle circostanze oggetto delle informazioni di cui all'articolo.",
        'testo_integrale': 'Il titolare ((di firma elettronica)), ovvero il terzo interessato se richiedente ai sensi del comma 3, comunicano tempestivamente al certificatore il modificarsi o venir meno delle circostanze oggetto delle informazioni di cui al presente articolo.',
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}, {'categoria': 'Terza parte', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 28 c.4-bis',
        'testo': "Il certificatore ha l'obbligo di conservare le informazioni di cui ai commi 3 e 4 per almeno venti anni dalla scadenza del certificato di firma.",
        'testo_integrale': "((4-bis. Il certificatore ha l'obbligo di conservare le informazioni di cui ai commi 3 e 4 per almeno venti anni decorrenti dalla scadenza del certificato di firma.))",
        'tipo_obbligo': 'di conservazione',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
]

RIGHE_PRINCIPI: list[dict] = [
    {
        'riferimento': 'art. 17 c.1-bis',
        'testo': "Agenzie, Forze armate (compresa l'Arma dei carabinieri e il Corpo delle capitanerie di porto) e Corpi di polizia hanno facolta' di individuare propri uffici per i compiti di cui al comma 1, senza incremento del numero complessivo degli uffici gia' previsti.",
        'testo_integrale': "Per lo svolgimento dei compiti di cui al comma 1, le Agenzie, le Forze armate, compresa l'Arma dei carabinieri e il Corpo delle capitanerie di porto, nonche' i Corpi di polizia hanno facolta' di individuare propri uffici senza incrementare il numero complessivo di quelli gia' previsti nei rispettivi assetti organizzativi.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 17 c.1-septies',
        'testo': "I soggetti di cui al comma 1-sexies possono esercitare le funzioni per il digitale anche in forma associata, ferma la facolta' di avvalersi, mediante convenzioni e senza nuovi o maggiori oneri, del supporto di societa' in house.",
        'testo_integrale': "I soggetti di cui al comma 1-sexies possono esercitare le funzioni di cui al medesimo comma anche in forma associata. ((E' fatta salva la facolta' di avvalersi, mediante apposite convenzioni e senza nuovi o maggiori oneri a carico della finanza pubblica, del supporto di societa' in house.))",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18 c.4',
        'testo': "I soggetti di cui all'articolo 2, comma 2, lettera a), possono pubblicare sulla piattaforma i provvedimenti che intendono adottare, o gia' adottati se soggetti a modifiche periodiche, aventi ad oggetto l'attuazione dell'agenda digitale.",
        'testo_integrale': "Tutti i soggetti di cui all'articolo 2, comma 2, lettera a), possono pubblicare sulla piattaforma i provvedimenti che intendono adottare o, qualora si tratti di provvedimenti soggetti a modifiche e aggiornamenti periodici, gia' adottati, aventi ad oggetto l'attuazione dell'agenda digitale.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18-bis c.4',
        'testo': "Le violazioni accertate da AgID rilevano ai fini della misurazione e valutazione della performance individuale dei dirigenti responsabili e comportano responsabilita' dirigenziale e disciplinare ex artt. 21 e 55 d.lgs. 165/2001, fermo quanto previsto da altre disposizioni del Codice e dal d.l. 179/2012.",
        'testo_integrale': "Le violazioni accertate dall'AgID rilevano ai fini della misurazione e della valutazione della performance individuale dei dirigenti responsabili e comportano responsabilita' dirigenziale e disciplinare ai sensi degli articoli 21 e 55 del decreto legislativo 30 marzo 2001, n. 165. Resta fermo quanto previsto dagli articoli 13-bis, 50, 50-ter, 64-bis, comma 1-quinquies, del presente Codice e dall'articolo 33-septies del decreto-legge 18 ottobre 2012, n. 179, convertito, con modificazioni, dalla legge 17 dicembre 2012, n. 221.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18-bis c.8',
        'testo': "All'attuazione dell'articolo si provvede con le risorse umane, strumentali e finanziarie gia' previste a legislazione vigente (clausola di invarianza finanziaria).",
        'testo_integrale': "All'attuazione della presente disposizione si provvede con le risorse umane, strumentali e finanziarie gia' previste a legislazione vigente.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 18-bis c.8-bis',
        'testo': "Le disposizioni dell'articolo si applicano in tutti i casi in cui AgID esercita poteri sanzionatori attribuiti dalla legge.",
        'testo_integrale': "((8-bis. Le disposizioni del presente articolo trovano applicazione in tutti i casi in cui l'AgID esercita poteri sanzionatori attribuiti dalla legge))",
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 19',
        'testo': 'Articolo abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': '((ARTICOLO ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179))',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 20 c.1',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 20 c.1-bis',
        'testo': "Il documento informatico soddisfa il requisito della forma scritta e ha l'efficacia dell'articolo 2702 c.c. quando vi e' apposta firma digitale, altra firma elettronica qualificata o firma elettronica avanzata, oppure quando e' formato secondo un processo con identificazione informatica dell'autore conforme ai requisiti AgID; negli altri casi, l'idoneita' a soddisfare la forma scritta e il valore probatorio sono liberamente valutabili in giudizio. Data e ora di formazione sono opponibili ai terzi se apposte secondo le Linee guida.",
        'testo_integrale': "Il documento informatico soddisfa il requisito della forma scritta e ha l'efficacia prevista dall'articolo 2702 del Codice civile quando vi e' apposta una firma digitale, altro tipo di firma elettronica qualificata o una firma elettronica avanzata o, comunque, e' formato, previa identificazione informatica del suo autore, attraverso un processo avente i requisiti fissati dall'AgID ai sensi dell'articolo 71 con modalita' tali da garantire la sicurezza, integrita' e immodificabilita' del documento e, in maniera manifesta e inequivoca, la sua riconducibilita' all'autore. In tutti gli altri casi, l'idoneita' del documento informatico a soddisfare il requisito della forma scritta e il suo valore probatorio sono liberamente valutabili in giudizio, in relazione alle caratteristiche di sicurezza, integrita' e immodificabilita'. La data e l'ora di formazione del documento informatico sono opponibili ai terzi se apposte in conformita' alle Linee guida.",
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['documento elettronico', 'firma elettronica avanzata', 'firma elettronica qualificata'],
    },
    {
        'riferimento': 'art. 20 c.1-ter',
        'testo': "L'utilizzo del dispositivo di firma elettronica qualificata o digitale si presume riconducibile al titolare, salvo prova contraria.",
        'testo_integrale': "L'utilizzo del dispositivo di firma elettronica qualificata o digitale si presume riconducibile al titolare di firma elettronica, salvo che questi dia prova contraria.",
        'tipo_principio': 'presunzione legale',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica qualificata', 'dispositivo qualificato di creazione di firma elettronica'],
    },
    {
        'riferimento': 'art. 20 c.1-quater',
        'testo': 'Restano ferme le disposizioni sul deposito telematico di atti e documenti secondo la normativa sul processo telematico.',
        'testo_integrale': 'Restano ferme le disposizioni concernenti il deposito degli atti e dei documenti in via telematica secondo la normativa, anche regolamentare, in materia di processo telematico.',
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 20 c.2',
        'testo': 'Comma abrogato dal D.Lgs. 30 dicembre 2010, n. 235.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 30 DICEMBRE 2010, N. 235.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 20 c.5',
        'testo': 'Restano ferme le disposizioni di legge in materia di protezione dei dati personali.',
        'testo_integrale': 'Restano ferme le disposizioni di legge in materia di protezione dei dati personali.',
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 20 c.5-bis',
        'testo': 'Gli obblighi di conservazione ed esibizione di documenti previsti dalla legge si intendono soddisfatti a mezzo di documenti informatici, se le procedure utilizzate sono conformi alle Linee guida.',
        'testo_integrale': 'Gli obblighi di conservazione e di esibizione di documenti previsti dalla legislazione vigente si intendono soddisfatti a tutti gli effetti di legge a mezzo di documenti informatici, se le procedure utilizzate sono conformi alle ((Linee guida)).',
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 21 c.1',
        'testo': 'Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.',
        'testo_integrale': '((COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217)).',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 21 c.2',
        'testo': 'Comma abrogato dal D.Lgs. 13 dicembre 2017, n. 217.',
        'testo_integrale': '((COMMA ABROGATO DAL D.LGS. 13 DICEMBRE 2017, N. 217)).',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 21 c.3',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 21 c.4',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 22 c.1',
        'testo': "I documenti informatici contenenti copia di atti pubblici, scritture private e documenti in genere, formati in origine su supporto analogico e spediti o rilasciati da depositari pubblici o pubblici ufficiali, hanno piena efficacia ex artt. 2714-2715 c.c. se formati ai sensi dell'articolo 20, comma 1-bis, primo periodo; la loro esibizione e produzione sostituisce quella dell'originale.",
        'testo_integrale': "I documenti informatici contenenti copia di atti pubblici, scritture private e documenti in genere, compresi gli atti e documenti amministrativi di ogni tipo formati in origine su supporto analogico, spediti o rilasciati dai depositari pubblici autorizzati e dai pubblici ufficiali, hanno piena efficacia, ai sensi degli articoli 2714 e 2715 del codice civile, se sono formati ai sensi dell'articolo 20, comma 1-bis, primo periodo. La loro esibizione e produzione sostituisce quella dell'originale.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'oggetti_giuridici': ['documento elettronico'],
    },
    {
        'riferimento': 'art. 22 c.2',
        'testo': "Le copie per immagine su supporto informatico di documenti analogici originali hanno la stessa efficacia probatoria degli originali se la conformita' e' attestata da un notaio o altro pubblico ufficiale autorizzato, secondo le Linee guida.",
        'testo_integrale': "Le copie per immagine su supporto informatico di documenti originali formati in origine su supporto analogico hanno la stessa efficacia probatoria degli originali da cui sono estratte, se la loro conformita' e' attestata da un notaio o da altro pubblico ufficiale a cio' autorizzato, secondo le Linee guida.",
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
        'condizione_applicabilita': "conformita' attestata da notaio o altro pubblico ufficiale autorizzato",
    },
    {
        'riferimento': 'art. 22 c.3',
        'testo': "Le copie per immagine su supporto informatico di documenti analogici originali, formate nel rispetto delle Linee guida, hanno la stessa efficacia probatoria degli originali se la conformita' non e' espressamente disconosciuta.",
        'testo_integrale': "Le copie per immagine su supporto informatico di documenti originali formati in origine su supporto analogico nel rispetto delle Linee guida hanno la stessa efficacia probatoria degli originali da cui sono tratte se la loro conformita' all'originale non e' espressamente disconosciuta.",
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
        'condizione_applicabilita': "conformita' non espressamente disconosciuta",
    },
    {
        'riferimento': 'art. 22 c.4',
        'testo': 'Le copie formate ai sensi dei commi 1, 1-bis, 2 e 3 sostituiscono ad ogni effetto di legge gli originali analogici e sono idonee ad assolvere gli obblighi di conservazione, salvo quanto previsto dal comma 5.',
        'testo_integrale': 'Le copie formate ai sensi dei commi 1, 1-bis, 2 e 3 sostituiscono ad ogni effetto di legge gli originali formati in origine su supporto analogico, e sono idonee ad assolvere gli obblighi di conservazione previsti dalla legge, salvo quanto stabilito dal comma 5.',
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 22 c.4-bis',
        'testo': "Le copie per immagine di atti e documenti analogici originali, depositati in procedimenti giudiziari civili definiti da almeno un anno con provvedimento non piu' impugnabile, sono idonee ad assolvere gli obblighi di conservazione se il cancelliere vi appone la firma digitale, ne attesta la conformita' e le inserisce nel fascicolo informatico secondo la normativa sul processo civile telematico; in tal caso gli originali analogici possono essere distrutti secondo le modalita' previste con decreto del Ministro della giustizia, sentiti il Garante privacy e l'Agenzia per l'Italia digitale.",
        'testo_integrale': "Le copie per immagine su supporto informatico di atti e documenti originali formati in origine su supporto analogico, depositati in procedimenti giudiziari civili definiti con provvedimento decisorio non piu' soggetto a impugnazione da almeno un anno, sono idonee ad ((assolvere agli obblighi)) di conservazione previsti dalla legge se il cancelliere vi appone la firma digitale, ne attesta la conformita' all'originale e le inserisce nel fascicolo informatico nel rispetto della normativa anche regolamentare concernente il processo civile telematico. In tali casi, si puo' procedere alla distruzione degli originali analogici, secondo le modalita' previste con decreto del Ministro della giustizia, sentiti il Garante per la protezione dei dati personali e l'Agenzia per l'Italia digitale.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'condizione_applicabilita': "il cancelliere appone la firma digitale, attesta la conformita' e inserisce la copia nel fascicolo informatico",
    },
    {
        'riferimento': 'art. 22 c.6',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 23 c.1',
        'testo': "Le copie su supporto analogico di documento informatico, anche sottoscritto con firma elettronica avanzata, qualificata o digitale, hanno la stessa efficacia probatoria dell'originale se la conformita' in tutte le sue componenti e' attestata da un pubblico ufficiale autorizzato.",
        'testo_integrale': "Le copie su supporto analogico di documento informatico, anche sottoscritto con firma elettronica avanzata, qualificata o digitale, hanno la stessa efficacia probatoria dell'originale da cui sono tratte se la loro conformita' all'originale in tutte le sue componenti e' attestata da un pubblico ufficiale a cio' autorizzato.",
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
        'condizione_applicabilita': "conformita' attestata da un pubblico ufficiale autorizzato",
    },
    {
        'riferimento': 'art. 23 c.2',
        'testo': "Le copie e gli estratti su supporto analogico del documento informatico, conformi alle vigenti regole tecniche, hanno la stessa efficacia probatoria dell'originale se la conformita' non e' espressamente disconosciuta; resta fermo, ove previsto, l'obbligo di conservazione dell'originale informatico.",
        'testo_integrale': "Le copie e gli estratti su supporto analogico del documento informatico, conformi alle vigenti regole tecniche, hanno la stessa efficacia probatoria dell'originale se la loto conformita' non e' espressamente disconosciuta. Resta fermo, ove previsto l'obbligo di conservazione dell'originale informatico.",
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
        'condizione_applicabilita': "conformita' non espressamente disconosciuta",
    },
    {
        'riferimento': 'art. 23-bis c.1',
        'testo': "I duplicati informatici hanno il medesimo valore giuridico, ad ogni effetto di legge, del documento informatico da cui sono tratti, se prodotti in conformita' alle Linee guida.",
        'testo_integrale': "I duplicati informatici hanno il medesimo valore giuridico, ad ogni effetto di legge, del documento informatico da cui sono tratti, se prodotti in conformita' alle ((Linee guida)).",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'oggetti_giuridici': ['documento elettronico'],
    },
    {
        'riferimento': 'art. 23-bis c.2',
        'testo': "Le copie e gli estratti informatici del documento informatico, se prodotti secondo le vigenti Linee guida, hanno la stessa efficacia probatoria dell'originale se la conformita' e' attestata da un pubblico ufficiale autorizzato o non e' espressamente disconosciuta; resta fermo, ove previsto, l'obbligo di conservazione dell'originale informatico.",
        'testo_integrale': "Le copie e gli estratti informatici del documento informatico, se prodotti in conformita' alle vigenti ((Linee guida)), hanno la stessa efficacia probatoria dell'originale da cui sono tratte se la loro conformita' all'originale, in tutti le sue componenti, e' attestata da un pubblico ufficiale a cio' autorizzato o se la conformita' non e' espressamente disconosciuta. Resta fermo, ove previsto, l'obbligo di conservazione dell'originale informatico.",
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 23-ter c.1',
        'testo': "Gli atti formati dalle pubbliche amministrazioni con strumenti informatici, nonche' i dati e i documenti informatici da esse detenuti, costituiscono informazione primaria ed originale da cui e' possibile effettuare duplicazioni e copie, su supporto identico o diverso, per gli usi consentiti dalla legge.",
        'testo_integrale': "Gli atti formati dalle pubbliche amministrazioni con strumenti informatici, nonche' i dati e i documenti informatici detenuti dalle stesse, costituiscono informazione primaria ed originale da cui e' possibile effettuare, su diversi o identici tipi di supporto, duplicazioni e copie per gli usi consentiti dalla legge.",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 23-ter c.2',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 23-ter c.3',
        'testo': "Le copie su supporto informatico di documenti formati dalla PA in origine su supporto analogico, o da essa detenuti, hanno il medesimo valore giuridico degli originali se la conformita' e' assicurata dal funzionario delegato mediante firma digitale o altra firma elettronica qualificata, nel rispetto delle Linee guida; in tal caso l'obbligo di conservazione dell'originale e' soddisfatto con la conservazione della copia informatica.",
        'testo_integrale': "Le copie su supporto informatico di documenti formati dalla pubblica amministrazione in origine su supporto analogico ovvero da essa detenuti, hanno il medesimo valore giuridico, ad ogni effetto di legge, degli originali da cui sono tratte, se la loro conformita' all'originale e' assicurata dal funzionario a cio' delegato nell'ambito dell'ordinamento proprio dell'amministrazione di appartenenza, mediante l'utilizzo della firma digitale o di altra firma elettronica qualificata e nel rispetto delle ((Linee guida)); in tale caso l'obbligo di conservazione dell'originale del documento e' soddisfatto con la conservazione della copia su supporto informatico.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'condizione_applicabilita': "conformita' assicurata dal funzionario delegato con firma digitale o firma elettronica qualificata, secondo le Linee guida",
    },
    {
        'riferimento': 'art. 23-ter c.5',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 23-ter c.6',
        'testo': "Per quanto non previsto dall'articolo si applicano gli articoli 21, 22, 23 e 23-bis.",
        'testo_integrale': 'Per quanto non previsto dal presente articolo si applicano gli articoli 21, 22 , 23 e 23-bis.',
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 23-quater c.1',
        'testo': 'L\'articolo 2712 del codice civile e\' modificato inserendo, dopo le parole "riproduzioni fotografiche", la parola ", informatiche", estendendo cosi\' alle riproduzioni informatiche il regime di efficacia probatoria gia\' previsto per le riproduzioni meccaniche.',
        'testo_integrale': 'All\'articolo 2712 del codice civile dopo le parole: "riproduzioni fotografiche" e\' inserita la seguente: ", informatiche".',
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 24 c.2',
        'testo': "L'apposizione di firma digitale integra e sostituisce l'apposizione di sigilli, punzoni, timbri, contrassegni e marchi di qualsiasi genere, ad ogni fine previsto dalla normativa vigente.",
        'testo_integrale': "L'apposizione di firma digitale integra e sostituisce l'apposizione di sigilli, punzoni, timbri, contrassegni e marchi di qualsiasi genere ad ogni fine previsto dalla normativa vigente.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica qualificata'],
    },
    {
        'riferimento': 'art. 24 c.4-bis',
        'testo': "L'apposizione di firma digitale o di altra firma elettronica qualificata basata su certificato revocato, scaduto o sospeso equivale a mancata sottoscrizione, salvo annullamento dello stato di sospensione; revoca e sospensione hanno effetto dal momento della pubblicazione, salvo che il revocante o richiedente dimostri che tutte le parti interessate ne erano gia' a conoscenza.",
        'testo_integrale': "L'apposizione a un documento informatico di una firma digitale o di un altro tipo di firma elettronica qualificata basata su un certificato elettronico revocato, scaduto o sospeso equivale a mancata sottoscrizione, salvo che lo stato di sospensione sia stato annullato. La revoca o la sospensione, comunque motivate, hanno effetto dal momento della pubblicazione, salvo che il revocante, o chi richiede la sospensione, non dimostri che essa era gia' a conoscenza di tutte le parti interessate.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica qualificata'],
    },
    {
        'riferimento': 'art. 24 c.4-ter',
        'testo': "Le disposizioni dell'articolo si applicano anche se la firma elettronica e' basata su un certificato qualificato rilasciato da un certificatore extra-UE, quando: il certificatore possiede i requisiti eIDAS ed e' qualificato in uno Stato membro; oppure il certificato e' garantito da un certificatore UE con i medesimi requisiti; oppure il certificato o il certificatore e' riconosciuto in forza di accordo bilaterale o multilaterale UE-Paesi terzi/organizzazioni internazionali.",
        'testo_integrale': "Le disposizioni del presente articolo si applicano anche se la firma elettronica e' basata su un certificato qualificato rilasciato da un certificatore stabilito in uno Stato non facente parte dell'Unione europea, quando ricorre una delle seguenti condizioni:\na) il certificatore possiede i requisiti previsti dal regolamento eIDAS ed e' qualificato in uno Stato membro;\nb) il certificato qualificato e' garantito da un certificatore stabilito nella Unione europea, in possesso dei requisiti di cui al medesimo regolamento;\nc) il certificato qualificato, o il certificatore, e' riconosciuto in forza di un accordo bilaterale o multilaterale tra l'Unione europea e Paesi terzi o organizzazioni internazionali.",
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 25 c.1',
        'testo': "Si ha per riconosciuta, ai sensi dell'articolo 2703 c.c., la firma elettronica o qualsiasi altro tipo di firma elettronica avanzata autenticata dal notaio o da altro pubblico ufficiale autorizzato.",
        'testo_integrale': "Si ha per riconosciuta, ai sensi dell'articolo 2703 del codice civile, la firma elettronica o qualsiasi altro tipo di firma ((elettronica))avanzata autenticata dal notaio o da altro pubblico ufficiale a cio' autorizzato.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 25 c.3',
        'testo': "L'apposizione della firma digitale da parte del pubblico ufficiale ha l'efficacia di cui all'articolo 24, comma 2 (sostituzione di sigilli, punzoni, timbri, contrassegni e marchi).",
        'testo_integrale': "L'apposizione della firma digitale da parte del pubblico ufficiale ha l'efficacia di cui all'articolo 24, comma 2.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 25 c.4',
        'testo': "Se al documento informatico autenticato deve essere allegato altro documento formato in originale su altro supporto, il pubblico ufficiale puo' allegare copia informatica autenticata dell'originale, secondo le disposizioni dell'articolo 23.",
        'testo_integrale': "Se al documento informatico autenticato deve essere allegato altro documento formato in originale su altro tipo di supporto, il pubblico ufficiale puo' allegare copia informatica autenticata dell'originale, secondo le disposizioni dell'articolo 23((...)).",
        'tipo_principio': 'altro',
        'stato': 'vigente',
    },
    {
        'riferimento': 'art. 26',
        'testo': 'Articolo abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': '((ARTICOLO ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179))',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 27',
        'testo': 'Articolo abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': '((ARTICOLO ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179))',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 28 c.1',
        'testo': 'Comma abrogato dal D.Lgs. 26 agosto 2016, n. 179.',
        'testo_integrale': 'COMMA ABROGATO DAL D.LGS. 26 AGOSTO 2016, N. 179.',
        'tipo_principio': 'altro',
        'stato': 'abrogato',
    },
    {
        'riferimento': 'art. 28 c.2',
        'testo': "In aggiunta alle informazioni previste dal Regolamento eIDAS, nel certificato di firma elettronica qualificata puo' essere inserito il codice fiscale; per i titolari residenti all'estero privi di codice fiscale, puo' indicarsi il codice fiscale estero o, in mancanza, un analogo codice identificativo univoco.",
        'testo_integrale': "In aggiunta alle informazioni previste nel Regolamento eIDAS ((...)) nel certificato di firma elettronica qualificata puo' essere inserito il codice fiscale. Per i titolari residenti all'estero cui non risulti attribuito il codice fiscale, si puo' indicare il codice fiscale rilasciato dall'autorita' fiscale del Paese di residenza o, in mancanza, un analogo codice identificativo univoco ((...)).",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['certificato qualificato di firma elettronica'],
    },
    {
        'riferimento': 'art. 28 c.3',
        'testo': "Il certificato di firma elettronica qualificata puo' contenere, ove richiesto dal titolare o dal terzo interessato e se pertinenti e non eccedenti: le qualifiche specifiche del titolare (ordini/collegi professionali, qualifica di pubblico ufficiale, albi, altre abilitazioni, poteri di rappresentanza); i limiti d'uso del certificato, inclusi quelli derivanti da tali qualifiche/poteri; i limiti del valore degli atti unilaterali e dei contratti per cui il certificato puo' essere usato; uno pseudonimo qualificato come tale.",
        'testo_integrale': "Il certificato di firma elettronica qualificata puo' contenere, ove richiesto dal titolare ((di firma elettronica)) o dal terzo interessato, le seguenti informazioni, se pertinenti e non eccedenti rispetto allo scopo per il quale il certificato e' richiesto:\na) le qualifiche specifiche del titolare ((di firma elettronica)), quali l'appartenenza ad ordini o collegi professionali, la qualifica di pubblico ufficiale, l'iscrizione ad albi o il possesso di altre abilitazioni professionali, nonche' poteri di rappresentanza;\nb) i limiti d'uso del certificato, inclusi quelli derivanti dalla titolarita' delle qualifiche e dai poteri di rappresentanza di cui alla lettera a) ai sensi dell'articolo 30, comma 3.\nc) limiti del valore degli atti unilaterali e dei contratti per i quali il certificato puo' essere usato, ove applicabili.\nc-bis) uno pseudonimo, qualificato come tale.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['certificato qualificato di firma elettronica'],
    },
]

INDICE_ARTICOLI_LOCALE: list[str] = [
    'art. 16 c.1',
    'art. 16 c.2',
    'art. 17 c.1',
    'art. 17 c.1-bis',
    'art. 17 c.1-ter',
    'art. 17 c.1-quater',
    'art. 17 c.1-quinquies',
    'art. 17 c.1-sexies',
    'art. 17 c.1-septies',
    'art. 18 c.1',
    'art. 18 c.2',
    'art. 18 c.3',
    'art. 18 c.4',
    'art. 18 c.5',
    'art. 18-bis c.1',
    'art. 18-bis c.2',
    'art. 18-bis c.3',
    'art. 18-bis c.4',
    'art. 18-bis c.5',
    'art. 18-bis c.6',
    'art. 18-bis c.7',
    'art. 18-bis c.8',
    'art. 18-bis c.8-bis',
    'art. 19',
    'art. 20 c.1',
    'art. 20 c.1-bis',
    'art. 20 c.1-ter',
    'art. 20 c.1-quater',
    'art. 20 c.2',
    'art. 20 c.3',
    'art. 20 c.4',
    'art. 20 c.5',
    'art. 20 c.5-bis',
    'art. 21 c.1',
    'art. 21 c.2',
    'art. 21 c.2-bis',
    'art. 21 c.2-ter',
    'art. 21 c.3',
    'art. 21 c.4',
    'art. 21 c.5',
    'art. 22 c.1',
    'art. 22 c.1-bis',
    'art. 22 c.2',
    'art. 22 c.3',
    'art. 22 c.4',
    'art. 22 c.4-bis',
    'art. 22 c.5',
    'art. 22 c.6',
    'art. 23 c.1',
    'art. 23 c.2',
    'art. 23 c.2-bis',
    'art. 23-bis c.1',
    'art. 23-bis c.2',
    'art. 23-ter c.1',
    'art. 23-ter c.1-bis',
    'art. 23-ter c.2',
    'art. 23-ter c.3',
    'art. 23-ter c.4',
    'art. 23-ter c.5',
    'art. 23-ter c.5-bis',
    'art. 23-ter c.6',
    'art. 23-quater c.1',
    'art. 24 c.1',
    'art. 24 c.2',
    'art. 24 c.3',
    'art. 24 c.4',
    'art. 24 c.4-bis',
    'art. 24 c.4-ter',
    'art. 25 c.1',
    'art. 25 c.2',
    'art. 25 c.3',
    'art. 25 c.4',
    'art. 26',
    'art. 27',
    'art. 28 c.1',
    'art. 28 c.2',
    'art. 28 c.3',
    'art. 28 c.3-bis',
    'art. 28 c.4',
    'art. 28 c.4-bis',
]

MAPPATURA_LOCALE: dict[str, list[str]] = {
    'art. 16 c.1': ['art. 16 c.1'],
    'art. 16 c.2': ['art. 16 c.2'],
    'art. 17 c.1': ['art. 17 c.1'],
    'art. 17 c.1-bis': ['art. 17 c.1-bis'],
    'art. 17 c.1-ter': ['art. 17 c.1-ter'],
    'art. 17 c.1-quater': ['art. 17 c.1-quater'],
    'art. 17 c.1-quinquies': ['art. 17 c.1-quinquies'],
    'art. 17 c.1-sexies': ['art. 17 c.1-sexies'],
    'art. 17 c.1-septies': ['art. 17 c.1-septies'],
    'art. 18 c.1': ['art. 18 c.1'],
    'art. 18 c.2': ['art. 18 c.2'],
    'art. 18 c.3': ['art. 18 c.3'],
    'art. 18 c.4': ['art. 18 c.4'],
    'art. 18 c.5': ['art. 18 c.5'],
    'art. 18-bis c.1': ['art. 18-bis c.1'],
    'art. 18-bis c.2': ['art. 18-bis c.2'],
    'art. 18-bis c.3': ['art. 18-bis c.3'],
    'art. 18-bis c.4': ['art. 18-bis c.4'],
    'art. 18-bis c.5': ['art. 18-bis c.5'],
    'art. 18-bis c.6': ['art. 18-bis c.6'],
    'art. 18-bis c.7': ['art. 18-bis c.7'],
    'art. 18-bis c.8': ['art. 18-bis c.8'],
    'art. 18-bis c.8-bis': ['art. 18-bis c.8-bis'],
    'art. 19': ['art. 19'],
    'art. 20 c.1': ['art. 20 c.1'],
    'art. 20 c.1-bis': ['art. 20 c.1-bis'],
    'art. 20 c.1-ter': ['art. 20 c.1-ter'],
    'art. 20 c.1-quater': ['art. 20 c.1-quater'],
    'art. 20 c.2': ['art. 20 c.2'],
    'art. 20 c.3': ['art. 20 c.3'],
    'art. 20 c.4': ['art. 20 c.4'],
    'art. 20 c.5': ['art. 20 c.5'],
    'art. 20 c.5-bis': ['art. 20 c.5-bis'],
    'art. 21 c.1': ['art. 21 c.1'],
    'art. 21 c.2': ['art. 21 c.2'],
    'art. 21 c.2-bis': ['art. 21 c.2-bis'],
    'art. 21 c.2-ter': ['art. 21 c.2-ter'],
    'art. 21 c.3': ['art. 21 c.3'],
    'art. 21 c.4': ['art. 21 c.4'],
    'art. 21 c.5': ['art. 21 c.5'],
    'art. 22 c.1': ['art. 22 c.1'],
    'art. 22 c.1-bis': ['art. 22 c.1-bis'],
    'art. 22 c.2': ['art. 22 c.2'],
    'art. 22 c.3': ['art. 22 c.3'],
    'art. 22 c.4': ['art. 22 c.4'],
    'art. 22 c.4-bis': ['art. 22 c.4-bis'],
    'art. 22 c.5': ['art. 22 c.5'],
    'art. 22 c.6': ['art. 22 c.6'],
    'art. 23 c.1': ['art. 23 c.1'],
    'art. 23 c.2': ['art. 23 c.2'],
    'art. 23 c.2-bis': ['art. 23 c.2-bis'],
    'art. 23-bis c.1': ['art. 23-bis c.1'],
    'art. 23-bis c.2': ['art. 23-bis c.2'],
    'art. 23-ter c.1': ['art. 23-ter c.1'],
    'art. 23-ter c.1-bis': ['art. 23-ter c.1-bis'],
    'art. 23-ter c.2': ['art. 23-ter c.2'],
    'art. 23-ter c.3': ['art. 23-ter c.3'],
    'art. 23-ter c.4': ['art. 23-ter c.4'],
    'art. 23-ter c.5': ['art. 23-ter c.5'],
    'art. 23-ter c.5-bis': ['art. 23-ter c.5-bis'],
    'art. 23-ter c.6': ['art. 23-ter c.6'],
    'art. 23-quater c.1': ['art. 23-quater c.1'],
    'art. 24 c.1': ['art. 24 c.1'],
    'art. 24 c.2': ['art. 24 c.2'],
    'art. 24 c.3': ['art. 24 c.3'],
    'art. 24 c.4': ['art. 24 c.4'],
    'art. 24 c.4-bis': ['art. 24 c.4-bis'],
    'art. 24 c.4-ter': ['art. 24 c.4-ter'],
    'art. 25 c.1': ['art. 25 c.1'],
    'art. 25 c.2': ['art. 25 c.2'],
    'art. 25 c.3': ['art. 25 c.3'],
    'art. 25 c.4': ['art. 25 c.4'],
    'art. 26': ['art. 26'],
    'art. 27': ['art. 27'],
    'art. 28 c.1': ['art. 28 c.1'],
    'art. 28 c.2': ['art. 28 c.2'],
    'art. 28 c.3': ['art. 28 c.3'],
    'art. 28 c.3-bis': ['art. 28 c.3-bis'],
    'art. 28 c.4': ['art. 28 c.4'],
    'art. 28 c.4-bis': ['art. 28 c.4-bis'],
}

RELAZIONI: list[dict] = [
    {
        'nodo_da': ('principio', None, 'art. 22 c.4-bis'),
        'nodo_a': ('obbligo', None, 'art. 22 c.5'),
        'tipo_relazione': 'deroga a',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 22 c.1'),
        'nodo_a': ('principio', None, 'art. 20 c.1-bis'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 21 c.2-bis'),
        'nodo_a': ('principio', None, 'art. 20 c.1-bis'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 25 c.3'),
        'nodo_a': ('principio', None, 'art. 24 c.2'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 25 c.4'),
        'nodo_a': ('principio', None, 'art. 23 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 23-ter c.6'),
        'nodo_a': ('obbligo', None, 'art. 21 c.2-bis'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 23-ter c.6'),
        'nodo_a': ('principio', None, 'art. 22 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 23-ter c.6'),
        'nodo_a': ('principio', None, 'art. 23 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('principio', None, 'art. 23-ter c.6'),
        'nodo_a': ('principio', None, 'art. 23-bis c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 17 c.1-quater'),
        'nodo_a': ('obbligo', None, 'art. 18-bis c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 17 c.1'),
        'nodo_a': ('obbligo', None, 'art. 16 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': None,
    },
]
