"""Relazioni cross-fonte ETSI EN 319 411-2 (fonte_id=18) verso tutte le altre
fonti gia' censite nel grafo (2026-09-23, ADR-0009 - fase 6 obbligatoria).

Modulo "capitolo virtuale" (nessuna riga obbligo/principio propria, solo
RELAZIONI) agganciato in coda alla lista capitoli di ETSI EN 319 411-2
(fonte_id=18) passata a inserisci_capitoli, DOPO che sia questa fonte sia
ETSI EN 319 411-1 (fonte_id=17) sono gia' presenti nel registro simbolico.
Stessa pipeline a 3 stadi del modulo gemello
app/seed_data/etsi_319_411_1/cap06_relazioni_cross.py (vedi quel docstring
per il dettaglio completo della metodologia).

1. KNN sui 173 nodi di questa fonte verso le altre 17 fonti -> 1.506 coppie
   con score >= 0.80, ridotto a top-3 per nodo con soglia >= 0.90 ->
   263 coppie shortlist.
2. Classificazione LLM: 22 chiamate completion() in parallelo con wait()
   (batch da 12 coppie), stesso prompt/tassonomia del modulo gemello.
3. Validazione: confidence >= 0.5, anti-allucinazione per costruzione
   (id risolti da Neo4j), dedup su (nodo_da, nodo_a).

Esito per fonte 18: 128 relazioni cross-fonte (si sovrappone a: 101, richiama: 18, specifica: 5, si applica a: 3, richiede come precondizione: 1).
Per fonte target: ETSI EN 319 411-1 (55): 1, ETSI TS 119 431-1 (49): 1, ETSI EN 319 412-5 (12): 1, Regole Tecniche AgID certificati qualificati 13/2/2020 (3): 1, eIDAS2 (3): 1, Reg. (UE) 2025/1566 (1): 1, ETSI TS 119 461 (3): 1, ETSI EN 319 401 (2): 1.
Zero verso: eIDAS, CAD, DPCM 22/2/2013, SPID (DPCM 24/10/2014), DPCM 19/10/2021, ETSI TS 119 431-2, Reg. AgID modalita' attuative SPID, Reg. (UE) 2015/1502, Codice Civile (nessun candidato KNN
sopra soglia con confidence sufficiente dopo classificazione). Coerente con
l'attesa: la quasi totalita' dei nodi di questa fonte cita testualmente
clausole omologhe di ETSI EN 319 411-1 (fonte_id=17, 55 relazioni verso
quella fonte) e degli standard ETSI su cui e' costruita (TS 119 461,
EN 319 401, TS 119 431-1, EN 319 412-5), non delle fonti nazionali/UE
sull'identificazione elettronica che non condividono lo stesso perimetro
tematico (certificati qualificati vs. mezzi di identificazione).
"""

RIGHE_OBBLIGHI: list[dict] = []
RIGHE_PRINCIPI: list[dict] = []
INDICE_ARTICOLI_LOCALE: list[str] = []
MAPPATURA_LOCALE: dict[str, list[str]] = {}

RELAZIONI = [
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 2.1 (Normative references)'),
        "nodo_a": ('principio', 17, 'Parte 1: Annex B (Conformity assessment checklist)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 2.1 (Normative references)'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-5.1-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 2.1 (Normative references)'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 2.1 (Normative references)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 3.1 (Terms)'),
        "nodo_a": ('principio', 7, 'Parte 5: Annex A.1 (mapping con Allegato I Reg. 910/2014)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 3.3 (Abbreviations)'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 3 (definizioni, simboli, abbreviazioni, notazioni)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 4.1 (General policy requirements concepts)'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 4.1'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 4.2.1 (Certification Practice Statement)'),
        "nodo_a": ('obbligo', 15, 'par. 4.1 punto 1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 4.2.2, policy 3) (QCP-n-qscd)'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 3 (definizioni, simboli, abbreviazioni, notazioni)'),
        "tipo_relazione": 'richiede come precondizione',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 4.2.2, policy 6) (QNCP-w)'),
        "nodo_a": ('principio', 2, 'art. 12-bis §3'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 4.2.3 (Terms and conditions and PKI disclosure statement)'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 4.3.2 (significato)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 4.2.3 (Terms and conditions and PKI disclosure statement)'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 4.3.4 (significato)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 4.2.3 (Terms and conditions and PKI disclosure statement)'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.3.4-06'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.1 (premessa)'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-5.2-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.1 (premessa)'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-5.2-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.3 (identificatori delle policy)'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 5.3'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.4.1 (premessa)'),
        "nodo_a": ('obbligo', 15, 'par. 4.1 punto 1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.4.2'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.9.4-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.4.2'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.5.1-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.4.2'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.4.4-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.5.1'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 3 (definizioni, simboli, abbreviazioni, notazioni)'),
        "tipo_relazione": 'si applica a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 5.5.7'),
        "nodo_a": ('principio', 2, 'art. 12-bis §3'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.2.1'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.9.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.2.1'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.2.1'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.4.2-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.3.11'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.3.11'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.4.7'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.4.7 (Key changeover)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.4.7'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.4.7'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.7'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.7'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.95,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.7'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.6 (Compliance audit and other assessment)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.1'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.1 (Fees)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.95,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.1'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.8.1'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.3'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.3 (Confidentiality of business information)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.5'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.5 (Intellectual property rights)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.5'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.8.5'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.7'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.8.7'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.7'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.9.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.7'),
        "nodo_a": ('principio', 8, 'allegato, punto 1 (riferimenti normativi)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.8'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.8.8'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.8'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.8 (Limitations of liability)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.10'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.3.11'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.12'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.12 (Amendments)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.12'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.8.12'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.14'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.8.14'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.14'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.14 (Governing law)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.16'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.8.9'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.16'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 6.7.9 (Indemnities)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: clausola 6.8.16'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 6.8.16'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: Annex A (Table A.1)'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-A.3-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: Annex A (Table A.1)'),
        "nodo_a": ('principio', 11, 'Parte 1: B.2'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: Annex A (Table A.1)'),
        "nodo_a": ('principio', 7, 'Parte 5: Annex A.1 (mapping con Allegato I Reg. 910/2014)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: Annex B'),
        "nodo_a": ('principio', 17, 'Parte 1: Annex B (Conformity assessment checklist)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: Annex B'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-5.2-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('principio', None, 'Parte 2: Annex B'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.9-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.1-01'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.5.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.1-09'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-5.2-07B'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.2-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.2-01'),
        "nodo_a": ('principio', 7, 'Parte 5: Annex A.1 (mapping con Allegato I Reg. 910/2014)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.5.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.9-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.4.1-01'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-5.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.4.1-01'),
        "nodo_a": ('principio', 11, 'Parte 1: clausola 1 (Scope)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-5.4.1-01'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 1 (Scope)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REV-6.2.4-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.1-01'),
        "nodo_a": ('principio', 9, 'clausola 4.3 (Identity proofing context)'),
        "tipo_relazione": 'si applica a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.1-01'),
        "nodo_a": ('principio', 9, 'clausola 4.6 (Identity proofing service policy)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.2-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: GEN-6.3.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: GEN-6.3.3-01'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: GEN-6.3.3-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: GEN-6.3.3-02'),
        "nodo_a": ('obbligo', 17, 'Parte 1: GEN-6.3.3-12'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: GEN-6.3.3-02'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-7.1-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.3.4-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.3.4-02'),
        "nodo_a": ('principio', 2, 'art. 51 §1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.3.5-07'),
        "nodo_a": ('obbligo', 11, 'Parte 1: SIG-A.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.3.5-08'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.3.5-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.6-04'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.7-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.6-04'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.6-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.6-05'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.7-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.6-05'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.6-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.7-03'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.7-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.7-03'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.6-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.7-04'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.7-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.7-04'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.6-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.8-04'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.7-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.8-04'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.6-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.8-05'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.7-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: REG-6.3.8-05'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.6-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: CSS-6.3.10-02A'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REV-6.3.9-16'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: CSS-6.3.10-02B'),
        "nodo_a": ('principio', 17, 'Parte 1: GEN-6.6.1-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: CSS-6.3.10-05'),
        "nodo_a": ('obbligo', 15, 'par. 4.4 §2'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: CSS-6.3.10-12'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REV-6.2.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.4.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.4.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.4.1-01'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.4.4-01'),
        "nodo_a": ('principio', 9, 'COL-8.2.8-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.4.5-03'),
        "nodo_a": ('obbligo', 10, 'REQ-7.10-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.4.5-03'),
        "nodo_a": ('obbligo', 10, 'REQ-7.10-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.4.5-03'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.4.5-11'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-A.3-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: GEN-A.4-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: SIG-A.5-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-04'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 4.2.2'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-04'),
        "nodo_a": ('obbligo', 17, 'Parte 1: REG-6.3.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-04'),
        "nodo_a": ('obbligo', 11, 'Parte 1: SIG-A.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-05'),
        "nodo_a": ('obbligo', 11, 'Parte 1: SIG-A.5-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-05'),
        "nodo_a": ('obbligo', 11, 'Parte 1: GEN-A.4-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-07A'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-A.3-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: SDP-6.5.1-07B'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-A.3-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: GEN-6.6.1-03'),
        "nodo_a": ('principio', 7, 'Parte 5: QCS-4.3.5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: GEN-6.6.1-03'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 1 (Scope)'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: GEN-6.6.1-03'),
        "nodo_a": ('obbligo', 11, 'Parte 1: SIG-A.5-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.9.4-03'),
        "nodo_a": ('obbligo', 17, 'Parte 1: OVR-6.3.4-06'),
        "tipo_relazione": 'si applica a',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.9.4-04'),
        "nodo_a": ('principio', 7, 'Parte 5: clausola 4.3.2 (significato)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-6.9.4-04'),
        "nodo_a": ('principio', 17, 'Parte 1: clausola 4.2.3'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-7.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-7.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.5.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-7.1-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.8-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-7.1-02'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-7-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-7.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.4.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-7.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.8.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ('obbligo', None, 'Parte 2: OVR-7.2-01'),
        "nodo_a": ('obbligo', 11, 'Parte 1: OVR-6.5.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
]
