"""ETSI EN 319 421 V1.3.1 (2025-07) (fonte_id=18) - capitolo virtuale di
collegamento cross-fonte (ADR-0009), Fase 6 obbligatoria.

Pipeline eseguita nella sessione principale (mai a subagent), 2026-09-24:

1) Generazione candidati a zero token LLM (script una tantum in /tmp, non nel
   repo) su 733 coppie -1:
   - KNN sugli indici vettoriali HNSW gia' popolati
     (idxEmbeddingObbligo/idxEmbeddingPrincipio), k=6 per nodo di partenza,
     soglia di score 0.84: 563 coppie da 122 dei 138 nodi della Fonte 18 verso
     i nodi di tutte le altre 15 Fonti censite;
   - grep/citazione testuale sui `testo_integrale` dei nodi della Fonte 18:
     risoluzione delle citazioni esplicite a clausola di standard ETSI
     ("ETSI EN 319 401 [4], clause X", "ETSI EN 319 411-1 [8], clause X") e ad
     articolo eIDAS ("... 910/2014 ... article N") contro i `riferimento`
     realmente presenti in Neo4j: 170 coppie. Le citazioni a standard NON
     censiti (ETSI EN 319 422, ETSI TS 119 312/119 612/119 615, EN 419231,
     TS 419221-2/-3/-4/-5, ISO/IEC 15408/19790, FIPS PUB 140-2/-3, CID (EU)
     2015/1505, direttiva 93/13/EEC) non producono candidati: nessun nodo
     controparte esiste nel grafo. "ETSI EN 319 403-1" e' citata solo a fini
     di guida per i valutatori di conformita' ed e' esclusa dal perimetro.

2) Classificazione LLM della shortlist, mai sul prodotto cartesiano
   138 x 3306: una chiamata `completion()` per nodo di partenza con candidati
   (122 chiamate, eseguite in 5 batch paralleli con `wait()`), prompt con solo
   `riferimento`+`testo` sintetico del nodo di partenza e dei candidati (mai
   `testo_integrale` per intero), tassonomia ristretta ad attua/richiama/
   specifica/si sovrappone a/definisce/recepisce/deroga a, regole esplicite
   anti-generalizzazione (nessuna relazione per sovrapposizione lessicale su
   termini comuni; nel dubbio omettere), output vincolato a schema JSON.
   Esito grezzo: 266 proposte.

3) Validazione (filtro confidence >= 0.6, lettura dei testi target, verifica
   che ogni `riferimento` proposto esista davvero in Neo4j):
   - 231 proposte sopra soglia; dedup -> 227 relazioni finali;
   - le proposte verso nodi eIDAS della Fonte 1 marcati "(abrogato, testo
     originario 2014)" per l'art. 24 §2 lettere (a)/(d)/(e)/(g)/(h)/(i) sono
     state rimappate al successore vigente in eIDAS2 (Fonte 2, "art. 24 §2(X)
     (vigente, eIDAS2)"), perche' il documento e' del 2025 e la Tabella E.1
     cita l'art. 24 §2 vigente; la lettera (j) ("abrogato senza successore")
     e' stata scartata;
   - scartate 3 coppie a sovrapposizione generica di cornice: clausola 7.1
     (Introduction) verso ETSI EN 319 411-1 clausola 5.1 (premessa) e verso
     ETSI EN 319 401 clausola 4.1 (General) - entrambe riducibili alla comune
     struttura "obiettivi di sicurezza + requisiti specifici", non allo stesso
     requisito sostanziale; Annex C (UTC) verso DPCM 22/2/2013 art. 51 c.2 -
     tipo "definisce" non sostenibile (il DPCM non rinvia all'Annex C).

   Esito: 227 relazioni cross-fonte - 165 "richiama",
   61 "si sovrappone a", 1 "specifica";
   164 textual, 63 inferred; verso eIDAS (Fonte 1)
   5, eIDAS2 (Fonte 2) 6, DPCM 22/2/2013 (Fonte 4) 3, ETSI TS
   119 461 (Fonte 9) 9, ETSI EN 319 401 (Fonte 10) 160, ETSI TS 119
   431 (Fonte 11) 11, ETSI EN 319 411 (Fonte 17) 33.

Modello dominante: le clausole 6.1-6.4, 7.2-7.16 e 8 di ETSI EN 319 421
incorporano per rinvio intere clausole di ETSI EN 319 401 ("The requirements
identified in ETSI EN 319 401 [4], clause X shall apply"): la relazione
"richiama" e' emessa verso ciascun nodo-requisito di quella clausola nella
Fonte 10 (l'incorporazione e' a livello di clausola, ma il grafo censa i
requisiti uno per uno - nessun nodo di clausola esiste per le clausole
7.2/7.6/7.7/... della Fonte 10). Da qui il fan-out elevato di alcuni nodi
(es. OVR-7.9-01 verso 26 nodi REQ-7.7-*), coerente con la granularita' di
ADR-0007 e con il precedente degli import ETSI EN 319 411 (192/128 relazioni).

Le relazioni interne alla Fonte 18 (8 in totale: 3 in cap03, 4 in cap04, 1 in
cap01, tutte da citazione letterale di un requirement id) sono nei rispettivi
moduli capitolo, non qui.
"""

RIGHE_OBBLIGHI: list[dict] = []
RIGHE_PRINCIPI: list[dict] = []
INDICE_ARTICOLI_LOCALE: list[str] = []
MAPPATURA_LOCALE: dict[str, list[str]] = {}

RELAZIONI: list[dict] = [
    {
        "nodo_da": ("principio", None, 'Annex B (Model TSA disclosure statement)'),
        "nodo_a": ("obbligo", 17, 'Parte 2: OVR-6.9.4-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex D (Long term verification of time-stamps)'),
        "nodo_a": ("obbligo", 17, 'Parte 1: GEN-6.3.3-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 1, 'art. 24 §2(b)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 1, 'art. 24 §2(c)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 1, 'art. 24 §2(f)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 1, 'art. 24 §2(k)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 1, 'art. 42 §1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 2, 'art. 24 §2(a) (vigente, eIDAS2)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 2, 'art. 24 §2(d) (vigente, eIDAS2)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 2, 'art. 24 §2(e) (vigente, eIDAS2)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 2, 'art. 24 §2(g) (vigente, eIDAS2)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 2, 'art. 24 §2(h) (vigente, eIDAS2)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex E (Regulation (EU) No 910/2014 and qualified electronic time-stamp policy cross-reference)'),
        "nodo_a": ("obbligo", 2, 'art. 24 §2(i) (vigente, eIDAS2)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex H (Conformity Assessment Check list)'),
        "nodo_a": ("principio", 17, 'Parte 1: Annex B (Conformity assessment checklist)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'Annex H (Conformity Assessment Check list)'),
        "nodo_a": ("principio", 17, 'Parte 2: Annex B'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 10, 'REQ-5-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 10, 'REQ-5-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 10, 'REQ-5-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 10, 'REQ-5-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 10, 'REQ-5-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 10, 'REQ-5-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 10, 'REQ-5-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 10, 'REQ-5-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 11, 'Parte 1: OVR-6.4.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.1-01'),
        "nodo_a": ("obbligo", 11, 'Parte 2: OVR-5-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-09'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-10'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.1-11'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-01'),
        "nodo_a": ("obbligo", 11, 'Parte 2: OVR-6.1-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.2-02'),
        "nodo_a": ("obbligo", 10, 'REQ-6.2-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.2-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.2-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.2-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.2-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.2-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.2-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.3-01'),
        "nodo_a": ("obbligo", 11, 'Parte 1: OVR-6.8.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 9, 'OVR-6.3-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 10, 'REQ-6.3-09'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-6.4-01'),
        "nodo_a": ("obbligo", 11, 'Parte 2: OVR-6.3-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 9, 'OVR-7.8-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.75,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-09'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-10'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-11'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-12'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-13'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-14'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-15'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-16'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-17'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-18'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-19'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-20'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-21'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-22'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-23'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.8-24'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-02'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.5.7-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-03'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.5.7-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.10-04'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.5.7-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.11-01'),
        "nodo_a": ("obbligo", 9, 'OVR-7.9-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-02'),
        "nodo_a": ("obbligo", 17, 'Parte 1: GEN-6.4.5-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-03'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.5-07A'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.12-04'),
        "nodo_a": ("obbligo", 10, 'REQ-7.10-05'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.13-01'),
        "nodo_a": ("obbligo", 9, 'OVR-7.11-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.13-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.11-1-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.13-02'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.8-08'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.13-03'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.8-11'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-09'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-10'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-11'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-01'),
        "nodo_a": ("obbligo", 11, 'Parte 1: OVR-6.4.9-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.14-03'),
        "nodo_a": ("obbligo", 10, 'REQ-7.12-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.15-01'),
        "nodo_a": ("obbligo", 9, 'OVR-7.13-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.15-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.13-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.15-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.13-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.15-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.13-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.15-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.13-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.15-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.13-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.15-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.13-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.16-01'),
        "nodo_a": ("obbligo", 9, 'OVR-7.14-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.16-01'),
        "nodo_a": ("obbligo", 11, 'Parte 1: OVR-6.5.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.2-04'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'PRO-7.2-10'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-09'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-11'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-12'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-13'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-14'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-15'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-16'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-17'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-18'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-19'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-20'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-21'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-22'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-23'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.2-24'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.3-01'),
        "nodo_a": ("obbligo", 11, 'Parte 1: OVR-6.4.4-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.6-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.5-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.6-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.5-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.6-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.5-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.6-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.5-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.6-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.5-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 9, 'OVR-7.6-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'PRO-7.6-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'PRO-7.6-10'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-09'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-11'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-12'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-13'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.6-14'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-01'),
        "nodo_a": ("obbligo", 11, 'Parte 1: OVR-6.4.2-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-03'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-04'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-05'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-06'),
        "nodo_a": ("obbligo", 4, 'art. 33 c.2'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-06'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-04'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-07'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-05'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-08'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-09'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-10'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-08'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-11'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.4.2-09'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.8-12'),
        "nodo_a": ("principio", 17, 'Parte 1: OVR-6.4.2-10'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 9, 'OVR-7.7-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'PRO-7.7-26'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-01'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-02'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-03'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-04'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-05'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-06'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-07'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-08'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-09'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-10'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-11'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-12'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-13'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-14'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-15'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-16'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-17'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-18'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-19'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-20'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-21'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-22'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-23'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-24'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-01'),
        "nodo_a": ("obbligo", 10, 'REQ-7.7-25'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'OVR-7.9-02'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.5.6-02'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.2-03'),
        "nodo_a": ("obbligo", 4, 'art. 17 c.4'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.2-03'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.5.2-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.2-03'),
        "nodo_a": ("principio", 17, 'Parte 1: OVR-6.5.2-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.75,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.2-05'),
        "nodo_a": ("principio", 17, 'Parte 1: GEN-6.5.1-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.3-02'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.5.2-01'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.3-02'),
        "nodo_a": ("principio", 17, 'Parte 1: OVR-6.5.2-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.3-03'),
        "nodo_a": ("principio", 17, 'Parte 1: OVR-6.5.2-03'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.3-04'),
        "nodo_a": ("obbligo", 17, 'Parte 1: GEN-6.5.2-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.6-01'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.5.2-10'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.6-02'),
        "nodo_a": ("obbligo", 17, 'Parte 1: OVR-6.5.2-11'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.6.7-03'),
        "nodo_a": ("principio", 17, 'Parte 1: GEN-6.5.1-07'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'TIS-7.7.1-05'),
        "nodo_a": ("obbligo", 4, 'art. 51 c.2'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("principio", None, 'clausola 1 (Scope)'),
        "nodo_a": ("principio", 10, 'clausola 1 (Scope)'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("principio", None, 'clausola 3.4 (Notation)'),
        "nodo_a": ("principio", 9, 'clausola 3.4 (Notations)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("principio", None, 'clausola 3.4 (Notation)'),
        "nodo_a": ("principio", 10, 'clausola 3.4 (Notation)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("principio", None, 'clausola 3.4 (Notation)'),
        "nodo_a": ("principio", 11, 'Parte 1: clausola 3.4 (Notations)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("principio", None, 'clausola 3.4 (Notation)'),
        "nodo_a": ("principio", 11, 'Parte 2: clausola 3.4 (Notations)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("principio", None, 'clausola 3.4 (Notation)'),
        "nodo_a": ("principio", 17, 'Parte 1: clausola 3.4 (Notations)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("principio", None, 'clausola 4.3 (Time-Stamping Authority (TSA))'),
        "nodo_a": ("obbligo", 10, 'REQ-7.14.3-06'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
]
