"""Estrazione granulare DPCM 22 febbraio 2013 - Titolo V, Firma elettronica avanzata
(artt. 55-61: disposizioni generali, caratteristiche delle soluzioni di FEA, obblighi dei
soggetti eroganti, soggetti realizzatori per conto terzi, affidabilita' delle soluzioni,
limiti d'uso, casi equiparati - PEC e CIE/CNS/Mod.ATe/passaporto elettronico).

Testo ufficiale vigente al 17/09/2026, fonte app/.source_cache/dpcm/cap07.txt (ADR-0007).
Modulo generato secondo il contratto di app/seed_data/lib.py: nessun discrimine di rilevanza,
copertura completa comma/lettera per comma/lettera.
"""

RIGHE_OBBLIGHI = [
    {
        'riferimento': 'art. 56 c.1 lett.a',
        'testo': "La soluzione di firma elettronica avanzata deve garantire l'identificazione del firmatario del documento.",
        'testo_integrale': "Le soluzioni di firma elettronica avanzata garantiscono: a) l'identificazione del firmatario del documento;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 56 c.1 lett.b',
        'testo': 'La soluzione di firma elettronica avanzata deve garantire la connessione univoca della firma al firmatario.',
        'testo_integrale': 'b) la connessione univoca della firma al firmatario;',
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 56 c.1 lett.c',
        'testo': 'La soluzione di firma elettronica avanzata deve garantire il controllo esclusivo del firmatario sul sistema di generazione della firma, inclusi gli eventuali dati biometrici utilizzati.',
        'testo_integrale': 'c) il controllo esclusivo del firmatario del sistema di generazione della firma, ivi inclusi i dati biometrici eventualmente utilizzati per la generazione della firma medesima;',
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 56 c.1 lett.d',
        'testo': 'La soluzione di firma elettronica avanzata deve garantire la possibilità di verificare che il documento sottoscritto non abbia subito modifiche dopo l\'apposizione della firma.',
        'testo_integrale': "d) la possibilità di verificare che il documento informatico sottoscritto non abbia subito modifiche dopo l'apposizione della firma;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 56 c.1 lett.e',
        'testo': 'La soluzione di firma elettronica avanzata deve garantire al firmatario la possibilità di ottenere evidenza di quanto sottoscritto.',
        'testo_integrale': 'e) la possibilità per il firmatario di ottenere evidenza di quanto sottoscritto;',
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 56 c.1 lett.f',
        'testo': "La soluzione di firma elettronica avanzata deve garantire l'individuazione del soggetto erogatore di cui all'art. 55, comma 2, lettera a).",
        'testo_integrale': "f) l'individuazione del soggetto di cui all'art. 55, comma 2, lettera a);",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 56 c.1 lett.g',
        'testo': "La soluzione di firma elettronica avanzata deve garantire l'assenza di qualunque elemento nell'oggetto della sottoscrizione idoneo a modificare gli atti, fatti o dati rappresentati.",
        'testo_integrale': "g) l'assenza di qualunque elemento nell'oggetto della sottoscrizione atto a modificarne gli atti, fatti o dati nello stesso rappresentati;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 56 c.1 lett.h',
        'testo': 'La soluzione di firma elettronica avanzata deve garantire la connessione univoca della firma al documento sottoscritto.',
        'testo_integrale': 'h) la connessione univoca della firma al documento sottoscritto.',
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.1 lett.a',
        'testo': "L'erogatore deve identificare in modo certo l'utente tramite un documento di riconoscimento valido, informarlo sui termini e condizioni d'uso del servizio (comprese eventuali limitazioni) e subordinare l'attivazione del servizio alla sottoscrizione di una dichiarazione di accettazione delle condizioni da parte dell'utente.",
        'testo_integrale': "I soggetti di cui all'art. 55, comma 2, lettera a) devono: a) identificare in modo certo l'utente tramite un valido documento di riconoscimento, informarlo in merito agli esatti termini e condizioni relative all'uso del servizio, compresa ogni eventuale limitazione dell'uso, subordinare l'attivazione del servizio alla sottoscrizione di una dichiarazione di accettazione delle condizioni del servizio da parte dell'utente;",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.1 lett.b',
        'testo': "L'erogatore deve conservare per almeno venti anni copia del documento di riconoscimento e della dichiarazione di cui alla lettera a), nonché ogni altra informazione idonea a dimostrare il rispetto dell'art. 56, comma 1, garantendone disponibilità, integrità, leggibilità e autenticità.",
        'testo_integrale': "b) conservare per almeno venti anni copia del documento di riconoscimento e la dichiarazione di cui alla lettera a) ed ogni altra informazione atta a dimostrare l'ottemperanza a quanto previsto all'art. 56, comma 1, garantendone la disponibilità, integrità, leggibilità e autenticità;",
        'tipo_obbligo': 'di conservazione',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.1 lett.c',
        'testo': "L'erogatore deve fornire liberamente e gratuitamente copia della dichiarazione e delle informazioni di cui alla lettera b) al firmatario, su richiesta di questo.",
        'testo_integrale': "c) fornire liberamente e gratuitamente copia della dichiarazione e le informazioni di cui alla lettera b) al firmatario, su richiesta di questo;",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.1 lett.d',
        'testo': "L'erogatore deve rendere note le modalità con cui effettuare la richiesta di cui alla lettera c), pubblicandole anche sul proprio sito internet.",
        'testo_integrale': "d) rendere note le modalità con cui effettuare la richiesta di cui al punto c), pubblicandole anche sul proprio sito internet;",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.1 lett.e',
        'testo': "L'erogatore deve rendere note le caratteristiche del sistema realizzato, idonee a garantire quanto prescritto dall'art. 56, comma 1.",
        'testo_integrale': "e) rendere note le caratteristiche del sistema realizzato atte a garantire quanto prescritto dall'art. 56, comma 1;",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.1 lett.f',
        'testo': "L'erogatore deve specificare le caratteristiche delle tecnologie utilizzate e come queste consentano di ottemperare a quanto prescritto.",
        'testo_integrale': 'f) specificare le caratteristiche delle tecnologie utilizzate e come queste consentono di ottemperare a quanto prescritto;',
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.1 lett.g',
        'testo': "L'erogatore deve pubblicare sul proprio sito internet le caratteristiche di cui alle lettere e) ed f).",
        'testo_integrale': 'g) pubblicare le caratteristiche di cui alle lettere e) ed f) sul proprio sito internet;',
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.1 lett.h',
        'testo': "L'erogatore deve assicurare, ove possibile, la disponibilità di un servizio di revoca del consenso all'utilizzo della soluzione di firma elettronica avanzata e un servizio di assistenza.",
        'testo_integrale': "h) assicurare, ove possibile, la disponibilità di un servizio di revoca del consenso all'utilizzo della soluzione di firma elettronica avanzata e un servizio di assistenza.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.2',
        'testo': 'Per proteggere i titolari della firma elettronica avanzata e i terzi da eventuali danni causati da soluzioni tecniche inadeguate, gli erogatori di soluzioni di firma elettronica avanzata devono dotarsi di una copertura assicurativa per la responsabilità civile, rilasciata da una società abilitata ad operare nel campo dei rischi industriali, per un ammontare non inferiore a euro cinquecentomila.',
        'testo_integrale': 'Al fine di proteggere i titolari della firma elettronica avanzata e i terzi da eventuali danni cagionati da inadeguate soluzioni tecniche, i soggetti di cui all\'art. 55, comma 2, lettera a), si dotano di una copertura assicurativa per la responsabilità civile rilasciata da una società di assicurazione abilitata ad esercitare nel campo dei rischi industriali per un ammontare non inferiore ad euro cinquecentomila.',
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.3',
        'testo': 'Le modalità scelte per ottemperare all\'obbligo di copertura assicurativa devono essere rese note ai soggetti interessati, pubblicandole anche sul proprio sito internet.',
        'testo_integrale': 'Le modalità scelte per ottemperare a quanto disposto al comma 2 devono essere rese note ai soggetti interessati, pubblicandole anche sul proprio sito internet.',
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 57 c.5',
        'testo': "Nell'ambito delle pubbliche amministrazioni e, per la categoria degli utenti cittadini fruitori di prestazioni sanitarie, in ambito sanitario, la dichiarazione di accettazione delle condizioni del servizio di cui alla lettera a) del comma 1 può essere resa oralmente dall'utente al funzionario pubblico o all'esercente la professione sanitaria, che la raccoglie in un documento informatico sottoscritto con firma elettronica qualificata o firma digitale.",
        'testo_integrale': "Nell'ambito delle pubbliche amministrazioni e in quello sanitario limitatamente alla categoria di utenti rappresentata dai cittadini fruitori di prestazioni sanitarie, la dichiarazione di accettazione delle condizioni del servizio prevista al comma 1, lettera a) può essere fornita oralmente dall'utente al funzionario pubblico o all'esercente la professione sanitaria, il quale la raccoglie in un documento informatico che sottoscrive con firma elettronica qualificata o firma digitale.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 58 c.1',
        'testo': "I realizzatori di soluzioni di firma elettronica avanzata a favore di terzi che offrono la soluzione alle pubbliche amministrazioni devono possedere la certificazione di conformità del proprio sistema di gestione della sicurezza delle informazioni ad esse relative alla norma ISO/IEC 27001, rilasciata da un terzo indipendente autorizzato secondo le norme vigenti.",
        'testo_integrale': "I soggetti di cui all'art. 55, comma 2, lettera b) che offrono una soluzione di firma elettronica avanzata alle pubbliche amministrazioni, devono essere in possesso della certificazione di conformità del proprio sistema di gestione per la sicurezza delle informazioni ad essi relative, alla norma ISO/IEC 27001, rilasciata da un terzo indipendente a tal fine autorizzato secondo le norme vigenti in materia.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 58 c.2',
        'testo': "I realizzatori di soluzioni di firma elettronica avanzata a favore di terzi che offrono la soluzione alle pubbliche amministrazioni, o le società che li controllano, devono possedere la certificazione di conformità del proprio sistema di qualità alla norma ISO 9001 (o a norme equivalenti).",
        'testo_integrale': "I soggetti di cui all'art. 55, comma 2, lettera b) che offrono soluzioni di firma elettronica avanzata alle pubbliche amministrazioni, ovvero le società che li controllano, devono essere in possesso della certificazione di conformità del proprio sistema di qualità alla norma ISO 9001 e successive modifiche o a norme equivalenti.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 58 c.5',
        'testo': "I realizzatori di soluzioni di firma elettronica avanzata a favore di terzi possono, per dare evidenza del grado di conformità della propria soluzione alle presenti regole tecniche, farla certificare secondo la norma ISO/IEC 15408, livello EAL 1 o superiore, da un terzo indipendente autorizzato secondo le norme vigenti.",
        'testo_integrale': "I soggetti di cui all'art. 55, comma 2, lettera b), al fine di dare evidenza del grado di conformità della soluzione di firma elettronica avanzata a quanto previsto dalle presenti regole tecniche, possono far certificare la propria soluzione secondo la norma ISO/IEC 15408, livello EAL 1 o superiore, da un terzo indipendente a tal fine autorizzato secondo le norme vigenti in materia.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 59 c.1',
        'testo': "Gli erogatori di soluzioni di firma elettronica avanzata possono, per dare evidenza del grado di conformità alla norma ISO/IEC 27001 del proprio sistema di gestione per la sicurezza delle informazioni a supporto della soluzione proposta, richiederne la certificazione a una terza parte indipendente autorizzata secondo le norme vigenti.",
        'testo_integrale': "I soggetti di cui all'art. 55, comma 2, lettera a), al fine di dare evidenza del grado di conformità alla norma ISO/IEC 27001 del proprio sistema di gestione per la sicurezza delle informazioni a supporto della soluzione di firma elettronica avanzata proposta, possono richiederne la certificazione ad una terza parte indipendente autorizzata allo scopo secondo le norme vigenti in materia.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 59 c.2',
        'testo': "Gli erogatori di soluzioni di firma elettronica avanzata possono, su base volontaria, per dare evidenza del grado di conformità della soluzione alle presenti regole tecniche, farla certificare secondo la norma ISO/IEC 15408, livello EAL 1 o superiore, da un terzo indipendente autorizzato.",
        'testo_integrale': "I soggetti di cui all'art. 55, comma 2, lettera a), al fine di dare evidenza del grado di conformità della soluzione di firma elettronica avanzata a quanto previsto dalle presenti regole tecniche, su base volontaria, possono far certificare la propria soluzione secondo la norma ISO/IEC 15408, livello EAL 1 o superiore da un terzo indipendente a tal fine autorizzato secondo le norme vigenti in materia.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 61 c.4',
        'testo': "Le applicazioni di verifica della firma generata ai sensi del comma 2 devono accertare che il certificato digitale utilizzato nel processo di verifica corrisponda a uno degli strumenti indicati nel medesimo comma.",
        'testo_integrale': "Le applicazioni di verifica della firma generata ai sensi del comma 2 devono accertare che il certificato digitale utilizzato nel processo di verifica corrisponda ad uno degli strumenti di cui al medesimo comma.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 61 c.5',
        'testo': 'I certificatori accreditati che emettono certificati per gli strumenti di cui al comma 2 devono rendere disponibili strumenti di verifica della firma.',
        'testo_integrale': 'I certificatori accreditati che emettono certificati per gli strumenti di cui al comma 2 rendono disponibili strumenti di verifica della firma.',
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 61 c.6',
        'testo': "Fermo restando quanto disposto dall'art. 55, comma 1, al fine di favorire la realizzazione di soluzioni di firma elettronica avanzata, l'Agenzia elabora Linee guida sulla base delle quali realizzare soluzioni di firma elettronica avanzata conformi alle presenti regole tecniche.",
        'testo_integrale': "Fermo restando quanto disposto dall'art. 55, comma 1, al fine di favorire la realizzazione di soluzioni di firma elettronica avanzata, l'Agenzia elabora Linee guida sulla base delle quali realizzare soluzioni di firma elettronica avanzata conformi alle presenti regole tecniche.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'obbligato'}],
    },
]

RIGHE_PRINCIPI = [
    {
        'riferimento': 'art. 55 c.1',
        'testo': 'La realizzazione di soluzioni di firma elettronica avanzata è libera e non richiede autorizzazione preventiva.',
        'testo_integrale': 'La realizzazione di soluzioni di firma elettronica avanzata è libera e non è soggetta ad alcuna autorizzazione preventiva.',
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 55 c.2 lett.a',
        'testo': 'Sono soggetti che erogano soluzioni di firma elettronica avanzata coloro che le erogano per utilizzarle nei rapporti con soggetti terzi per motivi istituzionali, societari o commerciali, realizzandole in proprio o avvalendosi di soluzioni realizzate dai soggetti di cui alla lettera b).',
        'testo_integrale': "I soggetti che erogano o realizzano soluzioni di firma elettronica avanzata si distinguono in: a) coloro che erogano soluzioni di firma elettronica avanzata al fine di utilizzarle nei rapporti intrattenuti con soggetti terzi per motivi istituzionali, societari o commerciali, realizzandole in proprio o anche avvalendosi di soluzioni realizzate dai soggetti di cui alla lettera b);",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 55 c.2 lett.b',
        'testo': "Sono soggetti che realizzano soluzioni di firma elettronica avanzata a favore di terzi coloro che, quale oggetto della propria attività d'impresa, le realizzano a favore dei soggetti di cui alla lettera a).",
        'testo_integrale': "b) coloro che, quale oggetto dell'attività di impresa, realizzano soluzioni di firma elettronica avanzata a favore dei soggetti di cui alla lettera a).",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 56 c.2',
        'testo': "La firma elettronica avanzata generata violando una o più delle garanzie previste dal comma 1, lettere a), b), c), d), e), g), h), non soddisfa i requisiti previsti dagli articoli 20, comma 1-bis, e 21, comma 2, del Codice.",
        'testo_integrale': "La firma elettronica avanzata generata in violazione di quanto disposto da una o più disposizioni di cui alle lettere a), b), c), d), e), g), h) del comma 1, non soddisfa i requisiti previsti dagli articoli 20, comma 1-bis, e 21, comma 2, del Codice.",
        'tipo_principio': 'valore probatorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 57 c.4',
        'testo': "L'obbligo di copertura assicurativa di cui al comma 2 non si applica alle persone giuridiche pubbliche che erogano soluzioni di firma elettronica avanzata per conto di pubbliche amministrazioni.",
        'testo_integrale': "Il comma 2 del presente articolo non si applica alle persone giuridiche pubbliche che erogano soluzioni di firma elettronica avanzata per conto di pubbliche amministrazioni.",
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 57 c.6',
        'testo': "I commi 1 e 2 dell'art. 57 non si applicano alle soluzioni di cui all'art. 61, commi 1 e 2, alle quali si applicano le norme vigenti in materia.",
        'testo_integrale': "I commi 1 e 2 non si applicano alle soluzioni di cui all'art. 61, commi 1 e 2, alle quali si applicano le norme vigenti in materia.",
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 58 c.3',
        'testo': "I commi 1 e 2 dell'art. 58 non si applicano alle persone giuridiche private partecipate, in tutto o in parte, dalla pubblica amministrazione qualora realizzino per la stessa soluzioni di firma elettronica avanzata.",
        'testo_integrale': "I commi 1 e 2 non si applicano alle persone giuridiche private partecipate, in tutto o in parte, dalla pubblica amministrazione qualora realizzino per la stessa soluzioni di firma elettronica avanzata.",
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 58 c.4',
        'testo': "I commi 1 e 2 dell'art. 58 non si applicano alle persone giuridiche pubbliche che rendono disponibili soluzioni di firma elettronica avanzata a pubbliche amministrazioni.",
        'testo_integrale': "I commi 1 e 2 del presente articolo non si applicano alle persone giuridiche pubbliche che rendono disponibili soluzioni di firma elettronica avanzata a pubbliche amministrazioni.",
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 60 c.1',
        'testo': "La firma elettronica avanzata realizzata in conformità con le presenti regole tecniche è utilizzabile limitatamente ai rapporti giuridici tra il sottoscrittore e il soggetto erogatore di cui all'art. 55, comma 2, lettera a).",
        'testo_integrale': "La firma elettronica avanzata realizzata in conformità con le disposizioni delle presenti regole tecniche, è utilizzabile limitatamente ai rapporti giuridici intercorrenti tra il sottoscrittore e il soggetto di cui all'art. 55, comma 2, lettera a).",
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 61 c.1',
        'testo': "L'invio tramite posta elettronica certificata (con ricevuta completa ai sensi del decreto 2 novembre 2005) sostituisce, nei confronti della pubblica amministrazione, la firma elettronica avanzata ai sensi delle presenti regole tecniche.",
        'testo_integrale': "L'invio tramite posta elettronica certificata di cui all'art. 65, comma 1, lettera c-bis) del Codice, effettuato richiedendo la ricevuta completa di cui all'art. 1, comma 1, lettera i) del decreto 2 novembre 2005 recante «Regole tecniche per la formazione, la trasmissione e la validazione, anche temporale, della posta elettronica certificata» sostituisce, nei confronti della pubblica amministrazione, la firma elettronica avanzata ai sensi delle presenti regole tecniche.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata', 'servizio di recapito elettronico certificato'],
    },
    {
        'riferimento': 'art. 61 c.2',
        'testo': "L'utilizzo della Carta d'Identità Elettronica, della Carta Nazionale dei Servizi, del documento d'identità dei pubblici dipendenti (Mod. ATe), del passaporto elettronico e degli altri strumenti ad essi conformi sostituisce, nei confronti della pubblica amministrazione, la firma elettronica avanzata per i servizi e le attività di cui agli articoli 64 e 65 del Codice.",
        'testo_integrale': "L'utilizzo della Carta d'Identità Elettronica, della Carta Nazionale dei Servizi, del documento d'identità dei pubblici dipendenti (Mod. ATe), del passaporto elettronico e degli altri strumenti ad essi conformi sostituisce, nei confronti della pubblica amministrazione, la firma elettronica avanzata ai sensi delle presenti regole tecniche per i servizi e le attività di cui agli articoli 64 e 65 del codice.",
        'tipo_principio': 'equivalenza giuridica',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
    {
        'riferimento': 'art. 61 c.3',
        'testo': "I formati della firma equiparata di cui al comma 2 sono gli stessi previsti dall'art. 4, comma 2.",
        'testo_integrale': "I formati della firma di cui al comma 2 sono gli stessi previsti ai sensi dell'art. 4, comma 2.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica avanzata'],
    },
]

INDICE_ARTICOLI_LOCALE = [
    'art. 55 c.1',
    'art. 55 c.2 lett.a',
    'art. 55 c.2 lett.b',
    'art. 56 c.1 lett.a',
    'art. 56 c.1 lett.b',
    'art. 56 c.1 lett.c',
    'art. 56 c.1 lett.d',
    'art. 56 c.1 lett.e',
    'art. 56 c.1 lett.f',
    'art. 56 c.1 lett.g',
    'art. 56 c.1 lett.h',
    'art. 56 c.2',
    'art. 57 c.1 lett.a',
    'art. 57 c.1 lett.b',
    'art. 57 c.1 lett.c',
    'art. 57 c.1 lett.d',
    'art. 57 c.1 lett.e',
    'art. 57 c.1 lett.f',
    'art. 57 c.1 lett.g',
    'art. 57 c.1 lett.h',
    'art. 57 c.2',
    'art. 57 c.3',
    'art. 57 c.4',
    'art. 57 c.5',
    'art. 57 c.6',
    'art. 58 c.1',
    'art. 58 c.2',
    'art. 58 c.3',
    'art. 58 c.4',
    'art. 58 c.5',
    'art. 59 c.1',
    'art. 59 c.2',
    'art. 60 c.1',
    'art. 61 c.1',
    'art. 61 c.2',
    'art. 61 c.3',
    'art. 61 c.4',
    'art. 61 c.5',
    'art. 61 c.6',
]

MAPPATURA_LOCALE = {item: [item] for item in INDICE_ARTICOLI_LOCALE}

RELAZIONI = [
    {
        'nodo_da': ('obbligo', None, 'art. 56 c.1 lett.f'),
        'nodo_a': ('principio', None, 'art. 55 c.2 lett.a'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 56 c.2'),
        'nodo_a': ('obbligo', None, 'art. 56 c.1 lett.a'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 56 c.2'),
        'nodo_a': ('obbligo', None, 'art. 56 c.1 lett.b'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 56 c.2'),
        'nodo_a': ('obbligo', None, 'art. 56 c.1 lett.c'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 56 c.2'),
        'nodo_a': ('obbligo', None, 'art. 56 c.1 lett.d'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 56 c.2'),
        'nodo_a': ('obbligo', None, 'art. 56 c.1 lett.e'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 56 c.2'),
        'nodo_a': ('obbligo', None, 'art. 56 c.1 lett.g'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 56 c.2'),
        'nodo_a': ('obbligo', None, 'art. 56 c.1 lett.h'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 57 c.1 lett.a'),
        'nodo_a': ('principio', None, 'art. 55 c.2 lett.a'),
        'tipo_relazione': 'si applica a',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 57 c.2'),
        'nodo_a': ('principio', None, 'art. 55 c.2 lett.a'),
        'tipo_relazione': 'si applica a',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 57 c.4'),
        'nodo_a': ('obbligo', None, 'art. 57 c.2'),
        'tipo_relazione': 'deroga a',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 57 c.5'),
        'nodo_a': ('obbligo', None, 'art. 57 c.1 lett.a'),
        'tipo_relazione': 'specifica',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('principio', None, 'art. 57 c.6'),
        'nodo_a': ('obbligo', None, 'art. 57 c.2'),
        'tipo_relazione': 'deroga a',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('principio', None, 'art. 57 c.6'),
        'nodo_a': ('principio', None, 'art. 61 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('principio', None, 'art. 57 c.6'),
        'nodo_a': ('principio', None, 'art. 61 c.2'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 58 c.1'),
        'nodo_a': ('principio', None, 'art. 55 c.2 lett.b'),
        'tipo_relazione': 'si applica a',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 58 c.3'),
        'nodo_a': ('obbligo', None, 'art. 58 c.1'),
        'tipo_relazione': 'deroga a',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('principio', None, 'art. 58 c.3'),
        'nodo_a': ('obbligo', None, 'art. 58 c.2'),
        'tipo_relazione': 'deroga a',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('principio', None, 'art. 58 c.4'),
        'nodo_a': ('obbligo', None, 'art. 58 c.1'),
        'tipo_relazione': 'deroga a',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('principio', None, 'art. 58 c.4'),
        'nodo_a': ('obbligo', None, 'art. 58 c.2'),
        'tipo_relazione': 'deroga a',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 58 c.1'),
        'nodo_a': ('obbligo', None, 'art. 59 c.1'),
        'tipo_relazione': 'si sovrappone a',
        'evidence_type': 'inferred',
        'confidence': 0.6,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 58 c.5'),
        'nodo_a': ('obbligo', None, 'art. 59 c.2'),
        'tipo_relazione': 'si sovrappone a',
        'evidence_type': 'inferred',
        'confidence': 0.6,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 59 c.1'),
        'nodo_a': ('principio', None, 'art. 55 c.2 lett.a'),
        'tipo_relazione': 'si applica a',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('principio', None, 'art. 60 c.1'),
        'nodo_a': ('principio', None, 'art. 55 c.2 lett.a'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('principio', None, 'art. 61 c.3'),
        'nodo_a': ('principio', None, 'art. 61 c.2'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 61 c.4'),
        'nodo_a': ('principio', None, 'art. 61 c.2'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.9,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 61 c.5'),
        'nodo_a': ('principio', None, 'art. 61 c.2'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
    {
        'nodo_da': ('obbligo', None, 'art. 61 c.6'),
        'nodo_a': ('principio', None, 'art. 55 c.1'),
        'tipo_relazione': 'richiama',
        'evidence_type': 'textual',
        'confidence': 0.85,
    },
]
