"""Estrazione granulare DPCM 22 febbraio 2013 (regole tecniche eIDAS/CAD per
firme elettroniche qualificate e digitali) — Titolo II, parte 1.

Artt. 4-14: norme tecniche di riferimento (4), caratteristiche generali delle
chiavi (5), generazione delle chiavi (6), modalità di generazione delle
chiavi (7), conservazione delle chiavi e dei dati per la creazione della
firma (8), generazione delle chiavi di sottoscrizione al di fuori del
dispositivo di firma (9), sicurezza del sistema di generazione delle chiavi
diverso dal dispositivo di firma (10), dispositivi sicuri e procedure per la
generazione delle firme elettroniche qualificate e digitali (11), ulteriori
requisiti per i dispositivi sicuri per la generazione della firma elettronica
qualificata (12), ulteriori requisiti per i dispositivi sicuri per la
generazione della firma digitale (13), verifica delle firme elettroniche
qualificate e digitali (14).

Copertura completa ADR-0007: ogni comma/lettera del range è rappresentato da
esattamente un nodo (Obbligo o Principio), incluse le disposizioni
definitorie (art. 5 c.4) e di mero rinvio/facoltà (es. art. 7 c.2, art. 9
c.1, art. 11 c.5, art. 13 c.1-c.2). Unica riga che accorpa più lettere:
art. 12 c.1 (lett. a e b sono due regimi alternativi dello stesso requisito
di certificazione EAL 4+, non due prescrizioni indipendenti).

`testo_integrale` è copia letterale dal testo ufficiale in
`app/.source_cache/dpcm/cap02.txt` (nessuna ricostruzione a memoria, nessun
prefisso numerico di comma/lettera). `testo` è una parafrasi in italiano
corrente.

Formato dei riferimenti: "art. N c.M" o "art. N c.M lett.x", coerente con lo
stile già in uso nel censimento (vedi `app/seed_data/cad/cap02.py`).

Le relazioni (`RELAZIONI`) sono limitate a rinvii testuali espliciti interni
a questo capitolo (artt. 4-14): niente riferimenti ad altri capitoli DPCM
(es. artt. 19, 21, 28, 29, 31, 32, 35, 36, 43 del Codice o del DPCM stesso,
tutti fuori range) né a CAD/eIDAS, per evitare la classe di bug "relazione
non risolvibile" nota da CLAUDE.md quando il nodo target non è ancora stato
inserito dal capitolo che lo definisce.
"""


RIGHE_OBBLIGHI = [
    {
        'riferimento': 'art. 4 c.2',
        'testo': "Algoritmi di generazione/verifica delle firme, caratteristiche delle chiavi, funzioni di hash, formati dei certificati qualificati e di attributo, formati delle firme e delle marche temporali, caratteristiche delle applicazioni di verifica (art. 14) e dell'elenco (art. 43), e modalità di pubblicazione dello stato dei certificati sono definiti dall'Agenzia con propri provvedimenti pubblicati sul suo sito; fino alla loro emanazione resta applicabile la delibera CNIPA n. 45/2009.",
        'testo_integrale': "Gli algoritmi di generazione e verifica della firma elettronica qualificata e della firma digitale, le caratteristiche delle chiavi utilizzate, le funzioni di hash, i formati e le caratteristiche dei certificati qualificati e dei certificati di attributo, i formati e le caratteristiche della firma elettronica qualificata e della firma digitale, delle marche temporali, le caratteristiche delle applicazioni di verifica di cui all'art. 14, il formato dell'elenco di cui all'art. 43 del presente decreto, le modalità con cui rendere disponibili le informazioni sullo stato dei certificati, sono definiti, anche ai fini del riconoscimento e della verifica del documento informatico, con provvedimenti dell'Agenzia e pubblicati sul sito internet dello stesso ente. Nelle more dell'emanazione di tali provvedimenti continua ad applicarsi la deliberazione del Centro nazionale per l'informatica nella pubblica amministrazione n. 45 del 21 maggio 2009 e successive modificazioni.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 5 c.1',
        'testo': "Una coppia di chiavi per la creazione/verifica della firma elettronica qualificata o digitale può essere assegnata a un solo titolare.",
        'testo_integrale': "Una coppia di chiavi per la creazione e la verifica della firma elettronica qualificata o della firma digitale può essere attribuita ad un solo titolare.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 5 c.2',
        'testo': "Chi appone la firma tramite procedura automatica (art. 35 c.3 del Codice) deve usare una coppia di chiavi dedicata, diversa dalle altre in suo possesso; l'uso della procedura automatica va indicato esplicitamente nel certificato qualificato.",
        'testo_integrale': "Se il soggetto appone la sua firma elettronica qualificata o firma digitale per mezzo di una procedura automatica ai sensi dell'art. 35, comma 3 del Codice, deve utilizzare una coppia di chiavi destinata a tale scopo, diversa da tutte le altre in suo possesso. L'utilizzo di tale procedura deve essere indicato esplicitamente nel certificato qualificato.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}, {'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 5 c.3',
        'testo': "Se la procedura automatica del c.2 utilizza più dispositivi sicuri di firma dello stesso soggetto, ogni dispositivo deve usare una coppia di chiavi diversa.",
        'testo_integrale': "Se la procedura automatica di cui al comma 2 fa uso di un insieme di dispositivi sicuri per la generazione della firma elettronica qualificata o firma digitale del medesimo soggetto, deve essere utilizzata una coppia di chiavi diversa per ciascun dispositivo utilizzato dalla procedura automatica.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 5 c.5',
        'testo': "È vietato usare una coppia di chiavi per funzioni diverse da quelle previste per la sua tipologia (c.4), salvo autorizzazione dell'Agenzia per un uso diverso, limitatamente alle chiavi di certificazione (c.4 lett.b).",
        'testo_integrale': "Non è consentito l'uso di una coppia di chiavi per funzioni diverse da quelle previste per ciascuna tipologia dal comma 4, salvo che, con riferimento esclusivo alle chiavi di cui al medesimo comma 4, lettera b), l'Agenzia non ne autorizzi l'utilizzo per altri scopi.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 5 c.6',
        'testo': "Le caratteristiche quantitative e qualitative delle chiavi devono garantire un adeguato livello di sicurezza rispetto allo stato dell'arte scientifico e tecnologico, secondo i provvedimenti dell'Agenzia ex art. 4 c.2.",
        'testo_integrale': "Le caratteristiche quantitative e qualitative delle chiavi sono tali da garantire un adeguato livello di sicurezza in rapporto allo stato delle conoscenze scientifiche e tecnologiche, in conformità con quanto indicato nei provvedimenti di cui all'art. 4, comma 2.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 5 c.7',
        'testo': "L'uso delle chiavi dedicate allo stato di validità (c.4 lett.d) e il profilo del relativo certificato sono definiti dal provvedimento dell'Agenzia ex art. 4 c.2; a tali chiavi va associato un certificato sottoscritto con le stesse chiavi di certificazione usate per i certificati di cui si forniscono le informazioni di stato.",
        'testo_integrale': "L'uso delle chiavi di cui al comma 4, lettera d), e il profilo del certificato alle stesse associato sono definiti con il provvedimento di cui all'art. 4, comma 2. A tali chiavi dovrà essere associato un certificato sottoscritto con le stesse chiavi di certificazione con cui sono sottoscritti i certificati di cui si forniscono informazioni sullo stato di validità.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 6 c.1',
        'testo': "La generazione della coppia di chiavi deve avvenire con dispositivi e procedure che garantiscano, secondo lo stato dell'arte, l'unicità e un adeguato livello di sicurezza della coppia generata e la segretezza della chiave privata.",
        'testo_integrale': "La generazione della coppia di chiavi è effettuata mediante dispositivi e procedure che assicurano, in rapporto allo stato delle conoscenze scientifiche e tecnologiche, l'unicità e un adeguato livello di sicurezza della coppia generata, nonché la segretezza della chiave privata.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 6 c.2 lett.a',
        'testo': "Il sistema di generazione deve garantire che la coppia di chiavi risponda ai requisiti degli algoritmi di generazione e verifica utilizzati.",
        'testo_integrale': "la rispondenza della coppia ai requisiti imposti dagli algoritmi di generazione e di verifica utilizzati;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 6 c.2 lett.b',
        'testo': "Il sistema deve usare algoritmi che garantiscano l'equiprobabilità di generazione di tutte le coppie di chiavi possibili.",
        'testo_integrale': "l'utilizzo di algoritmi che consentano l'equiprobabilità di generazione di tutte le coppie possibili;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 6 c.2 lett.c',
        'testo': "Il sistema deve autenticare informaticamente il soggetto che attiva la procedura di generazione delle chiavi.",
        'testo_integrale': "l'autenticazione informatica del soggetto che attiva la procedura di generazione.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 7 c.1',
        'testo': "Le chiavi di certificazione e quelle dedicate allo stato di validità (art. 5 c.4 lett.b e d) possono essere generate solo in presenza del responsabile del servizio.",
        'testo_integrale': "Le chiavi di cui all'art. 5, comma 4, lettere b) e d) possono essere generate esclusivamente in presenza del responsabile del servizio.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 7 c.3',
        'testo': "Se il titolare genera autonomamente le chiavi di sottoscrizione, la generazione deve avvenire all'interno del dispositivo sicuro di firma rilasciato o indicato dal certificatore, con modalità che impediscano l'associazione della stessa chiave a più certificati.",
        'testo_integrale': "La generazione delle chiavi di sottoscrizione effettuata autonomamente dal titolare, avviene all'interno del dispositivo sicuro per la generazione delle firme, che è rilasciato o indicato dal certificatore, con modalità atte ad impedire che la medesima chiave possa essere associata a più certificati.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}, {'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 7 c.4',
        'testo': "Il certificatore deve assicurarsi che il dispositivo sicuro di firma elettronica qualificata da lui fornito o indicato rispetti i requisiti di sicurezza (art. 35 del Codice, artt. 11 e 12 del decreto) e deve fornire all'Agenzia gli elementi per le verifiche e i controlli ex art. 31 del Codice.",
        'testo_integrale': "Il certificatore è tenuto ad assicurarsi che il dispositivo sicuro per la generazione della firma elettronica qualificata, da lui fornito o indicato, presenti le caratteristiche e i requisiti di sicurezza di cui all'art. 35 del Codice e agli articoli 11 e 12 del presente decreto e a fornire all'Agenzia gli elementi necessari ai fini delle verifiche e dei controlli di cui all'art. 31 del Codice.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'destinatario'}],
    },
    {
        'riferimento': 'art. 7 c.5',
        'testo': "Il certificatore deve assicurarsi che il dispositivo sicuro di firma digitale da lui fornito o indicato rispetti i requisiti di sicurezza (art. 35 del Codice, artt. 11 e 13 del decreto) e deve fornire all'Agenzia gli elementi per le verifiche e i controlli ex art. 31 del Codice.",
        'testo_integrale': "Il certificatore è tenuto ad assicurarsi che il dispositivo sicuro per la generazione della firma digitale, da lui fornito o indicato, presenti le caratteristiche e i requisiti di sicurezza di cui all'art. 35 del Codice e agli articoli 11 e 13 del presente decreto e a fornire all'Agenzia gli elementi necessari ai fini delle verifiche e dei controlli di cui all'art. 31 del Codice.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'destinatario'}],
    },
    {
        'riferimento': 'art. 7 c.6',
        'testo': "Il titolare deve utilizzare esclusivamente il dispositivo sicuro di firma fornito dal certificatore, o un dispositivo scelto tra quelli da lui indicati.",
        'testo_integrale': "Il titolare è tenuto ad utilizzare esclusivamente il dispositivo sicuro per la generazione delle firme fornito dal certificatore, ovvero un dispositivo scelto tra quelli indicati dal certificatore stesso.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.1',
        'testo': "Salvo quanto previsto ai commi 2, 3 e 4, è vietato duplicare la chiave privata e i dispositivi che la contengono.",
        'testo_integrale': "Fatto salvo quanto disposto ai commi 2, 3 e 4, è vietata la duplicazione della chiave privata e dei dispositivi che la contengono.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.2',
        'testo': "Per esigenze particolari di sicurezza è ammessa l'esportazione delle chiavi di certificazione, a condizione che non si riduca il livello di sicurezza e riservatezza delle chiavi.",
        'testo_integrale': "Per fini particolari di sicurezza, è consentito che le chiavi di certificazione vengano esportate, purché ciò avvenga con modalità tali da non ridurre il livello di sicurezza e di riservatezza delle chiavi stesse.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.3',
        'testo': "Per la firma remota è ammessa l'esportazione sicura delle chiavi private di sottoscrizione (art. 5 c.4 lett.a) presenti su HSM al di fuori del dispositivo, solo per ripristino guasti o aggiornamento, purché protette con algoritmi crittografici adeguati e con operazioni di export/import tramite funzionalità di sicurezza certificate; le chiavi esportate vanno conservate nell'ambiente operativo del dispositivo sicuro di firma, con misure di sicurezza fisiche e procedurali descritte nel traguardo di sicurezza.",
        'testo_integrale': "Per la firma remota, è consentita l'esportazione sicura delle chiavi private di cui all'art. 5, comma 4, lettera a) presenti su HSM al di fuori del dispositivo stesso, esclusivamente per motivi di ripristino in caso di guasto o di aggiornamento del dispositivo in uso, purché protette con algoritmi crittografici ritenuti adeguati ai fini della certificazione e purché le operazioni di esportazione e importazione delle chiavi siano effettuate mediante funzionalità di sicurezza certificate implementate dai dispositivi sicuri di firma. La conservazione delle chiavi esportate deve avvenire nell'ambiente operativo del dispositivo sicuro di firma, sottoposta a opportune misure di sicurezza di tipo fisico e procedurale che debbono essere descritte, in forma di obiettivi o ipotesi per l'ambiente, nel relativo traguardo di sicurezza.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.4',
        'testo': "Per la firma remota è ammessa la replicazione sicura delle chiavi private di sottoscrizione (art. 5 c.4 lett.a) su HSM per configurazioni ad alta affidabilità, purché la configurazione sia certificata ai sensi degli artt. 12 o 13; la replicazione deve proteggere le chiavi con algoritmi crittografici adeguati tramite funzionalità certificate, e le chiavi replicate vanno conservate in dispositivi certificati equivalenti, controllati dal dispositivo di origine; solo un dispositivo fisico alla volta può essere abilitato a firmare.",
        'testo_integrale': "Per la firma remota, è consentita la replicazione in sicurezza delle chiavi private di cui all'art. 5, comma 4, lettera a) presenti su HSM, al fine di realizzare una configurazione ad alta affidabilità del dispositivo sicuro di firma, a condizione che tale configurazione rientri tra quelle sottoposte a certificazione ai sensi degli articoli 12 o 13. L'operazione di replicazione deve prevedere la protezione delle chiavi con algoritmi crittografici ritenuti adeguati ai fini della certificazione ed essere effettuata mediante funzionalità di sicurezza certificate implementate dal dispositivo sicuro di firma. Le chiavi replicate debbono essere conservate all'interno di dispositivi certificati con le stesse caratteristiche di sicurezza e controllati dal dispositivo certificato di origine, collocati nello stesso ambiente operativo o in altro ambiente con equivalente livello di sicurezza. Solo uno dei dispositivi fisici in questa configurazione deve essere abilitato ad effettuare le operazioni di firma.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.5 lett.a',
        'testo': "Il titolare deve custodire il dispositivo sicuro di firma in suo possesso e adottare le misure di sicurezza fornite dal certificatore, per adempiere agli obblighi dell'art. 32 c.1 del Codice.",
        'testo_integrale': "assicura la custodia del dispositivo sicuro per la generazione della firma in suo possesso e adotta le misure di sicurezza fornite dal certificatore al fine di adempiere agli obblighi di cui all'art. 32, comma 1, del Codice;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.5 lett.b',
        'testo': "Il titolare deve conservare le informazioni di abilitazione all'uso della chiave privata separatamente dal dispositivo che la contiene, seguendo le indicazioni del certificatore.",
        'testo_integrale': "conserva le informazioni di abilitazione all'uso della chiave privata separatamente dal dispositivo contenente la chiave e segue le indicazioni fornite dal certificatore;",
        'tipo_obbligo': 'di conservazione',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.5 lett.c',
        'testo': "Il titolare deve chiedere immediatamente la revoca dei certificati qualificati relativi a chiavi contenute in dispositivi di firma inutilizzabili o di cui abbia perso il possesso o il controllo esclusivo.",
        'testo_integrale': "richiede immediatamente la revoca dei certificati qualificati relativi alle chiavi contenute in dispositivi sicuri per la generazione della firma elettronica qualificata o della firma digitale inutilizzabili o di cui abbia perduto il possesso o il controllo esclusivo;",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.5 lett.d',
        'testo': "Salvo quanto previsto ai commi 3 e 4, il titolare deve mantenere in modo esclusivo la conoscenza o la disponibilità di almeno uno dei dati per la creazione della firma.",
        'testo_integrale': "salvo quanto previsto dai commi 3 e 4, mantiene in modo esclusivo la conoscenza o la disponibilità di almeno uno dei dati per la creazione della firma elettronica qualificata o digitale;",
        'tipo_obbligo': 'di conservazione',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 8 c.5 lett.e',
        'testo': "Il titolare deve chiedere immediatamente la revoca dei certificati qualificati relativi a chiavi contenute in dispositivi di firma qualora abbia il ragionevole dubbio che siano usati da altri.",
        'testo_integrale': "richiede immediatamente la revoca dei certificati qualificati relativi alle chiavi contenute in dispositivi sicuri per la generazione della firma elettronica qualificata o della firma digitale qualora abbia il ragionevole dubbio che essi possano essere usati da altri.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 9 c.2',
        'testo': "Il certificatore deve descrivere dettagliatamente nel piano della sicurezza (art. 35) il sistema di generazione diverso di cui al c.1.",
        'testo_integrale': "Il certificatore descrive dettagliatamente il sistema di cui al comma 1 nel piano della sicurezza, di cui all'art. 35.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 10 c.1 lett.a',
        'testo': "Il sistema di generazione (art. 9) deve impedire l'intercettazione o il recupero di qualsiasi informazione, anche temporanea, prodotta durante la procedura.",
        'testo_integrale': "l'impossibilità di intercettazione o recupero di qualsiasi informazione, anche temporanea, prodotta durante l'esecuzione della procedura;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 10 c.1 lett.b',
        'testo': "Il sistema deve garantire il trasferimento della chiave privata, in condizioni di massima sicurezza, nel dispositivo di firma in cui sarà utilizzata.",
        'testo_integrale': "il trasferimento della chiave privata, in condizioni di massima sicurezza, nel dispositivo di firma in cui verrà utilizzata.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 10 c.2',
        'testo': "Il sistema di generazione deve essere isolato, dedicato esclusivamente a tale attività e adeguatamente protetto.",
        'testo_integrale': "Il sistema di generazione è isolato, dedicato esclusivamente a questa attività ed adeguatamente protetto.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 10 c.3',
        'testo': "L'accesso al sistema deve essere controllato, con identificazione preventiva per l'accesso fisico e autenticazione per l'accesso logico di ogni utente; ogni sessione di lavoro va registrata nel giornale di controllo.",
        'testo_integrale': "L'accesso al sistema è controllato e ciascun utente è preventivamente identificato per l'accesso fisico e autenticato per l'accesso logico. Ogni sessione di lavoro è registrata nel giornale di controllo.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 10 c.4',
        'testo': "Il sistema deve avere strumenti di controllo della propria configurazione per verificare autenticità e integrità del software installato, l'assenza di programmi non previsti e di dati residuali di generazioni precedenti che possano compromettere l'equiprobabilità delle generazioni successive.",
        'testo_integrale': "Il sistema è dotato di strumenti di controllo della propria configurazione che consentono di verificare l'autenticità e l'integrità del software installato e l'assenza di programmi non previsti dalla procedura e di dati residuali provenienti dalla generazione di coppie di chiavi precedenti che possano inficiare l'equiprobabilità della generazione di quelle successive.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 11 c.1',
        'testo': "La generazione delle firme elettroniche qualificate e digitali deve avvenire all'interno di un dispositivo sicuro di firma, in modo da impedire l'intercettazione della chiave privata utilizzata.",
        'testo_integrale': "La generazione delle firme elettroniche qualificate e delle firme digitali avviene all'interno di un dispositivo sicuro per la generazione delle firme, in maniera tale che non sia possibile l'intercettazione della chiave privata utilizzata.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 11 c.2',
        'testo': "Il dispositivo sicuro di firma deve poter essere attivato solo dal titolare, tramite sistemi di autenticazione ritenuti adeguati da OCSI e Agenzia (per le rispettive competenze), prima della generazione della firma.",
        'testo_integrale': "Il dispositivo sicuro per la generazione della firma elettronica qualificata o della firma digitale deve poter essere attivato esclusivamente dal titolare mediante sistemi di autenticazione ritenuti adeguati, secondo le rispettive competenze, dall'OCSI e dall'Agenzia, prima di procedere alla generazione della firma.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Utente/titolare', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 11 c.3',
        'testo': "Nell'ambito delle attività ex artt. 29 e 31 del Codice, l'Agenzia valuta l'adeguatezza tecnologica dei sistemi di autenticazione per l'interazione titolare-dispositivo di firma, considerando il traguardo di sicurezza del DPCM 30/10/2003 e il contesto di utilizzo.",
        'testo_integrale': "L'Agenzia, nell'ambito dell'attività di cui agli articoli 29 e 31 del Codice, valuta l'adeguatezza tecnologica dei sistemi di autenticazione per quanto concerne l'interazione fra il titolare e il dispositivo sicuro per la generazione della firma, tenuto conto del traguardo di sicurezza di cui al DPCM 30 ottobre 2003 e del contesto di utilizzo.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 11 c.4 lett.a',
        'testo': "La personalizzazione del dispositivo deve garantire almeno l'acquisizione, da parte del certificatore, dei dati identificativi del dispositivo sicuro di firma utilizzato e la loro associazione al titolare.",
        'testo_integrale': "l'acquisizione da parte del certificatore dei dati identificativi del dispositivo sicuro per la generazione della firma elettronica qualificata o della firma digitale utilizzato e la loro associazione al titolare;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 11 c.4 lett.b',
        'testo': "La personalizzazione deve garantire la registrazione, nel dispositivo sicuro di firma, del certificato qualificato relativo alle chiavi di sottoscrizione del titolare.",
        'testo_integrale': "la registrazione nel dispositivo sicuro per la generazione della firma elettronica qualificata o della firma digitale del certificato qualificato, relativo alle chiavi di sottoscrizione del titolare.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 11 c.6',
        'testo': "La personalizzazione del dispositivo sicuro di firma deve essere registrata nel giornale di controllo (art. 36).",
        'testo_integrale': "La personalizzazione del dispositivo sicuro per la generazione delle firme elettroniche qualificate o digitali è registrata nel giornale di controllo di cui all'art. 36.",
        'tipo_obbligo': 'di conservazione',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 11 c.7',
        'testo': "Nel processo di personalizzazione del dispositivo sicuro di firma, il certificatore deve adottare procedure idonee a identificare il titolare del dispositivo e dei certificati in esso contenuti.",
        'testo_integrale': "Il certificatore adotta, nel processo di personalizzazione del dispositivo sicuro per la generazione delle firme elettroniche qualificate e digitali, procedure atte ad identificare il titolare del dispositivo medesimo e dei certificati in esso contenuti.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 11 c.8',
        'testo': "I certificatori che rilasciano certificati qualificati devono fornire almeno un sistema che consenta di generare le firme elettroniche qualificate e digitali.",
        'testo_integrale': "I certificatori che rilasciano certificati qualificati forniscono almeno un sistema che consenta la generazione delle firme elettroniche qualificate e digitali.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 12 c.1',
        'testo': "La certificazione di sicurezza dei dispositivi sicuri per la creazione di firma elettronica qualificata (anche remota o automatica, ex art. 35 del Codice) deve rispettare criteri non inferiori al livello EAL 4+ della norma ISO/IEC 15408, secondo i profili di protezione della decisione della Commissione UE 14 luglio 2003, oppure secondo i profili di protezione o traguardi di sicurezza giudicati adeguati ai sensi dell'art. 35 commi 5 e 6 del Codice.",
        'testo_integrale': "La certificazione di sicurezza dei dispositivi sicuri per la creazione di una firma elettronica qualificata, anche remota o automatica, prevista dall'art. 35 del Codice è effettuata secondo criteri non inferiori a quelli previsti: a) dal livello EAL 4+ della norma ISO/IEC 15408, in conformità ai profili di protezione indicati nella decisione della Commissione europea 14 luglio 2003 e successive modificazioni; b) dal livello EAL 4+ della norma ISO/IEC 15408, in conformità ai profili di protezione o traguardi di sicurezza giudicati adeguati ai sensi dell'art. 35, commi 5 e 6 del Codice e successive modificazioni.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 13 c.3',
        'testo': "I certificati qualificati relativi a chiavi private custodite nei dispositivi ex c.2 non devono contenere l'estensione qcStatements id-etsi-qcs-QcSSCD.",
        'testo_integrale': "I certificati qualificati afferenti chiavi private custodite nei dispositivi di cui al comma 2, non devono contenere l'estensione qcStatements id-etsi-qcs-QcSSCD.",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 14 c.1',
        'testo': "I certificatori che rilasciano certificati qualificati devono fornire o indicare almeno un sistema di verifica delle firme elettroniche qualificate e digitali, conforme ai provvedimenti dell'Agenzia (art. 4 c.2).",
        'testo_integrale': "I certificatori che rilasciano certificati qualificati forniscono ovvero indicano almeno un sistema che consenta di effettuare la verifica delle firme elettroniche qualificate e delle firme digitali, conforme a quanto stabilito con i provvedimenti di cui all'art. 4, comma 2.",
        'tipo_obbligo': 'organizzativo',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 14 c.2 lett.a',
        'testo': "Il sistema di verifica deve presentare, almeno sinteticamente, lo stato di aggiornamento delle informazioni di validità dei certificati di certificazione presenti nell'elenco pubblico.",
        'testo_integrale': "presentare, almeno sinteticamente, lo stato di aggiornamento delle informazioni di validità dei certificati di certificazione presenti nell'elenco pubblico;",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'destinatario'}],
    },
    {
        'riferimento': 'art. 14 c.2 lett.b',
        'testo': "Il sistema deve visualizzare le informazioni presenti nel certificato qualificato (art. 28 c.3 del Codice) e le estensioni obbligatorie del certificato (qcStatements) indicate nei provvedimenti dell'Agenzia (art. 4 c.2).",
        'testo_integrale': "visualizzare le informazioni presenti nel certificato qualificato, in attuazione di quanto stabilito nell'art. 28, comma 3, del Codice, nonché le estensioni obbligatorie nel certificato qualificato (qcStatements), indicate nei provvedimenti di cui all'art. 4, comma 2;",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'destinatario'}],
    },
    {
        'riferimento': 'art. 14 c.2 lett.c',
        'testo': "Il sistema deve consentire l'aggiornamento telematico delle informazioni pubblicate nell'elenco pubblico dei certificatori.",
        'testo_integrale': "consentire l'aggiornamento, per via telematica, delle informazioni pubblicate nell'elenco pubblico dei certificatori;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 14 c.2 lett.d',
        'testo': "In caso di firme multiple, il sistema deve visualizzare l'eventuale dipendenza tra le firme.",
        'testo_integrale': "in caso di firme multiple, visualizzare l'eventuale dipendenza tra queste;",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'destinatario'}],
    },
    {
        'riferimento': 'art. 14 c.2 lett.e',
        'testo': "Il sistema deve visualizzare chiaramente l'esito della verifica dello stato dei certificati qualificati e degli eventuali certificati di attributo, secondo i provvedimenti dell'Agenzia (art. 4 c.2).",
        'testo_integrale': "visualizzare chiaramente l'esito della verifica dello stato dei certificati qualificati e di eventuali certificati di attributo secondo le modalità indicate nei provvedimenti di cui all'art. 4, comma 2;",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'destinatario'}],
    },
    {
        'riferimento': 'art. 14 c.2 lett.f',
        'testo': "Il sistema deve evidenziare eventuali modifiche del documento informatico intervenute dopo la sottoscrizione.",
        'testo_integrale': "evidenziare l'eventuale modifica del documento informatico dopo la sottoscrizione dello stesso;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 14 c.2 lett.g',
        'testo': "Il sistema deve consentire di salvare il risultato dell'operazione di verifica su un documento informatico.",
        'testo_integrale': "consentire di salvare il risultato dell'operazione di verifica su un documento informatico;",
        'tipo_obbligo': 'tecnico/sicurezza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 14 c.2 lett.h',
        'testo': "Il sistema deve rendere evidente la circostanza prevista dall'art. 19 c.7 del decreto.",
        'testo_integrale': "rendere evidente la circostanza di cui all'art. 19, comma 7.",
        'tipo_obbligo': 'informativo/trasparenza',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}, {'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'destinatario'}],
    },
    {
        'riferimento': 'art. 14 c.3',
        'testo': "Ai sensi dell'art. 31 del Codice, l'Agenzia accerta la conformità dei sistemi di verifica (c.1) alle norme del Codice e alle presenti regole tecniche.",
        'testo_integrale': "L'Agenzia, ai sensi dell'art. 31 del Codice, accerta la conformità dei sistemi di verifica di cui al comma 1 alle norme del Codice e alle presenti regole tecniche.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'soggetti': [{'categoria': 'Terzi affidanti/pubblico', 'ruolo': 'obbligato'}],
    },
    {
        'riferimento': 'art. 14 c.4',
        'testo': "L'Agenzia può elaborare Linee Guida per la verifica delle firme elettroniche qualificate e digitali (per garantire attendibilità e interoperabilità, anche in base all'evoluzione normativa UE e degli standard tecnici); se emanate, i certificatori accreditati hanno l'obbligo di attenersi ad esse.",
        'testo_integrale': "L'Agenzia, al fine di fornire garanzie di attendibilità nelle operazioni di verifica e di rendere effettivamente interoperabili le firme elettroniche qualificate e le firme digitali, anche in base all'evoluzione delle normative europee ed all'evoluzione degli standard tecnici, può elaborare Linee Guida utili per la verifica della firma elettronica qualificata e della firma digitale apposte a documenti informatici cui i certificatori accreditati hanno l'obbligo di attenersi.",
        'tipo_obbligo': 'procedurale',
        'stato': 'vigente',
        'condizione_applicabilita': "Applicabile ai certificatori accreditati solo se e quando l'Agenzia emana le Linee Guida di cui al presente comma.",
        'soggetti': [{'categoria': 'QTSP/gestore', 'ruolo': 'obbligato'}],
    },
]

RIGHE_PRINCIPI = [
    {
        'riferimento': 'art. 4 c.1',
        'testo': "Le regole tecniche sui dispositivi sicuri per la generazione delle firme (art. 35 del Codice) devono essere conformi agli standard internazionali generalmente riconosciuti.",
        'testo_integrale': "Le regole tecniche relative ai dispositivi sicuri per la generazione delle firme di cui all'art. 35 del Codice sono conformi alle norme generalmente riconosciute a livello internazionale.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['dispositivo qualificato di creazione di firma elettronica'],
    },
    {
        'riferimento': 'art. 4 c.3',
        'testo': "Il documento informatico sottoscritto con firma elettronica qualificata o digitale non soddisfa il requisito di immodificabilità (art. 21 c.2 del Codice) se contiene macroistruzioni, codici eseguibili o altri elementi capaci di modificarne atti, fatti o dati rappresentati.",
        'testo_integrale': "Il documento informatico, sottoscritto con firma elettronica qualificata o firma digitale, non soddisfa il requisito di immodificabilità del documento previsto dall'art. 21, comma 2, del Codice, se contiene macroistruzioni, codici eseguibili o altri elementi, tali da attivare funzionalità che possano modificare gli atti, i fatti o i dati nello stesso rappresentati.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['documento elettronico', 'firma elettronica qualificata'],
    },
    {
        'riferimento': 'art. 5 c.4 lett.a',
        'testo': "Le chiavi di sottoscrizione servono a generare e verificare la firma elettronica qualificata o digitale apposta o associata ai documenti.",
        'testo_integrale': "chiavi di sottoscrizione, destinate alla generazione e verifica della firma elettronica qualificata o della firma digitale apposta o associata ai documenti;",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['firma elettronica qualificata', 'documento elettronico'],
    },
    {
        'riferimento': 'art. 5 c.4 lett.b',
        'testo': "Le chiavi di certificazione servono a generare/verificare le firme sui certificati qualificati, a sottoscrivere le informazioni sullo stato di validità dei certificati e a sottoscrivere i certificati delle chiavi di marcatura temporale.",
        'testo_integrale': "chiavi di certificazione, utilizzabili per la generazione e verifica delle firme apposte o associate ai certificati qualificati, per la sottoscrizione delle informazioni sullo stato di validità dei certificati, per la sottoscrizione dei certificati relativi a chiavi di marcatura temporale;",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['certificato qualificato di firma elettronica'],
    },
    {
        'riferimento': 'art. 5 c.4 lett.c',
        'testo': "Le chiavi di marcatura temporale servono a generare e verificare le marche temporali.",
        'testo_integrale': "chiavi di marcatura temporale, destinate alla generazione e verifica delle marche temporali;",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['marca temporale elettronica qualificata'],
    },
    {
        'riferimento': 'art. 5 c.4 lett.d',
        'testo': "Le chiavi dedicate servono esclusivamente a sottoscrivere le informazioni sullo stato di validità dei certificati.",
        'testo_integrale': "chiavi dedicate alla sottoscrizione delle informazioni sullo stato di validità dei certificati;",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['certificato qualificato di firma elettronica'],
    },
    {
        'riferimento': 'art. 5 c.4 lett.e',
        'testo': "Le chiavi di questo tipo servono a sottoscrivere il separato certificato di attributo.",
        'testo_integrale': "chiavi destinate alla sottoscrizione del separato certificato di attributo.",
        'tipo_principio': 'definitorio',
        'stato': 'vigente',
        'oggetti_giuridici': ['attestato elettronico di attributi'],
    },
    {
        'riferimento': 'art. 7 c.2',
        'testo': "Le chiavi di sottoscrizione possono essere generate, alternativamente, dal titolare o dal certificatore.",
        'testo_integrale': "Le chiavi di sottoscrizione possono essere generate dal titolare o dal certificatore.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': [],
    },
    {
        'riferimento': 'art. 9 c.1',
        'testo': "Se la certificazione del dispositivo di firma lo consente, il certificatore può usare un sistema diverso da quello di uso della chiave privata per generare le chiavi di sottoscrizione.",
        'testo_integrale': "Il certificatore, se la certificazione del dispositivo di firma lo consente, può utilizzare un sistema diverso da quello destinato all'uso della chiave privata per la generazione delle chiavi di sottoscrizione.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': [],
    },
    {
        'riferimento': 'art. 11 c.5',
        'testo': "La personalizzazione del dispositivo può prevedere, facoltativamente, la registrazione nel dispositivo del certificato elettronico della chiave pubblica del certificatore la cui chiave privata corrispondente ha sottoscritto il certificato qualificato del titolare.",
        'testo_integrale': "La personalizzazione del dispositivo sicuro per la generazione delle firme elettroniche qualificate o digitali può prevedere, per l'utilizzo nelle procedure di firma, la registrazione, nel dispositivo medesimo, del certificato elettronico relativo alla chiave pubblica del certificatore la cui corrispondente privata è stata utilizzata per sottoscrivere il certificato qualificato relativo alle chiavi di sottoscrizione del titolare.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['certificato qualificato di firma elettronica'],
    },
    {
        'riferimento': 'art. 13 c.1',
        'testo': "Salvo quanto previsto al c.2, la certificazione di sicurezza dei dispositivi sicuri per la creazione della firma digitale segue i criteri dell'art. 12 (già previsti per la firma elettronica qualificata).",
        'testo_integrale': "Salvo quanto disposto al comma 2, la certificazione di sicurezza dei dispositivi sicuri per la creazione di una firma digitale è effettuata ai sensi dell'art. 12.",
        'tipo_principio': 'scopo/ambito di applicazione',
        'stato': 'vigente',
        'oggetti_giuridici': ['dispositivo qualificato di creazione di firma elettronica'],
    },
    {
        'riferimento': 'art. 13 c.2',
        'testo': "L'organismo di certificazione della sicurezza informatica può stabilire ulteriori modalità di verifica della conformità ai requisiti di sicurezza dei dispositivi sicuri per la firma digitale remota (art. 35 commi 1 e 2 del Codice).",
        'testo_integrale': "L'organismo di certificazione della sicurezza informatica può individuare ulteriori modalità di verifica della conformità ai requisiti di sicurezza dei dispositivi sicuri per la creazione di una firma digitale remota ai sensi dell'art. 35, commi 1 e 2 del Codice.",
        'tipo_principio': 'altro',
        'stato': 'vigente',
        'oggetti_giuridici': ['dispositivo qualificato di creazione di firma elettronica'],
    },
]

INDICE_ARTICOLI_LOCALE = [
    'art. 4 c.1',
    'art. 4 c.2',
    'art. 4 c.3',
    'art. 5 c.1',
    'art. 5 c.2',
    'art. 5 c.3',
    'art. 5 c.4 lett.a',
    'art. 5 c.4 lett.b',
    'art. 5 c.4 lett.c',
    'art. 5 c.4 lett.d',
    'art. 5 c.4 lett.e',
    'art. 5 c.5',
    'art. 5 c.6',
    'art. 5 c.7',
    'art. 6 c.1',
    'art. 6 c.2 lett.a',
    'art. 6 c.2 lett.b',
    'art. 6 c.2 lett.c',
    'art. 7 c.1',
    'art. 7 c.2',
    'art. 7 c.3',
    'art. 7 c.4',
    'art. 7 c.5',
    'art. 7 c.6',
    'art. 8 c.1',
    'art. 8 c.2',
    'art. 8 c.3',
    'art. 8 c.4',
    'art. 8 c.5 lett.a',
    'art. 8 c.5 lett.b',
    'art. 8 c.5 lett.c',
    'art. 8 c.5 lett.d',
    'art. 8 c.5 lett.e',
    'art. 9 c.1',
    'art. 9 c.2',
    'art. 10 c.1 lett.a',
    'art. 10 c.1 lett.b',
    'art. 10 c.2',
    'art. 10 c.3',
    'art. 10 c.4',
    'art. 11 c.1',
    'art. 11 c.2',
    'art. 11 c.3',
    'art. 11 c.4 lett.a',
    'art. 11 c.4 lett.b',
    'art. 11 c.5',
    'art. 11 c.6',
    'art. 11 c.7',
    'art. 11 c.8',
    'art. 12 c.1 lett.a',
    'art. 12 c.1 lett.b',
    'art. 13 c.1',
    'art. 13 c.2',
    'art. 13 c.3',
    'art. 14 c.1',
    'art. 14 c.2 lett.a',
    'art. 14 c.2 lett.b',
    'art. 14 c.2 lett.c',
    'art. 14 c.2 lett.d',
    'art. 14 c.2 lett.e',
    'art. 14 c.2 lett.f',
    'art. 14 c.2 lett.g',
    'art. 14 c.2 lett.h',
    'art. 14 c.3',
    'art. 14 c.4',
]

MAPPATURA_LOCALE = {
    'art. 4 c.1': ['art. 4 c.1'],
    'art. 4 c.2': ['art. 4 c.2'],
    'art. 4 c.3': ['art. 4 c.3'],
    'art. 5 c.1': ['art. 5 c.1'],
    'art. 5 c.2': ['art. 5 c.2'],
    'art. 5 c.3': ['art. 5 c.3'],
    'art. 5 c.4 lett.a': ['art. 5 c.4 lett.a'],
    'art. 5 c.4 lett.b': ['art. 5 c.4 lett.b'],
    'art. 5 c.4 lett.c': ['art. 5 c.4 lett.c'],
    'art. 5 c.4 lett.d': ['art. 5 c.4 lett.d'],
    'art. 5 c.4 lett.e': ['art. 5 c.4 lett.e'],
    'art. 5 c.5': ['art. 5 c.5'],
    'art. 5 c.6': ['art. 5 c.6'],
    'art. 5 c.7': ['art. 5 c.7'],
    'art. 6 c.1': ['art. 6 c.1'],
    'art. 6 c.2 lett.a': ['art. 6 c.2 lett.a'],
    'art. 6 c.2 lett.b': ['art. 6 c.2 lett.b'],
    'art. 6 c.2 lett.c': ['art. 6 c.2 lett.c'],
    'art. 7 c.1': ['art. 7 c.1'],
    'art. 7 c.2': ['art. 7 c.2'],
    'art. 7 c.3': ['art. 7 c.3'],
    'art. 7 c.4': ['art. 7 c.4'],
    'art. 7 c.5': ['art. 7 c.5'],
    'art. 7 c.6': ['art. 7 c.6'],
    'art. 8 c.1': ['art. 8 c.1'],
    'art. 8 c.2': ['art. 8 c.2'],
    'art. 8 c.3': ['art. 8 c.3'],
    'art. 8 c.4': ['art. 8 c.4'],
    'art. 8 c.5 lett.a': ['art. 8 c.5 lett.a'],
    'art. 8 c.5 lett.b': ['art. 8 c.5 lett.b'],
    'art. 8 c.5 lett.c': ['art. 8 c.5 lett.c'],
    'art. 8 c.5 lett.d': ['art. 8 c.5 lett.d'],
    'art. 8 c.5 lett.e': ['art. 8 c.5 lett.e'],
    'art. 9 c.1': ['art. 9 c.1'],
    'art. 9 c.2': ['art. 9 c.2'],
    'art. 10 c.1 lett.a': ['art. 10 c.1 lett.a'],
    'art. 10 c.1 lett.b': ['art. 10 c.1 lett.b'],
    'art. 10 c.2': ['art. 10 c.2'],
    'art. 10 c.3': ['art. 10 c.3'],
    'art. 10 c.4': ['art. 10 c.4'],
    'art. 11 c.1': ['art. 11 c.1'],
    'art. 11 c.2': ['art. 11 c.2'],
    'art. 11 c.3': ['art. 11 c.3'],
    'art. 11 c.4 lett.a': ['art. 11 c.4 lett.a'],
    'art. 11 c.4 lett.b': ['art. 11 c.4 lett.b'],
    'art. 11 c.5': ['art. 11 c.5'],
    'art. 11 c.6': ['art. 11 c.6'],
    'art. 11 c.7': ['art. 11 c.7'],
    'art. 11 c.8': ['art. 11 c.8'],
    'art. 12 c.1': ['art. 12 c.1 lett.a', 'art. 12 c.1 lett.b'],
    'art. 13 c.1': ['art. 13 c.1'],
    'art. 13 c.2': ['art. 13 c.2'],
    'art. 13 c.3': ['art. 13 c.3'],
    'art. 14 c.1': ['art. 14 c.1'],
    'art. 14 c.2 lett.a': ['art. 14 c.2 lett.a'],
    'art. 14 c.2 lett.b': ['art. 14 c.2 lett.b'],
    'art. 14 c.2 lett.c': ['art. 14 c.2 lett.c'],
    'art. 14 c.2 lett.d': ['art. 14 c.2 lett.d'],
    'art. 14 c.2 lett.e': ['art. 14 c.2 lett.e'],
    'art. 14 c.2 lett.f': ['art. 14 c.2 lett.f'],
    'art. 14 c.2 lett.g': ['art. 14 c.2 lett.g'],
    'art. 14 c.2 lett.h': ['art. 14 c.2 lett.h'],
    'art. 14 c.3': ['art. 14 c.3'],
    'art. 14 c.4': ['art. 14 c.4'],
}

RELAZIONI = [
    {
        "nodo_da": ('obbligo', None, 'art. 5 c.6'),
        "nodo_a": ('obbligo', None, 'art. 4 c.2'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 5 c.7'),
        "nodo_a": ('obbligo', None, 'art. 4 c.2'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 14 c.1'),
        "nodo_a": ('obbligo', None, 'art. 4 c.2'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 14 c.2 lett.b'),
        "nodo_a": ('obbligo', None, 'art. 4 c.2'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 14 c.2 lett.e'),
        "nodo_a": ('obbligo', None, 'art. 4 c.2'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 7 c.1'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.b'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 7 c.1'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.d'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 8 c.3'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.a'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 8 c.4'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.a'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 5 c.7'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.d'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 5 c.5'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.a'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 5 c.5'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.b'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 5 c.5'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.c'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 5 c.5'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.d'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 5 c.5'),
        "nodo_a": ('principio', None, 'art. 5 c.4 lett.e'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 8 c.5 lett.d'),
        "nodo_a": ('obbligo', None, 'art. 8 c.3'),
        "tipo_relazione": 'è condizionato da',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 8 c.5 lett.d'),
        "nodo_a": ('obbligo', None, 'art. 8 c.4'),
        "tipo_relazione": 'è condizionato da',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 8 c.1'),
        "nodo_a": ('obbligo', None, 'art. 8 c.2'),
        "tipo_relazione": 'è condizionato da',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 8 c.1'),
        "nodo_a": ('obbligo', None, 'art. 8 c.3'),
        "tipo_relazione": 'è condizionato da',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 8 c.1'),
        "nodo_a": ('obbligo', None, 'art. 8 c.4'),
        "tipo_relazione": 'è condizionato da',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 10 c.1 lett.a'),
        "nodo_a": ('principio', None, 'art. 9 c.1'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 10 c.1 lett.b'),
        "nodo_a": ('principio', None, 'art. 9 c.1'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('principio', None, 'art. 13 c.1'),
        "nodo_a": ('obbligo', None, 'art. 12 c.1'),
        "tipo_relazione": 'si applica a',
    },
    {
        "nodo_da": ('principio', None, 'art. 13 c.1'),
        "nodo_a": ('principio', None, 'art. 13 c.2'),
        "tipo_relazione": 'è condizionato da',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 13 c.3'),
        "nodo_a": ('principio', None, 'art. 13 c.2'),
        "tipo_relazione": 'richiama',
    },
    {
        "nodo_da": ('obbligo', None, 'art. 14 c.3'),
        "nodo_a": ('obbligo', None, 'art. 14 c.1'),
        "tipo_relazione": 'richiama',
    },
]
