"""Relazioni cross-fonte DPCM 22/2/2013 -> CAD / eIDAS / eIDAS2 (2026-09-17).

Modulo "capitolo virtuale" (nessuna riga obbligo/principio propria, solo
RELAZIONI) nel senso del contratto di app/seed_data/lib.py:inserisci_capitoli,
usato per collegare i 289 nodi DPCM (cap01-cap08) alle fonti gia' presenti nel
grafo (CAD, eIDAS, eIDAS2) al momento in cui viene processato, secondo
ADR-0009 (collegamento cross-fonte a posteriori).

Pipeline di generazione (non ripetere a mano):
1. candidati da citazione testuale esplicita nel testo ufficiale DPCM (grep su
   "art. N ... del Codice", 40 citazioni CAD risolte contro i nodi CAD reali
   per numero di articolo/comma citato; zero citazioni testuali dirette a
   eIDAS/eIDAS2 -- il DPCM e' del 22/2/2013, precedente al regolamento eIDAS
   del 2014, l'unico riferimento europeo nel testo e' alla direttiva 1999/93/CE
   [precedente ad eIDAS, gia' abrogata da eIDAS] senza citazione di un articolo
   specifico, non modellato come relazione) + candidati da similarita'
   vettoriale (KNN sugli indici idxEmbeddingObbligo/Principio gia' popolati da
   embed_neo4j.py, soglia score >= 0.90 -- soglia alzata rispetto a CAD/0.80
   perche' il dominio lessicale DPCM/CAD/eIDAS e' molto piu' ristretto
   [firma elettronica, certificati, chiavi] e produce falsi positivi tematici
   a soglie piu' basse: 1514 candidati a 0.80 vs 132 a 0.90) -- zero token LLM
   per questo stadio. Unione: 171 coppie candidate (105 CAD, 38 eIDAS, 28 eIDAS2).
2. classificazione LLM in batch da 12 coppie (completion() con schema JSON,
   system prompt con la tassonomia di CONTEXT.md ristretta a
   attua/specifica/richiama/si sovrappone a/recepisce/si applica a/modifica/
   deroga a/definisce/e condizionato da/sanziona, istruito a preferire
   "richiama" quando il nodo target ha stato "abrogato") sul solo shortlist
   dello stadio 1, non sul prodotto cartesiano DPCM x (CAD+eIDAS+eIDAS2).
3. filtro confidence >= 0.5, rimozione di 1 falso positivo (evidence_type
   "textual" verso eIDAS2 art. 32 dovuto a coincidenza numerica con una
   citazione CAD art. 32/33 nello stesso comma, impossibile per costruzione:
   nessuna citazione testuale DPCM->eIDAS esiste), validazione di ogni
   riferimento contro i nodi reali in Neo4j (tutti verificati esistenti)
   prima di scrivere questo file. Esito finale: 105 relazioni (92 verso CAD,
   11 verso eIDAS, 2 verso eIDAS2).
"""

RIGHE_OBBLIGHI: list[dict] = []
RIGHE_PRINCIPI: list[dict] = []
INDICE_ARTICOLI_LOCALE: list[str] = []
MAPPATURA_LOCALE: dict[str, list[str]] = {}

RELAZIONI = [
    {
        "nodo_da": ("obbligo", None, 'art. 3 c.5 lett.c)'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 3 c.7'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 3 c.7'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.1 lett.a'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 5 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.3'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 7 c.4'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.1 lett.a'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 7 c.4'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 7 c.5'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.1 lett.a'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 7 c.5'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 8 c.5 lett.a'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.1'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 11 c.3'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 12 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.1 lett.a'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 14 c.2 lett.b'),
        "nodo_a": ("principio", 3, 'art. 28 c.3'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 14 c.3'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'art. 4 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.1 lett.a'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'art. 4 c.3'),
        "nodo_a": ("principio", 3, 'art. 21 c.2'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 19 c.1 lett.a)'),
        "nodo_a": ("principio", 3, 'art. 28 c.1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 19 c.2'),
        "nodo_a": ("principio", 3, 'art. 28 c.1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("principio", None, 'art. 17 c.5'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 32 c.2'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("principio", None, 'art. 41 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 20 c.3'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("principio", None, 'art. 41 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 20 c.3'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("principio", None, 'art. 41 c.4'),
        "nodo_a": ("obbligo", 3, 'art. 48 c.1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 42 c.2'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 42 c.4'),
        "nodo_a": ("obbligo", 3, 'art. 29 c.1'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 42 c.7'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 42 c.8'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 42 c.9'),
        "nodo_a": ("obbligo", 3, 'art. 29 c.1'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 43 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 29 c.6'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 45 c.2'),
        "nodo_a": ("principio", 3, 'art. 28 c.3'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 45 c.3'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.3'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 52 c.4'),
        "nodo_a": ("principio", 3, 'art. 31'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("principio", None, 'art. 61 c.2'),
        "nodo_a": ("principio", 3, 'art. 64 c.1'),
        "tipo_relazione": 'richiama',
        "evidence_type": 'textual',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'art. 61 c.2'),
        "nodo_a": ("principio", 3, 'art. 65 c.1'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 63 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 29 c.1'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("principio", None, 'art. 1 c.1 lett.c)'),
        "nodo_a": ("principio", 3, 'art. 1 c.1 lett.0a)'),
        "tipo_relazione": 'definisce',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("principio", 1, 'art. 26'),
        "nodo_a": ("obbligo", None, 'art. 56 c.1 lett.a'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", 1, 'art. 26'),
        "nodo_a": ("obbligo", None, 'art. 56 c.1 lett.c'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("principio", None, 'art. 62 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.3'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", 1, 'art. 24 §1 (abrogato, testo originario 2014)'),
        "nodo_a": ("obbligo", None, 'art. 18 c.1 lett.a)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", 1, 'art. 24 §3'),
        "nodo_a": ("obbligo", None, 'art. 22 c.4'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 24 c.4'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.d'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 25 c.3'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.d'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 10 c.1 lett.b'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.1 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 14 c.1'),
        "nodo_a": ("obbligo", 1, 'art. 28 §1'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 7 c.5'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.2'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 24 c.4'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.b'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 56 c.1 lett.b'),
        "nodo_a": ("principio", 1, 'art. 26'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 25 c.3'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.b'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 12 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.5'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.9,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 56 c.1 lett.h'),
        "nodo_a": ("principio", 1, 'art. 26'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 11 c.7'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.1'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 34 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.3 lett.b'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 45 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.3 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 8 c.5 lett.a'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.2'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 25 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 34 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.3 lett.m'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 42 c.10'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'art. 19 c.7'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.4'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 19 c.1 lett.a)'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 45 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.c'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 3 c.5 lett.f)'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.2'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 59 c.1'),
        "nodo_a": ("obbligo", 1, 'art. 30 §3'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 56 c.1 lett.d'),
        "nodo_a": ("principio", 1, 'art. 26'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("principio", None, 'art. 3 c.3'),
        "nodo_a": ("obbligo", 3, 'art. 20 c.3'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 25 c.3'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 11 c.8'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.3'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 18 c.1 lett.a)'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", 2, 'art. 32-bis §1-§2'),
        "nodo_a": ("obbligo", None, 'art. 18 c.1 lett.a)'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 19 c.2'),
        "nodo_a": ("principio", 3, 'art. 28 c.3'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("principio", None, 'art. 62 c.1'),
        "nodo_a": ("principio", 3, 'art. 24 c.4-bis'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 21 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", 1, 'art. 30 §3'),
        "nodo_a": ("obbligo", None, 'art. 12 c.1'),
        "tipo_relazione": 'si sovrappone a',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("principio", None, 'art. 13 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 18 c.1 lett.a)'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.3 lett.a'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 8 c.5 lett.b'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.1 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 59 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.5'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("principio", None, 'art. 13 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.5'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("principio", None, 'art. 13 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("principio", None, 'art. 1 c.1 lett.n)'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.2'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 24 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.7,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 25 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 28 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 61 c.5'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 58 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.5'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 25 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.3 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 42 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.3 lett.m'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 11 c.4 lett.b'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.1'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 56 c.1 lett.e'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.2'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 44 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 28 c.3-bis'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 56 c.1 lett.d'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.2'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 56 c.1 lett.h'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.1'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 7 c.6'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.1'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.6,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 20 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.d'),
        "tipo_relazione": 'attua',
        "evidence_type": 'inferred',
        "confidence": 0.65,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 23 c.1'),
        "nodo_a": ("obbligo", 1, 'art. 24 §3'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("principio", None, 'art. 19 c.7'),
        "nodo_a": ("principio", 3, 'art. 28 c.3'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("principio", None, 'art. 13 c.1'),
        "nodo_a": ("principio", 1, 'art. 30 §1'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.5,
    },
    {
        "nodo_da": ("principio", None, 'art. 13 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.5'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 25 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.d'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 45 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 24 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 25 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.c'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.85,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 21 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.2'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("principio", None, 'art. 4 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.4'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 11 c.2'),
        "nodo_a": ("obbligo", 3, 'art. 32 c.1'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 3 c.5 lett.a)'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.2'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.75,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 26 c.1'),
        "nodo_a": ("obbligo", 3, 'art. 36 c.1 lett.b'),
        "tipo_relazione": 'attua',
        "evidence_type": 'textual',
        "confidence": 0.8,
    },
    {
        "nodo_da": ("obbligo", None, 'art. 8 c.5 lett.b'),
        "nodo_a": ("obbligo", 3, 'art. 35 c.1 lett.a'),
        "tipo_relazione": 'specifica',
        "evidence_type": 'inferred',
        "confidence": 0.55,
    },
]
