"""DPCM 22 febbraio 2013 - Titolo I, Disposizioni generali (artt. 1-3).

Estrazione granulare ADR-0007 dal testo ufficiale vigente al 17/09/2026
(fonte: app/.source_cache/dpcm/cap01.txt). Copertura completa comma/lettera:
nessun discrimine di rilevanza, incluse le definizioni (art. 1) e le
disposizioni di scopo/ambito di applicazione (art. 2).

Nessuna relazione cross-fonte (verso CAD/eIDAS/eIDAS2) è tentata in questo
modulo: solo rinvii testuali interni al Titolo I stesso (art. 1 <-> art. 2 <->
art. 3). I rinvii verso altri Titoli del DPCM (es. art. 12, art. 13, art. 20,
art. 31 del Codice) non sono risolvibili da questo capitolo in isolamento e
sono omessi.
"""

RIGHE_OBBLIGHI = [
    {
        "riferimento": "art. 2 c.4",
        "testo": "I certificatori accreditati devono rendere disponibile ai propri titolari un sistema di validazione temporale conforme al Titolo IV.",
        "testo_integrale": "I certificatori accreditati rendono disponibile ai propri titolari un sistema di validazione temporale conforme alle disposizioni di cui al Titolo IV.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [
            {"categoria": "QTSP/gestore", "ruolo": "obbligato"},
            {"categoria": "Utente/titolare", "ruolo": "destinatario"},
        ],
    },
    {
        "riferimento": "art. 3 c.1",
        "testo": "La firma elettronica qualificata deve essere generata esclusivamente con i dispositivi di cui all'art. 1, comma 1, lettere n) e p).",
        "testo_integrale": "La firma elettronica qualificata è generata esclusivamente con i dispositivi di cui all'art. 1, comma 1, lettere n) e p).",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "art. 3 c.2",
        "testo": "La firma digitale deve essere generata con i dispositivi di cui all'art. 1, comma 1, lettere o) e p).",
        "testo_integrale": "La firma digitale è generata con i dispositivi di cui all'art. 1, comma 1, lettere o) e p).",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "art. 3 c.4",
        "testo": "La firma remota è generata su un HSM custodito e gestito, sotto la responsabilità, dal certificatore accreditato oppure dall'organizzazione di appartenenza dei titolari che ha richiesto i certificati o dall'organizzazione che ha richiesto al certificatore certificati qualificati per altri soggetti al fine di dematerializzare lo scambio documentale; il certificatore deve poter individuare agevolmente, dato un certificato qualificato, il dispositivo cui è riferita la corrispondente chiave privata.",
        "testo_integrale": "La firma remota di cui all'art. 1, comma 1, lettera q), è generata su un HSM custodito e gestito, sotto la responsabilità, dal certificatore accreditato ovvero dall'organizzazione di appartenenza dei titolari dei certificati che ha richiesto i certificati medesimi ovvero dall'organizzazione che richiede al certificatore di fornire certificati qualificati ad altri soggetti al fine di dematerializzare lo scambio documentale con gli stessi. Il certificatore deve essere in grado, dato un certificato qualificato, di individuare agevolmente il dispositivo afferente la corrispondente chiave privata.",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "art. 3 c.5 lett.a)",
        "testo": "Il certificatore deve indicare al soggetto che custodisce il dispositivo le procedure operative, gestionali e le misure di sicurezza fisica e logica che tale soggetto è obbligato ad applicare.",
        "testo_integrale": "indicare al soggetto che custodisce il dispositivo le procedure operative, gestionali e le misure di sicurezza fisica e logica che tale soggetto è obbligato ad applicare;",
        "tipo_obbligo": "informativo/trasparenza",
        "stato": "vigente",
        "condizione_applicabilita": "Applicabile quando il dispositivo per la generazione della firma remota (art. 3 c.4) non è custodito dal certificatore ma da altro soggetto (organizzazione di appartenenza dei titolari o organizzazione richiedente i certificati).",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "art. 3 c.5 lett.b)",
        "testo": "Il certificatore deve effettuare verifiche periodiche sulla corretta applicazione delle indicazioni di cui alla lettera a); il soggetto che custodisce il dispositivo ha l'obbligo di consentire e agevolare tali verifiche.",
        "testo_integrale": "effettuare verifiche periodiche sulla corretta applicazione delle indicazioni di cui alla lettera a), che il soggetto che custodisce il dispositivo ha l'obbligo di consentire ed agevolare;",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
        "condizione_applicabilita": "Applicabile quando il dispositivo per la generazione della firma remota (art. 3 c.4) non è custodito dal certificatore ma da altro soggetto (organizzazione di appartenenza dei titolari o organizzazione richiedente i certificati).",
        "soggetti": [
            {"categoria": "QTSP/gestore", "ruolo": "obbligato"},
            {"categoria": "Terza parte", "ruolo": "obbligato"},
        ],
    },
    {
        "riferimento": "art. 3 c.5 lett.c)",
        "testo": "Il certificatore deve redigere i verbali dell'attività di verifica di cui alla lettera b), che l'Agenzia può richiedere in copia ai fini dell'attività di cui all'art. 31 del CAD.",
        "testo_integrale": "redigere i verbali dell'attività di verifica di cui alla lettera b) che potranno essere richiesti in copia dall'Agenzia ai fini dell'attività di cui all'art. 31 del Codice;",
        "tipo_obbligo": "di conservazione",
        "stato": "vigente",
        "condizione_applicabilita": "Applicabile quando il dispositivo per la generazione della firma remota (art. 3 c.4) non è custodito dal certificatore ma da altro soggetto (organizzazione di appartenenza dei titolari o organizzazione richiedente i certificati).",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "art. 3 c.5 lett.d)",
        "testo": "Il certificatore deve comunicare all'Agenzia il luogo in cui i dispositivi sono custoditi.",
        "testo_integrale": "comunicare all'Agenzia il luogo in cui i medesimi dispositivi sono custoditi;",
        "tipo_obbligo": "informativo/trasparenza",
        "stato": "vigente",
        "condizione_applicabilita": "Applicabile quando il dispositivo per la generazione della firma remota (art. 3 c.4) non è custodito dal certificatore ma da altro soggetto (organizzazione di appartenenza dei titolari o organizzazione richiedente i certificati).",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "art. 3 c.5 lett.e)",
        "testo": "Il certificatore deve effettuare ulteriori verifiche su richiesta dell'Agenzia, consentendo la partecipazione anche di incaricati della stessa.",
        "testo_integrale": "effettuare ulteriori verifiche su richiesta dell'Agenzia consentendo di partecipare anche ad incaricati dello stesso ente;",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
        "condizione_applicabilita": "Applicabile quando il dispositivo per la generazione della firma remota (art. 3 c.4) non è custodito dal certificatore ma da altro soggetto (organizzazione di appartenenza dei titolari o organizzazione richiedente i certificati).",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "art. 3 c.5 lett.f)",
        "testo": "Il certificatore deve assicurare che il soggetto che custodisce il dispositivo si impegni a consentire le verifiche di cui alle lettere b) ed e).",
        "testo_integrale": "assicurare che il soggetto che custodisce il dispositivo si impegni a consentire le verifiche di cui alle lettere b) ed e).",
        "tipo_obbligo": "organizzativo",
        "stato": "vigente",
        "condizione_applicabilita": "Applicabile quando il dispositivo per la generazione della firma remota (art. 3 c.4) non è custodito dal certificatore ma da altro soggetto (organizzazione di appartenenza dei titolari o organizzazione richiedente i certificati).",
        "soggetti": [
            {"categoria": "QTSP/gestore", "ruolo": "obbligato"},
            {"categoria": "Terza parte", "ruolo": "destinatario"},
        ],
    },
    {
        "riferimento": "art. 3 c.6",
        "testo": "Se il certificatore viene a conoscenza dell'inosservanza di quanto previsto al comma 5, deve procedere alla revoca dei certificati riferiti alle chiavi private custodite sui dispositivi oggetto dell'inadempienza.",
        "testo_integrale": "Nel caso in cui il certificatore venga a conoscenza dell'inosservanza di quanto previsto al comma 5, procede alla revoca dei certificati afferenti le chiavi private custodite sui dispositivi oggetto dell'inadempienza.",
        "tipo_obbligo": "procedurale",
        "stato": "vigente",
        "soggetti": [{"categoria": "QTSP/gestore", "ruolo": "obbligato"}],
    },
    {
        "riferimento": "art. 3 c.7",
        "testo": "La firma remota deve essere realizzata con misure tecniche e organizzative espressamente approvate, per le rispettive competenze, dall'Agenzia (nell'ambito delle attività di cui agli artt. 29 e 31 del CAD) e da OCSI (per la sicurezza del dispositivo ai sensi dell'art. 35 del CAD), tali da garantire al titolare il controllo esclusivo della chiave privata.",
        "testo_integrale": "La firma remota di cui all'art. 1, comma 1, lettera q), è realizzata con misure tecniche ed organizzative, esplicitamente approvate, per le rispettive competenze, dall'Agenzia, nell'ambito delle attività di cui agli articoli 29 e 31 del Codice, e da OCSI, per quanto concerne la sicurezza del dispositivo ai sensi dell'art. 35 del Codice, tali da garantire al titolare il controllo esclusivo della chiave privata.",
        "tipo_obbligo": "tecnico/sicurezza",
        "stato": "vigente",
        "soggetti": [
            {"categoria": "QTSP/gestore", "ruolo": "obbligato"},
            {"categoria": "Utente/titolare", "ruolo": "destinatario"},
        ],
    },
]

RIGHE_PRINCIPI = [
    {
        "riferimento": "art. 1 c.1",
        "testo": "Ai fini del presente decreto si applicano anzitutto le definizioni di cui all'art. 1 del CAD (d.lgs. 82/2005 e successive modificazioni); le lettere seguenti recano inoltre le definizioni specifiche delle presenti regole tecniche.",
        "testo_integrale": "Ai fini delle presenti regole tecniche si applicano le definizioni contenute nell'art. 1 del decreto legislativo 7 marzo 2005, n. 82, e successive modificazioni. Si intende, inoltre, per:",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.a)",
        "testo": "Definisce «Codice»: il Codice dell'amministrazione digitale, d.lgs. 7 marzo 2005, n. 82 e successive modificazioni.",
        "testo_integrale": "Codice: il Codice dell'amministrazione digitale, di cui al decreto legislativo 7 marzo 2005, n. 82 e successive modificazioni;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.b)",
        "testo": "Definisce «chiavi»: la coppia di chiavi asimmetriche di cui all'art. 1, comma 1, lettere h) e i), del CAD.",
        "testo_integrale": "chiavi: la coppia di chiavi asimmetriche come definite all'art. 1, comma 1, lettere h) e i), del Codice;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.c)",
        "testo": "Definisce «Agenzia»: l'Agenzia per l'Italia Digitale (AgID), di cui agli artt. 19-22 del d.l. 83/2012.",
        "testo_integrale": "Agenzia: l'Agenzia per l'Italia Digitale, di cui gli articoli da 19 a 22 del decreto-legge 22 giugno 2012, n. 83;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.d)",
        "testo": "Definisce «compromissione della chiave privata»: il venir meno dell'affidabilità delle caratteristiche di sicurezza della chiave crittografica privata.",
        "testo_integrale": "compromissione della chiave privata: la sopravvenuta assenza di affidabilità nelle caratteristiche di sicurezza della chiave crittografica privata;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.e)",
        "testo": "Definisce «dati per la creazione della firma elettronica qualificata o digitale»: l'insieme di codici personali e altre quantità di sicurezza (incluse le chiavi crittografiche private) usate dal firmatario per creare la firma.",
        "testo_integrale": "dati per la creazione della firma elettronica qualificata o digitale: l'insieme dei codici personali e delle altre quantità di sicurezza, quali le chiavi crittografiche private, utilizzate dal firmatario per creare una firma elettronica qualificata o una firma digitale;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
        "oggetti_giuridici": ["firma elettronica qualificata"],
    },
    {
        "riferimento": "art. 1 c.1 lett.f)",
        "testo": "Definisce «evidenza informatica»: una sequenza di bit elaborabile da una procedura informatica.",
        "testo_integrale": "evidenza informatica: una sequenza di simboli binari (bit) che può essere elaborata da una procedura informatica;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.g)",
        "testo": "Definisce «funzione di hash»: funzione matematica che genera un'impronta da un'evidenza informatica, tale da rendere di fatto impossibile risalire all'evidenza originaria o generare impronte identiche da evidenze diverse.",
        "testo_integrale": "funzione di hash: una funzione matematica che genera, a partire da una evidenza informatica, una impronta in modo tale che risulti di fatto impossibile, a partire da questa, ricostruire l'evidenza informatica originaria e generare impronte uguali a partire da evidenze informatiche differenti;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.h)",
        "testo": "Definisce «impronta» di una sequenza di bit: la sequenza di bit a lunghezza predefinita generata applicando alla prima una funzione di hash.",
        "testo_integrale": "impronta di una sequenza di simboli binari (bit): la sequenza di simboli binari (bit) di lunghezza predefinita generata mediante l'applicazione alla prima di una opportuna funzione di hash;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.i)",
        "testo": "Definisce «marca temporale»: il riferimento temporale che consente la validazione temporale e dimostra l'esistenza di un'evidenza informatica in un tempo certo.",
        "testo_integrale": "marca temporale: il riferimento temporale che consente la validazione temporale e che dimostra l'esistenza di un'evidenza informatica in un tempo certo;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
        "oggetti_giuridici": ["marca temporale elettronica qualificata"],
    },
    {
        "riferimento": "art. 1 c.1 lett.l)",
        "testo": "Definisce «registro dei certificati»: la combinazione di uno o più archivi informatici tenuti dal certificatore, contenenti tutti i certificati emessi.",
        "testo_integrale": "registro dei certificati: la combinazione di uno o più archivi informatici, tenuto dal certificatore, contenente tutti i certificati emessi;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.m)",
        "testo": "Definisce «riferimento temporale»: evidenza informatica contenente data e ora, associata a uno o più documenti informatici.",
        "testo_integrale": "riferimento temporale: evidenza informatica, contenente la data e l'ora, che viene associata ad uno o più documenti informatici;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.n)",
        "testo": "Definisce «dispositivi sicuri per la generazione della firma elettronica qualificata»: mezzi su cui il firmatario mantiene il controllo esclusivo, la cui conformità è accertata ai sensi dell'art. 12.",
        "testo_integrale": "dispositivi sicuri per la generazione della firma elettronica qualificata: mezzi sui quali il firmatario può conservare un controllo esclusivo la cui conformità è accertata ai sensi dell'art. 12;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
        "oggetti_giuridici": ["dispositivo qualificato di creazione di firma elettronica"],
    },
    {
        "riferimento": "art. 1 c.1 lett.o)",
        "testo": "Definisce «dispositivi sicuri per la generazione della firma digitale»: mezzi su cui il firmatario mantiene il controllo esclusivo, la cui conformità è accertata ai sensi dell'art. 13.",
        "testo_integrale": "dispositivi sicuri per la generazione della firma digitale: mezzi sui quali il firmatario può conservare un controllo esclusivo la cui conformità è accertata ai sensi dell'art. 13;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
        "oggetti_giuridici": ["dispositivo qualificato di creazione di firma elettronica"],
    },
    {
        "riferimento": "art. 1 c.1 lett.p)",
        "testo": "Definisce «HSM»: insieme di hardware e software che realizza dispositivi sicuri per la generazione delle firme, in grado di gestire in sicurezza una o più coppie di chiavi crittografiche.",
        "testo_integrale": "HSM: insieme di hardware e software che realizza dispositivi sicuri per la generazione delle firme in grado di gestire in modo sicuro una o più coppie di chiavi crittografiche;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.q)",
        "testo": "Definisce «firma remota»: procedura di firma elettronica qualificata o digitale generata su HSM, che garantisce il controllo esclusivo delle chiavi private da parte del titolare.",
        "testo_integrale": "firma remota: particolare procedura di firma elettronica qualificata o di firma digitale, generata su HSM, che consente di garantire il controllo esclusivo delle chiavi private da parte dei titolari delle stesse;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
        "oggetti_giuridici": ["firma elettronica qualificata"],
    },
    {
        "riferimento": "art. 1 c.1 lett.r)",
        "testo": "Definisce «firma automatica»: procedura informatica di firma elettronica qualificata o digitale eseguita previa autorizzazione del sottoscrittore, che mantiene il controllo esclusivo delle proprie chiavi senza presidio puntuale e continuo.",
        "testo_integrale": "firma automatica: particolare procedura informatica di firma elettronica qualificata o di firma digitale eseguita previa autorizzazione del sottoscrittore che mantiene il controllo esclusivo delle proprie chiavi di firma, in assenza di presidio puntuale e continuo da parte di questo;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
        "oggetti_giuridici": ["firma elettronica qualificata"],
    },
    {
        "riferimento": "art. 1 c.1 lett.s)",
        "testo": "Definisce «certificato di attributo»: certificato elettronico contenente le qualifiche di cui all'art. 28, comma 3, lettera a) del CAD, possedute da un soggetto.",
        "testo_integrale": "certificato di attributo: certificato elettronico contenente le qualifiche di cui all'art. 28, comma 3, lettera a) del Codice, possedute da un soggetto;",
        "tipo_principio": "definitorio",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 1 c.1 lett.t)",
        "testo": "Definisce «soluzioni di firma elettronica avanzata»: le soluzioni strumentali alla generazione e verifica della firma elettronica avanzata di cui all'art. 1, comma 1, lett. q-bis) del CAD.",
        "testo_integrale": "soluzioni di firma elettronica avanzata: soluzioni strumentali alla generazione e alla verifica della firma elettronica avanzata di cui all'art. 1, comma 1, lettera q-bis) del Codice.",
        "tipo_principio": "definitorio",
        "stato": "vigente",
        "oggetti_giuridici": ["firma elettronica avanzata"],
    },
    {
        "riferimento": "art. 2 c.1",
        "testo": "Il decreto stabilisce, ai sensi degli artt. 20, 24 c.4, 27, 28, 29, 32, 33, 35 c.2 e 36 del CAD, le regole tecniche per generazione, apposizione e verifica della firma elettronica avanzata, qualificata e digitale, per la validazione temporale e per lo svolgimento delle attività dei certificatori qualificati.",
        "testo_integrale": "Il presente decreto stabilisce, ai sensi degli articoli 20, 24, comma 4, 27, 28, 29, 32, 33, 35, comma 2, e 36, le regole tecniche per la generazione, apposizione e verifica della firma elettronica avanzata, qualificata e digitale, per la validazione temporale, nonché per lo svolgimento delle attività dei certificatori qualificati.",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
        "oggetti_giuridici": [
            "firma elettronica avanzata",
            "firma elettronica qualificata",
            "marca temporale elettronica qualificata",
        ],
    },
    {
        "riferimento": "art. 2 c.2",
        "testo": "Il Titolo II si applica ai certificatori che rilasciano al pubblico certificati qualificati in conformità al CAD.",
        "testo_integrale": "Le disposizioni di cui al Titolo II si applicano ai certificatori che rilasciano al pubblico certificati qualificati in conformità al Codice.",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 2 c.3",
        "testo": "Ai certificatori accreditati o che intendono accreditarsi ai sensi del CAD si applica, oltre a quanto previsto dal comma 2, anche il Titolo III.",
        "testo_integrale": "Ai certificatori accreditati o che intendono accreditarsi ai sensi del Codice, si applicano, oltre a quanto previsto dal comma 2, anche le disposizioni di cui al Titolo III.",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
    },
    {
        "riferimento": "art. 2 c.5",
        "testo": "Il Titolo V si applica ai soggetti che intendono realizzare soluzioni di firma elettronica avanzata ai sensi dell'art. 1, comma 1, lett. q-bis) del CAD; non si applica alle soluzioni di firma elettronica qualificata e digitale.",
        "testo_integrale": "Le disposizioni di cui al Titolo V si applicano ai soggetti che intendono realizzare soluzioni di firma elettronica avanzata di cui all'art. 1, comma 1, lettera q-bis) del Codice. Non si applicano a soluzioni di firma elettronica qualificata e digitale.",
        "tipo_principio": "scopo/ambito di applicazione",
        "stato": "vigente",
        "oggetti_giuridici": ["firma elettronica avanzata"],
    },
    {
        "riferimento": "art. 2 c.6",
        "testo": "I prodotti sviluppati o commercializzati in uno Stato UE/SEE in conformità alle norme nazionali di recepimento della direttiva 1999/93/CE possono circolare liberamente nel mercato interno.",
        "testo_integrale": "Ai prodotti sviluppati o commercializzati in uno degli Stati membri dell'Unione europea e dello spazio economico europeo in conformità alle norme nazionali di recepimento della direttiva 1999/93/CE del Parlamento europeo e del Consiglio, pubblicata nella Gazzetta Ufficiale dell'Unione europea, Serie L, n. 13 del 19 gennaio 2000, è consentito di circolare liberamente nel mercato interno.",
        "tipo_principio": "equivalenza giuridica",
        "stato": "vigente",
        "oggetti_giuridici": ["firma elettronica"],
    },
    {
        "riferimento": "art. 3 c.3",
        "testo": "Le regole tecniche definiscono le caratteristiche oggettive di qualità, sicurezza, integrità e immodificabilità del documento informatico sottoscritto con firma elettronica avanzata, qualificata o digitale, ai fini degli effetti di cui agli artt. 20 c.1-bis e 21 c.2 del CAD.",
        "testo_integrale": "Le presenti regole tecniche definiscono le caratteristiche oggettive di qualità, sicurezza, integrità e immodificabilità del documento informatico sottoscritto con firma elettronica avanzata, qualificata o digitale ai fini e per gli effetti di cui all'art. 20, comma 1-bis, e 21, comma 2, del Codice.",
        "tipo_principio": "valore probatorio",
        "stato": "vigente",
        "oggetti_giuridici": [
            "firma elettronica avanzata",
            "firma elettronica qualificata",
            "documento elettronico",
        ],
    },
]

INDICE_ARTICOLI_LOCALE = [
    "art. 1 c.1",
    "art. 1 c.1 lett.a)",
    "art. 1 c.1 lett.b)",
    "art. 1 c.1 lett.c)",
    "art. 1 c.1 lett.d)",
    "art. 1 c.1 lett.e)",
    "art. 1 c.1 lett.f)",
    "art. 1 c.1 lett.g)",
    "art. 1 c.1 lett.h)",
    "art. 1 c.1 lett.i)",
    "art. 1 c.1 lett.l)",
    "art. 1 c.1 lett.m)",
    "art. 1 c.1 lett.n)",
    "art. 1 c.1 lett.o)",
    "art. 1 c.1 lett.p)",
    "art. 1 c.1 lett.q)",
    "art. 1 c.1 lett.r)",
    "art. 1 c.1 lett.s)",
    "art. 1 c.1 lett.t)",
    "art. 2 c.1",
    "art. 2 c.2",
    "art. 2 c.3",
    "art. 2 c.4",
    "art. 2 c.5",
    "art. 2 c.6",
    "art. 3 c.1",
    "art. 3 c.2",
    "art. 3 c.3",
    "art. 3 c.4",
    "art. 3 c.5 lett.a)",
    "art. 3 c.5 lett.b)",
    "art. 3 c.5 lett.c)",
    "art. 3 c.5 lett.d)",
    "art. 3 c.5 lett.e)",
    "art. 3 c.5 lett.f)",
    "art. 3 c.6",
    "art. 3 c.7",
]

MAPPATURA_LOCALE = {
    "art. 1 c.1": ["art. 1 c.1"],
    "art. 1 c.1 lett.a)": ["art. 1 c.1 lett.a)"],
    "art. 1 c.1 lett.b)": ["art. 1 c.1 lett.b)"],
    "art. 1 c.1 lett.c)": ["art. 1 c.1 lett.c)"],
    "art. 1 c.1 lett.d)": ["art. 1 c.1 lett.d)"],
    "art. 1 c.1 lett.e)": ["art. 1 c.1 lett.e)"],
    "art. 1 c.1 lett.f)": ["art. 1 c.1 lett.f)"],
    "art. 1 c.1 lett.g)": ["art. 1 c.1 lett.g)"],
    "art. 1 c.1 lett.h)": ["art. 1 c.1 lett.h)"],
    "art. 1 c.1 lett.i)": ["art. 1 c.1 lett.i)"],
    "art. 1 c.1 lett.l)": ["art. 1 c.1 lett.l)"],
    "art. 1 c.1 lett.m)": ["art. 1 c.1 lett.m)"],
    "art. 1 c.1 lett.n)": ["art. 1 c.1 lett.n)"],
    "art. 1 c.1 lett.o)": ["art. 1 c.1 lett.o)"],
    "art. 1 c.1 lett.p)": ["art. 1 c.1 lett.p)"],
    "art. 1 c.1 lett.q)": ["art. 1 c.1 lett.q)"],
    "art. 1 c.1 lett.r)": ["art. 1 c.1 lett.r)"],
    "art. 1 c.1 lett.s)": ["art. 1 c.1 lett.s)"],
    "art. 1 c.1 lett.t)": ["art. 1 c.1 lett.t)"],
    "art. 2 c.1": ["art. 2 c.1"],
    "art. 2 c.2": ["art. 2 c.2"],
    "art. 2 c.3": ["art. 2 c.3"],
    "art. 2 c.4": ["art. 2 c.4"],
    "art. 2 c.5": ["art. 2 c.5"],
    "art. 2 c.6": ["art. 2 c.6"],
    "art. 3 c.1": ["art. 3 c.1"],
    "art. 3 c.2": ["art. 3 c.2"],
    "art. 3 c.3": ["art. 3 c.3"],
    "art. 3 c.4": ["art. 3 c.4"],
    "art. 3 c.5 lett.a)": ["art. 3 c.5 lett.a)"],
    "art. 3 c.5 lett.b)": ["art. 3 c.5 lett.b)"],
    "art. 3 c.5 lett.c)": ["art. 3 c.5 lett.c)"],
    "art. 3 c.5 lett.d)": ["art. 3 c.5 lett.d)"],
    "art. 3 c.5 lett.e)": ["art. 3 c.5 lett.e)"],
    "art. 3 c.5 lett.f)": ["art. 3 c.5 lett.f)"],
    "art. 3 c.6": ["art. 3 c.6"],
    "art. 3 c.7": ["art. 3 c.7"],
}

RELAZIONI = [
    {
        "nodo_da": ("obbligo", None, "art. 3 c.1"),
        "nodo_a": ("principio", None, "art. 1 c.1 lett.n)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.1"),
        "nodo_a": ("principio", None, "art. 1 c.1 lett.p)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.2"),
        "nodo_a": ("principio", None, "art. 1 c.1 lett.o)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.2"),
        "nodo_a": ("principio", None, "art. 1 c.1 lett.p)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.4"),
        "nodo_a": ("principio", None, "art. 1 c.1 lett.q)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.7"),
        "nodo_a": ("principio", None, "art. 1 c.1 lett.q)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("principio", None, "art. 2 c.3"),
        "nodo_a": ("principio", None, "art. 2 c.2"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.a)"),
        "nodo_a": ("obbligo", None, "art. 3 c.4"),
        "tipo_relazione": "è condizionato da",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.b)"),
        "nodo_a": ("obbligo", None, "art. 3 c.4"),
        "tipo_relazione": "è condizionato da",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.c)"),
        "nodo_a": ("obbligo", None, "art. 3 c.4"),
        "tipo_relazione": "è condizionato da",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.d)"),
        "nodo_a": ("obbligo", None, "art. 3 c.4"),
        "tipo_relazione": "è condizionato da",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.e)"),
        "nodo_a": ("obbligo", None, "art. 3 c.4"),
        "tipo_relazione": "è condizionato da",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.f)"),
        "nodo_a": ("obbligo", None, "art. 3 c.4"),
        "tipo_relazione": "è condizionato da",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.c)"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.b)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.f)"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.b)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.5 lett.f)"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.e)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.6"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.a)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.6"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.b)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.6"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.c)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.6"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.d)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.6"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.e)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
    {
        "nodo_da": ("obbligo", None, "art. 3 c.6"),
        "nodo_a": ("obbligo", None, "art. 3 c.5 lett.f)"),
        "tipo_relazione": "richiama",
        "evidence_type": "textual",
        "confidence": None,
    },
]
